### ISSUE TITLE
App Aktivierung durch Gruppenzuordnung

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#10]
Bei diesem Thema ist ehr Nora Expertin. Vielleicht sollten wir es bei dem Treffen besprechen, damit ich es auch besser verstehe.

**Comment by ottigerb** [comment]
Patientengruppen  http://demo.optinomic.org/api/#/patient-groups/groups_all können automatisch Applikationen aktivieren - dies sobald ein Patient in eine Gruppe 'fällt'.  Automatisch via `WHERE` oder auch manuell.

**Comment by schoenenb** [comment]
Was in meinen Augen wichtig wäre, ist ein gemeinsames Festlegen, welche Gruppen benötigt werden. Die Auslösung der Apps und damit der Fragebögen finde ich mit stationär / teilstationär und manueller EP-Zuordnung eigentlich gut händelbar.
Für die Exporte wird dieser Teil m.E. durch die neue User-App Klinikstichprobe, oder vermische ich da was?

**Comment by ottigerb** [comment]
Genau, die _User-App Klinikstichprobe_ kann Patientengruppen als "Dimension" hinzufügen. Zeige Euch dies gerne - falls Ihr es bis zu unserem Treffen nicht schon selbst 'geschafft' habt.

**Comment by SonjaKaufmann** [comment]
Müssen wir hier noch weiter drüber nachdenken oder ist der Punkt fertig?

**Comment by schoenenb** [comment]
Bin mir nicht sicher.
Für die Dimension "Patientengruppe" in der User-App Klinikstichprobe muss die Gruppe bereits definiert sein und aufgrund der Gruppe können dann die z-Werte für die Sub-Gruppe berechnet werden. Stimmt das soweit?

Und bisher ist in der User-App der TMT auswählbar - d.h., um z-Werte von Klinikstichproben berechnen zu können, müssten die jeweiligen Apps, für die z-Werte benötigt werden, noch mit einem Code ausgestattet werden?! Und das muss dann für jede einzelne App gemacht werden, auch wenn die Stichproben immer gleich zusammengesetzt sind?!

**Comment by ottigerb** [comment]
> YES!   Erfolg!


Unter http://optinomic.cust.local/api/#/patient-groups/groups_all  habe ich mal folgende `patient-groups` eröffnet:

![bildschirmfoto 2016-12-02 um 14 23 49](https://cloud.githubusercontent.com/assets/2470873/20835491/4384f916-b89b-11e6-974b-f3ba3077e2bf.png)

Wir können somit die ` Belegung: EAS (in aktueller Behandlung) `  resp. ` Belegung: EP (in aktueller Behandlung) ` verwenden um Apps automatisch zu aktivieren.  Oder?
=>  Kein manuelles Zuordnen von Patienten zu Programmen mehr nötig!  

Damit die Daten aktuell bleiben - regelmässig / täglich - folgende User-App öffnen & durchlaufen lassen: http://optinomic.cust.local/api/#/user_app/com.optinomic.apps.poly_stay
=>  Ich versuche selbst diesen Schritt zu automatisieren!  


Zudem kann bei jedem Patienten die  Belegungs-Details angesehen werden:    
Beispiel: http://optinomic.cust.local/api/#/patient/917/stay/985/app/com.optinomic.init.poly_stay

![bildschirmfoto 2016-12-02 um 14 30 24](https://cloud.githubusercontent.com/assets/2470873/20835638/f77f8c56-b89b-11e6-97b2-39ccd07fc361.png)

**Comment by schoenenb** [comment]
Woran kann es liegen, dass Patienten zwar einer Gruppe zugeordnet sind, jedoch die dazugehörigen Apps, die aktiviert werden sollten, nicht aktiviert werden? (so geschehen bei: http://optinomic.cust.local/api/#/patient/2215/stay/1214 - ev. weil d. Pat. vorher schon mal mit einem ambulanten Fall als stationär gezählt wurde und sich dort ev. etwas überschnitten hat?)

**Comment by schoenenb** [comment]
hmm, ok... Und zägg sind auf einmal alle aktiviert, nachdem ich den SCI aktiviert habe...

**Comment by ottigerb** [comment]
Freut mich, wenn's klappt!  :-)   Ich denke nicht, dass dies mit der Aktivierung des SCI "gelöst" wurde.  Die Aktivierung kann auch mittels dem Executable `PATIENT-GROUPS` unter `/api/#/admin/tools` forciert werden. Doch auch dann kann es noch einige Sekunden dauern bis die "Aktivierungen" abgearbeitet sind.
