### ISSUE TITLE
ch.suedhang.apps.ASRS

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#100]
- [x] App erstellen
- [x] Survey
- [x] Calculation: wenn grau hinterlegt = 1
- [x] Calculation: Anzahl 1
- [x] Ausgabe: ab 2 Punkten = auffällig

**Comment by schoenenb** [comment]
Bitte mal anschauen auf http://demo.optinomic.org/api/#/patient/1/stay/144/app/ch.suedhang.apps.asrs : 
- was fehlt bzgl. Text / Anzeigen in der Darstellung?
- was fehlt bzgl. Text / Anzeigen im Fragebogen?
- soll der Wert auch in die Assessment-Zusammenstellungen + ins PDF?
Wenn's nicht viele Änderungswünsche gibt, sollte ich den Fragebogen nächste Woche vervollständigen können und auf die Südhang-Anwendung laden können. Letzteres kann natürlich auch noch dein definitives "OK" abwarten und dann am 19. erfolgen.

**1 Frage:** Habe ich das richtig im Kopf, dass der nur bei Eintritt ausgefüllt wird?

**Comment by ottigerb** [comment]
# SUPER!

Eine tolle App hast Du hier entwickelt - Gratulation.

Ich habe das Template etwas an bisherige Apps angeglichen.
Die Werteübersicht - Block - braucht es wohl nicht.

**Comment by schoenenb** [comment]
Merci :)
Die Werte habe ich nur mal so drin gelassen, falls die auch irgendwie gebraucht würden.

**Comment by schoenenb** [comment]
Ich glaube, diese App ist fertig. :)
