### ISSUE TITLE
Mitarbeiter_Liste

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#101]
Kann man ehemalige Mitarbeiter aus der Mitarbeiterliste ausblenden oder kann man sie löschen?
Ziel ist, dass die Liste kürzer und überschaubarer wird.
Beim löschen befürchte ich aber, dass es dann Probleme mit den alten Fällen gibt, wenn der Bezugstherapeut nicht mehr in der Mitarbeiterliste ist oder ist dem nicht so?

**Comment by ottigerb** [comment]
Richtige Überlegung:  Mitarbeiter gilt es nicht zu löschen um nicht mögliche Referenzen zu "torpedieren".  Mitarbeiter können jedoch z.B. unter http://demo.optinomic.org/api/#/user/10 archiviert werden.

![bildschirmfoto 2017-03-17 um 09 10 53](https://cloud.githubusercontent.com/assets/2470873/24034488/b6158c04-0af1-11e7-986a-982c3dee1647.png)

Zum schnellen Auffinden eines Benutzers steht z.B. unter http://demo.optinomic.org/api/#/users die Filterfunktion zur Verfügung.

=>  Read & Close!

**Comment by schoenenb** [comment]
Ich hab's gelesen - gebe das "close" an Sonja ab.
