### ISSUE TITLE
Behandlungsauftrag: Error

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#102]
Ich wollte eben ausprobieren, ob das funktioniert mit der Zugriffsberechtigung, weil ich bei einer EAS-Therapeutin das Passwort ändern musste. Dazu habe ich einen TK-Fall (optinomic.cust.local/api/#/patient/2812/access/) angewählt und folgende Ausgabe erhalten:
![image](https://cloud.githubusercontent.com/assets/15833792/24033779/d9c3964e-0aee-11e7-8425-4723fe4ab62f.png)

Ist das ein einmaliger Fehler und hätte ich es mehrmals laden müssen, damit das Zugriffs-Formular erscheint? Die einzige Option hier war ABBRECHEN...

**Comment by ottigerb** [comment]
Tatsächlich:  Ich habe ein Fix (https://github.com/ottigerb/therapy-server/commit/7cdc729eed926fc24458cc0335232eb89ca0efbc) gepushed und werde dies auf demo prüfen.  Sobald i.O. => New Stable und auf Südhang lancieren.

**Comment by ottigerb** [comment]
Funktioniert auf Demo:  http://demo.optinomic.org/api/#/patient/1/access/Behandlungsauftrag
=> Neuer Stable ist erstellt - push to Südhang?  Da ist auch der Bugfix drin bzgl. `days_before_exit` (Falls 3 gesetzt wird kein Email Versendet wenn stop_datum z.B. 1 Tag vor Austritt gesetzt wurde.

**Comment by schoenenb** [comment]
Heisst das, im Südhang sollte es auch funktionieren?

**Comment by ottigerb** [comment]
...not yet!   :-(   Mein Fix funktioniert - will aber nicht in den Stable. => Tom @ https://github.com/ottigerb/therapy-server/issues/434

**Comment by schoenenb** [comment]
ok, gib Bescheid, wenn es heute noch läuft, dann probier ich's nochmals :)

**Comment by ottigerb** [comment]
http://optinomic.cust.local/api/#/patient/2279/access/Behandlungsauftrag  wird nun korrekt angezeigt Sollte nun also klappen.

=>  Test & Close!   Please!  :-)

**Comment by schoenenb** [comment]
Leider nein, sieht immer noch gleich aus und es poppt kein Behandlungsauftrag auf...

**Comment by ottigerb** [comment]
... maaaaan!  Da muss ich wohl tiefer eintauchen. Hmm.

schoenenb <notifications@github.com> schrieb am Fr., 17. März 2017, 18:16:

**Comment by ottigerb** [comment]
Dies ist gemäss Nora erledigt. 
=>  Reopen falls nötig.

**Comment by schoenenb** [comment]
sorry, hab vergessen, dass es dazu noch ein Issue gab :/
