### ISSUE TITLE
TMT ng-survey

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#104]
Eine Mitarbeiterin meldete mir eben folgendes:
Bei Klicken auf JETZT AUSFÜHREN erscheint folgende Seite
http://survey.demo.optinomic.org//surveys/745d804d-2c51-4251-95e4-529e4baa3eb80

mit dem angezeigten Text "404"

Müsste die Seite anders lauten (optinomic.org statt demo.optinomic.org)? Sonstige Hinweise?
Wenn's heute noch funktioniert, kann ich die Aufgabe der Mitarbeiterin "zurückgeben" - später müssten wir's selber nachtragen...

**Comment by schoenenb** [comment]
Ahja, Patient = http://optinomic.cust.local/api/#/patient/2303/stay/1175/app/ch.suedhang.apps.tmt.production

**Comment by ottigerb** [comment]
..hmmm:  
http://optinomic.cust.local/api/#/patient/2303/stay/1175/app/ch.suedhang.apps.tmt.production
=>  Jetzt ausführen (manuell)
 Funktioniert bei mir problemlos.  Jetzt ausführen öffnet korrekt den Fragebogen.

**Comment by schoenenb** [comment]
Bei mir jetzt auch... (hat allerdings eine neue #-Nummer)

**Comment by ottigerb** [comment]
...hmmm - in solchen Fällen allenfalls den Event löschen und neu versuchen.  

Close und weiter beobachten?

**Comment by schoenenb** [comment]
Scheint so :+1:

**Comment by schoenenb** [comment]
Das Phänomen ist bei allen automatisch ausgelösten TMTs zu beobachten - woran könnte das liegen?
Es sollte eine Ausnahme bleiben, dass die Therapeuten Events löschen müssen um neue Links zu generieren, auch wenn es an sich kein so hochkomplexer Vorgang wäre.

**Comment by ottigerb** [comment]
...hm - ich kann den Fehler nicht reproduzieren:

Ich habe bei [Patient 1](http://optinomic.cust.local/api/#/patient/1/stay/1/app/ch.suedhang.apps.tmt.production) den TMT aktiviert sodass folgender Event aktiviert wird:

```
[event activation]
type = on_activation
due_after = 259200
overdue = ignore
description = TMT-Erfassung
survey = tmt_ng
```

der neu erstellte [Task](http://survey.demo.optinomic.org//surveys/453a6b1c-a7c6-41c4-b0b2-613b5b4596b4) funktioniert einwandfrei.

Ist dieser Effekt allenfalls nur bei `[event exit]`?

**Comment by schoenenb** [comment]
Nein, der Link hat bisher bei allen nicht funktioniert.
Hier z.B. ein Eintritt der gestern nicht eingetragen werden konnte: http://optinomic.cust.local/api/#/patient/2872/stay/1329/app/ch.suedhang.apps.tmt.production

**Comment by ottigerb** [comment]
Ich habe https://github.com/ottigerb/therapy-server/issues/436 eröffnet.
=>   Eigenartiger Fehler: vielleicht seit dem Fix:  3 days before exit

**Comment by schoenenb** [comment]
Bin bei den Exporten über was gestolpert, das (bisher) auch nur den TMT-Survey betrifft:
Da das Erhebungsdatum nicht in der Response gespeichert wird, kann ich es nicht abrufen. Müsste im SQL statt _FROM "survey_response_view"_ sowas wie _FROM "survey_data"_ stehen?
![image](https://cloud.githubusercontent.com/assets/15833792/24795499/d4095350-1b89-11e7-8e65-30179632e4a3.png)

**Comment by ottigerb** [comment]
...öhm - verstehe nicht:  Da muss lediglich dass `filled` date gezogen werden. Nicht?

**Comment by schoenenb** [comment]
also mit 
`((cast(response AS json))->>'filled') as filled,`
kommt keine Ausgabe

**Comment by schoenenb** [comment]
ok, wahrscheinlich muss einfach die Zeile aus den Default-Werten wiederholt werden
`survey_response_view.filled as optinomic_survey_filled,`

**Comment by ottigerb** [comment]
Genau:  Jedoch nicht den `as` wiederholen - z.B.:
```SQL
survey_response_view.filled as erfassungsdatum,
```

**Comment by schoenenb** [comment]
Hab's sowieso ein wenig abgeändert, das Datumsformat hat mir nicht so gefallen. ;)
Ich lade die "neuen" SQLs nachher gemeinsam hoch. Dazu noch eine Frage in #15 ...

**Comment by ottigerb** [comment]
https://github.com/ottigerb/therapy-server/issues/436  is closed.
=>  Ich schliesse dies - falls wieder sowas  "auftaucht" bitte melden!

**Comment by schoenenb** [comment]
Leider immer noch da...
http://optinomic.cust.local/api/#/patient/2489
![image](https://cloud.githubusercontent.com/assets/15833792/25265479/a3a3b5e0-266d-11e7-9212-bc40c82cc00c.png)
![image](https://cloud.githubusercontent.com/assets/15833792/25265494/b17d9262-266d-11e7-89ee-2b10b375ba71.png)

**Comment by ottigerb** [comment]
...hmmm - stranges Issue!  

http://survey.demo.optinomic.org//surveys/8624d022-2c68-4b01-9611-6c460516afb90 zeigte ein 404 auch vor der neue Event manuell erstellt wurde?  Geh dem mal nach.

**Comment by schoenenb** [comment]
Ich habe bei allen, die heute Nami gebraucht werden, die automatisch ausgelöste Aufgabe gelöscht (und vom ersten Patienten die Screenshots gemacht), weil überall der 404-Text stand und habe die Aufgabe manuell erstellt.
Meinst du, es lässt sich heute lösen? Sonst werde ich am Abend die event activation rausnehmen.

**Comment by ottigerb** [comment]
Danke für kurze Bestätigung meines Eindrucks:
- `[event activation]` funktioniert problemlos. Meine Tests funktionieren:

```
[event activation]
type = on_activation
due_after = 259200
overdue = ignore
description = TMT-Erfassung
survey = tmt_ng
```
- `[event exit]` führt zu einem 404. Schwierig zu testen:
```
[event exit]
type = before_exit
days = 5
time = 08:00
due_after = 259200
overdue = ignore
description = TMT-Erfassung
survey = tmt_ng
```

Dies würde den Fehler doch stark "lokalisieren".  Wir erinnern uns an den Fehler: `before_exit, 5 days` - falls nun das Austrittsdatum 5 Tage vorher noch nicht bekannt war wurde kein Event ausgelöst. => Dies sollte nun gefixt sein - doch wohl nun mit diesem Effect.

**Comment by schoenenb** [comment]
Hmm, aber wenn das Austrittsdatum noch nicht bekannt wäre, würden auch die Assessmentfragebögen nicht aktiviert und die Events dort werden ja bereits 10 Tage vorher ausgelöst. Von den Hiwis habe ich nichts gehört, dass dort etwas nicht mehr funktioniert hätte.

**Comment by ottigerb** [comment]
...ja, klar.   Doch der `[event activation]` funktioniert.  Der `[event exit]` führt zu 404. Not?

**Comment by schoenenb** [comment]
Genau. Dann habe ich wohl deine Aussage oben falsch verstanden.

**Comment by ottigerb** [comment]
Ich habe https://github.com/ottigerb/therapy-server/issues/436 wieder geöffnet.  Ich denke nicht, dass Tom dies heute "erledigen" kann.

Bei anderen Apps mit `[event exit]` - actInfo Austritt - kommt dies nicht vor - oder?

**Comment by schoenenb** [comment]
Ich glaube nicht.

**Comment by schoenenb** [comment]
[event exit] funktioniert beim TMT leider weiterhin nicht

**Comment by ottigerb** [comment]
Yep - vgl.:   https://github.com/ottigerb/therapy-server/issues/436
Falls Du mal ein Beispiel für ein 404 bei `[event entry]` hast - wäre dies sehr interessant.

**Comment by schoenenb** [comment]
habe die Eintritte von dieser Woche durchgeschaut und dort haben alle funktioniert

**Comment by schoenenb** [comment]
404-Fehler nun auch bei Eintritten:
http://survey.demo.optinomic.org//surveys/9cb8a1a8-df1b-499d-882c-8a95e4337eeb bei
http://optinomic.cust.local/api/#/patient/3022/stay/1429/app/ch.suedhang.apps.tmt.production

**Comment by ottigerb** [comment]
Ich muss dies leider [direkt weiterleiten](https://github.com/ottigerb/therapy-server/issues/436#issuecomment-308951308) - wir finden diesen BUG - hoffentlich baaaald!

**Comment by ottigerb** [comment]
...gibt es hierzu spürbare "Verbesserungen".  Angeblich hat Tom etwas "gezaubert".  Bin gespannt auf Feedback - resp. hoffe dieses Issue schliessen zu können.

**Comment by schoenenb** [comment]
Dem TMT habe ich den Austritts-Event zurückgegeben - wenn nächste Woche alles i.O. ist mit den Links verschwindet dieses Issue!

**Comment by schoenenb** [comment]
Bisher keine Events ausgelöst bei Austritten vom 15.8. - mit der Festlegung von 5 Tagen vor Austritt um 8:00 hätte ich erwartet, dass eine Aufgabe auch mich wartet, die am 10.8. um 8:00 ausgelöst wurde, aber bisher ist nichts da:
http://optinomic.cust.local/api/#/patient/2986/stay/1411/app/ch.suedhang.apps.tmt.production
http://optinomic.cust.local/api/#/patient/387/stay/1458/app/ch.suedhang.apps.tmt.production
Mit dem Versionsabgleich sollte das ja auch für die Patienten oder Pseudopatienten gelten, bei denen die App bereits aktiviert war, oder nicht?

**Comment by ottigerb** [comment]
...hmm: M.E. sollten sich bereits aktivierte Apps bzgl. Events gleich verhalten.  

```
[event exit]
type = before_exit
days = 5
time = 08:00
due_after = 259200
overdue = ignore
description = TMT-Erfassung Austritt
survey = tmt_ng
```
Als Du diesen Block wieder eingefügt hattest - hast Du auf http://optinomic.cust.local/ schon ein `APP-FETCHER` gestartet - or?

Es scheint als müssten wir https://github.com/ottigerb/therapy-server/issues/436#issuecomment-308951308 wieder öffnen.  Kannst Du versuchen dass Issue resp. die neue Feststellung nochmals dort zu dokumentieren - Danke!

**Comment by schoenenb** [comment]
Ev. lag's am nur app-fetcher und nicht clean-upen (siehe https://github.com/ottigerb/therapy-server/issues/436#issuecomment-308951308) - ich schliesse hier auch mal und öffne allenfalls, wenn nächste Woche immer noch keine Aktivierung passiert ist.

**Comment by ottigerb** [comment]
Daumendrück!

schoenenb <notifications@github.com> schrieb am Fr., 11. Aug. 2017, 14:34:

**Comment by schoenenb** [comment]
Leider nein - zumindest keine Aktivierung bei den austretenden PatientInnen von nächster Woche, welche heute befragt werden...

**Comment by ottigerb** [comment]
...dies kann ebenfalls geschlossen werden. Or?

**Comment by schoenenb** [comment]
Ich habe nichts mehr in die Richtung gehört - danke für den Reminder.
