### ISSUE TITLE
[FIX]  Export.SQL 

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#105]
## Allgemein

Wenn eine App in der Export-Toolbox erscheinen soll, muss eine VIEW erstellt werden:

```
[sql_init]
include(includes/create_view.sql)
```
dies wiederum:
```
CREATE OR REPLACE VIEW sci_view AS 
include(includes/SCI_Export.sql)
```
Hier kann die aktuelle Version "referenziert" werden. Also nie ein SQL File überschreiben. Sondern ein neues erstellen und dann in `create_view.sql` referenzieren.

### Aktivierung der App
Die Änderungen können durch Deaktivieren / Aktivieren der jeweiligen App im [App-Store](http://optinomic.cust.local/api/#/app-store) vorgenommen werden. Dies hat keinerlei Einfluss auf den Betrieb - es werden also keine neuen Events etc. ausgelöst.  Doch:

### Warnung / Hinweis!
Trotzdem sollte dies mit Vorsicht gemacht werden, da es sein kann dass die `CREATE OR REPLACE VIEW` scheitert - auch wenn der erstellte SQL in der SQl-Toolbox einwandfrei funktioniert.  Falls dem so ist lässt sich die App nicht wieder "aktivieren". In der `Console` wird ein FEHLER ausgeben.  Dann entsprechend oben beschrieben verfahren und das alte Export.SQL File referenzieren und App damit wieder aktivieren:  Um den Betrieb sicherzustellen.

Falls ein Exportfile benötigt wird, kann das neue Export.sql File jederzeit in die SQL-Toolbox kopiert und ausgeführt werden. 

## Issue

Um diesen Aktivierungs / SQL-Fehler genauer zu eruieren muss folgendes File konsultiert werden - Optinomic only:

```
sudo less /var/log/upstart/therapyserver-api.log
```
[UNIX | HowTo's](https://github.com/ottigerb/therapy-server/wiki/UNIX---HowTo's)

Dieses Issue dient als "Taskliste" für solche Effekte.  Falls eine App nicht aktiviert werden kann bitte ich es hier zu hinterlegen.  Ich werde diesen Effekten nachgehen resp. in die Files "abtauchen" müssen.
 
### Issue-Vorlage
Pro solchen Fall kann folgende Vorlage (Kopieren / Anpassen und absenden & ergänzen)  verwendet werden:
``` 
### SCI : ch.suedhang.apps.sci.production

| Neu  |  Alt  |
|---|---|
|  `/includes/export_production_neu.sql`  |  `/includes/export_production.sql`
|  Funktioniert in SQL-Toolbox: Ja  |  Funktioniert in Export-Toolbox: Ja


- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
```

**Comment by ottigerb** [comment]
### SCI : ch.suedhang.apps.sci.production

| Neu  |  Alt  |
|---|---|
|  `/includes/export_production_neu.sql`  |  `/includes/export_production.sql`
|  Funktioniert in SQL-Toolbox: Ja  |  Funktioniert in Export-Toolbox: Ja


- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix

**Comment by schoenenb** [comment]
### AASE-G : ch.suedhang.apps.aase-g.production

| Neu  |  Alt  |
|---|---|
|  `/includes/export_production_neu.sql`  |  `/includes/export_production.sql`
|  Funktioniert in SQL-Toolbox: Ja  |  Funktioniert in SQL-Toolbox: Nein
|  Funktioniert in Export-Toolbox: Ja |  Funktioniert in Export-Toolbox: Nein


- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
- [x] App aktiviert (ohne Export)

**Comment by schoenenb** [comment]
### Act-Info Austritt : ch.suedhang.apps.actinfo_aus.production

| Neu  |  Alt  |
|---|---|
| `/includes/export_production_neu.sql`   |  `/includes/export_production.sql`
|  Funktioniert in SQL-Toolbox:  Ja |  Funktioniert in SQL-Toolbox:  Ja
|  Funktioniert in Export-Toolbox: Nein |  Funktioniert in Export-Toolbox: Ja


- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
- [x] App aktiviert (alter Export)

**Comment by schoenenb** [comment]
### Act-Info Eintritt : ch.suedhang.apps.actinfo_ein.production

| Neu  |  Alt  | AUDIT (neu - Zusatzexport) |
|---|---|---|
|  `/includes/export_production_neu.sql`  |  `/includes/export_production.sql` | `/includes/export_audit.sql`
|  Funktioniert in SQL-Toolbox:  Ja |  Funktioniert in SQL-Toolbox:  Ja |  Funktioniert in SQL-Toolbox:  Ja
| Funktioniert in Export-Toolbox: ? | Funktioniert in Export-Toolbox: Ja | Funktioniert in Export-Toolbox: Ja

- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
- [x] App aktiviert (alter Export)

**Comment by schoenenb** [comment]
### BDI : ch.suedhang.apps.bdi.production

| Neu  |  Alt  |
|---|---|
|  `/includes/export_production_neu.sql`  |  `/includes/export_production.sql`
|  Funktioniert in SQL-Toolbox: Ja  |  Funktioniert in SQL-Toolbox: Ja  
|  Funktioniert in Export-Toolbox: ? |  Funktioniert in Export-Toolbox: ?

- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
- [x] App aktiviert - ohne SQL

**Comment by schoenenb** [comment]
### BSCL: ch.suedhang.apps.bscl_anq.production

| Neu  |  Alt  | Intra|
|---|---|---|
| `/includes/export_production_neu.sql`  |  `/includes/export_production.sql`|`/includes/export_production_intra.sql`
|  Funktioniert in SQL-Toolbox:  Ja |  Funktioniert in SQL-Toolbox: Ja |  Funktioniert in SQL-Toolbox: Ja 
|  Funktioniert in Export-Toolbox: ? |  Funktioniert in Export-Toolbox: ? |  Funktioniert in Export-Toolbox: ?

- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
- [x] App aktiviert - ohne SQL

**Comment by schoenenb** [comment]
### CASE: ch.suedhang.apps.case.production

| Neu  |  Alt  |
|---|---|
|  `/includes/export_production_neu.sql`  |  `/includes/export_production.sql`
|  Funktioniert in SQL-Toolbox: Ja |  Funktioniert in SQL-Toolbox: Ja
|  Funktioniert in Export-Toolbox: ? |  Funktioniert in Export-Toolbox: ?

- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
- [x] App aktiviert OHNE SQL

**Comment by schoenenb** [comment]
### ISK : ch.suedhang.apps.isk.production

| Neu  |  Alt  |
|---|---|
|  `/includes/export_production_neu.sql`  |  `/includes/export_production.sql`
|  Funktioniert in SQL-Toolbox: Ja |  Funktioniert in SQL-Toolbox: Ja
|  Funktioniert in Export-Toolbox: ?  |  Funktioniert in Export-Toolbox: ?

- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
- [x] App aktiviert - ohne SQL

**Comment by schoenenb** [comment]
### TMT : ch.suedhang.apps.tmt.production

| Neu  |  Alt  |
|---|---|
|  `/includes/export_production_neu.sql`  |  `/includes/export_production.sql`
|  Funktioniert in SQL-Toolbox: Ja  |  Funktioniert in SQL-Toolbox: Ja 
 |  Funktioniert in Export-Toolbox: ? |  Funktioniert in Export-Toolbox: ?

- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
- [x] App aktiviert - ohne SQL

**Comment by schoenenb** [comment]
### ZüPaZ : ch.suedhang.apps.zuepaz.production

| Neu  |  Alt  |
|---|---|
|  `/includes/export_neu.sql`  |  `/includes/export.sql`
|  Funktioniert in SQL-Toolbox: Ja  |  Funktioniert in SQL-Toolbox: Ja
 |  Funktioniert in Export-Toolbox: n.b. |  Funktioniert in Export-Toolbox: n.b.

- [ ]  Optionomic | Untersucht
- [ ]  Optionomic | Fix
- [x] App aktiviert - ohne SQL

**Comment by schoenenb** [comment]
### HoNOS : ch.suedhang.apps.honos.production

| 'Neu' | Pabs |
|---|---|
|  `/includes/export_production_neu.sql`  |  `/includes/pabs_interface.sql`
|  Funktioniert in SQL-Toolbox: Ja  |  Funktioniert in Export-Toolbox: Ja

- [x] Optinomic | läuft : SQL-Toolbox mit 'pabs_interface'

**Comment by ottigerb** [comment]
Es scheint als hätten wir einen `[sql_init]` Bug entdeckt.  Diesbezüglich wurde folgendes Issue eröffnet: https://github.com/Optinomic/apps/issues/107.

### Quick & dirty solution:   
Umbenennen der neuen VIEW. Dies führt jedoch dazu, dass die Export-Toolbox mit vielen "Views" geflutet wird, welche unter umständen nicht mehr "aktiv" sind. Ich schlage vor:  Abwarten auf einen [Fix](https://github.com/Optinomic/apps/issues/107).  Falls in Zwischenzeit ein SQL-Export gewünscht wird - einfach direkt ausführen. 

Beispiel:  Anstatt
```
CREATE OR REPLACE VIEW sci_view AS 
```
ersetzen durch
```
CREATE OR REPLACE VIEW sci_view_production_neu AS 
```

**Comment by schoenenb** [comment]
### WHOQOL : ch.suedhang.apps.whoqol.production

 `/includes/WHOQOL_production.sql`  - funktioniert in SQL- & Export-Toolbox

- [x] App aktiviert - mit SQL

**Comment by schoenenb** [comment]
Wenn wir uns um die SQLs kümmern:
- [ ] noch nicht vorgenommen MedStatFID einbauen - siehe #98

**Comment by SonjaKaufmann** [comment]
Bisher war ich nicht bei diesem Issue drauf, daher wusste ich nicht, dass es dauerhafte Probleme mit der Export-Toolbox von V2 gibt.
Wann haben wir wieder eine funktionierende Yoghurt-User Export-Toolbox? Ich weiss für New Client hat es keine Prio, aber da es auch mit V2 nicht geht, sollten wir über die Prio nachdenken. Bin davon ausgegangen, das es in V2 funktioniert.
Bitte Eure Meinung dazu, dann können wir die Prio wieder anpassen, bis dahin gebe ich Prio 1.

**Comment by ottigerb** [comment]
Diese `[create views]` scheinen sich irgendwie eigenartig zu verhalten. Bin nicht mehr so überzeugt von diesem Konzept. Eine Prio 1 ist dies sicherlich nicht, da ja die Exportfiles als solche funktionieren und bestehen. Fallkonferenz / PDF ist im Fokus => Danach rückt die Admin-Toolbox wieder in den Fokus.

**Comment by SonjaKaufmann** [comment]
Gut, nur hat dann die Export-Toolbox Vorrang vor den anderen Admin-Toolbox-Funktionen. Wir brauchen eine gute Möglichkeit um Exporte machen zu können! Mich hatte das Konzept sehr überzeugt und wünsche mir für die Handhabung etwas ähnliches und nicht hineinkopieren und im SQL-Code anpassen müssen von irgendwelchen Einschränkungen. Schauen wir dann, was es für Ideen, Vorstellungen und Möglichkeiten gibt.

**Comment by schoenenb** [comment]
Dieses Thema hat sich mit den neuen Export-Toolboxen erledigt, nicht?! Von mir aus: schliessen. Ausser das bezieht sich auch auf die neuen Versionen...
