### ISSUE TITLE
Zusammenarbeit über Github

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#106]
Super, dann arbeiten wir jetzt bei Alltagsproblemen auch wieder über Github zusammen. Und für dringendes habe ich ja das Label "Kritisch".
Danke für die schnelle Klärung und sollte ich wieder davon abweichen, dann bitte sagt mir Bescheid. Bin es einfach noch nicht so gewohnt!

**Comment by ottigerb** [comment]
...@Nora:  Wenn gelesen => Close!

**Comment by schoenenb** [comment]
gelesen ;)
