### ISSUE TITLE
Mitarbeiternamen sind Dummies

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#108]
Ich wollte heute eine Therapeutin umschreiben, die von TK in die Klinik gewechselt hat und die Mitarbeiterliste ist derzeit nur mit Briten gefüllt. Könnt ihr die richtigen Namen wieder einspielen?

**Comment by ottigerb** [comment]
## ?  Ich verstehe nicht

### Eine Therapeutin einer anderen Rolle zuweisen?
1.  Den entsprechenden User unter http://optinomic.cust.local/api/#/users suchen
2.  Den selektieren User bearbeiten:  Z.B.  http://optinomic.cust.local/api/#/user/21/edit
3.  Seite nach unten scrollen und "Rolle" auswählen und speichern.


### Mitarbeiterliste ist derzeit nur mit Briten gefüllt
- Bist Du allenfalls auf dem Demoserver?

**Comment by SonjaKaufmann** [comment]
Wir unterscheiden zwischen Therapeuten EAS und Therapeuten TK, das wollte ich korrigieren und habe ich nun auch getan. Weiss auch nicht warum ich auf dem Demo gelandet bin, mhhh, aber Du hast wahrscheinlich recht. Werde dem noch nachgehen.
