### ISSUE TITLE
BSCL-GSI Normen

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#109]
Mir ist bei den Auswertungen aufgefallen, dass beim BSCL für den GSI die klinischen Normen nicht angezeigt werden. In den pdf-Versionen werden sie angezeigt, aber nicht bei der Optinomic-Ansicht.

**Comment by schoenenb** [comment]
Siehe auch #75 letzte 2 Kommentare..

**Comment by ottigerb** [comment]
Closed - because of #75
