### ISSUE TITLE
Dateneingabe durch Patienten vorbereiten

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#11]
Hier geht es darum, was die Patienten schlussendlich auf ihrem Bildschirm sehen und eingeben müssen. M.E. sollen sie möglichst wenig sehen und nicht aus versehen die Eingabe löschen oder abbrechen können. 
Wenn es irgendwie möglich ist, dann wäre ich auch dafür, wenn man die Apps zu einem Paket zusammennehmen könnte und die Patienten nicht nach jedem ausgefüllten Bogen diesen schliessen müssen und den nächsten öffnen, sondern dieser Zwischenschritt automatisiert werden könnte, denn es müssen ja alle im Gruppenassessment das gleiche Paket ausfüllen. Gibt es keinen elektronischen Tacker (Bostitch)?

**Comment by schoenenb** [comment]
Hier sehe ich zwei Ebenen:
1x allgemeine Umgebung, Bildschirmanzeige in Optinomic (Beat-Baustelle)
 --> was soll alles angezeigt werden, was nicht? (Bsp. Adresse, aktuell sogar 2x angegeben)
1x App- bzw. Limesurvey-Umgebung (Nora-Baustelle)

Die Weiterleitung zum nächsten Bogen funktioniert ja glaube ich nicht, weil pro Bogen und Patient ein Verbindungsschlüssel (Hashtag) generiert wird, stimmt das noch so?
Würde sich dieses "Problem" lösen, wenn die Daten "intern" via ng-survey erfasst würden? Oder braucht es diesen Verbindungsschlüssel nach wie vor?

**Comment by ottigerb** [comment]
Ja, das Patienten-Assessment ruft ebenfalls noch nach "Liebe".  Unnötiges entfernen => Eröffne dazu ein Issue.

Weiterleitungen von Fragebogen zu Fragebogen wird nicht unterstützt. Bei 'aufgeräumtem' Patienten-Assessment m.E. kein Thema.  Diesbezüglich ändert sich auch nichts bzgl. ng-survey.

Überarbeitung der Fragebögen:  M.E. gilt es vor allem unnötige Fragen zu verstecken. z.B. actInfo zeigt immer noch diese PID/FID fragen - muss nicht sein - oder? Bzgl. Design. Alle <font> Tags entfernen.

**Comment by ottigerb** [comment]
Ich schliesse dieses Issue aufgrund #14.
