### ISSUE TITLE
Falsche Werte zugeordnet?

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#110]
Lieber Beat, 

ich war für andere Dinge kurz in den Fragebogenauswertungen von 2 verschiedenen Fällen und da ist mir bei beiden aufgefallen, dass in manchen Bögen zuviele Messzeitpunkte enthalten sind. Z.B bei Patient 2489 hat es im TMT 2 Austritte. Der Herr 2206/stay/997 hat im TMT noch einen weiteren Messzeitpunkt, was wir eigentlich nicht haben. 
Bei einem anderen, dessen Nummer ich nicht mehr weiss, hatte ich im BSCL 2 Austritte gesehen. Kann es sein, dass da neu etwas durcheinandergeraten ist oder bin ich zufällig auf diese noch nicht korrekt zugeordneten Daten bei diesen Fällen gestossen?

Lieber Gruss
Sonja

**Comment by ottigerb** [comment]
http://optinomic.cust.local/api/#/patient/2489/stay/1203/app/ch.suedhang.apps.tmt.production

Hier liegen tatsächlich 2 Austritts-Erfassungen vor.  Es scheint als hätte der Therapeut TMT doppelt erfasst.  Beide "Events" wurden manuell gestartet.

1.   2017-05-08T08:47 
2.   2017-05-05T06:37


http://optinomic.cust.local/api/#/patient/2206/stay/997/app/ch.suedhang.apps.tmt.production
Nun, auch hier stimmt die Zuordnung. Im Fragebogen kann "Anderer Messzeitpunkt" gewählt werden.


=>  **Zuordnung ist korrekt** - m.E. liegt schlicht eine Doppelerfassung vor.

**Comment by schoenenb** [comment]
Um die Sache vielleicht noch aufzuklären:
So wie es aussieht, haben die neuen Hilfsassistentinnen beim Ablegen der Einzelassessments fleissig nochmals die TMT-Daten eingegeben, die bereits nach den Erhebungen von den PsychologInnen ausgefüllt worden war.
Ich habe ihnen ein Mail geschickt mit einer Liste aller doppelten Fragebögen und der Anleitung, wie sie die Fälle löschen können. Falls du möchtest, kann ich dir das Mail "nachschicken". Ich dachte mir, dass es sich bis zu deiner Rückkehr bereits erledigt hat und es dich deshalb nicht mehr interessieren würde...

Andere Messzeitpunkte gibt es immer dann, wenn ein kognitives Screening durchgeführt wird. Dies findet man bei Pat. 2206 zumindest in seiner RAP-Agenda, darum macht das für mich Sinn.

**Comment by SonjaKaufmann** [comment]
Liebe Nora,
Danke für die Aufklärung. Könntest du bitte noch schauen ob das bei den Hilfsassistenntinnen geklappt hat, dann muss ich nicht noch reinfunken.

**Comment by schoenenb** [comment]
Da die beiden in der Prüfungsphase stecken, werden sie sich danach asap drum kümmern. Ich habe ihnen aber gesagt, dass es von mir aus nicht so pressiert, weil die TMT-Daten nirgends geliefert werden müssen. Wenn du das anders siehst, oder für das Auswertungsprojekt immer noch laufende Daten dazugenommen werden, wär's gut, wenn du das ihnen so mitteilen kannst.

**Comment by SonjaKaufmann** [comment]
Das ist gut, wenn es keine Daten von 2016 betrifft, dann hat es ja Zeit. Vielen Dank.
