### ISSUE TITLE
Neue Patienten werden nicht geladen

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#111]
Neue Patienten scheinen nicht mehr geladen zu werden.  Nora hat geschaut, es handelt sich um Patienten die im PAPS im Polypoint aktiviert sind. Noras Vermutung ist, dass die Synchronisation nicht funktioniert.

**Comment by schoenenb** [comment]
Letzter Log der keine manuelle Aktion (z.B. Anmeldung, manuelle Gruppenzuteilung) beschreibt, scheint vom 5.5.2017 16:00 zu sein.

**Comment by schoenenb** [comment]
Aktiviert sein sollten z.B. seit gestern (9.5. Eintritt EP):
http://optinomic.cust.local/api/#/patient/3007
http://optinomic.cust.local/api/#/patient/2863
http://optinomic.cust.local/api/#/patient/886

...und andere Eintritte seit 8.5.

**Comment by ottigerb** [comment]
...tatsächlich:  Die Schnittstelle resp. unser Service [CIS_IMPORTER] scheint nicht mehr zu funktionieren. Ich steh hier ebenfalls auf dem Schlauch - Tom muss aushelfen 
=>   https://github.com/ottigerb/therapy-server/issues/440

**Comment by SonjaKaufmann** [comment]
Mhhh so ein M... , meinst Du das läuft bis morgen Mittag wieder?

**Comment by SonjaKaufmann** [comment]
Würde gerne etwas zum aktuellen Stand wissen, denn die gestern per Hand eingegebenen Assessments bei den 2 vorhendenen Patienten läd es auch nicht. Hoffe die Werte sind dennoch gespeichert. Frage mich auch was mit den HoNos die diese Woche eingegeben wurden ist. Sind die gespeichert oder gehen da Mahnungen für raus?

**Comment by ottigerb** [comment]
Ich hatte Tom gestern Abend erneut auf dieses Issue angesetzt - bisher hatte ich noch keine Reaktionen. Ich bleibe dran.

Resultate werden nicht geladen?  Hast Du hierfür Beispiele?  Sind die Daten in limeSurvey drin? Danke für mehr Info diesbezüglich - könne allenfalls ein neues Issue sein.

**Comment by SonjaKaufmann** [comment]
http://optinomic.cust.local/api/#/patient/2914
http://optinomic.cust.local/api/#/patient/1458/stay/1359/app/ch.suedhang.apps.aase-g.production
Sind gestern Nachmittag per Hand eingegeben worden. Weiss nicht ob sie im Limesurvey sind.

Ich weiss Fehler passieren und Du kannst nichts dafür, aber die Therapeuten verlieren langsam die Geduld mit dem Programm.

So doof, dann wird die Fallkonferenz heute wohl ein Blindflug :-(

**Comment by ottigerb** [comment]
http://optinomic.cust.local/api/#/  =>  Hat nun gar ein **502 Bad Gateway**!  **:-(**
=>  Es scheint als wären alle Optinomic-Services "down".   Strange!   **Sorry for trouble!!!**

Ich hoffe Tom kommt bald dazu: => ottigerb/therapy-server#440

**Comment by ottigerb** [comment]
YES:   Schon mal soweit:   👍 

____

Hi Beat, 

I was travelling so I've only seen it 30 minutes ago. I'm looking at it now. 

I'll keep you posted. 

Tom

**Comment by ottigerb** [comment]
## Huch, Entspannung

1. Server läuft wieder.

2. Auch sind die Daten geladen - habe folgendes kontrolliert:
http://optinomic.cust.local/api/#/patient/1458/stay/1359/app/ch.suedhang.apps.aase-g.production
http://optinomic.cust.local/api/#/patient/2914/stay/1390

3. Auch die Schnittstelle vermeldet - Success!


=>  Tom hat noch keine Rückmeldung hinterlassen, bin gespannt auf sein Feedback.  Anyway: Sorry for trouble und Danke für die Prüfung bzgl. Fehlender Daten / Patienten.

Falls soweit i.O.  =>   Bitte Issue schliessen!

**Comment by SonjaKaufmann** [comment]
Das hört sich toll an, drum habe ich die Daten von folgenden eingegeben, aber die Ergebnisse findet er nicht.
http://optinomic.cust.local/api/#/patient/886
http://optinomic.cust.local/api/#/patient/2863

und den findet er, obwohl auch eben eingegeben 
http://optinomic.cust.local/api/#/patient/3007/stay/1406

**Comment by ottigerb** [comment]
> The services are back online. There was a syntax error in the CRON file preventing tasks to be ran. In addition to that, `/media/cis_files` was not mounted anymore. 

->  Es scheint als hätten wir das "Schnittstellen-Drive" verloren gehabt - entsprechend konnten die Services nicht laden.  Da ich dies "forcieren" wollte hatten sich die weiteren Services ebenfalls "abgemeldet".  Hier habe ich keine Ahnung, wieso sowas vorkommen kann - hatten wir bisher noch nie.  Vielleicht ging auch das Netzwerk-Share kurz offline und unser Server konnte nicht automatisch wieder verbinden...  werde ich auf jeden Fall weiter beobachten.

-> M.E. läuft das System wieder. Daten sind keine verloren!!!   Die Daten der oben genannten Erfassungen sind da - resp. sollten bald da sein.  Nun, hat das System ordentlich "Arbeit", das verpasste "nachzurechnen". Der `result-daemon` (auf neue Ergebnisse prüfen) gefällt mir ebenfalls noch nicht - hier planen wir noch "Liebe" zu verbauen. Der neue Client sollte ebenfalls deutlich performanter arbeiten und den Server auch viel weniger belasten.  Hier bin ich "vollgas" dran.

Uff... das war ordentlich "Schreck" heute!

Danke für weitere "Auffälligkeiten" bzgl. diesen

**Comment by SonjaKaufmann** [comment]
Ja der Schreck war gross und auch für uns aufwendig, da natürlich genau an einem Donnerstag mit Fallkonferenz. Zum Glück ist alles gespeichert. 
Super konntest du dich so schnell drum tun. Tut mir immer leid wenn so was an deinen Therapietagen passiert.
Wünsche ein schönes Wochenende!
Ufff und ausatmen!

**Comment by ottigerb** [comment]
... Daaaaanke, liebe Sonja. Ach ja - Computer sind auch nicht immer so
"digital". Anyway - ich hoffe wir haben dieses Issue nun bald ausgemerzt
haben. Ich hoffe ebenfalls, dass Euer Mehraufwand sich in Grenzen hält.
Auch Dir ein frohes Wochenende.

SonjaKaufmann <notifications@github.com> schrieb am Do., 11. Mai 2017,
15:12:

**Comment by schoenenb** [comment]
Ich würde sagen ist erledigt? Die nicht angezeigten Fragebögen (886 und 2863) waren im falschen (vorherigen) Fall drin, die sind nun richtig platziert - hier unbedingt schauen, dass die Fragebögen nicht einfach bei irgend einem verfügbaren Fall eingetragen werden. Bei 3007 war das nicht möglich, weil er nur einen Fall hat - drum bereits am richtigen Ort. :)
