### ISSUE TITLE
Auswertungen ausserhalb des Rahmens

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#113]
Habe diese Auswertung im Pdf von http://optinomic.cust.local/api/#/patient/3013/stay/1427/app/ch.suedhang.apps.pdf_druckvorlagen
gefunden
![image](https://user-images.githubusercontent.com/20124244/26913979-c1966ef4-4c1e-11e7-812a-f103de6d6f56.png)
Ich glaube da stimmt etwas nicht.

**Comment by schoenenb** [comment]
Sorry fürs hin und her mit assignen - ich dachte, ich hätte den min_lastpage auf 13 gesetzt, damit das nicht mehr vorkommen kann. Allerdings hatte ich das bei der "parent app" gemacht und nicht bei der "südhang production app" - ich hole das gleich nach. Problem: Der Patient hat den Fragebogen nach Ausfüllen nochmals geöffnet und leer wieder geschlossen - da er auf Seite 5 gelandet ist und die letzte auszufüllende Seite noch auf 2 gesetzt war, hat es den ausgefüllten Bogen mit den leeren Angaben überschrieben. Durch löschen des leeren Fragebogens in Limesurvey und erneuten Abgleich auf der Patientenseite hätten die Daten "ganz einfach" reingeholt werden können...

**Comment by ottigerb** [comment]
:-)  Ich habe noch eine zusätzliche Sicherheit eingebaut: https://github.com/Optinomic/apps/commit/7909d32bee7143c08e862facf70eb2a476518444
