### ISSUE TITLE
Patient kann nicht geöffnet werden

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#114]
Es kommt zwar keine Fehlermeldung, aber die folgende Patientin kann icht geöffnet werden.
http://optinomic.cust.local/api/#/patient/2861

**Comment by schoenenb** [comment]
Das liegt daran, dass die Patientin ausserkantonal ist und daher ambulant verrechnet wird. Weil ich länger nicht im Monitoringfile nachgeschaut habe bzw. es dort nicht vermerkt war, habe ich sie bisher auch nicht im Pabs aktiviert. Ich werde die Patientin über Mittag aktivieren.
