### ISSUE TITLE
/client.new 

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#115]
Folgende Punkte wurden festgehalten:

### Login
- [x] Anmeldung mit `ENTER` ermöglichen.
- [x] Verschobenes Icon in Mobile-Darstellung.
- [x] Implement: Forgot PW.

### Startseite
- [x] Nur User-Tasks (Role-Tasks versteckt erreichbar).
- [x] Entwicklung / Optinomic-News erreichbar (für Interessierte).

### Allgemein
- [x] User-Kürzel verwenden (falls vorhanden) ansonsten aus Nachname/Vorname erstellen.
- [x] Bessere Icons für Tasks resp. Applikationen.
- [x]  Sprechende Icons ( Bild & Text  oder  bei Mouse Hover => Erklärung).
- [x]  Suchfeld-Position: Oben bei grossen Screen / Unten bei Mobile.

### [Patientenübersicht](https://demo.optinomic.org/client.new/#/patient/1)
- [x]  Mitglied der Gruppe (Auflistung in welchen PG's sich der Patient befindet). Allenfalls unnötig, wenn [App _Belegung] 
 (http://optinomic.cust.local/client.new/#/patient/2294/stay/1089/app/com.optinomic.init.poly_stay/template/init) dargestellt wird. => Würde sehr viele API calls bedeuten.
- [x] Statt FID: Optinomic-ID   die  `cis_fid` darstellen.
- [x] "stay-ID" statt "ID"

### [Fallübersicht](https://demo.optinomic.org/client.new/#/patient/1/stay/144)
- [x] `Reports` - Darstellung (Fallkonferenz...).
- [x] Möglichkeit App-Templates mit definierter Höhe darstellen lassen.

### [Appübersicht](https://demo.optinomic.org/client.new/#/patient/1/stay/144/app/org.optinomic.apps.polymer_cli)
- [x] Tasks für diese App/Patient darstellen.
- [x] Falls kein offener Task vorhanden: Möglichkeit `JETZT AUSFÜHREN`
- [x] Allenfalls direkt Ergebnis darstellen (wenn nur 1 Template vorhanden ist) => Überdenken.

### Apps
- [x] Max-Width festlegen =>  Keine Verzogenen / Übergrosse Grafiken.
- [ ] Nora: App-Namen etc. einheitlich vergeben!
- [ ] Nora: Untermenüs (Resultate/Score o.ä.) – einheitliche Namensgebung
- [x] Möglichkeit zur übersichtlicheren Darstellung (HTML-Formatierung?) mit Absätzen in Beschreibung (--> oder soll das übers readme gelöst werden?!)
- [x] bei Admins Anzeige der Daten in der App

### Patienten / Fallgruppe
- [x] Analog [altem Client](http://demo.optinomic.org/api/#/patient-groups/groups_all).

### Patientengruppen
- [x] Multi-Select Patienten manuell zur Gruppe hinzufügen

### Patienten-Übersichtslisten (Merkliste / Patientenliste / Alle Patienten)
- [x] Möglichkeit zu automatischer Einstellung der individuellen Patientenliste prüfen (z.B. für PsychologInnen mit Filter "eigene Patienten")

##### [Admin | Benutzer](https://demo.optinomic.org/client.new/#/admin/users)
- [x] Grid mit Darstellung von archivierten Benutzer.
- [x] CRUD von Benutzer möglich.
- [x] Passwort ändern / Rolle zuweisen möglich.
- [x] neue Benutzer erfassen können
- [x] Filterfunktion z.B. nach Rolle, archivierte ausblenden

##### [Admin | SQL-Toolbox](https://demo.optinomic.org/client.new/#/admin/sql-toolbox)
- [x] Wieso kein Code-Highlighting in BUILD-Version?
- [x] Fehlermeldung bei fehlerhaftem SQL-Code / vorhandene Daten löschen.
- [ ] Abfrage-Vorlagen anbieten.

##### Admin | Export-Toolbox 
- [ ] Gemäss Client 1 -> Zuerst SQL-Toolbox "optimieren".

##### Fallübersicht: 
- [x] Applikationen mit Daten färben, 0 Daten 
- [ ] Datenübersicht pro Fallgruppe (Patient (Name, Vorname etc.) /  Fall (START STOP) / App / Erhebungszeitpunkt )
- [x] Datenübersicht: Survey_Responses

##### Hirnschmalz: 
- [ ] Übertritte - Events auslösen für Patienten-Assessment - automatisch?
- [ ] Selektierte Patient in Übersicht - Darstellung?
- [x] Präsentationsmodus

**Comment by SonjaKaufmann** [comment]
Punkte von Nora:

- [x] 	Startseite  Wie sieht die effektiv aus? **Meine Aufgaben** / Meine Rollenaufgaben (nur ev.)

- [x] 	Eigene (= MA) Daten / Funktionen: Ans Ende des Menüs (vor „Abmelden“)

- [x] 	Zusammenstellung von Scores verschiedener Apps doch weiterhin möglich? (Polymer | CLI)

- [x] 	PDFs:
- Idealerweise auf Startseite des Falls oberhalb der Aktivierten Applikationen (wie bisher) mit Direktlink für:
	Fallkonferenz (nur relevante, SF fragen)
	Eintritt (für Psy / Pat)
	Austritt (für Psy / Pat)

- [x] Patient:

- Patientenliste:
	Individualisiert?
	Muss selbst eingestellt werden? Automatische Generierung je Rolle?
•	Psy (EP / EAS / TK): eigene Fälle, aktuell + je
•	QM, Admin: alle Fälle im Zeitraum von 1.1. letztes Jahr?
- Einbau von FID – SUPER!!! (Ev. ersetzen durch Fallnummer: / Fall xxx?)
- Wofür stehen die beiden Icons   ?
	Kalender = Fall
	A√ = Applikationen (aktiviert / deaktiviert / (De-)Aktivieren)
	Braucht es  noch, wenn Icons oben immer stehen?
- Apps / Patientendaten:
	Layout:
•	„Abgeschnittene“ Titel (Bsp. Ottiger, Optinomic, Polymer) -> Problem nur bei grossen Bildschirmen
 
- [x] App-Namen etc. einheitlich vergeben!
- [x] Auch Untermenüs – einheitliche Namensgebung
- [x] Darstellung (HTML-Formatierung?) noch überlegen -> Übersicht!
- [x] Datenausgabe bei Admins?

- [x] 	Patientengruppen:

- Aktivierung?
- Automatische / manuelle Zuordnung?

- [x] Exportfunktionen

- Export-Toolbox
	Funktionieren SQL-Codes wieder?
	Für Erhebungszeitraum Auswahl-Kalender?
	Vorlagen für Event/Stay/Response?
- SQL-Toolbox
	Fehlermeldung, wenn SQL fehlerhaft ist

- [x] Ansicht für Patienten bleibt gleich



_**EDIT:  Bereits mit Nora besprochen und in OP (Opening Post) übernommen.**_

**Comment by SonjaKaufmann** [comment]
Ich finde der New Client sieht sehr gut aus und ist wirklich übersichtlicher und intuitiver. Mir gefällt auch sehr, dass die FID-Nummer mit ausgegeben wird. Bin gespannt wie es bis zum 6.7. weitergeht.

Meine Punkte wären noch:

- [x] Beim **Login** sollte man nach Eingabe des Passwortes auch durch Enter weiterkommen und nicht umbedingt auf den Button Anmelden drücken müssen.

- [x] Ich fände das **Suchfeld für Patienten** oben über der Patientenliste viel praktischer, dann sieht man die Funktion und vergisst nicht, wenn man etwas gesucht hat  _**Sehe ich nicht so - das wichtigste ist der Patient - nicht meine Suche. Zudem ist die Darstellung auf dem Handy deutlich unübersichtlicher.**_

- [x] Ja die **Exorttoolbox** wie im alten Client wäre mir auch wichtig, auch mit den Auswahlfeldern. Und am besten mit der Standardeinstellung des Exports mit Pipes |

- [x] Generell fände ich es gut, wenn die **Icons sprechend** wären, also wenn man mit dem Cursor drauf geht, dass dann der Titel der Funktion erscheint. Finde die Piktogramme nicht immer selbsterklärend.

- [x] **Graphiken 1:** Finde es ungünstig, dass man 2 Mal klicken muss um zu den Graphiken zu kommen, da erst das sogenannte Inhaltsverzeichnis kommt. Fände sinnvoller zu den Ergebnissen zu kommen und dann übert einen Link/Titel noch zum Inhaltsverzeichnis gehen zu können, wenn dieses separat sein muss.

- [x] **Graphiken 2:** Im Moment sind die Graphiken noch sehr breit gezogen (verzogen).

- [x]  **PDFs** funktioniert auf New Client m.E. aktuell noch nicht, bzw. es hat lange geladen, ist aber nicht zu einem Ergebnis gekommen _**Die Version ist unverändert - resp. die gleiche Version wie Client V1. =>  Die PDF-App benötigt wohl noch etwas "Fehlertoleranz".**_

- [x]  Gibt es für den Administrator noch die Funktion bei den Z-Werten die Vergleichsgruppe auszuwählen? Bzw. wird es noch die **Zusammenfassungsfunktionen** geben, welche wir Mal besprochen haben. z.b. nach Jahren vergleichen oder Männer und Frauen über bestimmten Zeitraum, Bildungsgruppen vergleichen _**Klar, solche User-Apps können wir gerne angehen - freu mich auch schon auf diesen Teil.**_

**Comment by ottigerb** [comment]
Ich habe die Punkte "kommentiert" und die relevanten Punkte in den Opening-Post:  ToDo's übernommen.

**Comment by SonjaKaufmann** [comment]
Super, danke.

Zu dem Suchfeld, vielleicht habe ich mich falsch ausgedrückt. Denn ich suche ja nur nach Patienten, wenn ich eine lange Liste habe, z.B. mit allen Patienten und Herrn XY finden möchte und nicht ganz runterscrollen will. Das Suchfeld übersieht man da unten sehr leicht, aber vielleicht kann man es auch optisch etwas mehr hervorheben und es ist Gewöhnungssache. Aber bezüglich Gewöhnung muss ich schon sagen, das ich von Internetseiten gewohnt bin irgendwo oben ein Suchfeld zu haben. Mir ist es halt vorhin passiert, dass ich eine Patientin gesucht habe und dann bin ich zurück auf alle Patienten und dann ist das Suchfeld ja immer noch aktiv und bis mir das eingefallen war,... 
Kurz gesagt: Ich finde oben besser. Wir können ja vielleicht noch Nora, Wale und Noemi (Hilfsassisstentin) fragen.

**Comment by SonjaKaufmann** [comment]
Wie sollen wir mit diesem Issue verfahren, damit es nicht zu gross wird bzw. unübersichtlich. Willst du wie oben die Punkte prüfen und ggf. ins Opening-Post übernehmen und wenn nicht passend, dann durch Kommentar erklären oder willst Du verschiedene Issues? 
Könnten wir die Position des Suchfeldes zu diskutieren zu den Issues im noch in den Opening-Post setzen.

- [x] Mir ist noch aufgefallen, dass die FID nicht das Format hat, welches vom PABS ausgegeben wird und daher als unser Leitformat gilt. Das Format ist PID*10000+Fall. Beispiel PID=12345 Fall=1 (oder Fall=11), dann FID=123450001 (FID=123450011).

- [x] Ist es möglich bei den Fallen anzugeben, in welcher OE sie sind? Eventuell wäre es ja sogar möglich unsere 3 Angebote (nur EAS, nur EP, EAS&EP) zu unterscheiden, wenn man die OE bei Eintritt und die OE bei Austritt kombiniert. Aber auch sonst wäre die OE interessant und zukunftsträchtig, wenn irgendwann auch ambulante Fälle ins Optinomic kommen. Mir ist aufgefallen, dass man so gar nicht sieht ob jemand in der TK oder stationär ist. Oder habe ich die Info übersehen?

- [x] Habe in V2 und New Client versucht bei einem Fall die Druckvorlagen_Pdfs zu öffnen und es geht bei beiden nicht. In V2 unter Berichte Ein- und Austrittsassessment geht es. Aber beim gleichen Fall dreht es im New Client unter Druckvorlagen "Assessment Report only" ohne Ende.

**Comment by ottigerb** [comment]
Genau:   Ich prüfe neue Einträge und übernehme diese ins OP.

**Übernommen**:  Suchfeld-Position - meine Meinung ist diesbezüglich klar!  :-)

**Kommentar zu den Punkten FID & OE:** Die FID ist die, welche die Schnittstelle liefert. Südhang-Spezifisches können wir dann durch den Punkt `Möglichkeit App-Templates mit definierter Höhe darstellen lassen.` erfüllen.  

**PDF**:  Dies ist exakt die gleiche App / gleiches Frame:  Das kann keinen Unterschied haben. Nenne mir doch in solchen Fällen die komplette URL (Fall/Patient).  Dann kann ich schauen, wo und warum ein Fehler auftaucht.  Falls es "ewig" dreht - einfach mal die Seite mit F5 neu laden.

**Comment by SonjaKaufmann** [comment]
**PDFs:** Client new, F5 hilft nicht, dreht weiter ewig: http://optinomic.cust.local/client.new/#/patient/2976/stay/1383/app/ch.suedhang.apps.pdf_druckvorlagen/template/assessment_report_only
V2, hier komme ich relativ zügig zu den pdfs:
http://optinomic.cust.local/api/#/patient/2976/stay/1383/report/ein____austritts_assessment

**Zu Kommentar zu den Punkten FID & OE:** -> kannst Du bei dem Post noch in Klammern schreiben: PABS-FID und OE, sonst weiss ich später nicht was damit gemeint ist.

**Zu Suchfeld-Position:** Ja deine Meinung ist klar und ich möchte von den anderen noch die Meinung einholen. Sehe es nicht auf der OP-Liste. Oder ist die OP-Liste nicht dein erster Eintrag in diesem Issue?

**Wie funktioniert die OP und was ist sie genau?** Wenn etwas abgehakt ist, heisst das dann das es erledigt ist? Z.B. das mit dem Enter bei Login funktioniert nämlich bei mir nicht. Oder heisst der Haken, dass Du es auf eine andere Liste gesetzt hast?

**Comment by ottigerb** [comment]
Die neuste Version ist immer auf:  https://demo.optinomic.org/client.new/   -> bitte dort testen!
=>  Allenfalls muss der [Browser-Cache geleert](http://lmgtfy.com/?q=chrome+browser+cache+leere) werden.

**Comment by SonjaKaufmann** [comment]
Ach so .......
Aber auf Demo finde ich doch nicht unsere Patienten, oder? Also da kann man "nur" gucken was geht, aber nicht anhand eines Beispiels V2 und New Client vergleichen, oder? Aber da klappt es mit dem ENTER :-) Super!
Für welchen Fall muss ich den Browser leeren, denn ich möchte nicht meine Kennwörter verlieren.

Ach ich bin gespannt auf den 6.7., zur Vorstellung werden auch die beiden Hilfsassisstentinnen QM kommen, weil sie im Klinikalltag am meisten mit dem Programm schaffen und den Wale habe ich eingeladen, er ist allerdings bis zu der Woche in Ferien, weiss nicht ob er dann Zeit hat.

**Comment by ottigerb** [comment]
> PDFs: Client new, F5 hilft nicht, dreht weiter ewig: http://optinomic.cust.local/client.new/#/patient/2976/stay/1383/app/ch.suedhang.apps.pdf_druckvorlagen/template/assessment_report_only
> V2, hier komme ich relativ zügig zu den pdfs:
> http://optinomic.cust.local/api/#/patient/2976/stay/1383/report/ein____austritts_assessment

Ich habe die neue Version auf den Südhang-Server gepusht. Scheint mir bereits etwas "besser" - nicht?   So wie es für mich aussieht, kämpfen  `/pdf` & `/assessment_report_only` um "Aufmerksamkeit".  Aktuell lade ich immer alle Templates - das aktuelle Template mit 3 Sekunden "Vorsprung", damit sich die anderen nicht in die Quere kommen. Hope that helps.

**Comment by SonjaKaufmann** [comment]
Lieber Beat,

leider verstehe ich das nicht mit pushen und Templates und demo oder südhang,...... Es ist ja kein aktuelles Problem, denn ich bekomme die PDFs ja in V2. Wollte Dir nur an einem Beispiel das ich ausprobiert habe sagen, dass es beim New Client Südhang noch nicht so funktioniert. Und wenn ich es richtig verstanden habe, dann weisst Du das und aktuell ist der Demo das ausschlaggebende um die Funktionen zu testen und das wusste ich nicht. Ich denke nur, wenn wir testen sollen, dann müssen wir vorher gut besprechen was man wo und wie testen kann und dann müssen wir es mit Beispielen durchgehen. Im Moment können so Laien wie ich und vielleicht auch die QM-Assis auf Demo mal rumklicken zum Kennenlernen und das Testen mit Südhangdaten wird dann nach dem 6.7. parallel mit V2 laufen, wenn Du New Client quasi zum Testen freigibst. Ist das richtig so?

**Comment by ottigerb** [comment]
Zur Info:  Ich habe `ch.suedhang.apps.pdf_druckvorlagen` etwas "robuster" gestaltet.
=>  Ich finde keine Patienten mehr, welche hier "ewig laden" - auch nicht im `/client.new`!

**Comment by schoenenb** [comment]
Scheint mir auch schneller zu gehen... :+1:

**Comment by schoenenb** [comment]
Ich habe am OP folgende Kategorien um Punkte ergänzt, welche meiner Meinung nach noch fehlten:
- Patientenübersicht
- Apps
- Admin | Benutzer
+ zusätzlich: Patienten-Übersicht

Mein Standpunkt zu der Suchfeldfrage sieht gleich aus wie der von Sonja: Suchfeld oben einbauen oder zumindest den Kunden die Option lassen, dies am Seitenanfang platzieren zu können.

Der Punkt zur FID im MedStat-Format (PID-00-Fallnr.) ist zwar abgehakt, es ist aber nach wie vor das Format drin, welches direkt von der Schnittstelle geliefert wird (PID-Fallnr.-00). Geht da noch was?

Auf den Punkt zur Angabe der Organisationseinheit (korrigiert mich, wenn mit OE nicht das gemeint ist!) ist Beat nicht eingegangen - geht das, dies anzuzeigen? (Ich stell mir das vor wie - ist Mitglied der Gruppe EP / EAS / TK) Oder ist es sogar bereits umgesetzt?

**Comment by ottigerb** [comment]
> Möglichkeit zur übersichtlicheren Darstellung (HTML-Formatierung?) mit Absätzen in Beschreibung (--> oder soll das übers readme gelöst werden?!)

=> Description ist nur ein String => also keine Formatierung. Details etc. wie gesagt:  `readme.md`

Suchfeld:  Nun, ich staune über das Echo bzgl. diesem Thema. Worauf ich mich einlassen könnte: Auf grossen Screens `> Medium` Suchfeld oben.  Auf dem Mobile bleibt Suchfeld unten.

FID/OE:  Die FID kann in der [Patientenübersicht](http://therapyserver.dev/client.new/#/patient/1) nicht geändert werden.  Wir können im [Fall](http://therapyserver.dev/client.new/#/patient/1/stay/144) ein App-Template  einblenden lassen. Dieses Template gilt es von der [App _Belegung](http://optinomic.cust.local/client.new/#/patient/2294/stay/1089/app/com.optinomic.init.poly_stay/template/init) zu erstellen.  Da haben wir dann die ganzen Belegungen / Polypoint ID's etc. etc. 

Mitglied der Gruppe:  Interessante Idee!  Das könnte in der [Patientenübersicht](http://therapyserver.dev/client.new/#/patient/1) dargestellt werden. => Hinzugefügt im OP.

**Comment by schoenenb** [comment]
Da Mobile bei uns nicht gebraucht wird, mache ich mir dort halt nicht so Gedanken... ;)

**Comment by SonjaKaufmann** [comment]
**Suchfeld:** :-) Ja so sind wir :-) Ausserdem sind wir ausser bei so manchen Design-Issues nicht gewohnt das Du nein sagst :-) Finde ich eine super Lösung, denn Mobile benutzen wir ja nicht. 
**FID/OE:** Für die FID wäre es mit vor allem für die Exporte wichtig das andere Format haben zu können.
**OE:** Fände ich in der Fallansicht sehr gut und auch für die Exporte extrem hilfreich!
Wünsche einen guten Wochenstart!

**Comment by SonjaKaufmann** [comment]
Filter ist sehr gut, habe noch kleinen Schreibfehler gefunden:
![image](https://user-images.githubusercontent.com/20124244/28008986-fefc26ea-6559-11e7-8e1d-65633d9e3362.png)
Fände es noch gut, wenn es einen anderen Namen als Patientenliste hätte, weil da denke ich an alle Patietnen. Eventuell **Patientenauswahl** oder **ausgewählte Patienten**?

**Comment by ottigerb** [comment]
### Patientenauswahl
Danke:  Schreibfehler ist korrigiert und umbenannt in:
> Patientenauswahl

=> Wird mit dem nächsten Stable geliefert.

### Erfüllungsgrad
Übrigens: http://optinomic.cust.local/client.new/#/user/app/com.optinomic.user.apps.fulfillment/template/fulfillment   funktioniert soweit.
=>  Ich werde hier jedoch weiter etwas "hirnschmalzen" um Patientengruppen und all deren aktivierten Applikationen basierte Erfüllungsgrade darstellen zu können.

**Comment by SonjaKaufmann** [comment]
Kann es nicht anschauen, kann mich über den Link und generell nicht mehr bei New Client einloggen

**Comment by SonjaKaufmann** [comment]
Lieber Beat,
von unserer Seite wäre der nächste Schritt, dass die Fallkonferenz-App oder Bericht funktioniert. Im Moment kommen noch die falschen Bögen beim anwählen und auch nicht alle Bögen.  Dies ist sehr wichtig um die Praktikabilität für die Fallkonferenz mit den Therapieleitenden zu besprechen und diese sind unsere **wichtigsten User!** Im Moment ist es noch kompliziert dort hin zu kommen für eine ganze Gruppe von Patienten. Vielleicht wäre es doch sinnvoll, wenn es für diese Anwendung eine Ebene mehr hätte. Diesen Punkt müssen wir irgendwie griffiger hinbekommen. Die Daten laden zwar schneller, aber dafür muss man bedeutend mehr klicken. Vielleicht hast du ja noch Ideen für einen einfacheren Zugang. Kannst Du uns sagen, bis wann Du ungefähr die New Client-Fallkonferenz-Ansicht (meine mit den alten Profilen, also noch nicht die Polymer) auf Südhang hast. Könntest du auch eine Abschätzung abgeben bis wann die neuen Polymer-Auswertungen für all unsere FB fertig sein könnten, damit wieder eine Darstellung in einem Frame möglich wäre (was natürlich auch neue PDFs bedeutet).
Diese Angaben bräuchten Wale und ich noch für die weitere Planung der Einführung.
Herzliche Grüsse
Sonja

**Comment by ottigerb** [comment]
**Fallkonferenz-App oder Bericht funktioniert:**  Hier schlage ich einen "Patientengruppen-Navigator" vor. Die Navigationsleiste verschwindet und ein neuer "Navigator" öffnet sich. Hier kann der User die gewünschte Patientengruppe selektieren/speichern. Dargestellt werden alle Patienten in dieser Gruppe. Allenfalls mit einem Switch -> direkt in den letzten Fall wechseln. Oder analog: Icon -> letzter Fall;  Name führt zu Patienten-Seite. Ich denke so haben wir viele "Fliegen" erledigt und die Übersichtlichkeit leidet nicht. Auch wäre dann der User mit einem Klick direkt beim PDF oder Reports.
=>  Aufwand: Ca 2 Wochen. Ich gehe dieses Feature an. **Wichtigste User!**

**Polymer-Auswertungen | Z-Score Lininiendiagramme:** Dies sollte nicht so viel Aufwand sein, alle bestehenden Apps im Template also der Appansicht zu erstellen.
=>  Aufwand 1-2 Arbeitstage.

**Polymer-Auswertungen | Z-Score Lininiendiagramme im PDF:** Dies ist Arbeit - auch bin ich mir unsicher, ob ich dieses PDF-Ding nicht besser auch als "Polymer-App" umsetze. Auch eine Erweiterung der PDF-App wäre wohl ähnlich viel Aufwand. Es werden ja die meisten Grafiken durch die neuen Z-Score Grafiken ersetzt. Stanine-Grafiken könnten allenfalls auch hier "gelöst" werden. Entsprechend ist hier die Aufwandsabschätzung im Moment schwer.  
=>  Aufwand 4-6 Arbeitstage.

**Comment by schoenenb** [comment]
#### Erfüllungsgrad
So wie's jetzt aufgebaut ist, scheint mir die Übersicht nicht sehr hilfreich. Ich dachte, wir hätten bei der Sitzung letzte Woche was von einer Tabelle (ähnlich der SQL-Toolbox) gesprochen - geht so was nicht?

**Comment by ottigerb** [comment]
...soeben ein Stable im Südhang angekommen.  Diverse Bugfixes rund um Berichte, User-Apps etc. etc.

**Comment by schoenenb** [comment]
Zusatzwunsch (im OP ergänzt):

### [Admin | SQL-Toolbox](https://demo.optinomic.org/client.new/#/admin/)
##### [Admin | Benutzer](https://demo.optinomic.org/client.new/#/admin/users)
- [ ] Filterfunktion z.B. nach Rolle, archivierte ausblenden

Könnte man die Userliste auch drucken? Oder geht das nur über die SQL-Toolbox?

**Comment by schoenenb** [comment]
Woran kann das liegen, dass bei mir in der Ansicht die Verknüpfungen zu den Übersichten neben den einzelnen Fragebögen erscheinen...
![image](https://user-images.githubusercontent.com/15833792/38924430-3d41d144-42fd-11e8-9fce-1a625e27ffda.png)

...bei PB (ID 7) jedoch nicht?
![image](https://user-images.githubusercontent.com/15833792/38924365-115e0ee4-42fd-11e8-9223-add774ce5e36.png)

An der Bildschirmgrösse sollte es nicht liegen, weil es bei mir sogar bei Fenster-Verkleinerung funktioniert...

**Comment by ottigerb** [comment]
https://github.com/Optinomic/apps/issues/115#issuecomment-382328406 =>  Verstehe ich richtig:  Die Verknüpfungen werden nicht angezeigt?  

=> Standard - Fix versucht:  Abmelden, durch Mülleimer Speicher löschen - neu anmelden.

**Comment by schoenenb** [comment]
Sorry, zu wenig präzise: beim betroffenen Therapeuten werden sie unten angehängt. Hängt's trotzdem mit dem cache zusammen?

**Comment by ottigerb** [comment]
...öhm - diesen Effekt habe ich noch nie gesehen. Hmm... kann ich mir nicht vorstellen, dass es etwas mit dem User zu tun hat. Allenfalls ist ein Cache / Browser-Daten löschen interessant. Browser grösser, kleiner machen - damit es sich wieder neu "ordnet" hilft ebenfalls nicht?

**Comment by schoenenb** [comment]
Ich hatte leider nicht gross Zeit zum ausprobieren, aber ich werde es ihm mal vorschlagen.

**Comment by ottigerb** [comment]
...ich schliesse dies mal bzgl. Übersichtlichkeit - falls noch was "offen" gewünscht ist - einfach neues Issue eröffnen.
