### ISSUE TITLE
Apps:  readme.md

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#116]
## Hintergrund

Apps sind nun in der Lage ein "App-Manual" darzustellen. Dieses Manual dient zur ausführlichen Beschreibung von Applikationen. Dieses Markdown-File kann Umbrüche, Grafiken, Links etc. beinhalten. 

Vgl. diesbezüglich:  https://doc.optinomic.org/V2/Developers/app_spezifikation.html#readme-optional

## Issue / ToDo's

- [x] Alle Apps mit folgendem Tag (`opapp.m4`) ausstatten:
```
[readme]
include(readme.md)
```
- [ ] Inhalt des bestehenden `readme.md` anpassen - falls nicht bereits sinnvollen Content beinhaltet.  Als [Vorlage könnte z.B. dieses File dienen](https://github.com/Optinomic/apps/edit/master/com.optinomic.apps.aus/readme.md).

**Comment by schoenenb** [comment]
- [x] für Südhang-Apps readme's und Inhalt angepasst
_edit_ ...wobei Inhalt bedeutet, dass nun überall die gleiche Struktur vorliegt, eigentlicher Inhalt ist nur beschränkt vorhanden

**Comment by schoenenb** [comment]
Momentan sind +/- die gleichen Beschreibungen drin wie in der App - sind da noch mehr Infos zur Auswertung und Interpretation gewünscht? Und wenn ja, wie ausführlich?
- in der Fallkonferenz-App können diese durch Klicken auf das Fragezeichen eingeblendet werden
- in der Einzel-App werden die Informationen angezeigt, wenn man in der Übersicht auf den Titel klickt statt auf das Kästchen (für die direkte Anzeige der Resultate)
