### ISSUE TITLE
Austritt nicht übernommen

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#117]
Ich bin bei folgendem Patienten über Probleme gestolpert:
http://optinomic.cust.local/api/#/patient/3037/stay/1422
Der Patient hat zwei Aufenthalte. Er erscheint aber nicht auf der Patientenliste der Therapeutin die ihn aktuell gehandelt. Dann bin ich darauf gekommen, dass es daran liegt, dass der erste ambulante Fall noch nicht geschlossen ist. Daraufhin habe ich im PABS und RAP nachgesehen und da ist aber der 19.5.2017 als Austrittsdatum eingetragen.
Zum einen wäre ich froh, wenn Du herausfinden könntest, warum das Austrittsdatum nicht geladen wird und zum anderen denke ich , wir müssen uns dieses Problem grundsätzlicher überlegen, denn es kann bei unseren Strukturen durchaus vorkommen, dass jemand einen offenen ambulanten Fall im Ambi hat und der während des stationären Aufenthaltes nicht geschlossen wird. Und aus dem oben genannten Problem folgere ich, dass wir dann Probleme bekommen.

**Comment by schoenenb** [comment]
Falls so was wieder mal vorkommt noch zum Nachlesen:
Wie es scheint, wurde der Patient bei Eintritt als stationär erfasst und später auf ambulant gewechselt. Da die Schnittstelle zu Pabs keine Ambulanten Daten abgleicht, wurde somit auch kein Austrittsdatum abgegriffen. Der Fall kann normalerweise von Hand abgeschlossen werden, funktioniert im Moment (14.7.17) aber gerade nicht...

**Comment by schoenenb** [comment]
- "Alle Einträge" aktivieren
![image](https://user-images.githubusercontent.com/15833792/28207211-1ca54c4e-6889-11e7-9c2a-74c84a4e9ce9.png)
- ganz nach unten scrollen
- Austrittsdatum (Stop) auswählen oder eingeben (1) und speichern (2)
![image](https://user-images.githubusercontent.com/15833792/28207286-73f277ec-6889-11e7-87e0-e5d705f30856.png)
