### ISSUE TITLE
Komische TMT

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#118]
Auf den PDf wird der TMT komisch ausgegeben
Siehe z.B. TMT-Eintrittsassessment-File von folgendem Patienten:
http://optinomic.cust.local/api/#/patient/3089/stay/1482/report/ein____austritts_assessment

Zudem sind die Farben beim TMT falsch. Ich glaube wir hatten das schon Mal korrigiert, aber hohe negative Werte sind langsamer als die Vergleichsgruppe und damit rot und hohe positive Werte sind schneller als die Vergleichsgruppe und damit grün.

Wäre froh, wenn dies sehr bald korrigiert würde, denn es führt zu falschen Interpretationen

**Comment by ottigerb** [comment]
## Farben
Ich habe die Farben (Auffällige Testleistung) wie folgt angepasst:

```Javascript
// Auffällige Testleistung |  Vergleich mit den Gesunden 
                if (messung_obj.zscore.zscore >= 2) {
                    // Auffällige Testleistung: Grün
                    messung_obj.zscore.zscore_color = '#4CAF50';
                };

                if (messung_obj.zscore.zscore <= -2) {
                    // Auffällige Testleistung: Rot
                    messung_obj.zscore.zscore_color = '#F44336';
                };
```

Scheint soweit alles i.O. zu sein:

## App
![bildschirmfoto 2017-07-03 um 15 08 17](https://user-images.githubusercontent.com/2470873/27794600-172b605c-6003-11e7-9779-ddd468775daf.png)

## PDF
![bildschirmfoto 2017-07-03 um 15 19 03](https://user-images.githubusercontent.com/2470873/27794601-172bdcc6-6003-11e7-9a07-a384b7435016.png)
