### ISSUE TITLE
Z-Werte für den WHOQOL_BREF

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#119]
Für diesen Bogen können wir auch Z-Werte berechnen und Z-Wert-Graphiken machen, da wir Normen haben. Wir haben halt nur die beiden Skalen Physische und Psychische Lebensqualität drin.
Hänge die Normtabellen hier noch rein.
[WHOQOL_Bref Normen 1.pdf](https://github.com/Optinomic/apps/files/1152194/WHOQOL_Bref.Normen.1.pdf)
[WHOQOL_Bref Normen 2.pdf](https://github.com/Optinomic/apps/files/1152193/WHOQOL_Bref.Normen.2.pdf)

**Comment by ottigerb** [comment]
Super !

SonjaKaufmann <notifications@github.com> schrieb am Mo., 17. Juli 2017,
12:04:

**Comment by schoenenb** [comment]
Die Excel-Tabelle dazu habe ich bereits und auf dem Südhang-Server abgelegt (wo die beiden PDF-Dateien auch liegen).
Sobald ich dazu komme, trage ich diese im dafür zuständigen Code ein.

**Comment by schoenenb** [comment]
Ist m.M.n. erledigt --> commit https://github.com/Optinomic/apps/commit/d770a9c92dbe858a9a90a51087c741d9ea0954b1

**Comment by schoenenb** [comment]
Da wir's noch nicht umgesetzt haben, öffne ich dieses Issue nochmals.

**Comment by ottigerb** [comment]
Z-Werte ist umgesetzt.
=>  Klinikstichproben muss noch berechnet werden.

**Comment by ottigerb** [comment]
Done
