### ISSUE TITLE
Suedhang :: No AASE Data is loaded anymore |  V1

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#12]
Südhang has problems with importing data from limeSurveys.  Data is there in limeSurvey but, Optinomic V1 is not importing them anymore.

Login to Südhang: https://github.com/ottigerb/therapy-server/wiki/Suedhang-@-in4u
=>  Yes, I know - you hate it because not SSH - anyway - we have to fix this **ASAP**!  Thanks.
### Example:  ALCOHOL ABSTINENCE SELF-EFFICACY SCALE (AASE)

Patient:
http://optinomic.cust.local/patient/2234##modanch-8

Result in limeSurvey  :
http://xwp4105.cust.local/index.php?r=admin/dataentry/sa/editdata/subaction/edit/surveyid/526942/id/732

Hash / PID / FID is correct stored also:
526942X4X64=319cd2f9a0bc7a12
526942X4X65=11757
526942X4X66=117570200

Multiple times [check for results] did not imported something.

Other examples:
http://optinomic.cust.local/patient/2083##modanch-8 | 
http://xwp4105.cust.local/index.php?r=admin/dataentry/sa/editdata/subaction/edit/surveyid/526942/id/727

&

http://optinomic.cust.local/patient/2076##modanch-8 | 
http://xwp4105.cust.local/index.php?r=admin/dataentry/sa/editdata/subaction/edit/surveyid/526942/id/730

I tried to fix this issue - without luck - by:

```
$ sudo rm /var/therapyserver/lime_requests/*
$ sudo service therapyserver restart
$ sudo service therapyserver-result-daemon restart
```

Did we changed something here - maybe since new 'stable build'?  Is V1 importing data by therapyserver-result-daemon (/var/therapyserver/lime_requests/)?   We need to fix that!

**Comment by ottigerb** [comment]
Daten sind nun geladen!

Hinweis von Tom:

> I think it's fixed. It was possibly due to a change in LimeSurvey's page numbering. New results are showing in the DB so I guess it's fine now.

=> Ich werde dies genau im Auge behalten, da dies wohl auch in unserer V2 ein Problem sein könnte. 

=> Auch sollten wir im Südhang die limeSurvey Installation anheben auf `Version 2.06+ Build 151205`. Diese Version verwendet: http://limesurvey.optinomic.org/index.php/admin/index  Doch ein limeSurvey Update bedeutet doch ordentlich 'pain'. Allenfalls eine 'neue' Installation installieren und V2 Module dort 'erfassen' lassen. Wäre auch gleich eine gute "Datentrennung" V1 -> V2.

Was denkt ihr?

**Comment by SonjaKaufmann** [comment]
Da bin ich absolut überfragt bzw überfordert. Sollten wir vielleicht nächsten Freitag genauer besprechen was das bedeutet.

**Comment by schoenenb** [comment]
Finde die Idee gut. Es war ja sowieso angedacht gewesen, die Version zu aktualisieren. Ein Wechsel ebenfalls auf Anfang 2017 finde ich daher sinnvoll. Bis dahin habe ich sicher auch alle Limesurvey-Fragebögen layouttechnisch überarbeitet. Aber vielleicht wär's trotzdem gut, da noch gemeinsam hinzuschauen, ob & wo es allenfalls Schwachstellen gibt.
