### ISSUE TITLE
Angabe Aufenthaltsdauer

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#120]
Mir ist grad aufgefallen, dass da bei der Berechnung irgendwas nicht stimmen kann:
http://optinomic.cust.local/client.new/#/patient/3058
![image](https://user-images.githubusercontent.com/15833792/29701544-a22b2312-896c-11e7-9dd0-82a47a0427a8.png)
...in V2 sogar
![image](https://user-images.githubusercontent.com/15833792/29701582-c8807120-896c-11e7-93e0-5506e009ec7c.png)

Tatsächliche Aufenthaltsdauer: 2 Tage

**Comment by ottigerb** [comment]
Fixed.

**Comment by schoenenb** [comment]
![image](https://user-images.githubusercontent.com/15833792/58948369-4129b600-878a-11e9-9a36-8e4ec8d2e637.png)
Hat das etwas mit dem Fix vor 2 Jahren zu tun?
Die Patienten mit Eintritt heute werden nämlich auch für die Patientengruppenzuteilung (Aktuell PTS / QUEA) nicht berücksichtig:
http://optinomic.suedhang.ch/client.new/#/patient/3696 und
http://optinomic.suedhang.ch/client.new/#/patient/4629/stay/6312

Oder muss ich für die Gruppenzuteilung nur die Abfrage "AND stay.start <= now()" um "AND stay.start <= now()+1" ergänzen?

**Comment by ottigerb** [comment]
> Oder muss ich für die Gruppenzuteilung nur die Abfrage "AND stay.start <= now()" um "AND stay.start <= now()+1" ergänzen?

Wäre sicherlich ein Quickfix!   Try!


Vielleicht wird im HL7 ein falsches Timeformat oder so verwendet - werde da mal Nachgehen.

**Comment by ottigerb** [comment]
Scheint mit dem Datum/Zeitformat Bug hat sich dieser Effekt gefixt:
![Bildschirmfoto 2019-06-06 um 16 39 00](https://user-images.githubusercontent.com/2470873/59041805-a3adaf80-8879-11e9-874e-54c53ebc9e34.png)


Vgl. auch https://github.com/ottigerb/therapy-server/issues/551#issuecomment-499525579

**Comment by schoenenb** [comment]
Super, hab's nämlich nicht geschafft mit dem +1, die Vorlage dazu war glaube ich im QuEA/PTS aktuell, welche ich nach erfolgreichem Testen überschrieben hatte...

**Comment by ottigerb** [comment]
...immerhin haben wir nun eine +1 Vorlage für ein Andermal!  Gibt es aktuell noch weitere "Dinge" auf der ToDo Liste bei welcher ich Dich unterstützen kann?  M.E. sieht es nun gut aus - not?
