### ISSUE TITLE
Fallkonferenz-App

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#121]
Hallo Zusammen,

ich schreibe jetzt wieder in GitHub, damit wir wieder auf den gleichen Stand kommen. Grundsätzlich finde ich es toll wie die neuen Profile aussehen, habe auch den Eindruck die Hintergründe und Farben stimmen gut und die neue Darstellung ist ein Quantensprung. Jetzt geht es eher noch um Feinheiten.

Zu den Graphiken: 
**Querlinien:**
- [x] Finde die Querlinien, welche man nicht lesen muss noch zu stark ausgeprägt, denn eigentlich bräuchte es die gar nicht. Es braucht nur die Linien die eine Skala von der nächsten abgrenzt. Die könnte noch deutlicher sein.

**Allgemeine Layout-Wünsche:**
- [x] Keine Möglichkeit bieten, um Klinikstichproben oder Interpretationshintergründe auszublenden
- [x] Idealerweise soll die Angabe zur Klinikstichprobe immer sichtbar sein, allenfalls über ein Pfeilsymbol (analog zur Glühbirne in V2) angepasst werden können.

**TMT:**
- [x] Ist beim TMT Eintritt der Quotient verloren gegangen?
- [x] Bei Ottiger Patient ist mir zudem aufgefallen, dass der MZP Eintritt nicht schwarz dargestellt wird, wie wir es in den anderen Graphiken haben.

**Act-Info:** Finde ich so sehr gut.
- [x] wenn es gelingt noch den Programmiertext für die Dauer der Abhängigkeit und so zu korrigieren. 
- [x] Im Text zu den Substanzen hat es noch kleine Tippfehler. Eine Lücke zwischen Zahl und g für Gramm und  in der Klammer das ausschliesslich wäre klein und nicht gross geschrieben.
- [x] Fagerström: Kann man (wie bisher) Nichtraucher ausweisen, statt Wert = 0 eintragen?
- [x] Fagerström nur anzeigen, wenn Daten vorhanden sind

**AASE:** Schön ist der drin und sieh toll aus
- [x] Es fehlt noch die Skala für den Gesamtwert. Man könnte sie direkt unten anhängen. Um auf die gleiche Skalierung zu kommen müsste man den Wert einfach dividieren.
- [x] Die Beschriftung an den Seiten würde ich noch ändern. Auf der linken Seite Skalenname und darunter geringe Ausprägung und auf der rechten nicht nochmal den Skalennamen, aber starke Ausprägung.
- [x] Die Interpretation fehlt noch
- [x] Substanzangabe: Zu welcher Substanz wurden die Fragen beantwortet (Alkohol vs. andere Substanz)?
- Anzeige von Mittelwert + Standardabweichung der Normstichprobe beim Gesamtwert möglich? _Werte müssen noch rausgesucht werden_

**ASRS:**
- [x] Anzeige nur bei Resultat im auffälligen Bereich. => _Sobald Messungen vorhanden sind, erfolgt eine Darstellung. Ich kann lediglich den ganzen Bereich ausblenden wenn keine Messungen vorhanden sind._

**BSI/BSCL:** Sehr schön. 
- [x] Würde ich nun doch zwischen TMT und AASE setzen.
- [x] Umgang mit Dropouts klären

**BDI:** 
- [x] Man könnte Platz sparen, wenn man _in der Interpretation_ nur V.a. leichte Depression schreiben würde.

**ISK:** 
Finde ich sehr gut so.

**SCI:**
- [x] Dieser braucht nicht 2 Mal die Messung/Klinikstichprobe/Interpretation. Könnte meintetwegen sogar in eine Graphik, wenn der obere Teil (Skala 1 und 2) deutlich von den Copingskalen abgesetzt wäre. Zum Beispiel durch eine Leerzeile in der nur die Überschrift Bewältigungsstrategien steht. 
- [x] die Bezeichnung Hilfreiche Copingstrategien stimmt so nicht. Auf der linken Seite sind ungünstige oder maladaptive Ausprägungen und auf der rechten Seite sind adaptive Ausprägungen des jeweiligen Bewältigungsmechanismus.
- [x] Wo stammen die Beschreibungen auf der rechten Seite her? Kann mich nicht an diese erinnern.
- [x] Skalen so invertieren, dass immer links die gesunde/günstige Ausprägung ist und rechts die ungünstige. Dass heisst viele Stressoren links, wenig rechts und viele körperliche Stresssymptome links und wenig rechts. -> Ziel: nur eine Graphik

**WHOQOL:**
- [x] Hier fehlt noch die Normierung mit der Klinischen Stichprobe.
- [x] invertieren in z-Wert-Grafik
- [x] Angabe von Eintritt / Austritt statt App-Name bei der Messung

**Comment by ottigerb** [comment]
Querlinien:  Dies kann in den Chart-Optionen ausgeschaltet werden - mittels `"show_baseline": false,`.  Vgl.:  

```
"options": {
        "min": -2,
        "max": "auto",
        "item_height": 60,
        "item_text_left": 100,
        "item_text_right": 350,
        "color_grid": "#9E9E9E",
        "color_clinic_sample": "#888888",
        "color_skin": "grey_dark_to_light",
        "show_baseline": true,
        "show_scale_text": true,
        "show_score_vertical_line": false,
        "show_score_profile_line": true,
        "show_score_circles": true,
        "range_alpha": 0.1,
        "vertical_grid_every_x": 1,
        "response_title_path": "calculation.scores_calculation.info.mz.mz_typ",
        "response_date_path": "date"
    },
```

**Comment by ottigerb** [comment]
**zurInfo:**   actInfo: Zusatzangaben sind nun drin - vgl. Patient 1.




_"Bei Ottiger Patient ist mir zudem aufgefallen, dass der MZP Eintritt nicht schwarz dargestellt wird, wie wir es in den anderen Graphiken haben."_  

=>  Die Linien werden in der "einkommenden" Reihenfolge gefärbt. Also erste Messung "dunkel" -> "hell".  Die Färbungen können mittels dem Skin `"color_skin": "grey_dark_to_light",` festgelegt werden.  Da wir ja immer zuerst Eintritt messen sollten => ist diese immer "schwarz".

```
color_skin | measurements colors skin. 
Possible values so far are: 
default, zebra, pink_dark_to_light, indigo_dark_to_light, grey_dark_to_light 
Default: 'default'
```

Falls Ihr weitere Skins wollt - oder diese modifizieren wollt - liefert mir sowas:

``` JS
      if (color_skin === 'default') {
        colors.push("#3F51B5");
        colors.push("#E91E63");
        colors.push("#00BCD4");
        colors.push("#8BC34A");
        colors.push("#FFC107");
        colors.push("#795548");

        colors.push("#673AB7");
        colors.push("#F44336");
        colors.push("#03A9F4");
        colors.push("#4CAF50");
        colors.push("#FFEB3B");
        colors.push("#FF5722");

        colors.push("#2196F3");
        colors.push("#9C27B0");
        colors.push("#009688");
        colors.push("#CDDC39");
        colors.push("#FF9800");
        colors.push("#607D8B");
      };

      if (color_skin === 'grey_dark_to_light') {
        colors.push("#212121");
        colors.push("#616161");
        colors.push("#9E9E9E");
        colors.push("#E0E0E0");
        colors.push("#F5F5F5");
      };

      if (color_skin === 'indigo_dark_to_light') {
        colors.push("#1A237E");
        colors.push("#303F9F");
        colors.push("#3F51B5");
        colors.push("#7986CB");
        colors.push("#C5CAE9");
      };

      if (color_skin === 'pink_dark_to_light') {
        colors.push("#880E4F");
        colors.push("#C2185B");
        colors.push("#E91E63");
        colors.push("#F06292");
        colors.push("#F8BBD0");
      };

      if (color_skin === 'zebra') {
        colors.push("#212121");
        colors.push("#EEEEEE");
      };
```

**Comment by ottigerb** [comment]
> Im Text zu den Substanzen hat es noch kleine Tippfehler. Eine Lücke zwischen Zahl und g für Gramm und in der Klammer das ausschliesslich wäre klein und nicht gross geschrieben.

What?  

Aktuell z.B.:  
`Täglich, jeweils 34.4g (Bestehend aus 12g Bier, 22.4g Schnäpse (ink. Café Schnaps)).`
wird zu:
`Täglich, jeweils 34.4 g (bestehend aus 12g Bier, 22.4g Schnäpse (ink. Café Schnaps)).`

Oder

`4-6 Tage pro Woche, jeweils 6.4g (Ausschliesslich Bier).`  
wird zu
`4-6 Tage pro Woche, jeweils 6.4 g (ausschliesslich Bier).`

**Comment by ottigerb** [comment]
**zurInfo:**  AASE-G: Gesamtscore ist nun ebenfalls vorhanden - vgl. Patient 1.

Bzgl. Ranges gilt es folgendes Objekt zu modifizieren:
https://github.com/Optinomic/apps/blob/develop/ch.suedhang.apps.fallkonferenz/definitions/aase.js#L58-L78

Aktuell:   
```JS
 "ranges": [{
        "range_start": 0,
        "range_stop": 1.5,
        "text": "?",
        "color": "#2E7D32"
    }, {
        "range_start": 1.5,
        "range_stop": 2.5,
        "text": "?",
        "color": "#FFA000"
    }, {
        "range_start": 2.5,
        "range_stop": 3.5,
        "text": "?",
        "color": "#FB7200"
    }, {
        "range_start": 3.5,
        "range_stop": 999,
        "text": "?",
        "color": "#C62828"
    }]

```
Zur Info:  999 = Unendlich,  hier also >= 3.5   /  Das geht auch bei `range_start` mit -999 Unendlich im Minusbereich also <= Irgendwas.

**Comment by ottigerb** [comment]
> Dieser braucht nicht 2 Mal die Messung/Klinikstichprobe/Interpretation. Könnte meintetwegen sogar in eine Graphik, wenn der obere Teil (Skala 1 und 2) deutlich von den Copingskalen abgesetzt wäre. Zum Beispiel durch eine Leerzeile in der nur die Überschrift Bewältigungsstrategien steht.

Ja, ich sehe was Du meinst.  Da die beiden Teile jedoch unterschiedliche Interpretationen haben muss dies so sein.  Ich sehe keine Möglichkeit dies zu erreichen.  Könnte allenfalls "Stressereignisse und Syptome" irgendwie umkodiert werden, damit diese in die Interpretation der "Copingstrategien" passen?

**Comment by SonjaKaufmann** [comment]
- [x] Querlinien-Angaben super, Nora: kannst Du das umsetzen?

- Act-Info sehr gut, es wäre jeweils die 2. Text-Variante, aber die Lücke vor dem g sieht riesig und komisch aus. Aber eigetlich kommt doch ein Leerschlag zwischen Zahl und Messeinheit, oder? Und wenn ja, dann müsste dies immer so sein, auch bei den Gewichten in der Klammer.

- Ist der TMT-Quotient nur nicht im Beispiel oder sehe ich ihn nicht, Du hast es abgehäklet?

- AASE: Das ging schnell mit dem Gesamtscore, merci

- [x] Nora: AASE: Kannst Du das mit den Ranges anpassen Nora

- SCI: Ja man könnte die Copingskalen alle invers darstellen, dann wäre generell Links gute Ausprägungen und rechts ungünstige. Das würde auch mehr unseren anderen Graphiken entsprechen, wo Auffälligkeiten/ungünstige Werte rechts dargestellt sind ( z.B. beim BSCL, BDI). 
- Wenn wir den TMT und den WHOQOL auch drehen, dann hätten wir die rechts-ungünstig-Strategie bei allen möglichen Skalen durchgezogen. Was meint Ihr, macht das Sinn?

**Comment by ottigerb** [comment]
- Querlinien (Baseline = false) ist umgesetzt. 
- Text: Mein Auge würde diese Variante "sehen": `4-6 Tage pro Woche, jeweils 6.4g (ausschliesslich Bier).`
- TMT: B/A ist jeweils beim Eintritt angegeben:  
<img width="864" alt="bildschirmfoto 2017-09-05 um 09 05 39" src="https://user-images.githubusercontent.com/2470873/30049151-c6ddb674-9219-11e7-949c-2d435109032d.png">
=>  Allenfalls wäre hier auch eine Art Datenblatt Ansicht nötig:  Fehler / Zeit / B/A bei Eintritt - oder?    

- AASE:  Ranges:  Wenn Du mir die Ranges lieferst implementiere ich diese - easy!

- SCI invertieren und in die gleiche Grafik pflanzen halte ich für eine gute Idee! Bin mir jedoch unsicher: Stanine 1 & 2 sind bei den "Stress" grün => Invertiert wäre dies dann Stanine 8 & 9. Die "Copingstrategien" sind von Stanine 5-9 grün. Hmm...

- TMT & WHOQOL drehen: Mein Instinkt würde es so belassen / ich bin auch unsicher, wie einfach dies wäre. Grafik kann nur von z.B. -4 bis +4 darstellen;  nicht etwas  +4 bis -4.  Dann müssten wir die Z-Werte auch irgendwie drehen, was dann wohl "falsch" wäre - nicht? Obwohl die Einheitlichkeit bzgl. links = gut schon "attraktiv" wäre.

**Comment by SonjaKaufmann** [comment]
- Querlinien sieht gut aus, Nur beim BSCL sind noch welche drin.
- Text-Act-Info: Mein Auge ist auch für deine Variante
- Das mit den AASE-Ranges muss ich mir noch durch den Kopf gehen lassen
- SCI invertieren: Ja das mit den Staninen muss ich mir nochmal durch den Kopf gehen lassen, denn Stanine sind ja nicht immer gleich gross, oder? Mhhh, bin wohl nicht Z-Wert-Logik drangegangen. Ach dieser blöde SCI, 
- Wenn TMT und WHOQOL "falsch herum" angeschrieben wären, wäre das nicht so ein Problem, denn da kommt es dann eher auf die Benennung/Bewertung der Seiten an. 
- TMT-Quotient: Stimmt, den habe ich an der Stelle nicht gesucht, wo er jetzt steht. Weiss nciht genau wie eine Datenblatt-Ansicht aussehen würde, hört sich aber nach einer guten Idee an.

- [ ] Finde die farbliche Zuordnung der Messungskästchen zu den richtigen Linien übrigens nicht so einfach. Fand es besser als es über ein kleines farbiges Kästchen ging. Wäre es möglich: kleines farbiges Kästchen/MZP & Datum/Häkli-Kästchen zum aktivieren zu machen?

**Comment by ottigerb** [comment]
Das TMT [Datenblatt](https://demo.optinomic.org/api/modules/ch.suedhang.apps.fallkonferenz/view/Entwicklung#patient_id=1,token=d7df4786-784a-4a4d-a36c-c757613764c8,app_name=app_id=ch.suedhang.apps.fallkonferenz,api_url=//demo.optinomic.org/api/,user_id=2,stay_id=144) ist hier mal zur Demo erstellt.  
ToDo:

- Quotient nur bei Eintritt anzeigen
- oder bei "Nicht Eintritt" mit einem Stern versehen und dann * erklären mit: "Nicht relevant" oder sowas

What do you think?  Übernehmen? 

BSCL:  baseline=false!

**Comment by SonjaKaufmann** [comment]
Datenblatt finde ich gut. Es braucht nur eigentlich keinen Schieber, oder braucht es das für unterschiedlich grosse Bildschirme?
Die Sortierungspfeile braucht es meines Erachtens nach auch nicht. 
Fände das ganze etwas kompakter noch gut und den Quotienten fett. Bei anderen Patienten hat es dann ja nur 2 Zeilen und dafür nimmt es viel Space ein.
Ach ist das schwierig, man kommt immer sofort auf x verschiedene Schriftgrössen, weil man immer die optimale Grösse für die Info wählt, aber dann wird es uneinheitlich und unruhig. Aber Schriften anzupassen ist wahrscheinlich kein Ding und feines Feintunig. Nehme an Du wolltest nur einen Kommentar zum Datenblatt.

**Comment by ottigerb** [comment]
- [x] `Alkohol: Kein Konsum, jeweils 0g (Ausschliesslich ). AUDIT: Bei Eintritt bestand eine «Risikoarmer Alkoholkonsum» (∑=0).`  =>  Bei Kein Konsum resp. 0g keine Angabe von `(ausschliesslich...)` 

- [x] Text neu formatieren:  `4-6 Tage pro Woche, jeweils 6.4g (ausschliesslich Bier).`

**Comment by ottigerb** [comment]
- [ ] BSCL - Dropouts behandeln:  Aktuell wird eine vertikale Linie bei `0` dargestellt.

Vgl.:  [Beispiel: Patient 3019](http://optinomic.cust.local/api/modules/ch.suedhang.apps.fallkonferenz.production/view/overview#patient_id=3019,token=7c5a238d-28c8-4581-a1a2-0456dcdb10ed,app_name=Test_Fallkonferenz,app_id=ch.suedhang.apps.fallkonferenz.production,api_url=http://optinomic.cust.local/api/,user_id=2,stay_id=1407).

## Frage
Wie sollte dies gelöst sein?
Ich kann mir folgende Lösung vorstellen:

1. In der Grafik werden nur "echte" Messungen dargestellt - also Dropouts nicht.
2. Dropouts werden unter der Grafik aufgeführt im Sinne von:
____
Dropouts

Austritt EP, 28.8.2017  |  Dropout: Ablehnung Patient/in.

**Comment by SonjaKaufmann** [comment]
Ja genau so!
Könnte das mit den Farben Probleme geben, wenn der Patient den Übertritt nicht ausfüllt aber den Austritt? oder ist durch einen Dropoutgrund die Farbe an den Messzeitpunkt in der richtigen Reihenfolge gewährleistet?

**Comment by ottigerb** [comment]
**Farben:** [Wie gesagt](https://github.com/Optinomic/apps/issues/121#issuecomment-326971190) - also dann wäre bei dem genannten Szenario:  Eintritt =  Farbe 1; Dropout-Übertritt wird nicht dargestellt; Austritt = Farbe 2  vom gewählten Skin.  

Allenfalls wäre es auch denkbar, dass die Grafik die Messung auch zeigt - jeweils einfach mit dem Häcken auf aus [ ]. Also wenn ein Dropout Flag aktiviert wird - einfach diese Linie nicht darstellen und beim Messzeitpunkt vermerken:  z.B. `[ ] Austritt | Dropout`.  Falls dann jemand dies aktivieren würde sieht er einfach einen 0-Linie.  Dies wäre deutlich aufwendigere Lösung.

@SonjaKaufmann Welche Tests haben alle Dropout Möglichkeit?  Und findest Du Beispiele mit Dropouts?  Wäre sehr hilfreich um dies direkt bei allen zu implementieren und testen.  Danke

**Comment by SonjaKaufmann** [comment]
Die erste Lösung ist gut, wird nicht so oft vorkommen und man hat ja die richtige Zuordnung von Farbe und MZP unten angegeben. Wollte es nur wissen.
Ich glaube es geht eh nur der BSCL. Die anderen haben dann einfach keine Werte eingegeben. Meine Phantasie ist wohl mit nicht vorhandenen Problemen durchgegangen. Sorry!

**Comment by schoenenb** [comment]
Puh, schwierig bei den vielen Diskussionen hier den Überblick zu behalten.
Meine Fragen zu den einzelnen Apps:

- BDI
> - [ ] Man könnte Platz sparen, wenn man nur V.a. leichte Depression schreiben würde.

Wünschst du dir das nur für die Interpretation, die Grafikbeschriftung oder beides?
![image](https://user-images.githubusercontent.com/15833792/30205990-f6ccf188-948a-11e7-8847-bf8894bae0ce.png)

**Comment by schoenenb** [comment]
- BSCL:
> - [x] Würde ich nun doch zwischen TMT und AASE setzen.

Ist abgehakt, der BSCL kommt aber trotzdem nach dem AASE - müsste der noch verschoben werden?
Und mit der Erhebung des ASRS ist die Abfolge nun TMT - ASRS - AASE - BSCL --> neu wäre TMT - ASRS - BSCL - AASE gedacht?

**Comment by schoenenb** [comment]
- Act-Info:
Zusätzlicher Punkt im OP bezüglich Fagerström (Anzeige "Nichtraucher" statt Fagerström = 0?)

Textanpassungen vom TMT habe ich abgehakt

**Comment by schoenenb** [comment]
- SCI:
> - [x] Wo stammen die Beschreibungen auf der rechten Seite her? Kann mich nicht an diese erinnern.

War der Text vorhin anders?

Zusätzlicher Punkt aus der Diskussion: ev. Copingstrategien inverten und mit Stressereignissen und Syptomen zusammenfügen

**Comment by schoenenb** [comment]
- WHOQOL:
Zusätzliche Punkte in OP eingetragen:
-- ev. invertieren
-- Angabe von Eintritt / Austritt statt App-Name bei der Messung
![image](https://user-images.githubusercontent.com/15833792/30206853-b92b821a-948d-11e7-8731-24aba9486ec7.png)

**Comment by schoenenb** [comment]
> - [ ] Finde die farbliche Zuordnung der Messungskästchen zu den richtigen Linien übrigens nicht so einfach. Fand es besser als es über ein kleines farbiges Kästchen ging. Wäre es möglich: kleines farbiges Kästchen/MZP & Datum/Häkli-Kästchen zum aktivieren zu machen?

Komme ich nicht draus: 
- Meinst du anstelle der z.B. oben im WHOQOL dargestellten roten Kreise einen farbigen Punkt, der dann mit der Farbe vom Text (Eintritt / Austritt) im Messkasten übereinstimmt, wobei die Strichfarbe dann immer schwarz / grau wäre?
- Wenn, dann wäre das ja dann für alle Apps nochmals anzupassen, liege ich da soweit richtig?

**Comment by schoenenb** [comment]
Antwort auf die Frage zu den BSCL - Dropouts:
Ich fänd's schick, wenn
- nur die vorhandenen Daten in der Grafik angezeigt werden.
- a) der Dropoutgrund direkt im Messzeitpunkt-Fenster angezeigt wird.
- b) oder aber der Dropoutgrund wie vorgeschlagen unterhalb angezeigt wird.
--> würde b) bedeuten, dass die Grafik gar nicht angezeigt wird, wenn nur Dropouts vorliegen (z.B. bei Sprachschwierigkeiten, welche sich oftmals nicht während des Aufenthaltes ändern)

**Comment by schoenenb** [comment]
- AASE:
> - Die Interpretation fehlt noch
> - Für den AASE hätten wir eine klinische Normstichprobe und sicherlich auch genug Werte von unseren bisherigen Patienten. Meint ihr es macht Sinn die Klinische Norm (Stationäre Alkoholpatienten) einzubinden? Das wären dann Z-Werte aber auf einer "erkrankten Stichprobe".

Gibt es dazu eine Interpretation?
Vielleicht analog der Itemeinschätzung und wegen der Mittelung +/- 0.5 (ist dann halt recht willkürlich)? 

Wert | Einschätzung | | Interpretation | Range |
-- | -- | -- | -- | -- |
0 | gar nicht | => | keine Versuchung | 0-0.5
1 | wenig | => | geringe Versuchung | 0.5-1.5
2 | mässig | => | mittel-/mässige Versuchung | 1.5-2.5
3 | sehr | => | starke Versuchung | 2.5-3.5
4 | äusserst | => | sehr starke/äusserste Versuchung | 3.5-4

Z-Werte würde ich glaube ich weglassen, weil es m.E. um die absolute Versuchung bzw. den intraindividuellen Unterschied geht - welche Situationen führen den Patienten / die Patientin am stärksten in Versuchung? statt Wie stark ist die Versuchung dieses Patienten im Vergleich zu anderen PatientInnen ausgeprägt?
Theoretisch würde dann jemand, der genau in der Mitte der Normstichprobe liegt keine Auffälligkeiten zeigen, obwohl die Werte z.B. immer über 2 oder 3 liegen. Zudem müsste für PatientInnen mit anderen Hauptproblemsubstanzen trotzdem eine separate Darstellung (wie bis anhin wahrscheinlich) gemacht werden, weil sie nicht in die Normstichprobe passen. Oder habe ich was durcheinander gebracht?

**Comment by schoenenb** [comment]
Beim **AASE** könnte man alternativ auch die Angaben aus dem PDF nehmen:
0-.9: sehr geringe Versuchung
1-1.9: geringe Versuchung
2-2.9: hohe Versuchung
3-3.9: sehr hohe Versuchung

**Comment by ottigerb** [comment]
Bessere Unterscheidung der einzelnen Messungen:
- [x] Grafik SKIN einbauen:   Indigo, Grau, Pink  jeweils  Dunkel bis Hell

**Comment by ottigerb** [comment]
Es steht nun ebenfalls folgendes SKIN zur Verfügung: `indigo_grey_pink`.  Diese habe ich hier mal aktiviert: [SKIN :: indigo_grey_pink](https://demo.optinomic.org/api/modules/ch.suedhang.apps.fallkonferenz/view/overview#patient_id=1,token=377e9daa-1d4e-410d-9cc5-08b3ce944870,app_name=Fallkonferenz,app_id=ch.suedhang.apps.fallkonferenz,api_url=//demo.optinomic.org/api/,user_id=2,stay_id=144)  Meines Erachtens ist die Zuordnung deutlich einfacher und trotzdem nicht gerade ein "bunter Hund".

**Comment by SonjaKaufmann** [comment]
Mhhh, weiss nicht, bin nicht für so viel Farben, aber habe es mir halt nur vorgestellt.

Finde die Form der alsen Zuordnung nach wie vor besser als jetzt über die Hntergrundfarbe der grossen MZP-Kästen.

**Comment by SonjaKaufmann** [comment]
Habe es mir auch angeschaut, sorry aber das ist ein bunter Hund:
![image](https://user-images.githubusercontent.com/20124244/30270287-5abd867c-96ec-11e7-9c52-476d4b3e2d08.png)

Möchte auf jeden Fall bei den Grautönen bleiben, zumal die Punkte ja schon bunt sind!

Finde nur die Farbgebung über die Hintergründe der Messzeitmunktbeschriftung nicht gut! Fände es klarer mit einem gefüllten Kästchen oder einer LInienlegende.

**Comment by SonjaKaufmann** [comment]
Zum AASE: Ich finde die oben vorgeschlagene Einteilung, welche gröber ist passt gut, also die nach dem PDF. Und ich gebe Dir recht, Normen machen da wenig Sinn, da es um die individuellen Ausprägungen geht. Für den Gesamtwert könnte es sinnvoll sein zu wissen, ob jemand viel oder wenig Versuchung angibt. Wie wäre es mit der Angabe von Mittelwert und Standardabweichung in der Graphik, aber als Fixpunkte.

**Comment by SonjaKaufmann** [comment]
Finde das Issue sehr unübersichtlich. Soll ich es auf Einzelissues aufteilen?

**Comment by ottigerb** [comment]
Einzelissues:  Meines Erachtens passt es so. Einfach offene Punkte im OP
(opening post) vermerken. Doch as you like - nur nicht alles mit Prio 1
versehen.  ;¬)

Interpretation: Das wäre nun ein guter Moment für zusätzliche Texte /
Interpretationen. Auch im Hinblick auf die PDF's. Hier habe ich übrigens
die ersten Hürden genommen und kann bald erste Ergebnisse zeigen.

**Comment by SonjaKaufmann** [comment]
Ah okay, so funktioniert das, wenn es im ersten Post drin ist, dann kommt es ins Issue, verstehe verstehe. Und wenn sich neues daraus ergibt, dann wäre dies ein neues Issue.

ZuM BDI Verdacht auf kürzen: M.E. nach sollte es in der Graphik gekürzt werden.

**Comment by SonjaKaufmann** [comment]
SCI: 

- Skalen so invertieren, dass immer links die gesunde/günstige Ausprägung ist und rechts die ungünstige. Dass heisst viele Stressoren links, wenig rechts und viele körperliche Stresssymptome links und wenig rechts.  -> Ziel: nur eine Graphik
_in OP übernommen_

**Comment by schoenenb** [comment]
Allgemeine Layout-Wünsche:
- Keine Möglichkeit bieten, um Klinikstichproben oder Interpretationshintergründe auszublenden
- Idealerweise soll die Angabe zur Klinikstichprobe immer sichtbar sein, allenfalls über ein Pfeilsymbol (analog zur Glühbirne in V2) angepasst werden können.

**Comment by schoenenb** [comment]
**ASRS:**
- Lässt es sich einrichten, dass der ASRS in der Fallkonferenz-Zusammenstellung nur angezeigt wird, wenn das Resultat im auffälligen Bereich liegt (bzw. unterdrücken, wenn unauffällig)?

**Comment by schoenenb** [comment]
**WHOQOL**:
- soll invertiert werden, sobald die Daten z-Wert-transformiert und entsprechend dargestellt werden

**Comment by schoenenb** [comment]
AASE:
- Substanzangabe: Zu welcher Substanz wurden die Fragen beantwortet (Alkohol vs. andere Substanz)?
- Mittelwert + Standardabweichung der Normstichprobe beim Gesamtwert anzeigen - möglich?

**Comment by ottigerb** [comment]
> WHOQOL:  soll invertiert werden, sobald die Daten z-Wert-transformiert und entsprechend dargestellt werden

Wie soll [das](https://github.com/Optinomic/apps/issues/121#issuecomment-329466039) gehen? Die Grafik kann nicht von +4 .... -4 darstellen.   D.h. wir müssten aus einem z.B. -4 ein +4 machen.  Stimmt dann noch die Aussage?

**Comment by schoenenb** [comment]
Da kommt dann eben das invertieren zum Zug - alles wird *-1 gerechnet - die Interpretation von gut links - ungut rechts wird ja dann über die Farben bzw. die Angaben neben der Grafik gesteuert. D.h. jemand der seine Lebensqualität +2SD besser einschätzt als die Norm wird bei -2 SD dargestellt, aber trotzdem in die Richtung "bessere/normale Lebensqualität"

Off-Topic: Wie kann ich auf einen Issue-Comment Bezug nehmen? Bzw. woher kennst du die issuecomment-Nummer?

> Wie soll [das](https://github.com/Optinomic/apps/issues/121#issuecomment-329466039) gehen?

**Comment by ottigerb** [comment]
Jä so!  Also easy!  :-)  

Off-Topic:  Den Link der Zeitangabe kopieren neben `commented ...`.

**Comment by schoenenb** [comment]
Habe gerade noch bemerkt, dass die Fagerström-Maske auch angezeigt wird, wenn keine act-info Angaben vorhanden sind. Mit meinen Commits https://github.com/Optinomic/apps/commit/a99d0f98625e0a59634357fc35bb2b5f24dc7c29 und https://github.com/Optinomic/apps/commit/9d2c171ef5eca0821a4765be251870ac29b9f701 konnte ich leider nichts bewirken...
- Fagerström nur anzeigen, wenn Daten vorhanden sind

**Comment by schoenenb** [comment]
Still und heimlich hat sich ein "Inhaltsverzeichnis" eingeschlichen, um zu den einzelnen Resultaten "runter" zu springen (und wieder zurück) - finde ich genial!

**Comment by SonjaKaufmann** [comment]
Was mir beim kurzen drüberschauen aufgefallen ist:
1. Es sieht toll aus

- [x] Die Farben in der Graphik und in der Datenbeschriftung sind nicht immer gleich. Die schwarze Linie ist in manchen Graphiken dunkelgrau (oder mein Auge täuscht sich, kann auch sein) z.B. beim Audit.

- [x] Ich finde die Graphiken noch zu weit auseinander uns zuwenig kompakt. Bin unsicher ob der ganze Text zum Fragebogen drauf soll. Ich finde es zu dominant

- [x] Finde auch die Interpretation nicht notwendig, da wir ja extra das Farbschema dafür aufgebaut haben. Fände es gut, wenn man die Interpretation durch das öffnen von einem Icon anschauen könnte, muss aber meiner Meinung nach nicht zu jeder Graphik. 

- [x] Gleiches gilt für mich für die gesunde Normstichprobe. Ich finde es müsste nur mit Gesunde angeschrieben sein und für mehr Infos der Klick auf einen Infofenster. Bei der Klinischen Norm würde ich mehr schreiben, denn da haben wir ja Eintrittsvergleiche, sowie Austrittsvergleiche und so.

- [x] Finde die Zusatztabellen nehmen recht viel Platz ein, könnte man dies auch kompakter machen? z.B. geringere Abstände?

**Comment by ottigerb** [comment]
# Gut zum Druck! 
Meines Erachtens ist das PDF nun ✨😍✨ geworden:
-  [2017_10_07 - Assessment - Herr Brooks Christian (23.1.1962 - 55).pdf](https://github.com/Optinomic/apps/files/1364610/2017_10_07.-.Assessment.-.Herr.Brooks.Christian.23.1.1962.-.55.pdf)
- [2017_10_08 - Assessment - Herr B. C. (1962).pdf](https://github.com/Optinomic/apps/files/1366988/2017_10_08.-.Assessment.-.Herr.B.C.1962.pdf)

1.) Die Punkte vom [Opening Post](https://github.com/Optinomic/apps/issues/121#issue-255037695) sind m.E. erledigt. 
- [x] **EDIT:** PDF-Fusszeile (Seite 1/7) & "Secure Patientinfo" in Header 
(vgl. 2017_10_08 - Assessment - Herr B. C. (1962).pdf)

2.) Die `Fallkonferenz-App` ist auch auf dem Südhang-Server.  Ich bitte Euch ( @SonjaKaufmann & @schoenenb ) das PDF in verschiedenen Situationen (Nichtraucher, Keine Daten, Dropouts...) direkt im Live-Server zu testen.  Falls hierbei noch "Fehler" ersichtlich werden:  Bitte Angabe zum Patient/Fall hinterlassen, damit ich solche "Sonderfälle" beheben kann. Danke!
