### ISSUE TITLE
Fallkonferenz-App auf Client New Südhang

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#122]
Zum testen sollte die Fallkonferenz-App möglichst bald auf Client New Südhang aktiviert oder aufgespielt werden. Soweit ich verstanden habe muss man es dann auch in V2 einspielen. Bitte machen und in V2 oder überall irgendwie so benennen, dass nicht alle Therapeuten gucken gehen. Können es ja Dummi nennen :-)
Lieber wir irritieren ein paar neugierige Therapeuten als das wir potentielle Fehler nicht finden.

**Comment by ottigerb** [comment]
## App ist aktiviert
Die Fallkonferenz-App ist auf dem Südhang-Server aktiviert. Ich habe die App "Test :: Fallkonferenz" betitelt. Somit sollte klar sein, dass es sich hier um "Tests" handelt.

## Calculations
Die App benötigt einige Calculation-Updates - entsprechend werden nun "Calculations" neu gerechnet - ich hoffe nicht, dass das System sehr langsam wird. Calculations werden einfach abgearbeitet - ohne jegliche Priorität oder sowas.

Beim ersten Aufruf der [Fallkonferenz-App](http://optinomic.cust.local/api/modules/ch.suedhang.apps.fallkonferenz.production/view/overview#patient_id=1,token=e9777b90-f451-4832-abe0-dbf7d5c12c0e,app_name=Test,app_id=ch.suedhang.apps.fallkonferenz.production,api_url=http://optinomic.cust.local/api/,user_id=2,stay_id=1) beim Patienten 1 waren die Calculations für TMT / ASRS & BSCL noch nicht neu berechnet.  Dies brauch nun etwas Geduld. Ungeduldige können dies wie folgt forcieren: 

## Calculation manuell 
Calculations können manuell pro Patient forciert werden:

http://optinomic.cust.local/api/#/admin/tools
<img width="658" alt="bildschirmfoto 2017-09-05 um 15 21 04" src="https://user-images.githubusercontent.com/2470873/30063158-02aa9698-924e-11e7-9f9b-e7800c5b71b1.png">


## WIP 
Ich beobachte die App / Calculation noch bis am Freitag. Vielleicht hat sich auch noch irgendwo ein Bock eingeschlichen in der schnellen Umstellung auf `.production`.

**Comment by SonjaKaufmann** [comment]
Super, ich werde dann morgen oder übermorgen draufschauen, bin ausnahmsweise Mal von der geduldigen Sorte :-)
Dennoch bin ich sehr gespannt wie schön das bei unseren Patienten aussehen wird.

**Comment by ottigerb** [comment]
## Fixes:

Ich konnte noch einige Fehler beheben. M.E. funktioniert die Fallkonferenz-App bereits wunderbar.
Test:  [Fallkonferenz bei z.B. Patient 2294](http://optinomic.cust.local/api/modules/ch.suedhang.apps.fallkonferenz.production/view/overview#patient_id=2294,token=7c5a238d-28c8-4581-a1a2-0456dcdb10ed,app_name=Fallkonferenz,app_id=ch.suedhang.apps.fallkonferenz.production,api_url=http://optinomic.cust.local/api/,user_id=2,stay_id=1089)  oder [Patient 3259](http://optinomic.cust.local/api/modules/ch.suedhang.apps.fallkonferenz.production/view/overview#patient_id=3259,token=7c5a238d-28c8-4581-a1a2-0456dcdb10ed,app_name=Fallkonferenz,app_id=ch.suedhang.apps.fallkonferenz.production,api_url=http://optinomic.cust.local/api/,user_id=2,stay_id=1575) .  :-)

## Performance
Geschwindigkeit ist m.E. ebenfalls gut.  Allenfalls könnten wir noch etwas "Ladezeit" einsparen indem wir das TMT-Datenblatt nicht immer darstellen.  Also im Sinne von:

____

Datenblatt: Trail Making Test (TMT)     `[anzeigen]`  (default =  geschlossen)  resp.  `[schliessen]`

____
=>  Ich denke nicht dass es vieeeeel schneller sein wird - doch immerhin.  Was denkt ihr?  Die Schriftarten sind übrigens angepasst und der Scrollbalken erscheint nur bei zu "kleinen" Screens.

## Technisch:
@schoenenb Der Unterschied `demo`  & `.production` ist nur noch in folgenden Files: [_loadData.m4](https://github.com/Optinomic/apps/blob/master/ch.suedhang.apps.fallkonferenz/_loadData.m4) sowie [_properties.js](https://github.com/Optinomic/apps/blob/master/ch.suedhang.apps.fallkonferenz/_properties.js).  Somit können wir leicht auf Demo weiterentwickeln und bei grünem Licht lediglich die entsprechende [view.html](https://github.com/Optinomic/apps/blob/master/ch.suedhang.apps.fallkonferenz/elements/view.html)  1:1 ins `.production` kopieren.  Done!

**Comment by schoenenb** [comment]
Kleine Anpassung:
- Test :: Fallkonferenz wird seit heute Morgen nur noch für die EP-PatientInnen automatisch aktiviert (da den anderen Fällen die meisten Daten fehlen).

:+1: Zudem habe ich gesehen, dass man die App theoretisch trotzdem auch in V2 einsehen kann, wenn man die App wie beschrieben in einem neuen Fenster/Tab öffnen lässt.

**Comment by SonjaKaufmann** [comment]
Wird die Fallkonferenz eigentlich nur bei neuen Patienten angezeigt und bei alten nicht?

**Comment by ottigerb** [comment]
> Wird die Fallkonferenz eigentlich nur bei neuen Patienten angezeigt und bei alten nicht?

...da wo die App aktiviert ist!

**Comment by schoenenb** [comment]
> Wird die Fallkonferenz eigentlich nur bei neuen Patienten angezeigt und bei alten nicht?

Ja, eigentlich schon.
Wenn's bei allen EP-Patienten aktiviert sein soll, könnte man's ev. über die Gruppen "Belegung: EP (einst)" & "Belegung: EAS & EP (einst)" aktivieren.
**Frage an Beat:** _Oder geht das dann nur für die neusten Fälle oder wenn ein Patient neu in die Gruppe kommt?_
Ansonsten müsste man halt die App bei den älteren Fällen aktivieren, für die man die Übersicht anschauen will.

**Comment by ottigerb** [comment]
Wenn nicht "manuell" bei alten Fällten aktiviert werden soll, kann die App der gewünschten Gruppe hinzugefügt werden.  Sobald ein Patient neu in die Gruppe kommt -> App aktiviert.  Um die bisherigen Patienten / Fälle auch zu erreichen kann unter `/client.new/#/admin` die Exexutables `PATIENT-GROUPS` ausgeführt werden. Voila!  :-)

**Comment by ottigerb** [comment]
Ich habe die `ch.suedhang.apps.fallkonferenz.production` auf den aktuellsten Stand angehoben. 

## Quicklinks / Verknüpfungen
Zudem habe ich `Quicklinks` eingeführt:

![bildschirmfoto 2017-10-02 um 12 13 33](https://user-images.githubusercontent.com/2470873/31073167-160acb18-a76b-11e7-8953-d6c44673b019.png)
=>  Diese Verknüpfungen springen direkt zu den jeweiligen Darstellungen. Das gute daran ist:  1.) Keine Ladezeit  2.) Die App Fallkonferenz muss nicht mal aktiviert sein.  

## PDF's

PDF's der einzelnen Tests können über das Print-Icon geöffnet werden. Danach kann öffnen/speichern gewählt werden:
![bildschirmfoto 2017-10-02 um 12 17 52](https://user-images.githubusercontent.com/2470873/31073326-c5195106-a76b-11e7-98d5-d25d81525093.png)

Das Übergeordnete PDF ist dann ein Zusammenzug aller PDF's und kann hier bezogen werden:
![bildschirmfoto 2017-10-02 um 12 07 31](https://user-images.githubusercontent.com/2470873/31073270-7cead3d2-a76b-11e7-9968-91c4d6a2ad06.png)

**Comment by ottigerb** [comment]
Closed because of https://github.com/Optinomic/apps/issues/121#issuecomment-334932703
