### ISSUE TITLE
AASE sieht komisch aus

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#123]
Beispiel:
http://optinomic.cust.local/client.new/#/patient/2254/stay/1457/app/ch.suedhang.apps.fallkonferenz.production/template/overview

**Comment by ottigerb** [comment]
Alles i.O.!  Das sind lediglich Überlagerungen der einzelnen Messungen:
![bildschirmfoto 2017-09-11 um 11 42 00](https://user-images.githubusercontent.com/2470873/30268596-85228a6c-96e6-11e7-863e-2ec784f98647.png)
![bildschirmfoto 2017-09-11 um 11 42 10](https://user-images.githubusercontent.com/2470873/30268597-85233606-96e6-11e7-9547-ded9d5e1965b.png)

**Comment by SonjaKaufmann** [comment]
Ach so, gut hast Du es gesehen! Merci!
