### ISSUE TITLE
Linien und Beschriftung

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#124]
•	[ ] Finde die farbliche Zuordnung der Messungskästchen zu den richtigen Linien übrigens nicht so einfach. Fand es besser als es über ein kleines farbiges Kästchen ging. Wäre es möglich: kleines farbiges Kästchen/MZP & Datum/Häkli-Kästchen zum aktivieren zu machen?
Komme ich nicht draus:
•	Meinst du anstelle der z.B. oben im WHOQOL dargestellten roten Kreise einen farbigen Punkt, der dann mit der Farbe vom Text (Eintritt / Austritt) im Messkasten übereinstimmt, wobei die Strichfarbe dann immer schwarz / grau wäre?
•	Wenn, dann wäre das ja dann für alle Apps nochmals anzupassen, liege ich da soweit richtig?

Ich meine Folgendes:
![image](https://user-images.githubusercontent.com/20124244/30268093-e62540e0-96e4-11e7-9a87-ee0cbc33eab2.png)

Ich finde in der alten Version ist es besser gelöst:
![image](https://user-images.githubusercontent.com/20124244/30268299-9bba710a-96e5-11e7-9782-31dc2315abb6.png)

Ich denke also eher an eine klassische Legende im Excel-Style. Bin auch noch am überlegen, ob es nicht klarer wäre den Linienstyle (durchgehend, gestrichelt, gepunktet) zu variieren anstatt die Farbe. Was meint ihr dazu?

**Comment by ottigerb** [comment]
Die Umrahmung der und Hintergrundfarbe der Kästchen bezieht sich auf die Farbe des Skins!

Ich schlage einen anderen Skin vor:  

Indigo_Grey_Pink:  
Erste Messung ist indigo (blau), zweite Messung ist grau und dritte Messung pink. Falls eine 4. Messung vorhanden = Helleres blau,  5. Messung = Helleres Grau etc.

Also:
Indigo, Grau, Pink  jeweils  Dunkel bis Hell

Close:  Gehört zu https://github.com/Optinomic/apps/issues/121
