### ISSUE TITLE
Act-Info Erinnerungen

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#125]
Ich bekam gestern von den Therapeuten die Information, dass sie eine E-Mail-Flut erhalten haben. Letzte Woche sind anscheinend keine Erinnerungsmails rausgegangen und diese Woche dafür nachträglich die Erinnerungen und die 2. Erinnerungen, wobei die Bögen teilweise schon selbstständig selbstständig ausgeführt worden sind. 
Weiss nicht ob dies ein passageres Problem war oder ob irgendwas mit der Erinnerungsauslösung nicht stimmt.

**Comment by ottigerb** [comment]
Juhuuuuuuuu! 

Es scheint als konnte ein alter bug endlich behoben werden. 

Bzgl. der Mailflut müssen wir uns wohl einfach entschuldigen mit dem Hinweis, dass es in Zukunft wie erwartet funktionieren wird. :blush:
