### ISSUE TITLE
BSCL Falsche Skalenreihenfolge

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#126]
Im BSCL ist die Reihenfolge der Skalen durcheinandergeraten.
Die Reihenfolge von Oben nach Unten ist:
Somatisierung:
Zwanghaftigkeit:
Unsicherheit im Sozialkontakt:
Depressivität: 
Ängstlichkeit:
Aggressivität/Feindseligkeit:
Phobische Angst:
Paranoides Denken:
Psychotizismus:
GSI: Grundsätzliche psychische Belastung

Weiss nicht welche Prio es hat, dachte weil eventuell auch relevant für die PDF nehme ich Prio 1, könnt es aber auch runterstufen.

**Comment by ottigerb** [comment]
Du kannst die Reihenfolge der `"scales"` hier selbst anpassen:
https://github.com/Optinomic/apps/edit/develop/ch.suedhang.apps.fallkonferenz/definitions/bscl.js

**Comment by SonjaKaufmann** [comment]
Liebe Nora,

könntest Du das bitte machen und dann das Issue schliessen?

Herzlichen Dank
Sonja

**Comment by ottigerb** [comment]
Done:  https://github.com/Optinomic/apps/commit/d982e19c02f59106d62a49d73715ea7aa620e073
