### ISSUE TITLE
Allgemeine Fragen mit Issue-Potenzial

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#128]
Auf dem Weg zur Idealdarstellung unserer Daten hätten wir noch folgende Anregungen / Wünsche:
- Lässt sich die Linienart (in Word genannt "Strichtyp", z.B. ----- | ....... | *****) auch anders darstellen als wie bisher als durchgezogene Linie?
- Können die Messzeitpunkte mit kleineren Symbolen dargestellt werden (wie beim neuen PDF :) ) und dafür die Checkbox dahinter? Ungefähr so: 
![grafik](https://user-images.githubusercontent.com/15833792/30428518-30894ade-9954-11e7-92ee-52cd959d2943.png)
(bzw. bei gegebener Möglichkeit von anderen Linienmustern anstelle des gefüllten Kästchens die Linienform)
- Kann der Inhalt der Interpretation (v.a. die Zahlenangabe) unabhängig vom Range angepasst werden? Das würde mir erlauben, den Farbverlauf mit fliessenden Übergängen zu gestalten und in der Interpretation z.B. Werte wie >5 bis 6 anzugeben. Soweit ich das verstanden habe, geht das bisher nur bei den tiefsten & höchsten Werten, wenn als min. bzw. max. (-)999 angegeben ist.
Oder die Werte gleich gar nicht mehr anzeigen? (Die Interpretation erfolgt dann aufgrund der Farbzuteilung bzw. könnten die Werte im readme hinterlegt werden.)
- Können calculations die berechneten z-Werte auch speichern? Das wäre dann relevant für den Export.

**Comment by ottigerb** [comment]
> Lässt sich die Linienart (in Word genannt "Strichtyp", z.B. ----- | ....... | *****) auch anders darstellen als wie bisher als durchgezogene Linie?

=> Leider Nein. Ihr könnt gerne bei [PDFMAKE ein Feature-Request](https://github.com/bpampuch/pdfmake/issues) hinterlegen.

Zu den anderen Themen:

- Messzeitpunkte mit kleiner Symbolen / Interpretation ausblenden/darstellen:  Done.
```
"show_settings_block": true,
"allow_toggle_settings_block": false,
"show_ranges_overview": true,
```
`show_settings_block` - stellt die bisherige Tabdarstellung mit allen Settings dar.
`show_ranges_overview` kann eingestellt werden ob über der Grafik die Ranges ausformuliert werden sollen. 

Dokumentation von <optinomic-chart-profile> 
https://github.com/Optinomic/polymer-cdn/tree/master/lib/optinomic-chart-profile


Calculations sind immer gespeichert. Exporte von Calculations sind somit möglich - da müssen wir nur bekanntermassen gut aufpassen.


Ich schliesse dieses Issue.

**Comment by schoenenb** [comment]
Da war ich zu ungenau bei den Formulierungen - es ging bei den Fragen nicht ums PDF, sondern hauptsächlich um die Polymer-Darstellungen.
Heisst das, dort funktionieren verschiedene Strichtypen auch nicht?

Merci für den Link und die (neuen?) Optionen - ich schaue mir das gleich mal an. :)

**Comment by ottigerb** [comment]
...App- & PDF-Darstellung sollen möglichst identisch bleiben.  In der App wäre dies sicher irgendwie denkbar... Eröffne gleich ein neues Issue.
