### ISSUE TITLE
[App & PDF] :: Fallkonferenz Views

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#129]
## Aufgaben
- [x] @schoenenb Nochmals die [Definitionen](https://github.com/Optinomic/apps/blob/master/ch.suedhang.apps.fallkonferenz/definitions/bscl.js
) prüfen. Allenfalls ist mir hier etwas untergegangen.
- [ ] @SonjaKaufmann  App-Darstellungen "absegnen".
- [ ] @SonjaKaufmann  PDF-Darstellungen "absegnen". Gibt es hier unterschiedliche Darstellungen / Druckvorlagen?
- [x] @ottigerb padding für text_right einfügen

## App
Aktuell wird die Symptomcheckliste BSCL (ch.suedhang.apps.fallkonferenz) wie folgt dargestellt:

![bildschirmfoto 2017-09-22 um 08 28 46](https://user-images.githubusercontent.com/2470873/30731872-333c2be4-9f70-11e7-9e3e-38544e5c3013.png)

## PDF
Jede App (hier BSCL) kann eine oder mehrere Druckvorlagen definieren. Was und in welcher Reihenfolge die Druckvorlage erstellt => Wird [hier festgelegt](https://github.com/Optinomic/apps/blob/master/ch.suedhang.apps.fallkonferenz/elements/bscl-element.html#L482-L488). Um die aktuelle Druckvorlage zu "erreichen": Click auf das [Print] Icon:

![bildschirmfoto 2017-09-22 um 08 36 59](https://user-images.githubusercontent.com/2470873/30732201-af9c00be-9f71-11e7-9aed-7c1a7ef60b76.png)

Aktuell wird dann folgendes PDF erstellt:
## Allgemein
App & PDF verwenden die gleichen [Definitionen](https://github.com/Optinomic/apps/blob/master/ch.suedhang.apps.fallkonferenz/definitions/bscl.js
)!   Yes!   Die eigentliche Z-Score-Grafik beachtet nun auch Dropouts. Die Dropout-Messung wird nicht dargestellt, beansprucht jedoch seine "Farbe". D.h. die Farbreihenfolge des SKINS bleibt bestehen. Yes! 

### Verständnis:  Assessment / Fallkonferenz
Ein Assessment PDF hat ebenfalls eine oder mehrere Druckvorlagen. Es können auch die "Druckvorlagen" der Unter-Apps einbezogen und dargestellt werden. Somit muss das Assessment-PDF keinerlei Logik / Dropouts etc. beachten - ist also "dumm".  Entsprechend läuft dann das erstellen der PDF's schnell und gut.  Ein Beispiel Assessment-PDF sieht dann z.B. wie folgt aus: 
[2017_09_22 - Fallkonferenz - Patient.pdf](https://github.com/Optinomic/apps/files/1323669/2017_09_22.-.Fallkonferenz.-.Patient.pdf).  

Hinweis:  Ein z.B.  "Eintritts-Assessment" vs. "Austritts-Assessment" kann sich somit wie folgt unterscheiden:  Es werden nur bestimmte vs. alle Druckvorlagen der Unter-Apps dargestellt. Diese werden unterschiedlich "angereichert" mit eigenen Texten etc.  **Hinweis:**  Dass nur Eintrittsmessungen im Chart sind wird nicht unterstützt!  

### Folgende elements gilt es zu beachten:

Grundsätzliche Issues/Requests zu der Chart/PDF-Darstellung kann auch direkt hier hinterlassen werden:

<[optinomic-chart-profile](https://github.com/Optinomic/optinomic-chart-profile)>   regelt die Chart-Darstellung innerhalb der App.

<[optinomic-pdf-chart-profile](https://github.com/Optinomic/optinomic-pdfmake-chart-profile)>   regelt die PDF-Darstellung. 

<[optinomic-pdfmake](https://github.com/Optinomic/optinomic-pdfmake)>   Erstellt das eigentliche PDF. Bekanntes Issue: [Footer funktioniert nicht](https://github.com/Optinomic/optinomic-pdfmake/issues/1).

**Comment by schoenenb** [comment]
Definitionen sind angepasst --> https://github.com/Optinomic/apps/commit/af0adc005c6d2034f8ef8c3cae7b0e20f438b098
waren aber nur einige wenige Veränderungen

Padding beim text_right wäre super, obwohl es mit leicht erhöhter item_height im PDF nach wie vor auf eine Seite passt.

**Comment by schoenenb** [comment]
@ottigerb Kannst du das so programmieren, dass bei Patienten, die nur Dropouts (z.B. Sprachschwierigkeiten, Spitalverlegung kurz nach Eintritt) als Messungen haben, nur die Dropoutangabe steht, statt der leeren Grafik und der leeren Zusatzitem-Tabelle? z.B.  https://demo.optinomic.org/client.new/#/patient/387/stay/1038/app/ch.suedhang.apps.fallkonferenz/template/overview

@SonjaKaufmann Oder spielt das für uns keine Rolle, weil das bei den genannten Fällen sowieso niemand anschaut und/oder ausdruckt?

**Comment by ottigerb** [comment]
**Done:**  

- Wenn nur Dropouts vorliegen wird keine Grafik dargestellt.
- Wenn Dropouts & Messungen vorliegen wird die Grafik, Zusatzangaben und Dropouts Tabelle dargestellt.
- Wenn keine Dropouts vorliegen wird die Grafik & Zusasatzangaben-Tabelle dargestellt.

**Comment by ottigerb** [comment]
Related to https://github.com/Optinomic/apps/issues/121

**Comment by SonjaKaufmann** [comment]
Weiss jetzt nicht ob ich in 121 schreiben soll oder hier?
Habe mir die pdf genauer angeschaut. Es gilt das gleiche wie ich für die App im 121 angemerkt habe.

- [ ] Zusätzlich finde ich die Beschreibung des Fragebogens unter der Graphik sehr irritierend. Neben der Frage ob die Beschreibung überhaupt rein soll oder so ausführlich rein soll, muss die Beschreibung sonst unter den Fragebogentitel. 

- [ ] Die Datenblätter sind zu gross, Es könnte m.E. die gleiche Schriftgrösse verwendet werden wie bei den Graphikbeschriftungen

- [ ] Der ASRS muss nicht auf das PDF, eigentlich muss er auch nicht umbedingt auf die Fallkonferenz, nur wenn auffällig, dann wäre er interessant.

- [ ] Es fehlen noch die klinischen Stichproben

- [ ] Wir sollten nach Möglichkeit das Muster günstige Werte links, ungünstige Werte rechts durchziehen, also z.B. die Copingskalen noch umpolen

**Comment by schoenenb** [comment]
Falls die Option "Interpretation anzeigen" in den chart-profiles schon existiert, wie lautet die property?
Andernfalls: kannst du das so kreieren, dass die Interpretation separat ein- / ausgeschaltet werden kann?

**Comment by ottigerb** [comment]
`"show_ranges_overview": false`
=>  Einfach diesen Flag in den Options setzen.

**Comment by ottigerb** [comment]
Closed because of https://github.com/Optinomic/apps/issues/121#issuecomment-334932703
