### ISSUE TITLE
Limesurvey update V1 -> V2

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#13]
_**Beat:**_
=> Auch sollten wir im Südhang die limeSurvey Installation anheben auf Version 2.06+ Build 151205. Diese Version verwendet: http://limesurvey.optinomic.org/index.php/admin/index Doch ein limeSurvey Update bedeutet doch ordentlich 'pain'. Allenfalls eine 'neue' Installation installieren und V2 Module dort 'erfassen' lassen. Wäre auch gleich eine gute "Datentrennung" V1 -> V2.

Was denkt ihr?

_**Sonja:**_
Da bin ich absolut überfragt bzw überfordert. Sollten wir vielleicht nächsten Freitag genauer besprechen was das bedeutet.

_**Nora:**_
Finde die Idee gut. Es war ja sowieso angedacht gewesen, die Version zu aktualisieren. Ein Wechsel ebenfalls auf Anfang 2017 finde ich daher sinnvoll. Bis dahin habe ich sicher auch alle Limesurvey-Fragebögen layouttechnisch überarbeitet. Aber vielleicht wär's trotzdem gut, da noch gemeinsam hinzuschauen, ob & wo es allenfalls Schwachstellen gibt.

**Comment by HansaYohaku** [comment]
Ich finde auch, mit V2 sollte ein upgedatetes limesurvey kommen. Der Jahreswechsel wäre ein guter Zeitpunkt. Bin gespannt auf eure Erfahrungen mit der Umstellung auf V2...

**Comment by ottigerb** [comment]
Ich schlage`Version 2.06+ Build 151205` Build vor - dieser hat sich auf Demo gut bewährt. Bin mir unsicher, ob wir bzgl. limeSurvey auf 'latest / greatest' wechseln sollten. Mittlerweile haben wir die Datenabfragen / Schnittstelle  `Optinomic <- limeSurvey` im Griff.  Auch soll ja in Zukunft nicht mehr limeSurvey sondern NG-Survey bevorzugt werden. 

@HansaYohaku:   Freut mich, von Dir zu lesen.  :-)

**Comment by ottigerb** [comment]
...asap um V2 zu testen.

**Comment by SonjaKaufmann** [comment]
Wann wäre asap? Wir sollten die Dezemberabwesenheiten im Auge haben. Also wann können wir umstellen und was braucht es dafür noch?

**Comment by ottigerb** [comment]
**Good NEWS:**
- Die neuste limeSurvey Version ist installiert und Optinomic V2 arbeitet perfekt mit dieser Version zusammen.  Daten werden schnell in Optinomic geladen und Calculations unmittelbar ausgeführt.  
  
  YES!  
- Zugangsdaten etc. werde ich Euch bald zukommen lassen.

**Comment by SonjaKaufmann** [comment]
Hey, das ist ja super!

**Comment by SonjaKaufmann** [comment]
Können wir den Punkt schliessen?

**Comment by ottigerb** [comment]
Erfolgreiche Abschlusstests.  Yes.
=>  Email mit Zugangsdaten versenden.
