### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#130]
**_Leichte Verwirrung auf meiner Seite heute Morgen - 404 und 502 Fehlermeldungen im Template, wobei sich die 404 bisher spätestens nach 1 Minute verzogen haben - und etwas angezeigt oder in 502 geendet haben._**
![image](https://user-images.githubusercontent.com/15833792/31004143-647ad0a6-a4f3-11e7-8de1-54698d33866a.png)
bei http://optinomic.cust.local/api/#/patient/1371/stay/1635/app/ch.suedhang.apps.bscl_anq.production

![image](https://user-images.githubusercontent.com/15833792/31004057-01846af2-a4f3-11e7-8fb2-6ce677e9664c.png)
bei http://optinomic.cust.local/api/#/patient/3085/stay/1615/app/ch.suedhang.apps.tmt.production

**_Da verstehe ich leider immer noch zu wenig davon - siehst du, wo das Problem liegt @ottigerb ?_**

**Comment by schoenenb** [comment]
Die "404 - File not found"-Meldung erscheint bisher bei jeder App, bevor überhaupt etwas geladen wird. Auch wenn man's nur kurz lesen kann, finde ich es doch sehr irritierend.

**Comment by ottigerb** [comment]
Closed because of  https://github.com/ottigerb/therapy-server/issues/462
