### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#131]
Also ich eingeloggt als Therapeutin (Mein 2. Account Sonja Kohls) Frieda Muster öffnen wollte, wurde ich rausgeschmissen und bekam die folgende Fehlermeldung:
![image](https://user-images.githubusercontent.com/20124244/31265984-fb84cd84-aa71-11e7-9cbf-9d1ac64f8236.png)

**Comment by ottigerb** [comment]
...Seite neu laden und nochmals anmelden!  Allenfalls Clear-Browser-Cache.
