### ISSUE TITLE
Schnittstelle :: HoNOS  (Optinomic -> PABS)

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#133]
Lieber Beat, 
wir haben uns der Einfachheit halber darauf geeinigt, dass beim HoNOS als Erhabungsdatum beim Eintritt das Eintrittsdatum und beim Austritt das Austrittsdatum genommen werden soll unabhängig vom wirklichen Eingabedatum. Weil dies mit unterschiedlichen Datumsformaten und der Schnittstelle zu tun hat, wären wir froh, wenn Du dies machen könntest.

**Comment by ottigerb** [comment]
Was ist mit `Messzeitpunkt=3` (Anderer Messzeitpunkt)? 
=>  Den angegebenen Messzeitpunkt nehmen?

**Comment by SonjaKaufmann** [comment]
Mhhh, das müssten dann ja eigentlich die Übertritte sein, sonst haben wir ja keine anderen Messungen mehr. Könnte man da das Übertrittsdatum nehmen?

**Comment by ottigerb** [comment]
Nein, `Übertritt Datum` liegt nicht vor.
Ich schlage vor:  Bei MZ 3  - das angegebene Datum zu verwenden.

**Comment by SonjaKaufmann** [comment]
Ja das ist gut.

**Comment by SonjaKaufmann** [comment]
Kann von mir aus geschlossen werden.

**Comment by schoenenb** [comment]
Was ich am OP noch vermisse ist der Hinweis, dass es um die Export-Syntax geht, nicht um die Darstellung in der App. Dann sollten nämlich auch gar keine MZP=3 mehr vorkommen. Falls ich da was missverstanden habe, bitte noch korrigieren @SonjaKaufmann .

**Comment by SonjaKaufmann** [comment]
Ja ich meinte für den Export ins PABS. Sorry wenn das missverständlich war, dachte dadurch das wir beim Skype drüber geredet haben sei dies klar.

**Comment by ottigerb** [comment]
Der Ball liegt bei D. Graf @ AGB70.  Schnittstelle mit den gewünschten Änderungen läuft. 
=> WARTEN

**Comment by SonjaKaufmann** [comment]
**Nur nochmal zur Nachfrage vor dem Jahreswechsel:** 
Ist es korrekt, dass ab dem nächsten Jahr beim Erfassungsdatum beim HoNOS je nach dem das Eintritts- oder Austrittsdatum steht und nicht das wirkliche Erfassungsdatum? Denn so fordert das BFS die Daten die wir aus dem PABS exportieren. Für 2017 wird es uns noch nachträglich von Freudiger korrigiert, aber ab nächstes Jahr sollte es wie eben beschrieben sein.

**Comment by ottigerb** [comment]
...ich werde diesen Freitag das Thema nochmals vertiefen und dies sicherstellen.

**Comment by ottigerb** [comment]
Die Schnittstellendefinition wurde angepasst:
-  Es kommen ab sofort keine "leeren Fälle" (`cis_fid`) mehr vor. Vgl. Mail von Hr. Daniel.Graf@agb70.ch (Fehler in ANQHONOS-Datei | Patient ohne Fallnummer).

Bzgl. den Eintritts- oder Austrittsdatum - dies ist bereits umgesetzt.  Der Export kann geprüft werden indem ihr folgenden SQL-Code in http://optinomic.cust.local/client.new/#/admin/sql-toolbox kopiert und mittels `[RUN]` ausführt. 

```SQL

SELECT

-- START:  Optinoimc Default |  Needed for Export-Toolbox
  survey_response_view.patient_id as optinomic_patient_id,
  survey_response_view.stay_id as optinomic_stay_id,
  survey_response_view.event_id as optinomic_event_id,
  survey_response_view.survey_response_id as optinomic_survey_response_id,
  survey_response_view.filled as optinomic_survey_filled,
  ((cast(response AS json))->>'id') as optinomic_limesurvey_id,
  -- END:  Optinoimc Default |  Needed for Export-Toolbox

  patient.cis_pid as cis_pid,
  CONCAT(patient.cis_pid, '00', RIGHT((stay.cis_fid/100)::text,2)) as medstatfid,
  stay.cis_fid/100 as fid,
  ((cast(response AS json))->>'FID') as fid_survey,

  'PH' as Rekordart,
  71286515 as betriebsnummer_bur,


  CASE WHEN ((cast(response AS json))->>'q401V04')~E'^\\d+$' THEN ((cast(response AS json))->>'q401V04')::integer ELSE 3 END as zeitpunkt_honos,
  ((cast(response AS json))->>'q401V05') as dropoutcode_honos,
  ((cast(response AS json))->>'q401V06') as spezifikation_dropout_honos_andere,

  CASE (CASE WHEN ((cast(response AS json))->>'q401V04')~E'^\\d+$' THEN ((cast(response AS json))->>'q401V04')::integer ELSE 3 END)
  WHEN 1 THEN to_char(stay.start, 'YYYYMMDD')
  WHEN 2 THEN to_char(stay.stop, 'YYYYMMDD')
  ELSE TO_CHAR(TO_DATE(((cast(response AS json))->>'q402V00'), 'YYYY-MM-DD'), 'YYYYMMDD')
  END as datum_erhebung_honos,

  ((cast(response AS json))->>'H1[402V01]') as honos_h1,
  ((cast(response AS json))->>'H1[402V02]') as honos_h2,
  ((cast(response AS json))->>'H1[402V03]') as honos_h3,
  ((cast(response AS json))->>'H1[402V04]') as honos_h4,
  ((cast(response AS json))->>'H1[402V05]') as honos_h5,
  ((cast(response AS json))->>'H1[402V06]') as honos_h6,
  ((cast(response AS json))->>'H1[402V07]') as honos_h7,
  ((cast(response AS json))->>'H1[402V08]') as honos_h8,
  ((cast(response AS json))->>'q402V09') as honos_h8a,
  ((cast(response AS json))->>'q402V10') as honos_h8b,
  ((cast(response AS json))->>'H2[402V11]') as honos_h9,
  ((cast(response AS json))->>'H2[402V12]') as honos_h10,
  ((cast(response AS json))->>'H2[402V13]') as honos_h11,
  ((cast(response AS json))->>'H2[402V14]') as honos_h12
FROM "survey_response_view"
LEFT JOIN patient ON(survey_response_view.patient_id = patient.id)
LEFT JOIN stay ON(survey_response_view.stay_id = stay.id)
WHERE module = 'ch.suedhang.apps.honos.production'
AND ((cast(response AS json))->>'q401V04') != ''
AND stay.cis_fid is not null
AND survey_response_view.patient_id != '1169'
AND survey_response_view.patient_id != '387'
AND survey_response_view.patient_id != '1'
ORDER BY  patient.cis_pid, stay.cis_fid;
```
