### ISSUE TITLE
Kleinere Änderungen PDFs

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#134]
Lieber Beat,

bis auf kleine Punkte die ich noch mit Nora besprochen hatte, finde ich das es toll geworden ist. Du hast es nochmal kompakter gemacht, das ist schön :-)
Ich nehme an, dass Nora diese Punkte noch postet oder anpasst oder mit Dir anschaut. 

- [ ] Die Lösung mit den Initialen oben auf der Seite und dem Jahrgang finde ich sehr gut, nur würde ich meinen Namen mit S.K. abkürzen und nicht mit K.S., also Vorname.Nachname. 

- [x] Das ganze Dokument würde ich "Fragebogenauswertung" nennen.

- [x] Mir ist aufgefallen, dass bei den Austritts-pdf beim Act-Info die Info über die Rauchstop-Motivation nicht erscheint.

Werde versuchen es wie gewünscht zu testen und dann jeweils Auffälligkeiten in dieses Issue zu schreiben.

**Comment by schoenenb** [comment]
Vielleicht noch als Ergänzung: die Rauchstopp-Motivation steht beim Fagerström. Sonja wünscht sich, dass bei den Problemsubstanzen die Texte audit_text und fagerstroem_text nicht mehr stehen, dafür der motivation_text (siehe meine Änderungen https://github.com/Optinomic/apps/commit/83092bc2e5a36e227ac55d068888b93047a00dfe) nach dem Fagerström.
Ich habe aber gerade gemerkt, dass das mit der aktuellen Darstellung (auch bei Austritt steht: "Folgende Substanzen konsumierte XY vor dem aktuellen Entzug in der angegebenen Häufigkeit:") gar nicht so viel Sinn macht. Ich habe den Ausschnitt drum vorerst mal oberhalb der Fagerström-Darstellung stehenlassen:
![image](https://user-images.githubusercontent.com/15833792/31545195-ad071a1a-b01e-11e7-8456-6573aa2c4059.png)

@ottigerb  Um die ausformulierten Resultate auszublenden habe ich den oben genannten motivation_text anstelle des fagerstroem_text gesetzt und das sieht wie erwartet aus bei den Rauchern (z.B. http://optinomic.cust.local/client.new/#/patient/3211/stay/1546/app/ch.suedhang.apps.fallkonferenz.production/template/overview), aber leider fehlt dadurch jegliche Ausgabe bei den Nichtrauchern, welche du so schön gemacht hast. :(  (z.B. http://optinomic.cust.local/client.new/#/patient/3198/stay/1531/app/ch.suedhang.apps.fallkonferenz.production/template/overview)
- [x] Kannst du den Code so anpassen, dass der Text bei Nichtrauchern wieder eingeblendet wird?
- [x] Kannst du den Code so anpassen, dass der audit_text und fagerstroem_text bei den Problemsubstanzen nicht mehr angezeigt wird?

**Comment by ottigerb** [comment]
Close:  Doppelangabe aus https://github.com/Optinomic/apps/issues/146.

### Sicheres Kürzel:  
Ich habe bei meinen Kollegen gefragt:  
Fazit:   Herr S.B.  =>  S = Nachname & B. = Vorname

**Comment by SonjaKaufmann** [comment]
okay, dann hatte ich das halt verkehrt herum im Kopf, vielleicht ist das ja ein Schweiz-Deutschland- Untterschied :-)
