### ISSUE TITLE
Einführung Client New

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#135]
Lieber Beat, Liebe Nora,

wir haben den Vorstellungstermin für Client New jetzt auf den 25.10.2017 festgesetzt, da wir sonst erst im Dezember ein Zeitfenster gefunden hätten. Ich werde die Einführung dann alleine machen, denke aber ich bekomme das hin.
Ich muss den Therapeuten ja nur zeigen:
- wie sie zu Client New kommen
- Wie Einloggen und das ist gleich geblieben
- wie zum HoNos/TMT/Neuroassessment kommen zum ausfüllen
- wie sie zum Pdf Fragebogenauswertungen kommen und wie die Profile zu verstehen sind
- ggf. wie sie die Auswahl bei einer Fragebogengrafik verändern können, wenn sie spezifisch etwas interessiert (Zahnrädli und Fragezeichen)

Sollte ich noch etwas wichtiges vergessen haben, so schreibt es mir doch bitte. 
Dann gehe ich davon aus, dass die Therapeuten den neuen Link brauchen und wir die Verknüpfung im Polypoint wieder ändern müssen. Dazu habe ich noch ein paar Fragen:

- [x] Können wir diesmal V2 und Client New parallel laufen lassen, so dass sie im Übergang beides nutzen können bis sie sich eingefuchst haben, bzw. eingeführt wurden? Natürlich mit der Empfehlung nach der Einführung das neue System zu nutzen.

- [x] Müssen wir sie anweisen den Cache zu leeren, wie regelmässig und brauchen sie dazu eine Anleitung?

- [x] Beim letzten Mal gab es auch immer Mal wieder Probleme weil Pop-Up-Fenster blockiert waren, kann man das generell einstellen oder muss das jeder bei sich einstellen und haben wir dazu auch eine Anleitung oder soll ich das erwähnen oder sollte dies kein Problem mehr sein, weil schon bei V2 Optinomic Pop-Ups zugelassen werden mussten.

- [x] Können wir für Client New wieder ein Icon anlegen, welches sie auf ihren Desktop kopieren können? Und könntest Du Nora für die beiden Icons und damit verbundenen Weblinks eine Anleitung schreiben? Wo sie sie finden und wie auf ihren Schreibtisch kopieren?

- [x] Wer kann die Verlinkung im Polypoint machen? Damit sollten wir warten bis zumindest alle mit Client New vertraut sind und ich muss dann auch noch die TK einführen und dafür habe ich noch keinen Termin. Vorher sollten sie über den Desktoplink gehen.

- [x] Dann ist mir noch eingefallen, haben wir die Ergebnisse des CASE nicht auch mal irgendwo dargestellt gehabt? Ist uns das durchgegangen oder verwechsle ich da was?

**Comment by schoenenb** [comment]
- Ich glaube die Punkte zu Cache leeren, Pop-Up-Fenster und ev. Polypoint-Verlinkung laufen über TB bzw. Netrics. Falls seit dem 21.7. ein Update gemacht wurde, ist die Pop-Up-Sache ev. schon behoben, müsste ich aber nochmals bei Thömu nachfragen.
- Alles ums neue Icon (solls auch wieder rot sein? oder diesmal grün? ;)) verschiebe ich auf nächste Woche. Falls du @ottigerb eine Vorlage von der Grafik hast, wäre das sehr hilfreich, damit ich nicht wieder alle Kreise im PowerPoint nachzeichnen müsste. :)
- Wird denn der CASE (Summenwert) gebraucht für die Fallkonferenz? Bisher war der glaube ich einfach in einem Satz verpackt angezeigt worden - "XY wies im CASE einen Summenwert von 00 auf".

**Comment by ottigerb** [comment]
- Cache leeren:  Eine kurze Einführung ist m.E. sicherlich sinnvoll. 
- Grafik:  Verstehe nicht genau, was ihr möchtet. Es ist ja ein Favicon vorhanden.
- Polypoint: Header-Link muss ich anpassen. Sobald ihr dies wollt - nach TK Einführung - mir melden.
- Pop-Ups / Links:  Thömu

**Comment by schoenenb** [comment]
Dann werde ich wohl wieder das rote Logo nehmen, damit die Versionen farblich unterschieden werden können.
Wegen dem CASE - habt ihr euch da per Mail abgesprochen, ob der noch reinkommt, weil die Aufgabe abgehakt ist?

**Comment by schoenenb** [comment]
Ich bin gerade beim Anleitung schreiben und da habe ich ein Problem:
Wohin wird der Knopf in Polypoint führen? Zur letzten Behandlung des Patienten oder zur Patientenhauptseite?
@SonjaKaufmann Da der Knopf zum Zeitpunkt der Einführung noch auf V2 geht, müsste das vielleicht noch erwähnt werden:
- V3-Zugang via Verknüpfung, Daten können eingesehen werden, Patienten müssen rausgesucht werden (ausser beim Therapeuten ist ein HoNOS offen, dann erscheint der Patient bereits auf der Startseite bei den offenen Aufgaben)
- V2-Zugang weiterhin via Verknüpfung + innerhalb von 20 Min. nach Anmeldung über den Polypoint-Knopf

**Comment by ottigerb** [comment]
Polypoint-Knopf:  Startseite des Patienten also Patientenhauptseite.
CASE:  Aktuell haben wir ja "nur":  _Herr X weist im CASE einen Summenwert von 100 auf._  Hier müsste sicherlich noch "Spezifiziert" werden.

**Comment by SonjaKaufmann** [comment]
Stimmt. Ich finde der CASE Eintritt sowie Austritt enthält wichtige Infos und finde es schade das er in einem einzigen Summenwert dargestellt wird. Da sollten wir nach der Einführung nochmal drüber nachdenken. Werde dann auch noch das Gespräch mit der Therapieleitung suchen, aber eigentlich möchten sie ja gerne auf einen Blick wissen, wieviel Entzüge z.B. schon stattgefunden haben und so. Wäre wohl sinnvoll mal die alten CASE-Daten auszuwerten, was davon zur Prognose des Therapieerfolges sinnvolle Informationen bietet. Aber ich denke das vertagen wir für nach der Einführung.
