### ISSUE TITLE
TMT Werte nicht beschränkt

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#136]
http://optinomic.cust.local/client.new/#/patient/3198/stay/1531/app/ch.suedhang.apps.fallkonferenz.production/template/overview

Bei diesem Patienten sieht die TMT-Auswertung etwas komisch aus (geht aus Darstellungsbereich)

Könntet ihr diese Einstellungen noch korrigieren?

**Comment by SonjaKaufmann** [comment]
Mir ist auch noch aufgefallen, dass der TMT nicht mit unserem rechts/links-Schma übereinstimmt. Könnte man den noch umpolen und natürlich auch die Beschriftung wechseln? Links schnell und somit günstige Werte und rechts langsam und somit rote ungünstige Werte.

**Comment by schoenenb** [comment]
Abgesehen davon, dass der Darstellungsbereich zu klein war, sieht die Grafik auch komisch aus, weil die Klinikstichprobe aus N=1 und damit keine Streuung besteht, bzw. die A- & B-Werte der "Vergleichsstichprobe" als Mittelwert angezeigt werden.
Eine neue Variable für tmtA & tmtB habe ich erstellt -> tmtA_z_neu & tmtB_z_neu sowie die _rounded Kurzformen (https://github.com/Optinomic/apps/commit/c81af044ab2f1f3f4d6269bea0dd4804b79ad1ae) - habe aber nicht geschnallt, wo ich die einsetzen müsste, damit dann tatsächlich diese Daten erscheinen. Wo ich's in element-tmt.html hätte ändern können hat sich mir leider auch nicht erschlossen, drum die Variante über die calculations...

@ottigerb Wie du siehst (https://github.com/Optinomic/apps/commit/d33aa9afe1192abf93d94b318b6a0deb29d5e43a & https://github.com/Optinomic/apps/commit/644e76aecc854a90ffd8ded98d54c400da038459) wollte ich erst die Variablen umbenennen. Das wäre zwar in meinen Augen leichter gewesen, um die Darstellung schnell zu ändern, hätte aber wieder ein Durcheinander beim Export gegeben, weil dann die alten Limesurvey-Daten die gleiche Variablenbezeichnung hätten wie die neuen umgedrehten z-Werte (*-1).

**Comment by schoenenb** [comment]
@ottigerb kommst du dazu, beim TMT noch die neuen Werte (tmtA_z_neu und tmt_B_z_neu bzw. _rounded) einzubinden?
Wenn ja, würden sich die definitions folgendermassen ändern:
```
d.tmt = {
    "options": {
        "min": -6,
        "max": 6,
        "item_height": 58,
        "item_text_left": 100,
        "item_text_right": 100,
        "color_grid": "#9E9E9E",
        "color_clinic_sample": "#888888",
        "color_skin": "grey_dark_to_light",
        "show_baseline": false,
        "show_ranges_overview": false,
        "show_scale_text": true,
        "show_score_vertical_line": false,
        "show_score_profile_line": true,
        "show_score_circles": true,
        "range_alpha": 0.09,
        "show_settings_block": false,
        "allow_toggle_settings_block": true,
        "topnumber_hide_first_last": false,
        "vertical_grid_every_x": 1,
        "norm_sample": "Z-Normierung anhand von Gesunden",
        "response_title_path": "calculation.tmt_score.Messzeitpunkt.Messzeitpunkt_Text",
        "response_date_path": "date"
    },
    "start": {
        "left_title": "schnell",
        "left_text": "Schneller im Vergleich zur Norm",
        "left_color": "#4CAF50",
        "right_title": "langsam",
        "right_text": "Verlangsamung gegenüber Norm",
        "right_color": "#F44336"
    },
    "scales": [{
        "left_title": "TMT A",
        "left_text": "schnell",
        "right_title": "TMT A",
        "right_text": "langsam",
        "m_norm": "?",
        "sd_norm": "?",
        "score_path": "calculation.tmt_score.percentile.z_scores.tmtA_z_rounded",
        "clinic_sample_var": "TMTAZ",
        "items": 1
    }, {
        "id": 1,
        "left_title": "TMT B",
        "left_text": "schnell",
        "right_title": "TMT B",
        "right_text": "langsam",
        "m_norm": "?",
        "sd_norm": "?",
        "score_path": "calculation.tmt_score.percentile.z_scores.tmtB_z_rounded",
        "clinic_sample_var": "TMTBZ",
        "items": 5
    }],
    "ranges": [{
        "range_start": -999,
        "range_stop": -2,
        "text": "Normale Geschwindigkeit",
        "color": "#2E7D32"
    }, {
        "range_start": 1,
        "range_stop": 999,
        "text": "Verlangsamung gegenüber Norm",
        "color": "#C62828"
    }]
};
```

**Comment by SonjaKaufmann** [comment]
Ja das bräuchte es noch, bei Pat. http://optinomic.cust.local/client.new/#/patient/3347/stay/1633 geht es immer noch über die Graphik.

**Comment by SonjaKaufmann** [comment]
- [x] Auch das umdrehen für die richtige rechts-links Logik fehlt noch

- [x] Begrenzen des TMT fehlt noch

**Comment by ottigerb** [comment]
## Done - Example:  
http://optinomic.cust.local/client.new/#/patient/2853/stay/1542/app/ch.suedhang.apps.fallkonferenz.production/template/overview

**Comment by SonjaKaufmann** [comment]
blob:http://optinomic.cust.local/7073a8c1-a24d-46f2-a17c-de0ab2ab0f47

Also hier stimmt der TMT noch nicht, die Begrenzug funktioniert nicht, die Werte liegen ausserhalb der Graphik. Und die Hintergründe müssen auch noch neu angepasst werden. Der grüne Hintergrund geht bis -1 und der rote startet bei +2.
Ist für die Einführung nicht so wichtig, aber stimmt halt noch nicht.

**Comment by SonjaKaufmann** [comment]
Sorry, der grüne HIntergrund geht bis +1 und der rote fängt bei +2 an zwischen +1 und +2 ist der Hintergrund weiss.

**Comment by ottigerb** [comment]
Done

**Comment by SonjaKaufmann** [comment]
Mhh, glaube das gleiche gilt dann auch für den WHOQoL.  Ich versuche Mal die logik dahinter auszuformulieren, da ich mitlerweile auch etwas verunsichert bin. +/- 1 Standardabweichung um 0 befinden sich Normal/Gesunde Werte = Gute Werte. Wenn jemand 2 Standardabweichungen von Z-Wert 0 abweicht, dann haben nur ca. 2,5 % der gesunden ähnlich schlechte Werte oder schlechtere Werte, wenn es in die ungünstige Richtung, bei uns also rechts. Dazwischen sind sie nicht im gesunden Rahmen, aber auch nicht extrem auffällig. Klingt das plausibel für Euch?

**Comment by SonjaKaufmann** [comment]
Der Patient hat zB immer noch Werte ausserhalb der Graphik, daher öffne ich den Punkt nochmal.
http://optinomic.cust.local/client.new/#/patient/3347/stay/1633

**Comment by ottigerb** [comment]
Der Range der Grafik wird hier definiert:
```
d.tmt = {
    "options": {
        "min": -6,
        "max": 6,
```

Gemäss http://optinomic.cust.local/client.new/#/user/app/ch.suedhang.user.apps.ks_tmt/template/score_overview liegt TMTAZ zwischen 2.8 und -9.8 / TMTBZ zwischen 4.0 und -18.6 

Wir könnten nun die Angabe von Options wie folgt erweitern:

1.)   Options erweitern
```
d.tmt = {
    "options": {
        "min": -3,
        "max": 19,
```
oder

2.) Automatische Rangebestimmung
```
d.tmt = {
    "options": {
        "min": -3,
        "max": "auto",
```

Meine Stimme geht für 2.) auch wenn dann die Grafiken nicht immer den selben "Ausschnitt" zeigen.

**Comment by SonjaKaufmann** [comment]
Ja da bin ich auch dafür. Und wenn es die Therapeuten zu sehr irritiert, dann können wir ja wieder wechseln.
