### ISSUE TITLE
Access - Forms :: Improvements

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#138]
### Access - Forms

- [x] Data Refresh gemäss https://github.com/Optinomic/apps/issues/138#issuecomment-338716787

**Comment by ottigerb** [comment]
Bitte klarer spezifizieren:  
- Welcher Client
- Warst Du angemeldet, oder lange Zeit nicht mehr aktiv?
- Lässt sich der Effekt reproduzieren?

Alles `Prio 1`!?   Wirklich!?

**Comment by SonjaKaufmann** [comment]
Client Sonja Kohls (Psychologin)
Patient 3108, welcher schon abgeschlossen ist und daher auch keine Berechtigung besteht, aber deshalb muss mich das System ja nicht rausschmeissen und ich mich wieder neu einloggen.
Und ja Prio 1, denn wenn es das nach der Einführung bei allen macht und sie sich dauernd neu einloggen müssen, dann werden sie recht genervt sein!
Fehler reproduzierbar mit der folgenden Fehlermeldung:
![image](https://user-images.githubusercontent.com/20124244/31715903-f9d4cde8-b405-11e7-9cfe-0fee0264dfef.png)

**Comment by ottigerb** [comment]
Tatsächlich - Fehler behoben: https://github.com/ottigerb/therapy-server/commit/9fecded0db0cedf8ccfc031229b6448708b2374c 

Wenn der Zugriff aufgrund der `Patient-Access` (Impliziter / Expliziter Behandlungsauftrag) verweigert wird erscheint nun wieder korrekterweise das entsprechende Formular.

**Comment by SonjaKaufmann** [comment]
Es passiert immer noch. Habe Cache geleert und bei einem anderen abgeschlossenen Patienten versucht und wurde wieder rausgeworfen (damit meine ich, dass ich wieder zum Login komme und es kam wieder der Fehler.
![image](https://user-images.githubusercontent.com/20124244/31718572-bc31cf9e-b410-11e7-9daf-77dd6c1a9d8f.png)

**Comment by SonjaKaufmann** [comment]
Wenn ich mich dann wieder einlogge, dann muss ich unten den Fehler wegklicken, aber es erscheint kein Formular.

Soll ich den Punkt mit den Rollenaufgaben separat nehmen, denn die sind auch noch drauf?

**Comment by ottigerb** [comment]
...Du bist lokal - Südhang?  Der Fix wird erst auf den demoserver geladen.  Beim nächsten Stable wird dieser ach der Südhang erhalten. Testen der neusten Features/Bugfixes immer auf dem Demo.

**Comment by SonjaKaufmann** [comment]
Okay, jetzt habe ich es erneut angeschaut und ich nehme an es ist aktualisiert, denn die Rollenaufgaben sind nun verschwunden :-) und komme jetzt auf die Maske für die Angabe des Nutzungsgrundes, aber wenn ich dort etwas auswähle und 24 Stunden Zugriff möchte, dann kommt der folgende Fehler:
![image](https://user-images.githubusercontent.com/20124244/31875064-bf2b63b2-b7cc-11e7-8dd9-7fab3c820def.png)

**Comment by ottigerb** [comment]
Fehler bestätigt - wird hoffentlich dadurch eliminiert:  https://github.com/ottigerb/therapy-server/commit/66d588b663d84aabe289b8ed71e4431eb76eae0c. =>  Next Stable!

Versuche doch noch andere Formulareingaben - bin gespannt welche Variante zu "erfolgreichem" Speichern führt.  :-)

**Comment by SonjaKaufmann** [comment]
alle Varianten führen zu dem Fehler und ich komme nicht weiter. Zudem kann man Assessment nicht alleine anklicken, es sind in dem Fall dann immer zwei aktiviert.

Wann wird denn der Next Stable ausgeführt?

**Comment by ottigerb** [comment]
```
    "access_forms": [{
        "identifier": "Behandlungsauftrag",
        "description": "Informationen zu Ihrem Behandlungsauftrag",
        "type": "patient",
        "title": "Behandlungsauftrag | Zugriff",
        "header": "Behandlungsauftrag: Es ist Ihnen kein impliziter Behandlungsauftrag zugeordnet.",
        "fields": [{
            "type": "select",
            "identifier": "FormBA_Select_Reason",
            "label": "Begründung",
            "options": [
                { "value": "1", "text": "Zur Fertigstellung von Berichten" },
                { "value": "2", "text": "Notfallsituation" },
                { "value": "3", "text": "Zur Vorbereitung | Geplanter Eintritt" },
                { "value": "4", "text": "Assessment" }
            ]
        }, {
            "type": "textarea",
            "identifier": "FormBA_Textarea_Remarks",
            "label": "Bemerkungen"
        }],
        "footer": "Begründen Sie, warum Sie auf den oben genannten Patienten zugreifen möchten. Danke.",
        "validity": 86400
    }],
```

=>  Oh, guter Hinweis - Assessment war fälschlicherweise auch mit Value=3 versehen. Interessant, dass dies erst jetzt "gemerkt" wird.  Dies hat nichts mit `client.new` zu tun.  Anyway:  Fixed:  https://github.com/ottigerb/therapy-server/commit/c79222e0e6d8eee6440db311d9115e5c87ce197c

=> Stable ist angekommen.  Jedoch noch nicht mit diesem Assessment doppelt.  Versuche jetzt nochmals - zuerst Cache leeren - zur Sicherheit!  Danke!

**Comment by SonjaKaufmann** [comment]
Irgendwie verschwinden heute auch meine GitHub-Einträge immer wieder, komisch.
Also der Fehler taucht als Therapeut/Psychologe immer noch auf.

**Comment by ottigerb** [comment]
Hast Du "Cache" geleert?  Habe soeben den aktuellen Stable angefordert. 


Dieser sollte in den nächsten 10 Minuten ankommen:
http://optinomic.cust.local/client.new/#/admin  zeigt aktuell:  https://github.com/ottigerb/therapy-server/commit/9592c170eebc40ac3f4adb7d89ea872b16e1af26   wird c79222e0e6d8eee6440db311d9115e5c87ce197c.

**Comment by SonjaKaufmann** [comment]
Ne noch nicht, war mich gerade am ausloggen, aber dann prüfe ich das gleich nochmal.

**Comment by SonjaKaufmann** [comment]
Mhhhh, muss wohl nochmal leeren und noch warten, gerade ging es noch nicht.

**Comment by SonjaKaufmann** [comment]
Es geht immer noch nicht. Nur das wir uns nicht falsch verstehen. Es handelt sich um abgeschlossene Patienten, welche ich als Therapeut aus irgendeinem Grund einsehen möchte und mir ist noch kein Behandlungsauftrag zugeordnet. Also wenn ich z.B, weiss es kommt ein Patient, der war vor längerem schon Mal da und ich möchte mit die letzte Behandlung anschauen. Wenn ich als Admin reingehe, dann habe ich ja immer Zugriff. Aber wenn ich mit meinem 2. Therapeuten-Account drin bin, dann geht es immer noch nicht.
Verabschiede mich jetzt in den Feierabend und versuche es morgen wieder, nachdem ich den Cache geleert habe.

**Comment by ottigerb** [comment]
Ich habe einen Testtherapeuten (Therapeut Test) angelegt und selbst versucht:

1.)  Access-Form erscheint wie erwartet:
![bildschirmfoto 2017-10-23 um 18 20 56](https://user-images.githubusercontent.com/2470873/31901102-cc58a3c0-b820-11e7-9926-2fb279250a57.png)



2.)  Zugriff anfordern funktioniert ebenfalls. Die Behandlungen bleiben jedoch leer.
![bildschirmfoto 2017-10-23 um 18 21 11](https://user-images.githubusercontent.com/2470873/31901112-d660bec0-b820-11e7-947b-855cf5829669.png)

Nach einem F5 der Seite:  http://optinomic.cust.local/client.new/#/patient/1453
Wird auch der Fall etc. geladen und kann "normal" betrachtet werden:

![bildschirmfoto 2017-10-23 um 18 21 52](https://user-images.githubusercontent.com/2470873/31901133-df70c9d8-b820-11e7-81b9-cdff304ee7f5.png)



=>  Bug.:  Assessment / Doppelte Selektion wird morgen behoben. 
=>  Prio 2 ::  Sauberes "Data Refresh" nachdem das Formular versendet wurde.

**Comment by SonjaKaufmann** [comment]
Also ich bekomme weiter den Fehler 500 und komme nicht weiter.

Dann verstehe ich nicht, wie man den Fall auswählen soll, wenn die Behandlungen leer bleiben?
Bzw. wieso nochmal ein F5, Also das hat für mich Prio 1, denn das ist echt doof, wenn ich bei der Einführung schon tricksen muss.
Das mit dem doppelten Klick auf Assessment ist nicht so wichtig.

**Comment by ottigerb** [comment]
...versuche doch weiterhin ob Du den Error 500 "beheben" kannst. Cache leeren, Access-Form Seite neu laden etc. etc.  =  Ich kann diesen Fehler nicht reproduzieren. 

...bzgl. Tricks - ich schau, was ich heute noch erreiche. Vielleicht fällt ja ein Patient aus - oder es gibt Nachtschicht. Hab da eine Idee wie dieses "Reload" gelöst werden könnte.

**Comment by SonjaKaufmann** [comment]
Ich versuche es nochmal. 
Vielleicht kannst Du mir ja mal deinen Testtherapeuten nennen und sein login und ich kann schauen ob es nur bei meinem Kohls-Testtherapeuten schief läuft.

**Comment by SonjaKaufmann** [comment]
Habe alles versucht:
Login ,it privaten Computer, logout und neu Login -> Fehler 500 beim auftun des Patienten
erneut Cache geleert -> Fehler 500
F5 -> Fehler 500
**Seite neu gelade -> Erfolg!!!!!!**
Hoffe das wirkt nachhaltig. Habe es mit zweitem Patienten versucht und auch dort ging es ohne das ich etwas machen musst.

**Comment by SonjaKaufmann** [comment]
Das mit dem Seite neu laden funktioniert, bis ich wieder ausgelockt war. Dann muss ich beim ersten Formular nochmal Seite neu laden, dann geht es auch bei allen weiteren. Hope that helps.

**Comment by ottigerb** [comment]
...Danke - solche Feedbacks sind sehr hilfreich!

**Comment by ottigerb** [comment]
Again:  Der Tip mit "neu anmelden" => SQL Error 500 war wirklich Gold wert.  Ich konnte den Fehler reproduzieren und dann auch lösen. Auch wird nun gleich nach `[Zugriff für 24 Stunden]` alle Daten korrekt geladen.  Neuer Stable is currently building => Wird asap den Weg zu Euch finden. Ich werde es auf dem Südhang-Server nochmals testen und hoffentlich Issue schliessen.

**Comment by ottigerb** [comment]
**YES** :: Funktioniert m.E. nun "tadellos"!

**Comment by SonjaKaufmann** [comment]
Also zur Einführung ist es nicht so schlimm, aber bei mir kommt jetzt gar nicht mehr das Zugriffsformular, habe von meinem Therapeuten-Account Zugriff auf alle Daten!

**Comment by ottigerb** [comment]
Vielleicht sind die 24 Stunden noch nicht abgelaufen?  Andere Patienten ebenfalls geprüft?

EDIT:: Soeben nochmals getestet:  Bei mir funktioniert alles Einwandfrei.

**Comment by SonjaKaufmann** [comment]
Mehrere Pateinten getestet und sind schon länger ausgetreten. Kein Formular.

**Comment by ottigerb** [comment]
...bei mir wie gesagt: Alles tiptop.  Allenfalls Cache nochmals leeren.

**Comment by SonjaKaufmann** [comment]
Jetzt ist es angekommen :-) Tiptop!
