### ISSUE TITLE
Satz zuviel

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#139]
![image](https://user-images.githubusercontent.com/20124244/31718191-35ed0292-b40f-11e7-8ef6-3d38ba82f44a.png)

- [ ] Der Satz ist irreführend, bitte streichen in App und pdf.

**Comment by schoenenb** [comment]
Das hatten wir vorletzte Woche besprochen und ich meinte das letzte Woche auch geändert zu haben. Muss da in dem Fall nochmals schauen, weshalb das nicht funktioniert hat. Merci für die Rückmeldung!

**Comment by ottigerb** [comment]
...das ist m.E. erledigt. Allenfalls "App-Fetcher"

**Comment by schoenenb** [comment]
Ich hatte sie nur bei der Demo-Version angepasst, werde die Version noch auf die Südhang-Version anpassen.
