### ISSUE TITLE
[Optinomic] Patienten-Assessment :: Cleanup

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#14]
Überarbeitung der **Patienten-Assessment** Übersicht.  
### Grundsätzlich

So 'clean' wie möglich.  Unnötiges nicht anzeigen. M.E. die rot markierten Zonen:

![neubildschirmfoto-2016-10-21-um-09 47 49](https://cloud.githubusercontent.com/assets/2470873/19590918/ad3ea46c-9774-11e6-844e-4cfa0ccc4d7b.png)

Sprachauswahl und Klinikinfos würde ich beibehalten.
### Offene Aufgaben

Folgender Screen wird aktuell gezeigt, wenn der Patient offene Aufgaben hat:   

![bildschirmfoto 2016-10-21 um 09 56 19](https://cloud.githubusercontent.com/assets/2470873/19590920/b1da3108-9774-11e6-9a15-29e91ae562ea.png)
### Fragen
- Wie soll der Knopf [Auf neue Ergebnisse prüfen] benannt werden?  
- Sind die Texte so i.O.?
- Roter Bereich löschen? Noch mehr löschen?

**Comment by schoenenb** [comment]
Genau, der rote Teil soll weg. 
Wenn's nach mir geht auch die Adressangabe unterhalb der Überschrift "Aufgaben: Ottiger Patient" sowohl in der Seitenüberschrift als auch im Titel (Geburtsdatum und Alter so belassen).
- Den Text möchte ich noch überarbeiten. Es sollte sicher etwas von dem stehen, was bisher auf dem Deckblatt von den Assessment-FBn vermerkt war. 
- Auf dem Knopf sollte sowas wie [Bestätigen] oder [Ich habe alle Fragebögen ausgefüllt.] stehen.

**Comment by ottigerb** [comment]
Wunderbar:  Ich warte mal Deine Textüberarbeitung ab - dann wird umgesetzt.

**Comment by SonjaKaufmann** [comment]
Nochmal meine Frage, die ich wohl an anderer "falscher" Stelle gestellt habe.
Ist es nicht möglich die Aufgabe "Eintritts resp. Austrittsassessment" ausfüllen zu kreieren und die Fragebögen irgendwie zusammenzuhängen? So das die Patienten nicht 7 Fragebögen hintereinander offnen und schliessen müssen? Natürlich mit verstecktem Abbruchbutton für uns, falls jemand nur in der Lage ist die wichtigsten auszufüllen.

**Comment by ottigerb** [comment]
@SonjaKaufmann   Nein, jeder Fragebogen hat seinen eigenen "Event" (diese HASH-ID's)  - diese als Gruppe zusammenfügen ist vom Design nicht vorgesehen.    

Heute ist 'Therapie-Tag' - ich wünsche Euch frohes Sein. 
=>Die Sonne scheint ja schon mal im Sonja Logo.   Schööön!

**Comment by SonjaKaufmann** [comment]
Ach, ich finde Design wird schlicht weg überschätzt, ha ha ha!

Wünsche auch frohes Sein in der Therapie und habe jetzt auch meine Kommentare fertig!

**Comment by ottigerb** [comment]
Willkommen zum Gruppen-Assessment der Klinik Südhang!

Sie finden untenstehend einige Fragebögen, in denen Sie Aussagen zu verschiedenen Themen und Zeiträumen einschätzen sollen. Lesen Sie bitte am Anfang jedes Fragebogens die Anweisungen sorgfältig durch. Achten Sie dabei auf die rot markierten Angaben zu den Zeiträumen, auf die sich die Fragen und Aussagen beziehen. Diese sind von Fragebogen zu Fragebogen unterschiedlich.
Alle Fragebögen enthalten Aussagen. Ihre Aufgabe ist zu bewerten, inwieweit diese Aussagen auf Sie bzw. Ihre Situation zutreffen. Antworten Sie möglichst spontan – es gibt keine richtigen oder falschen Antworten. Wichtig ist, dass die jeweilige Antwort für Sie persönlich stimmt.
Wir bitten Sie, die unten aufgeführten Fragebögen in der bestehenden Reihenfolge lückenlos zu bearbeiten. Zum starten JEDES EINZELNEN Fragebogens klicken Sie am rechten Rand des angegebenen Fragebogens auf „START“.

Falls Sie Fragen nicht verstehen oder etwas unklar ist, wenden Sie sich an die anwesende Betreuungsperson.
BSCL (Datum; ohne „scheduled manually“) …. [START]
SCI (Datum; ohne „scheduled manually“)…. [START]
AASE-G (Datum; ohne „scheduled manually“)…. [START]
[…]

Wenn Sie mit der Bearbeitung fertig sind, bestätigen Sie dies bitte, indem Sie auf den folgenden Knopf drücken.
[Bestätigen]

**Comment by ottigerb** [comment]
Sonja gibt ein 'Go'.

**Comment by schoenenb** [comment]
Ein paar Änderungen von Sonja, so kann's dann übernommen werden:

Willkommen zum Gruppen-Assessment der Klinik Südhang!

Sie finden untenstehend einige Fragebögen, in denen Sie Aussagen zu verschiedenen Themen und Zeiträumen einschätzen sollen. Am Anfang jedes Fragebogens finden Sie eine kurze Anleitung. Lesen Sie diese bitte sorgfältig durch. Achten Sie dabei auf die rot markierten Angaben zu den Zeiträumen, auf die sich die Fragen und Aussagen beziehen. Diese können von Fragebogen zu Fragebogen unterschiedlich sein.
Alle Fragebögen enthalten Aussagen. Ihre Aufgabe ist zu bewerten, inwieweit diese Aussagen auf Sie bzw. Ihre Situation zutreffen. Antworten Sie möglichst spontan – es gibt keine richtigen oder falschen Antworten. Wichtig ist, dass die jeweilige Antwort für Sie persönlich stimmt.
Wir bitten Sie, die unten aufgeführten Fragebögen in der bestehenden Reihenfolge lückenlos zu bearbeiten. Zum starten JEDES EINZELNEN Fragebogens klicken Sie am rechten Rand des angegebenen Fragebogens auf „START“.

Falls Sie Fragen nicht verstehen oder etwas unklar ist, wenden Sie sich an die anwesende Betreuungsperson.
BSCL (ohne Datum; ohne „scheduled manually“) …. [START]
SCI (ohne Datum; ohne „scheduled manually“)…. [START]
AASE-G (ohne Datum; ohne „scheduled manually“)…. [START]
[…]

Wenn Sie alle Fragebögen in der Liste vollständig ausgefüllt haben, bestätigen Sie dies bitte, indem Sie auf den folgenden Knopf drücken.

Herzlichen Dank :-)
[Bestätigen]

**Comment by ottigerb** [comment]
Super, Danke!

**Comment by ottigerb** [comment]
Texte sind drin:
![bildschirmfoto 2016-11-04 um 14 33 10](https://cloud.githubusercontent.com/assets/2470873/20007265/bb238912-a29b-11e6-91b3-29ff7500020d.png)

sowie:

![bildschirmfoto 2016-11-04 um 14 33 27](https://cloud.githubusercontent.com/assets/2470873/20007264/bb07e626-a29b-11e6-978b-147cd56b36dc.png)

Mögliches Tuning | Reopen if needed!  
- Allenfalls kleinere Schriftgrösse? Lesbarkeit ist jedoch mit dieser Schriftgrösse perfekt!
- Titel (Müller Fridolin) ersetzen mit _Willkommen zum Gruppen..._

**Comment by schoenenb** [comment]
Anordnung der Fragebögen möglich? Bin mir nicht sicher, ob es eine Rolle spielt, in welcher Reihenfolge die Bögen ausgefüllt werden, grundsätzlich hatten wir uns dort aber mal etwas überlegt, weshalb die in der bestehenden Reihenfolge vorgegeben werden...
Oder nur über Namensgebung "1. BSCL", "2. SCI" usw. möglich?

**Comment by schoenenb** [comment]
Tut mir leid, dass ich im Moment nichts rechtzeitig liefern kann. Im Folgenden findest du meinen Vorschlag für die Anzeige beim Patientenzugang. Eigentlich steht da schon alles, nur was hier eben nicht mehr steht, sollte weg (der erste grosse Textblock).
**Falls das gleich in einem Zug geht wär's gut, den Titel "Name | Geb.datum | Aufgaben" wegzulassen oder mit dem Willkommens-Teil zu ersetzen.**

Willkommen auf der Fragebogen-Plattform der Klinik Südhang! 

Wir bitten Sie, die unten aufgeführten Fragebögen in der bestehenden Reihenfolge lückenlos zu bearbeiten. Zum starten JEDES EINZELNEN Fragebogens klicken Sie am rechten Rand des angegebenen Fragebogens auf «START».

Falls Sie Fragen nicht verstehen oder etwas unklar ist, wenden Sie sich an die anwesende Betreuungsperson.

Fragebogen 1 – [START]
Fragebogen 2 – [START]
Fragebogen 3 – [START]
Fragebogen 4 – [START]

Wenn Sie alle Fragebögen in der Liste vollständig ausgefüllt haben, bestätigen Sie dies bitte, indem Sie auf den folgenden Knopf drücken:

BESTÄTIGEN

Herzlichen Dank!

**Comment by schoenenb** [comment]
Im Patientenassessment steht leider immer noch der gesamte Text... Ich bin davon ausgegangen, dass dies der Teil ist, den ich nicht selber machen kann, weil ihr das irgendwo im Hintergrund programmiert.

**Comment by ottigerb** [comment]
...jep, dies ist klar.   Ich habe nun die "Fixes" - pushed @ https://github.com/ottigerb/therapy-server/commit/6cc82a7e845856892313e8d842a347f77ff1e883 bis https://github.com/ottigerb/therapy-server/commit/1483fcfc13b524f1c62f4183026faf0a2029fa53.  Nun muss ein neuer "Stable Build" erstellt werden, welcher dann auf Südhang eingespielt werden kann. Das Assessment ist nicht eine "App" welche on-the-fly ersetzt werden kann.  

...vielleicht haben diese Versuche auch was mit  https://github.com/Optinomic/apps/issues/66 zu tun.  

=>  Finden wir es raus!

**Comment by ottigerb** [comment]
Patienten-Assessment wurde wie folgt aktualisiert:

### Mit Tasks:
![bildschirmfoto 2017-01-23 um 15 16 40](https://cloud.githubusercontent.com/assets/2470873/22207546/df764a48-e17f-11e6-92e8-3f65c6e04a55.png)


### Done:
![bildschirmfoto 2017-01-23 um 15 18 31](https://cloud.githubusercontent.com/assets/2470873/22207547/df76b46a-e17f-11e6-9cab-81c9b884dcd2.png)

**Comment by schoenenb** [comment]
Da von den HiWis nachgefragt wurde, stelle ich die Frage von Anfangs Jahr nochmals - hoffe das hat sich nicht mal in einem Mail beantwortet:

> Anordnung der Fragebögen möglich? Bin mir nicht sicher, ob es eine Rolle spielt, in welcher Reihenfolge die Bögen ausgefüllt werden, grundsätzlich hatten wir uns dort aber mal etwas überlegt, weshalb die in der bestehenden Reihenfolge vorgegeben werden...
Oder nur über Namensgebung "1. BSCL", "2. SCI" usw. möglich?

Wär's über eine Nummerierung möglich, die Fragebögen fix anzuordnen statt dass sie bei jedem Patienten in einer anderen Reihenfolge erscheinen?

**Comment by ottigerb** [comment]
Kann es sein, dass die Reihenfolge bestimmt ist in welcher die Applikationen in der Patientengruppe hinzugefügt werden?

**Comment by schoenenb** [comment]
Sieht so aus. Es scheint sich aber an der Reihenfolge, wie sie in V2 aufgeführt war zu orientieren. Allerdings ist das im client.new nicht mehr ersichtlich, weil sie dort nach Alphabet sortiert sind.
Erst dachte ich anhand der Logfiles, dass die Apps manuell erstellt worden sind...
![image](https://user-images.githubusercontent.com/15833792/41027242-ce96d85c-6976-11e8-9c61-9788c8f7d1f0.png) [patient-id 3858]
Allerdings zeigt es mir dasselbe an bei einem Patientn, den ich heute manuell hinzugefügt habe [patient-id 3414].

Hier mal ein Einblick, wie unterschiedlich die Fragebögen angeordnet sind (PID - Aktivierungsdatum - Fragebögen):

13008 | 13002 | 11815 | 13003 | 12997 | 13014 | 12646
-- | -- | -- | -- | -- | -- | --
4.6. | 4.6. | 4.6. | 4.6. | 4.6. | 5.6. | 6.6.
ASRS | WHOQOL | ASRS | ASRS | ASRS | ASRS | BSCL
ISK-K | BDI | SCI | SCI | BDI | SCI | ASRS
SCI | ASRS | AASE-G | AASE-G | WHOQOL | AASE-G | SCI
AASE-G | SCI | ISK-K | ISK-K | SCI | ISK-K | AASE-G
WHOQOL | AASE-G | WHOQOL | WHOQOL | AASE-G | WHOQOL | ISK-K
BDI | ISK-K | BDI | BDI | ISK-K | BSCL | WHOQOL
  |   |   |   |   | BDI | BDI
