### ISSUE TITLE
_Belegung liefert fehlerhafte Daten => Patientengruppen leer / falsch

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#140]
`com.optinomic.init.poly_stay` liefert:  `Invalid Date`
Bsp.:
http://optinomic.cust.local/client.new/#/patient/2854/stay/1669/app/com.optinomic.init.poly_stay/template/init

=>  Patientengruppen:  "EAS aktuell" etc. funktionieren nicht mehr.

`com.optinomic.apps.poly_stay` / Task debuggen!

**Comment by SonjaKaufmann** [comment]
Lieber Beat,
kannst Du mir noch erklären welche Patienten eigentlich in der Patientenauswahl sind? Es sind ja nicht die Favoriten, die sind ja unter Favoriten. Ist das eine Gruppe die der Therapeut, wenn die Patientengruppenzusammenstellungen nach Filtern funktionieren selber zusammenstellen kann? Und aktuell? Sind da dann alle Patienten drin die ihm zugeordnet sind oder ist die Patietnenauswahl vorerst noch leer?

**Comment by SonjaKaufmann** [comment]
Und die Patientengruppen, da haben die Psychologen dann derzeit nichts zur Auswahl oder haben sie alle mit V2 erstellten Gruppen zur Auswahl, wenn es wieder läuft?

**Comment by ottigerb** [comment]
**Patientenauswahl:**  Der Benutzer kann hier seinen Filter erstellen / verändern:  http://optinomic.cust.local/client.new/#/patients/filter/edit

Aktuell sind alle Patientengruppen mit "_Belegung" als Datenquelle - also EAS aktuell" etc. leer. Vorhanden sind diese und werden auch wieder korrekt gefüllt sobald der BUG behoben ist.

**Comment by SonjaKaufmann** [comment]
Ah über den Stift, den hatte ich übersehen. Danke.

**Comment by ottigerb** [comment]
### FIXED  
Gruppenzuordnung funktioniert nun wieder einwandfrei.
