### ISSUE TITLE
Falsche Normwerte ISK?

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#142]
Ich habe gerade mit Erschrecken festgestellt, dass die Normwerte in der ISK-Definition denen vom BSCL entsprechen!
Für den ISK haben wir nämlich gar keine Geschlechterunterscheidung bei der Normierung.
Oder werden die m_norm und sd_norm gar nicht verwendet?

**Comment by schoenenb** [comment]
Habe beim TMT gesehen, dass dort ? drin steht, dann wirds wohl nicht so wichtig sein. Sorry für die Hysterie.

**Comment by ottigerb** [comment]
Nicht verstanden.

**Comment by ottigerb** [comment]
m_norm und sd_norm wird nicht verwendet.  =>  Close
