### ISSUE TITLE
Angabe Normstichprobe

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#143]
Beim TMT & WHOQOL unterscheidet sich das N der Normstichprobe je nach Gruppe.

Kann man in der Definition (Bsp. vom WHOQOL)...
`"norm_sample": "Z-Normierung anhand von Gesunden",` 
...dem Text noch ein (N = calculation.phys_psych_calculation.age_norm.n) anhängen?

**Comment by ottigerb** [comment]
Fixed by https://github.com/Optinomic/apps/commit/be1565a8be608d63cddc70ec477af3ec89ba3f6a
