### ISSUE TITLE
Readme-Anzeige

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#144]
- [x] Was beim "Weiterlesen" bzw. der Readme-Anzeige noch angepasst werden müsste ist auf jeden Fall die Angabe "Hilfe" statt "Hile" oder gleich nur Readme
- [x] nach Möglichkeit auch den Entwickler entfernen
- [x] der Readme-Teil vom Parent sollte auch nicht angezeigt werden
![image](https://user-images.githubusercontent.com/15833792/31828852-d010d8b4-b5bb-11e7-96ab-3de2640de0d0.png)
...
![image](https://user-images.githubusercontent.com/15833792/31829122-a7ec2f18-b5bc-11e7-86c9-4286e4a64648.png)

**Comment by ottigerb** [comment]
Parent-Teil wird separiert: https://github.com/ottigerb/therapy-server/issues/445#issuecomment-338634631

**Comment by ottigerb** [comment]
Done
