### ISSUE TITLE
Einzel-Apps

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#145]
Werden die Einzel-Apps bis Mittwoch ebenfalls auf die Polymer-Anzeige umgestellt, oder passiert das erst, wenn alle eine Einführung in V3 hatten und auch der Polypoint-Knopf umgestellt wird - also V2 nicht mehr gebraucht werden sollte?

**Comment by ottigerb** [comment]
Guter Punkt: M.E. erst sobald nur noch V3 verwendet werden sollte & der Polypoint-Knopf umgestellt ist. 
=> Dann können wir die einzelnen "elemente" der jeweiligen App zuordnen und Fallkonferenz-Apps darauf zugreifen lassen.

**Comment by SonjaKaufmann** [comment]
Kann man das in V3 umstellen und in V2 alt lassen oder stellt man immer beides um?

Ich würde in V3 noch die Berichte (Ein- und Austrittsassessment, Fallkonferenz EAS, Fallkonferenz EP) runternehmen, und das neue Pdf der Fallkonferenz müsste dann unter Berichte, eben mit dem Namen "Fragebogenauswertung" benannt. WEnn wir die Logik mit den Berichten so beibehalten wollen.

**Comment by ottigerb** [comment]
1.) Es stellt immer beides um. Das alte Template könnte jedoch parallel weiter bestehen. Allenfalls als  _ALT_ markiert. Zur Übergangszeit vielleicht hilfreich.

2.) Gilt auch für Berichte:  Generell wohl alle Berichte entfernen sobald die Templates/Knopf umgestellt ist. 

3.)  Die Benennung der Verknüpfung kann hier hinterlegt werden:

`/get annotations`
```JSON
"optinomic_patient_stay_quickjumps": [
    {
      "app_template": "overview",
      "name": "Fragebogenauswertung",
      "app_id": "ch.suedhang.apps.fallkonferenz.production"
    },
    {
      "app_template": "init",
      "name": "Polypoint - Belegung",
      "app_id": "com.optinomic.init.poly_stay"
    }
  ]
```

**Comment by SonjaKaufmann** [comment]
Wie sollen wir es jetzt konkret machen?
1.) Waren davon ausgegangen, dass die Apps zur Einführung von V3 die neuen Graphiken haben. Weil wir dachten es sei "nur" eine Verknüpfung mit den neuen Graphiken notwendig. Fände es gut, wenn man erstmal alt und neu hätte und dann die alten rausnehmen könnte. Nora ist allerdings diese Woche in Ferien bzw. bis zur Einführung am Mittwoch nicht mehr da.
2.) habe schon länger versucht zu sagen, dass die Fallkonferenz und das neue PDF nicht das selbe sind. Nach der alten Logik ist das PDF ein Bericht und heisst ja auch schon Fragebogenauswertung. Nur kommt man nur über die Fallkonferenz zu diesem Bericht, was meiner Logik wiederspricht. Eigentlich sollte Fragebogenauswertungs-PDF unter Berichte. Geht das ?
3.) Sowas kann ich nicht und Nora wie gesagt nicht da.

**Comment by ottigerb** [comment]
**1.)**  Ich have versucht ein "Alt" & "Neu" gleichzeitig in der gleichen App zu implementieren. Führt zu folgendem Error: `BDI_simple_score_neu:3866 Uncaught ReferenceError: agGrid is not defined`. Die "alten" Templates laden Angular `[javascript]`.  Entsprechend ist somit ein "ALT" & "NEU" Parallel nicht möglich - resp. würde ordentlich "Fehlersuche" und "Bugfixing" bedeuten. Ich schlage vor - wir behalten die "alten" Templates bis wir komplett auf `/client.new` umstellen.  

Dies gibt uns auch nochmals die Möglichkeit alle alten Templates nochmals genau zu sichten: Mir ist z.B. aufgefallen, dass der BDI ja noch die Antworten anzeigt. Was das neue Template noch nicht kann. 

**2.)**  Öhm, ja. Das ist ja auch berücksichtigt idem der ADHS Teil im PDF nicht erscheint. Das Fragebogenauswertungs-PDF kann nicht "Standalone" sein, d.h. es muss innerhalb der "Fallkonferenz-App" oder wie wir dieses Ding dann auch benennen leben.    Die "Verknüpfung" kann benannt werden wie wir wollen. Z.B.:  `Fallkonferenz & Auswertungs PDF`. Wie soll ich dies benennen? Bitte nicht zu laaaaaaaange wie: `Fallkonferenz & Fragebogenauswertung PDF`.
"Berichte" würde ich bei der "Komplettumstellung" nicht mehr verwenden und entfernen.

**Comment by SonjaKaufmann** [comment]
Zu 1.) okay, dann ist das so. Dann führe ich mit alten Graphiken in der Einzel-App-Ansicht ein und die Fallkonferenz-Zusammenstellung ist nach dem neuen Schema. Da die TKs nur das Act-Info ausfüllen können müssen und die anderen Anwendungen nicht benutzen, können wir eigentlich schon ab Einführung Südhang (also 25.10.) umstellen. Da es aber wohl besser ist ein wenig Zeit dafür zu haben, würde ich vorschlagen, dass wir ab Montag 30.10.17 die neuen Ansichten verwenden bzw. komplett umstellen (Link im Polypoint sowie die neuen Apps). Den BDI-Text können wir doch auch nachträglich noch einfügen, oder? Dann könnten wir das NEWS-Fenster nutzen um dies zu kommunizieren.

zu 2.) Okay, aber dann kann die Rubrik Berichte von Anfang an fehlen. Dann würde ich das PDF folgendermassen benennen "PDF Fragebogenauswertung".
Dazu habe ich noch eine Frage. Im Moment ist ja vorne der Titel zu sehen und hinten steht Speichern und Öffnen. Ich klicke immer intuitiv auf das PDF Fragebogenauswertung, weil es wie ein Icon aussieht und sehe dann erst hinterher hinten die beiden Optionen.
![image](https://user-images.githubusercontent.com/20124244/31889514-72195604-b800-11e7-8d83-ba2f85f454da.png)
Könnte man das irgendwie anders darstellen, z.B. ÖFFNEN und SPEICHERN näher an das PDF Fragebogenauswertung rücken und als Button darstellen und nicht nur Text?
![image](https://user-images.githubusercontent.com/20124244/31889586-a39b2f4a-b800-11e7-9667-78ee6e1fb42e.png)

**Comment by ottigerb** [comment]
1.)   30.10  =>  D.h. ich werde am Freitag, 27.10 alle Apps auf die neue Darstellung "umbauen" & Polypoint Link anpassen. Nora ist ja diese Woche nicht da - wäre da der 6.11 nicht irgendwie besser?

2.)  Berichte sind ab sofort gelöscht. Allenfalls werden diese bei Dir trotzdem noch angezeigt. Abmelden. Neu Anmelden mit Flag [X] Öffentlicher Computer. Danach erneut abmelden und "normal" anmelden.  Verknüpfung wurde umbenannt.

PDF-Icon könnte ja auch ein "SPEICHERN" sein.  Das Element nimmt komplette Breite und die Knöpfe dann rechts aligned.

**Comment by SonjaKaufmann** [comment]
1.) Eine Woche spräter geht auch. Nur den Link im Polypoint würde ich früher machen.

2.) Habe alles nach Anweisung gemacht, aber Berichte sind noch da. Meintest Du im Demo?

3.) Ja das wäre auch eine Option. Die Buttons deutlicher und dem PDF-Icon die Funktion Öffnen hinterlegt.

**Comment by SonjaKaufmann** [comment]
ad 2.) Berichte sind jetzt nicht mehr da, das ist gut.

Dafür scheint mein häufigster Testpatient 3108 irgendwie kaputt zu sein. Bei ihm bekomme ich keine Aufenthalte mehr angezeigt.
![image](https://user-images.githubusercontent.com/20124244/31896498-3a972562-b814-11e7-8379-7dac42e1af99.png)

**Comment by ottigerb** [comment]
Patient 3108 funktioniert hier problemlos! F5 schon versucht?

**Comment by SonjaKaufmann** [comment]
Ja er geht jetzt wieder.

**Comment by SonjaKaufmann** [comment]
Du hast wohl gestern die ganze APP umbenannt in PDF Fragebogenauswertung. Auf jeden Fall erscheint es nun so unter den Verknüpfungen. Aber man kommt ja erstmal auf die APP und die ist ja kein PDF. Daher schlage ich vor für die APP nur **Fragebogenauswertung** zu nehmen. Und für den LINK in der APP auf das PDF dann PDF Fragebogenauswertung.
