### ISSUE TITLE
weniger Angaben zu AUDIT & Fagerström

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#146]
Die Fagerström-Angaben habe ich wieder zurückgesetzt. Was nun noch geändert werden dürfte ist Folgendes:
- [x] Bei den Problemsubstanzen sollten AUDIT & Fagerström nicht mehr stehen.
- [x] Beim Fagerström sollte nur die Änderungsmotivation stehen. Weil die Nichtraucher aber den "fagerstroem_text" brauchen, konnte ich den für die Raucher nicht sinnvoll eliminieren, bzw. habe ihn wieder eingefügt. Ev. kannst du trotzdem die Variable "motivation_text" brauchen, oder aber die Variable, die bei den !smoker gebraucht wird, heisst ebenfalls "motivation_text", und dann könnte man https://github.com/Optinomic/apps/commit/17157eb87fe8ec49a811c729b5f5f437d706195c wieder reverten...

Der Grund: Die Zahlen sollten aufgrund der Grafiken erkannt werden.

@SonjaKaufmann Falls etwas davon nicht mehr stimmt, bitte hier gleich melden. Die Kombination von Substanzkonsum bei Eintritt und Änderungsmotivation bei Austritt geht wohl nicht, wie Beat in seinem Mail bereits geschrieben hat.

![image](https://user-images.githubusercontent.com/15833792/31830092-82c22a3c-b5bf-11e7-92cc-37b87c5b3bae.png)

**Comment by ottigerb** [comment]
- AUDIT & Fagerström aus Problemsubstanzen entfernt. Im PDF sollte dies bald auch sein - Calculation läuft. **EDIT** Auch im PDF erfolgreich entfernt!

- Bzgl. AUDIT & Fagerström Text:  Ich habe den Text drin gelassen. Grund:  Die Grafik wird nicht immer dargestellt: Z.B.  Nichtraucher.  Dann macht ein "Nichtraucher-Text" auch Sinn. 

Ich schlage vor:  Wir sammeln alle "Sonderfälle" und schauen, wie sich diese "verhalten". Nichtraucher, Bereits nach Entzug eingetreten etc. etc. - daraus gilt es dann eine klare Tabelle zu entwickeln, welcher Text wann - resp. wann nicht erscheinen soll.  Jetzt schnell was "rausstreichen" um dann andere "Fehler" zu erben finde ich doof. =>  Close.
