### ISSUE TITLE
WHOQOL Normen stimmen nicht!

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#148]
Ich habe heute zum Test Mal die positivsten Werte die möglich sind bei Frieda Muster im WHOQOL eingegeben und es kommt dabei ein sehr negatives Profil heraus, also das müssen wir dringend überprüfen! Irgendwas stimmt da mit den Normen nicht. Zur Einführung heute wird es nicht mehr langen, aber es sollte dringend überprüft werden, bevor die Therapeuten anfangen damit zu arbeiten.

**Comment by ottigerb** [comment]
**Fixed** by https://github.com/Optinomic/apps/commit/c67140a7d1284267540010780dd7c3c500f6b012 vgl.: [Frau Muster F.](http://optinomic.cust.local/api/modules/ch.suedhang.apps.fallkonferenz.production/view/overview#patient_id=1169,token=18b3c7a9-5d24-4580-9ace-129a160aa022,app_id=ch.suedhang.apps.fallkonferenz.production,api_url=http://optinomic.cust.local/api/,user_id=2,stay_id=594).    Danke nochmals für das XLS und Normen => Hilfreich!

Klinikstichproben lasse ich somit nochmals rechnen.

**Comment by ottigerb** [comment]
Klinikstichprobe aktualisiert und Ranges angepasst.
