### ISSUE TITLE
Einladung zum Assessment

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#149]
Weiss gerade nicht, ob Du dies schon auf dem Schirm hast.
Es scheint mir kein Problem von den Pop-ups zu sein, denn diese sollten jetzt generell für Optinomic freigegeben sein. 
Allerdings funktioniert das mit den Einladungen weder für V2 noch für V3.
Immer wenn man die pdf-Einladungen anfordert, öffnet sich ein neues Tap welches Unbekannt  heisst und aus einer leeren Seite besteht.

**Comment by ottigerb** [comment]
Martina hat mich gestern kontaktiert: Jep, ist klar. Wird morgen erledigt.

**Comment by ottigerb** [comment]
[USER-APP](http://optinomic.cust.local/client.new/#/user/app/com.optinomic.user.apps.assessment/template/print_access) wurde gefixed. [Patienten-App](http://optinomic.cust.local/client.new/#/patient/3242/stay/1563/app/com.optinomic.apps.pdf.patient.allgemein/template/PDF) wurde komplett ersetzt.
