### ISSUE TITLE
Exportsyntaxen fertigstellen

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#15]
erledigt:
- ActInfo Eintritt
- ActInfo Austritt
  (Kontrollfelder weglassen via Export-Toolbox gelöst -> #9 )
  --> nochmals überprüfen, wie Export in definitivem Export-Format (Excel, SPSS?) aussieht, ev. Anpassungen nötig

to do:
- HoNOS (Tarpsy-Datum ziert sich noch etwas, ansonsten done)
- BSCL (gleiches Tarpsy-Problem auch hier)
- HoNOS Verlauf
- alle FBn vom Gruppenassessment
- alle FBn vom Einzelassessment

**Comment by ottigerb** [comment]
Damit die Export-Toolbox funktioniert:

Unter `base.opapp.m4` folgenden Eintrag hinzufügen:

```
[sql_init]
include(includes/create_view.sql)
```

`includes/create_view.sql` überarbeiten - hier unbedingt den Namen (`actinfo_ein_view`)  an die App anpassen:

```
CREATE OR REPLACE VIEW actinfo_ein_view AS 

include(includes/export.sql)
```

Dann noch `includes/export.sql` wie folgt anpassen:

``` SQL

SELECT

  -- START:  Optinoimc Default |  Needed for Export-Toolbox
  survey_response_view.patient_id as optinomic_patient_id,
  survey_response_view.stay_id as optinomic_stay_id,
  survey_response_view.event_id as optinomic_event_id,
  survey_response_view.survey_response_id as optinomic_survey_response_id,
  survey_response_view.filled as optinomic_survey_filled,
  ((cast(response AS json))->>'id') as optinomic_limesurvey_id,
  -- END:  Optinoimc Default |  Needed for Export-Toolbox

...


FROM "survey_response_view" 
LEFT JOIN patient ON(survey_response_view.patient_id = patient.id) 
LEFT JOIN stay ON(survey_response_view.stay_id = stay.id) 

WHERE module = 'ch.suedhang.apps.actinfo_ein';


```

**Comment by schoenenb** [comment]
HoNOS & BSCL angepasst, erscheint jedoch nicht in Toolbox --> noch abchecken, was vergessen ging!!

**Comment by ottigerb** [comment]
...diese 'create_views' werden beim Aktivieren der App |  übernommen.  => App deaktivieren und wieder aktivieren.  Export-Toolbox!

**Comment by schoenenb** [comment]
Scheint nicht der einzige Stolperstein zu sein. Nächste Woche wieder...

**Comment by ottigerb** [comment]
_...diese 'create_views' werden beim Aktivieren der App | übernommen. => App deaktivieren und wieder aktivieren._   Deaktivieren / Aktivieren jeweils 'gblobal' unter:  http://demo.optinomic.org/api/#/app-store  also nicht auf 'Patientenebene'.  Folgendes Procedere hat sich bewährt:
1. Jeweilige App deaktivieren
2. CleanUp
3. Applikationen aktualisieren
4. App wieder aktivieren

HoNOS habe ich noch etwas angepasst: https://github.com/Optinomic/apps/commit/95d76310d3a12e2fda5f1d8adbbee44c268bedbf

HoNOS & BSCL sind nun in der Export-Toolbox.  
=> BSCL gleich 'doppelt' - da muss ich wohl noch etwas 'fixen'.

**Comment by ottigerb** [comment]
**Beispiel erstellen für:**
- Datum: `YYYYMMDD` als Text  |  ISO 112
- Austritts-Datum: `YYYYMMDD` als Text  |  ISO 112   -  1 Tag

**Comment by ottigerb** [comment]
Anbei ein Example |  Datum aus `response-Feld`:

``` SQL
SELECT 

((cast(response AS json))->>'datestamp') as datestamp,
TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD')  as datestamp_iso_112,
TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD') - integer '1' as datestamp_minus_one_day,

SUBSTRING(((cast(response AS json))->>'datestamp'),12,5) AS datestamp_time,
SUBSTRING(((cast(response AS json))->>'datestamp'),1,4)::integer AS datestamp_year,
EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')) AS datestamp_week

FROM "survey_response" 
LIMIT 10 
```

**Comment by schoenenb** [comment]
Exportsyntaxen V2:
- [x] BSCL
- [x] HoNOS ANQ
- [ ] HoNOS Tarpsy

**Comment by schoenenb** [comment]
> TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD')  as datestamp_iso_112,

...gibt auch "einfach" das Datum aus, aber nicht Text im Format YYYYMMDD.

**Comment by ottigerb** [comment]
```SQL
SELECT 

TO_CHAR(TO_DATE(((cast(response AS json))->>'datestamp'), 'YY-MM-DD'),'YYYYMMDD')  as nora,

((cast(response AS json))->>'datestamp') as datestamp,
TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD')  as datestamp_iso_112,
TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD') - integer '1' as datestamp_minus_one_day,

SUBSTRING(((cast(response AS json))->>'datestamp'),12,5) AS datestamp_time,
SUBSTRING(((cast(response AS json))->>'datestamp'),1,4)::integer AS datestamp_year,
EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')) AS datestamp_week

FROM "survey_response" 
LIMIT 10 
````

Zum Feld `nora`:   

1. `cast(response AS json))->>'datestamp'` liest aus den Messungen als String. 
2. TO_DATE  wandelt den Sting in ein Datum - `'YYYY-MM-DD'` gibt vor, in welchem Format das Datum vorliegt.
3. TO_CHAR  wandelt das Datum nun erneut in ein String. Das Format wird durch `'YYYYMMDD'` bestimmt. kann also auch `'DD.MM.YYYY'` oder irgendwas sein.

**Comment by schoenenb** [comment]
aah, das hat noch gefehlt! Ich hab's mit TO_CHAR probiert, aber vergessen nochmals die Formatierung anzugeben. MERCI!!!

**Comment by schoenenb** [comment]
Können mit "create view" auch mehrer Exportsyntaxen von der gleichen App in die Export-Toolbox geladen werden? Wäre hier gäbig für HoNOS Version ANQ/Tarpsy, wobei ja nur noch für die Daten von 2016....

**Comment by schoenenb** [comment]
restliche Exportsyntaxen fertigstellen mit Einbezug von calculations #23 _funktioniert aufgrund falscher Ausgabe von Calculations aktuell nicht_
- [x] AASE-G
- [x] BDI
- [x] ISK
- [x] SCI
- [x] WHOQOL-BREF
- [ ] TMT _Altersvariable für ng_survey_
- [x] CASE
- [ ] Neuroanamnese

**Comment by schoenenb** [comment]
Falls möglich auch z-Werte (Skalen) mit ausgeben lassen

**Comment by schoenenb** [comment]
- [ ] BSCL-Version mit Skalen- & Z-Werten _funktioniert aufgrund falscher Ausgabe von Calculations aktuell nicht_
- [ ] Abgleich (Ausfülldatum - Eintrittsdatum) bzw. (Austrittsdatum - Ausfülldatum) >= 3 --> Verwenden von Ein- bzw. Austrittsdatum _Kombination aus Berechnung und Bedingung funktioniert nicht_

**Comment by schoenenb** [comment]
Wenn ich die Apps erst deaktivieren und wieder aktivieren muss, damit die create_views aktualisiert werden - dann geschieht auf Patientenebene nichts mit Event-Aktivierung oder sowas in der Art, richtig?
Sonst würde ich die Events für die Aktivierung rausnehmen, damit nicht x Mails rausgehen, weil die Apps aktiviert wurden...

**Comment by ottigerb** [comment]
Diese views können auch direkt unter
http://optinomic.cust.local/api/#/admin/tools/sql

wie folgt "erstellt / ersetzt" werden:

```SQL
CREATE OR REPLACE VIEW tmt_view AS 

SELECT

  -- START:  Optinoimc Default |  Needed for Export-Toolbox
  survey_response_view.patient_id as optinomic_patient_id,
  survey_response_view.stay_id as optinomic_stay_id,
  survey_response_view.event_id as optinomic_event_id,
  survey_response_view.survey_response_id as optinomic_survey_response_id,
  survey_response_view.filled as optinomic_survey_filled,
  ((cast(response AS json))->>'id') as optinomic_limesurvey_id,
  -- END:  Optinoimc Default |  Needed for Export-Toolbox

  stay.cis_fid as cis_fid,
  stay.cis_fid/100 as FID,
  ((cast(response AS json))->>'Alter') as Alter,
  ((cast(response AS json))->>'Ausbildungsjahre') as Ausbildungsjahre,
  ((cast(response AS json))->>'TMTATime') as ZeitA,
  ((cast(response AS json))->>'TMTAError') as FehlerA,
  ((cast(response AS json))->>'AzWert') as zWertA,
  ((cast(response AS json))->>'TMTBTime') as ZeitB,
  ((cast(response AS json))->>'TMTBError') as FehlerB,
  ((cast(response AS json))->>'BzWert') as zWertB,
  ((cast(response AS json))->>'BAzWert') as zWertQ,
  ((cast(response AS json))->>'filled') as filled,
  ((cast(response AS json))->>'Date') as Datum,
  TO_DATE(((cast(response AS json))->>'Date'), 'YYYY-MM-DD HH24:MI:SS')  as datum_date,
  SUBSTRING(((cast(response AS json))->>'Date'),12,5) AS datum_time,
  SUBSTRING(((cast(response AS json))->>'Date'),1,4)::integer AS datum_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'Date'), 'YYYY-MM-DD HH24:MI:SS')) AS datum_week,
  ((cast(response AS json))->>'Messzeitpunkt') as erhebungszeitpunkt,
  ((cast(response AS json))->>'FID') as fid_survey,
  ((cast(response AS json))->>'PID') as pid,
  ((cast(response AS json))->>'datestamp') as datestamp,
  TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')  as datestamp_date,
  SUBSTRING(((cast(response AS json))->>'datestamp'),12,5) AS datestamp_time,
  SUBSTRING(((cast(response AS json))->>'datestamp'),1,4)::integer AS datestamp_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')) AS datestamp_week,
  ((cast(response AS json))->>'id') as id,
  ((cast(response AS json))->>'lastpage') as lastpage,
  ((cast(response AS json))->>'optinomixHASH') as optinomixhash,
  ((cast(response AS json))->>'startdate') as startdate,
  TO_DATE(((cast(response AS json))->>'startdate'), 'YYYY-MM-DD HH24:MI:SS')  as startdate_date,
  SUBSTRING(((cast(response AS json))->>'startdate'),12,5) AS startdate_time,
  SUBSTRING(((cast(response AS json))->>'startdate'),1,4)::integer AS startdate_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'startdate'), 'YYYY-MM-DD HH24:MI:SS')) AS startdate_week,
  ((cast(response AS json))->>'startlanguage') as startlanguage,
  ((cast(response AS json))->>'submitdate') as submitdate


FROM "survey_response_view" 
LEFT JOIN patient ON(survey_response_view.patient_id = patient.id) 
LEFT JOIN stay ON(survey_response_view.stay_id = stay.id) 

WHERE module = 'ch.suedhang.apps.tmt_V3';
```

=>  Somit die `create_view.sql` kopieren inklusive den `export.sql` String.


Ein De/Aktivieren der App unter http://optinomic.cust.local/api/#/app-store sollte nicht erneut "Events" oder sowas auslösen.  Bei einem Fehler im SQL lässt sich jedoch die App nicht wieder aktivieren.

**Comment by schoenenb** [comment]
Ah gäbig! Dann mach ich das wohl dann gleich in der SQL-Toolbox. Soll ich nur die "production"-Exporte anpassen oder auch gleich die "adult"-Apps?

**Comment by ottigerb** [comment]
Production is fine!  :-)

**Comment by schoenenb** [comment]
Kann ich via SQL-Toolbox auch neue Views erstellen?
z.B. 
```CREATE OR REPLACE VIEW bscl_intra_view AS 
SELECT
...
FROM "survey_response_view" 
WHERE module = 'ch.suedhang.apps.bscl_anq.production';```

Und wenn ich das nächste Mal github-Desktop synchronisiere erscheint diese View dann an gleicher Stelle wie die anderen...?

**Comment by ottigerb** [comment]
Ja, auch neue können erstellt werden - immer mit `CREATE OR REPLACE VIEW` beginnen:

```SQL
CREATE OR REPLACE VIEW irgendwas AS 

SELECT
*
FROM "survey_response_view" 
WHERE module = 'ch.suedhang.apps.bscl_anq.production';
```

=> SQL files auf jeden Fall unter den `.production` in  `includes` ablegen. Wie bisher.

**Comment by schoenenb** [comment]
Bin mir nicht sicher, ob ich's richtig gemacht habe - beim Exportversuch mit der Export-Toolbox kam jedenfalls noch die alte Version vom TMT... Ich werde es mir in zwei Wochen anschauen müssen. :(

**Comment by schoenenb** [comment]
Das Thema ging mir unter - die Exportsyntaxen wurden nicht aktualisiert: es befinden sich noch die "alten" Exportsyntaxen in der Export-Toolbox.
- AASE & SCI geben eine SQL-Fehlermeldung aus
- CASE & HoNOS_view [HoNOS_interface_pabs geht] ergeben kein Download-Link (SQL läuft durch, beim Drücken des Downloadknopfs erscheint aber nichts)
- _WHOQOL fehlt ganz - könnte dies daran liegen, dass ich die view anders benannt hatte als in der "adult"-App? (whoqol_view_production vs. whoqol_view)_ lag daran, dass der [sql init] nicht in der base.opapp aufgeführt war - wird heute Nami behoben

**Comment by schoenenb** [comment]
Die Exportsyntaxen für die SQL-Toolbox befinden sich in unserem System unter folgendem Pfad:
T:\010.QMS\010.10.QMS Ergebnisqualität\Messinstrumente\0 ZFBB\Syntaxen für SQL-Toolbox
