### ISSUE TITLE
Views V2 & V3 - Fortschritt

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#150]
Anpassungen im base.opapp.m4-File:
- Zusatz Variante für V3:
```
[template BDI 6 12]
include(../lib/polymer/index.m4)
include(elements/element-bdi.html)
include(elements/view.html)
```
- Variante für V2 mit
bisher [css] Inhalt --> <style>Inhalt</style>
bisher [javascript] Inhalt --> <script>Inhalt</script>
```
[template BDI_simple_score 6 6]
<style> 
 include(../lib/css/set/optinomic_material_bootstrap.m4)
 include(style.css)
</style> 
include(templates/score.html)
<script>
 include(../lib/js/optinomic/data_module/optinomic_app_api.m4)
 include(main.js)
</script>
```
- [x] BDI (Beat)
- [x] AASE-G
- [x] Act-info Eintritt
- [x] Act-info Austritt
- [x] BSCL
- [x] ASRS
- [x] ISK
- [x] SCI
- [x] WHOQOL-BREF
- [x] TMT

**Comment by ottigerb** [comment]
- ActInfo-Austritt ist m.E. gleich wie Eintritt. 
- TMT macht Ärger?

**Comment by schoenenb** [comment]
Mit der Anpassung werden die Balkengrafiken, welche bisher die ganze Breite einer Seite eingenommen hatten, komprimiert - wo kann man dies einstellen? Ich dachte, solange ich nur die neue Version hinzufüge und sonst eigentlich nichts ändere, sollten auch die Grafiken gleich bleiben.
Bsp.:
https://demo.optinomic.org/api/#/patient/387/stay/43/app/ch.suedhang.apps.bscl_anq
![image](https://user-images.githubusercontent.com/15833792/32376376-ebc4c536-c0a4-11e7-9a51-17ec0ccbf805.png)

https://demo.optinomic.org/api/#/patient/387/stay/43/app/ch.suedhang.apps.aase-g
![image](https://user-images.githubusercontent.com/15833792/32376434-166ce02a-c0a5-11e7-9c4d-220f57dd3e3f.png)

https://demo.optinomic.org/api/#/patient/387/stay/43/app/ch.suedhang.apps.sci
![image](https://user-images.githubusercontent.com/15833792/32376473-27f83100-c0a5-11e7-851e-2b4748b9b192.png)

**Comment by schoenenb** [comment]
Jein, die anderen machen etwas Ärger, drum wollte ich den TMT noch nicht ändern, solange heute noch Messungen stattfinden.

**Comment by ottigerb** [comment]
=> Sieht nach CSS-Effekt aus => Allenfalls folgendes Versuchen:

```
<head><style> 
 include(../lib/css/set/optinomic_material_bootstrap.m4)
 include(style.css)
</style></head> 
```

**Comment by schoenenb** [comment]
Bzgl. Actinfo habe ich mich gefragt, ob das nun die Möglichkeit wäre, die beiden Fragebögen in eine App zu nehmen. Oder müsste man dann alle Berechnungen, Views etc. wieder umschreiben?

**Comment by ottigerb** [comment]
...öhm - ja:  Habe ich mir auch überlegt => Doch:  Lieber nicht!

**Comment by schoenenb** [comment]
Also wie bisher aber ohne Umschläge?
```
<style>
include(../lib/css/set/optinomic_material_bootstrap.m4)
include(style.css)
</style>
```

**Comment by ottigerb** [comment]
```
<head><style> 
 include(../lib/css/set/optinomic_material_bootstrap.m4)
 include(style.css)
</style></head> 
```
=> Mit HEAD - Umschläge spielen keine Rolle.

**Comment by schoenenb** [comment]
scheint nichts zu ändern... https://demo.optinomic.org/client.new/#/patient/387/stay/43/app/ch.suedhang.apps.bscl_anq/template/z_scores
bzw. 
https://demo.optinomic.org/api/#/patient/387/stay/43/app/ch.suedhang.apps.bscl_anq

**Comment by ottigerb** [comment]
Hmmm...  BSCL :: Alte Version komplett weg!?  
=> Ich denke wir müssten hier in den Template-Code.  Keine Ahnung wieso dies so gestaucht wird.

**Comment by schoenenb** [comment]
Hat's ev. hiermit zu tun?
![image](https://user-images.githubusercontent.com/15833792/32377413-dece205e-c0a7-11e7-8a97-5d9972e0f1dc.png)

**Comment by schoenenb** [comment]
Aber keine Ahnung, woher die svg-Vorlage kommt oder was das ist...

**Comment by ottigerb** [comment]
...eher mit den `flex` resp. `flex-80`:   Allenfalls hier etwas spielen.  
SVG ist die Grafik => Diese nimmt soviel Platz wie sie bekommt:  100%!

**Comment by schoenenb** [comment]
Hmm, habe die commits reverted und [css] verweist ja noch immer auf die gleichen Stylesheets - braucht's ev. noch mehr als <head> wenn man das template mit <style> definiert?

**Comment by SonjaKaufmann** [comment]
Ich nehme an, ihr seid Euch bewusst, dass derzeit keine Einzelgraphiken im V3 erscheinen, oder? Oder müssen jetzt alle inklusive mir den Cache leeren?

Ich finde das wäre jetzt etwas, was in den News stehen sollte. Wenn Cache leeren, dann wäre die Anleitung dazu in den News auch sinnvoll.

**Comment by SonjaKaufmann** [comment]
Cache leeren hilft nicht

**Comment by ottigerb** [comment]
Oh, war nicht bewusst - Danke für den Hinweis. Ich habe wohl Nora schlecht instruiert - anyway:  

- Die neuen Templates sind nun vorhanden. 
- Die alten (v2) Templates habe ich entfernt - ausser beim BDI (da dieser hier noch Mehrwert bietet - Antworten anzeigen).
- actInfo Austritt zeigt gleiches Template wie Eintritt.
