### ISSUE TITLE
Frage der TK

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#152]
Die Therapeuten von der TK haben mich gefragt, ab wann sie jeweils das Act-Info ausführen können. Ich war der Meinung ab dem Eintrittstag, so dass es eigentlich sobald der Fall im RAP eröffnet ist, funktionieren sollte. 
Stimmt das so, oder wie funktioniert das?

**Comment by schoenenb** [comment]
Meines Wissens läuft das so ab:
1. Patient tritt ein
2. Fall wird von der Patientenadmin im Pabs eröffnet
3. Falldaten werden an Optinomic gesendet (Ausnahme: TKAK*, weil diese nicht teilstationär, sondern ambulant abgerechnet werden!)

Ab diesem Zeitpunkt können Fragebogen erfasst werden, allerdings muss die entsprechende App vor 4.  von Hand aktiviert werden.

4. Am Mittag und um Mitternacht geschieht der Optinomic-Polypoint-Abgleich, der Patient wird als TK-Fall erkannt und die (noch nicht aktivierten) entsprechenden Apps werden aktiviert.

*Damit die TKAK-Fälle auch in Optinomic erkannt werden, muss in Pabs die Abrechnungsart für ca. 10-15 Minuten auf "teilstationär" gesetzt + abgespeichert werden. Sobald die Daten in Optinomic drin sind, wird wieder "ambulant" gewählt. Damit man der Patientenadmin nicht reinfunkt, unbedingt mit CS & DB kurz absprechen.

**Comment by SonjaKaufmann** [comment]
Ja dann war das wohl ein Fall, wo sie vor 12 Uhr das Act-Info machen wollten. In so einem Fall müssen sie das Act-Info einfach aktivieren. Gut, das habe ich ihnen gezeigt, dann brauche ich ihnen nur die Info schicken. (Es war kein ausserkantonaler Fall :-) !) Danke für Info.
