### ISSUE TITLE
Anmeldung - autocomplete?

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#153]
Möglichkeit prüfen, ob das Feld "E-Mail" mit autocomplete="on" definiert werden kann.

**Comment by ottigerb** [comment]
Note to myself:  https://github.com/PolymerElements/paper-input/issues/462#issuecomment-264950010

**Comment by ottigerb** [comment]
### E-Mail Feld hat nun ein "Autocomplete"
Improvements are done @ https://github.com/ottigerb/therapy-server/commit/73c7536d5b4087faf0c79c1de60ce87b797f4fae

**Still open:**
Passwort wird nicht automatisch gesetzt - vgl. diesbezüglich u.A.:
https://github.com/PolymerElements/iron-form/issues/197
https://github.com/PolymerElements/paper-input/issues/462
=> `Warten`  auf "gute Idee"!  ;-)

**Comment by SonjaKaufmann** [comment]
Also bei mir wird auch die E-Mail nicht autoausgefüllt, obwohl Einstellungen bei Chrome mit Thömu überprüft, dort ist Autoausfüllen zugelassen.

**Comment by ottigerb** [comment]
...vorerst nur auf Demo.  Werde wohl diesen Freitag ein neues Stable beim Südhang einspielen.

**Comment by SonjaKaufmann** [comment]
Ahhh, super. Bin am Freitag vormittag auch im Südhang :-)

**Comment by ottigerb** [comment]
...im Südhang angekommen!
