### ISSUE TITLE
Z-Werte Text

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#155]
In was für einen Satz sollen die Z-Werte in Berichte?

Sollen das ganze Assessment in Text ausgegeben werden können für Berichte?

**Comment by ottigerb** [comment]
@SonjaKaufmann Konntest Du diesbezüglich etwas erreichen?

**Comment by SonjaKaufmann** [comment]
Nein noch nicht, werde Sandro nochmal erinnern, er hat gerade viel um die Ohren. Bitte Issue offen lassen.

**Comment by schoenenb** [comment]
Für Berichte oder ähnliches wird der z-Wert nicht gebraucht. (Um das mal abzuschliessen.)

Heute kam nochmals die Anfrage, ob man beim TMT (nur dort) den Z-Wert mit ausgeben könnte.
Kommst du dazu, die Tabelle um die Z-Werte zu ergänzen? (Entweder als separate Spalte oder in Klammern hinter der Zeit-Anzeige?)
![image](https://user-images.githubusercontent.com/15833792/66043867-93a09680-e520-11e9-8040-9fdd2913d3af.png)

Wär's möglich dort auch noch gleich als Datum die Variable Erhebungsdatum zu nehmen, wenn vorhanden?
![image](https://user-images.githubusercontent.com/15833792/66043954-c9457f80-e520-11e9-9177-3a211a6b8de3.png)

Ich hätte es sehr gerne selber gemacht, aber ich hab mittlerweile nur noch eine ungefähre Ahnung, wo die Änderung hin muss, aber nicht wie...

**Comment by ottigerb** [comment]
OK - gehe ich an - diesen Freitag wird allenfalls knapp - ein Freund von mir heiratet und ich bin Trauzeuge.  

Nur zum Verständnis:  Also den Z-Wert im Datenblatt sowie Erhebungsdatum (wenn vorhanden) anzeigen.

**Comment by schoenenb** [comment]
Wie schön! Ich habe bereits angekündigt, dass ich nicht weiss, ob du am Freitag arbeitest und ob du dafür Zeit hast. Wenn’s Platz hat, wär’s super, sonst gerne demnächst.
Genau, den z-Wert angeben und wenn vorhanden das Erhebungsdatum aus dem Fragebogen nehmen, nicht aus dem «filled»-Feld oder wie es im ng-survey heisst…

**Comment by ottigerb** [comment]
### Erledig
Ich habe ein commit folgender Änderungen ausgelöst: https://github.com/Optinomic/ch.suedhang.apps.tmt_V3/commit/0a2d354f348e5bff7eb84db9d121418d7157784d & zusätzlich habe ich das Submodule in ch.suedhang.apps.tmt.production aktualisiert:   https://github.com/Optinomic/ch.suedhang.apps.tmt.production/commit/d274033371ee86a51ec88f3bd5feb803d57006ed

### Datenblatt
Das Datenblatt zeigt nun die gewünschten Z-Werte an. Das Datum (Erhebungsdatum wenn vorhanden)wird in der Calculation in folgenden Zeilen gesetzt: https://github.com/Optinomic/ch.suedhang.apps.tmt_V3/blob/master/calculations/tmt_score.js#L649-L654

![Bildschirmfoto 2019-10-04 um 13 01 29](https://user-images.githubusercontent.com/2470873/66203001-7518d780-e6a7-11e9-8e30-1f16419062ab.png)
