### ISSUE TITLE
PDF TMT Graphik

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#156]
![image](https://user-images.githubusercontent.com/20124244/33012033-fe93ae6e-cddf-11e7-8f50-c487f8cf3100.png)

Habe diese pdf-Graphik bei 
blob:http://optinomic.cust.local/765f3984-da33-4f26-9160-0fac07ee028e
gefunden. Weiss nicht ob es auch ei anderen so aussieht.

**Comment by ottigerb** [comment]
Link zu BLOB ist nicht hilfreich - kann nicht reproduziert werden - dieses File wird bei jedem Öffnen neu erstellt!  Also Link zum Patient/Fall/TMT!  Danke!  

Prüfe auch andere PDF's - Danke!

**Comment by SonjaKaufmann** [comment]
/patient/3142/stay/1568

**Comment by SonjaKaufmann** [comment]
Noch ein Zufallsfund, kleiner Schreibfehler in App und PDF
![image](https://user-images.githubusercontent.com/20124244/33012657-df445bba-cde1-11e7-8bf2-c6526b16f247.png)

**Comment by schoenenb** [comment]
gleiches Muster:
http://optinomic.cust.local/client.new/#/patient/2489/stay/1203/app/ch.suedhang.apps.tmt.production/template/TMT
http://optinomic.cust.local/client.new/#/patient/2318/stay/1109/app/ch.suedhang.apps.fallkonferenz.production/template/overview
http://optinomic.cust.local/client.new/#/patient/2373/stay/1127/app/ch.suedhang.apps.tmt.production/template/TMT
http://optinomic.cust.local/client.new/#/patient/2820/stay/1276/app/ch.suedhang.apps.tmt.production/template/TMT
http://optinomic.cust.local/client.new/#/patient/2821/stay/1277/app/ch.suedhang.apps.tmt.production/template/TMT
--> Keine z-Werte > 0
--> d.h. wir müssten für die Grafik eben doch einen fixen Maximalwert angeben?

**Comment by schoenenb** [comment]
Dafür ein weiteres Phänomen - Klinikstichprobe geht aus der Grafik hinaus:
http://optinomic.cust.local/client.new/#/patient/2110/stay/1529/app/ch.suedhang.apps.tmt.production/template/TMT
--> Min & Max der StichprobenMW +/- 1 SD nachschauen + Grafik entsprechend anpassen?

**Comment by schoenenb** [comment]
Typo ist behoben, merci für den Hinweis!

**Comment by ottigerb** [comment]
> --> Min & Max der StichprobenMW +/- 1 SD nachschauen + Grafik entsprechend anpassen?

Yep - oder "auto"!?

**Comment by schoenenb** [comment]
O-oh - da ist was untergegangen...
Dass "auto" eingestellt ist, ist doch genau das Problem - für die Polymer-Grafik funktioniert es, aber im PDF zeigt es trotzdem den Hintergrund bis 2 an. Das passiert allerdings nur, wenn ein Patient in allen vorhandenen Messungen nicht verlangsamt ist. Oder ist das im PDF aktuell anders programmiert und könnte dort ebenfalls auf "auto" gesetzt werden?

**Comment by schoenenb** [comment]
Wo stehen wir hier?

**Comment by ottigerb** [comment]
## Finally - Fixed

Folgender Fix https://github.com/Optinomic/optinomic-pdfmake-chart-profile/commit/f96736517e0eb03175384f18ebf31fe74a35d255 schneidet den "Overflow" ab - zB.:

![bildschirmfoto 2018-03-16 um 13 00 32](https://user-images.githubusercontent.com/2470873/37519633-1b77befe-291a-11e8-91b7-eac945a8ebd0.png)

**Comment by schoenenb** [comment]
Super!!!

**Comment by schoenenb** [comment]
Leider muss ich das Issue nochmals öffnen: das Phänomen gibt's auch in die andere Richtung...
http://optinomic.cust.local/client.new/#/patient/2110/stay/5632/app/ch.suedhang.apps.fallkonferenz.production/template/overview
![image](https://user-images.githubusercontent.com/15833792/38679540-522f09b6-3e64-11e8-9b65-fae90fe0b4c4.png)

**Comment by ottigerb** [comment]
Danke für den Hinweis!

## FIXED by:

https://github.com/Optinomic/optinomic-chart-profile/commit/65f6377080cbe55e9af515628561b68bd441833f

https://github.com/Optinomic/optinomic-pdfmake-chart-profile/commit/8093b6f9d8524fa9cb6db02724bec52c47e16ed6

https://github.com/Optinomic/polymer-cdn/commit/b7937af0bc7a7535415d496ce23ad0b8fcce0353

**Comment by schoenenb** [comment]
Herzlichen Dank für die prompte Korrektur!!
