### ISSUE TITLE
Auswahl Alle Patienten verschwunden

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#157]
Durch Rückmeldungen von Therapeuten ist mir heute aufgefallen, dass bei den Therapeuten sowie bei den Administratoren unter Patietnen nur noch die Patientenauswahl sowie die Favoriten vorhanden sind, aber nicht mehr Patienten vorhanden ist, wo jeweils alle Patienten drin waren. So ist es auch gar nicht mehr möglich einen Patienten zu suchen.

**Comment by ottigerb** [comment]
Der Menueintrag `Alle Patienten` ist in die Kategorie **Patientengruppen** gewandert. 
Somit sind `Patienten` - Gruppen, welche mit mir als User in Verbindung stehen und generelle Patientengruppen wie `Alle Patienten` sind unter `Patientengruppen` vereint. M.E. macht dies so deutlich mehr Sinn.

**Comment by SonjaKaufmann** [comment]
Ich weiss nicht ob es für mich mehr Sinn macht, auf jeden Fall wäre eine kurze Info gut gewesen, da sich schon alle an den vorherigen Stand gewöhnt hatten.
Meinetwegen kann es in den Patientengruppen bleiben, aber dann sollte es zu oberst stehen, sonst wäre ich für die alte Art, da kann es nicht so leicht zwischen vielen anderen Gruppen verloren gehen.

**Comment by ottigerb** [comment]
Die linke Navigationsliste wurde erneut überarbeitet. M.E. nun sehr übersichtlich.

**Comment by SonjaKaufmann** [comment]
Lieber Beat,

ja die Icons finde ich auch sehr anschaulich. 
Allerdings habe wir die gleichen Sachen nun einmal unter Patienten und einmal unter Patietnengruppen drin und das ist eher verwirrend und nicht einfacher.
Aus meiner Sicht sollte unter Patienten: Meine Favoriten, Meine Auswahl und das Icon zum suchen in Alle Patienten sein. Und unter Patientengruppen dann : Alle Patientengruppen und Alle Fallgruppen und die Auswahl der schon erstellten Gruppen.
In diesem Rahmen möchte ich auch nochmal darauf hinweisen, dass wir ja eigentlich das News-Fenster diskutiert haben. Wenn wir es weiter so wie bin anhin nutzen und keine News für unsere User drauftun, wo sie für sie relevante Änderungen nachlesen können, dann sollten wir das Newsfenster bei den Therapeuten runternehmen.
Übrigens super dass das mit den Fallgruppen funktioniert. Müssen die mit einer Nummer benannt sein?  Denn die Nummer sagt unseren Therapeuten natürlich gar nichts und liefert ihnen so keine Info und verwirrt. Wenn es die Polypoint-Fid wäre, dann würde es noch Sinn machen. Aber es arbeitet ja keiner mit den Optinomic-nr ausser Ihr für die Programmierung.

**Comment by ottigerb** [comment]
Close because of: https://github.com/Optinomic/apps/issues/158
