### ISSUE TITLE
NEWS

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#158]
## Nachrichten
Ab sofort steht auf dem Demo eine neue [NEWS Section](https://demo.optinomic.org/client.new/#/news) zur Verfügung. Zudem werden auf der [Startseite](https://demo.optinomic.org/client.new/#/home) die neusten 3 Neuigkeiten angezeigt.

### Hinzufügen
Nachrichten, können unter folgendem Link erstellt werden: 
https://demo.optinomic.org/client.new/#/news/add

Die so erstellten Nachrichten sind nur innerhalb der aktuellen Klinik sichtbar und können bearbeitet und gelöscht werden. 

#### Cache
Falls ein aktuelles Optiomic-Fenster offen ist, muss allenfalls der Browser-Cache gelöscht werden. Falls Optinomic nicht offen ist, sollten die NEWS ohne Cache löschen erscheinen. 

## Close
=>  Bitte prüft die aktuelle Funktionalität und teilt hier mit, ob dies so in "Stable" übernommen werden kann - oder ob noch Funktionen vermisst werden.  Thanks!

**Comment by schoenenb** [comment]
Danke für die Demonstration heute ;) Ich denke, die News sind gut und ausreichend platziert, so wie sie jetzt auf dem Demoserver sind.
Ev. könnte man  zusätzlich noch die Zielgruppe auswählen. Also wenn etwas z.B. nur für Admins relevant ist oder nur EAS-Therapeuten betrifft usw., dass es nur bei denen auf der Startseite erscheint, bei den anderen nicht. Weiss nicht, ob das bei uns relevant ist, ev. macht das auch eher Sinn, wenn mehrere Berufsgruppen darauf zugreifen, was bei uns (noch) nicht der Fall ist...

**Comment by ottigerb** [comment]
NEWS: Im Südhang angekommen. 

Schliesse dieses Issue - falls noch Berufsgruppen etc. relevant werden => Reopen.
