### ISSUE TITLE
An/Abmeldung :: 401-Error  |  Client vs. API - Token

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#159]
Habe heuten TK-Psychologen eingeführt und immer wenn ich ihm "Meine Auswahl" zeigen wollte, hat uns das Programm den folgenden Fehler geliefert und ihn "halb" abgemeldet. Siehe Bild, es kommt wieder der Anmeldebildschirm, aber er ist weiterhin eingeloggt in der Taskleiste. Man kann weiterarbeiten ohne Neuanmeldung, denkt aber man müsse sich neu anmelden.
![image](https://user-images.githubusercontent.com/20124244/34715215-1a429a8a-f52c-11e7-914b-94dd81aad6c0.png)

**Comment by ottigerb** [comment]
Ich konnte den Fehler wie folgt reproduzieren:
1.)  Anmelden
2.) Browser offen lassen und in ein anderen Browsertab (also nicht Optinomic) wechseln.
3.) Eine Nacht warten.
=> (401) Unathorized Error.

### Grundsätzlich:
Im beschriebenen Bug ist der Client noch angemeldet / die dahinter liegende API jedoch nicht mehr. Dieser 401 Error zeigt, dass die API nicht mehr einen gültigen Schlüssel (Token) hat. Weiterarbeiten in diesem Zustand ist also nicht zu empfehlen. Nur bereits geladene Daten sind dank client.new weiter zugänglich. 

Wenn im Optinomic-Brwosertab 'übernachtet' wird, findet nach Inaktivität automatisch eine Abmeldung statt und der User muss/kann sich wieder ordnungsgemäss anmelden. Nicht aktive Tabs sind durch den Chrome-Update nicht mehr in der Lage eine Inaktivität zu erkennen (Memory Einsparung). 

M.E. gilt es in diesem Zusammenhang folgenden Hinweis zu erteilen:
### Optinomic am Abend (oder bei längeren Pausen) ordnungsgemäss abmelden! Bei einem 401 Error die Neuanmeldung durchführen.

Ich sehe hier nur folgende Möglichkeit:
1.)  **Bei einem 401 automatische Abmeldung.** Bei einem 401 könnte ich auch automatisch abmelden, dass wieder eine ordentliche Anmeldung nötig wird. Doch wir hatten diesbezüglich ja mal ein Issue gefixt, welches nicht direkt "rausschmeissen" soll.

**Comment by SonjaKaufmann** [comment]
Ich verstehe nicht alles, aber ich hatte den Benutzer gerade erst eingerichtet und er war nicht über Nacht oder länger offen, da ich ihn erst 1 Stunde vorher erstellt habe!

**Comment by ottigerb** [comment]
...und Optinomic war mit dem neuen User angemeldet? Kann ich mir nicht vorstellen. Hmm... anyway: 401 => Neu anmelden.

**Comment by SonjaKaufmann** [comment]
Ja war er, denn der Fehler kam in seiner Einführung und ich habe ihn später nochmal mit seinem Login rekonstruiert um das Bildli für dich zu machen.

**Comment by ottigerb** [comment]
...kannst Du mir mal seine User-ID zustellen? Ist dieser User korrekt als "Therapeut" eingetragen? Somit kannst Du den Effekt regelmässig rekonstruieren?  Gespannt!

**Comment by ottigerb** [comment]
...oh - tatsächlich - hat irgendwie mit den Benutzerrechten zu tun.  Ich bin hier dran!

**Comment by ottigerb** [comment]
### Note to myself:

Fehler liegt bei "Anzeige offene / erledigte Aufgaben".  Wenn kein Explizit/Impliziter Behandlungsauftrag vorhanden ist - meldet z.B. die Abfrage: `/api/patients/1962/events` ein 401 zurück.  => Lösung:  Zuerst `GET /patients/:patient_id/access` - nur wenn der User Zugriff auf den Patienten hat - die Events offene / erledigte abfragen und darstellen.

**Comment by ottigerb** [comment]
FIXED! 

Guter Fund - Danke!   :-)
