### ISSUE TITLE
[limeSurvey] Fragebogen-Layout

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#16]
**Einheitliches Layout**
(Schriftgrösse // Abstand // Absatz vor/nach neuem Absatz // Ausrichtung // Feld in Limesurvey)

_Headline:_
(21.5 //  1.0   //  (0/10)  //  links  //  Umfragetitel)
_2. Headline:_
(21.5 //  1.0   //  (0/0)   //  links  //  Titel der Fragegruppe)
_Instruktionstext:_
(13.5 // 1.15 // (0/10)  // (links) // Beschreibung d. Fragegruppe)
_Fragentext:_
(13.5 // 1.15 // (0/10)  // links  // Fragefelder)
_Antwortkategorien:_
(13.5 // 1.0  // (0/10)  // zentriert, unten // Antwortfelder)
_Hinweise:_
(13.5 // [1.0 // (0/0) // links ]  // Hilfetext)

Spezialformate:
- Pflichtfragen: Kennzeichnung \* nicht anzeigen oder in unauffälliger Farbe darstellen (z.B. weiss)
- einzelne Wörter hervorheben: <span style="color: rgb(255, 0, 0);"> _Text_ </span>

**Comment by schoenenb** [comment]
einzelne Wörter hervorheben: Schriftfarbe rot (-> "span style="color: rgb(255, 0, 0);"> </span")

**Comment by HansaYohaku** [comment]
Bin einfach erstaunt und überrascht, wie viel sich hier tut :-)

**Comment by ottigerb** [comment]
> Bin einfach erstaunt und überrascht, wie viel sich hier tut :-)

=>  Optinomic lebt!  👍

**Comment by ottigerb** [comment]
Template.css  ->  Wo soll was geändert werden?  Welche Bereiche steuern die Überschriften / Titel / Texte etc.

**Comment by ottigerb** [comment]
Die Vorlagen (Optinomic_Skeleton) haben sich in der neuen Version ebenfalls geändert.  Ich habe den neuen Standard genommen & kurz auf Optinomic angepasst.  Änderungen gilt es hier einzupflegen:  

http://xwp4105.cust.local:8000/limesurvey_v2/index.php/admin/templates?sa=view&screenname=welcome&templatename=Optinomic&editfile=css%2Fflat_and_modern.css

resp. ab sofort auch in unserem APPS-Repo (Damit wir Änderungen an einem zentralen Ort haben):  https://github.com/Optinomic/apps/tree/master/lib/limeSurvey/Optinomic_Template

**Comment by schoenenb** [comment]
Ist es aufwendiger

1. unsere Wünsche wie eingangs beschrieben ins Optinomic_Skeleton (neue oder alte Version) einzubauen, oder
2. die Bögen in ngSurvey zu erfassen? ...vorausgesetzt wir können das Layout dort so anpassen, dass es den Vorgaben entspricht.

Für die Patienteneingabe muss das Layout gut strukturiert und eingängig sein.

**Comment by schoenenb** [comment]
Anscheinend nicht angekommen weil nicht assigned ;)

Diverse Änderungen notwendig...

**Comment by schoenenb** [comment]
Startseite:
![image](https://cloud.githubusercontent.com/assets/15833792/20839457/f6d9e4ca-b8ac-11e6-85c5-7818e574df1c.png)

- [ ] "Weiter"-Knopf: Schrift mittig?

**Comment by schoenenb** [comment]
Administratives:
![image](https://cloud.githubusercontent.com/assets/15833792/20839490/1cd8b476-b8ad-11e6-800e-1d97e5e7e9a5.png)

- [ ] Text neben radiobutton (nicht darunter)
Datum wird automatisch das heutige gewählt bei Klick ins Feld

**Comment by schoenenb** [comment]
Frageblock:
![image](https://cloud.githubusercontent.com/assets/15833792/20839595/8665f3d6-b8ad-11e6-8979-438254e4ed7c.png)

- [ ] Beschriftung der Auswahlfelder entfernen

- [ ] runden Radiobutton anzeigen (allenfalls Beschriftung bei drüberfahren mit der Maus)

- [ ] linksbündiger Text

**Comment by schoenenb** [comment]
Rückmeldung bei fehlenden Antworten:
![image](https://cloud.githubusercontent.com/assets/15833792/20839712/e9e4632a-b8ad-11e6-8392-28348998e5e2.png)

- [ ] auf Item-Ebene möglich? Bei einer Liste von 20 Items oder mehr kaum zu finden...

**Comment by ottigerb** [comment]
...ich komme hier voran - mehr morgen!   Nach wohl zu viel "Eigenleistung" habe ich wohl eine gute Lösung in Sicht!   :-)

**Comment by ottigerb** [comment]
### Gekaufte Templates
Wie bereits angekündet - ich "schenke" uns die [Templates vom limeSurvey-Team](https://www.limesurvey.org/downloads/category/29-design-tempates). Diese habe ich käuflich erworben und leicht an "Optinomic" angepasst.  Entsprechend sind nun folgende Templates zur Verfügung:

![bildschirmfoto 2017-01-05 um 11 33 17](https://cloud.githubusercontent.com/assets/2470873/21677525/df135850-d33a-11e6-8aed-f9f416e79c09.png)
=> Als "Standard-Vorlage" schlage ich `optinomic_material` vor.  M.E. passt dieses ebenfalls an Material-Design orientierte Design perfekt zu Optinomic. Der Arbeitsaufwand diese "selbst" zu erstellen ist schlicht zu gross - auch scheinen diese Templates je nach limeSurvey Version sich zu verändern.  Ich denke gut investiertes Geld diese zu erwerben.

### Lessons Learned

#### Präsentations-Einstellungen beachten
![bildschirmfoto 2017-01-05 um 11 22 11](https://cloud.githubusercontent.com/assets/2470873/21677527/df13ce0c-d33a-11e6-842c-a33090ce7593.png)
M.E. erzielen wir die besten Ergebnisse, wenn wir "**nur Frgegruppenname**" und "**nur Fragencode**" anzeigen.  Dies führt dann zu folgender Darstellung:


![bildschirmfoto 2017-01-05 um 11 20 12](https://cloud.githubusercontent.com/assets/2470873/21677526/df13b6c4-d33a-11e6-9304-0b15b8c90573.png)

Somit wird die Fragegruppe "Administrative Angaben" sowie der Fragencode "VMEB001" dargestellt.


#### Frage & Hilfetext als "Quellcode" bearbeiten

![bildschirmfoto 2017-01-05 um 11 26 05](https://cloud.githubusercontent.com/assets/2470873/21677531/df2b6166-d33a-11e6-96cc-58da0d537da2.png)

Zu beachten gilt:  Sobald wir hier irgendwelche `div` `span - font`  Tags drin haben, werden die Einstellungen des Templates überschrieben.

#### Tags entfernen

![bildschirmfoto 2017-01-05 um 11 24 01](https://cloud.githubusercontent.com/assets/2470873/21677528/df14a9e4-d33a-11e6-8e07-bf43de2994c8.png)

M.E. erzielen wir das beste Ergebnis, wenn wir diese Tags komplett entfernen.

#### gewünschte Design-Layout

Um das gewünschte Design-Layout zu erreichen schlage ich vor die Frage als `<h3>` zu deklarieren:
![bildschirmfoto 2017-01-05 um 11 25 19](https://cloud.githubusercontent.com/assets/2470873/21677530/df1549b2-d33a-11e6-81c5-1527d3bbee8d.png)


Dies führt dann zu folgendem "Endergebnis":

![bildschirmfoto 2017-01-05 um 11 28 06](https://cloud.githubusercontent.com/assets/2470873/21677532/df2da73c-d33a-11e6-84db-baa2c4a29062.png)


#### Missing fields
Das neue Template löst auch fehlende Zeilen deutlicher auf:
![bildschirmfoto 2017-01-05 um 12 00 29](https://cloud.githubusercontent.com/assets/2470873/21678347/ac2be7f0-d33e-11e6-9bf9-d221348781fa.png)

**Comment by SonjaKaufmann** [comment]
Ist nochmal Weihnachten, dass es Geschenke gibt :-) Merci lieber Januar-Weihnachtsmann!

Finde es sieht gut aus, würde es gerne Mal anschauen wie es dann zur Eingabe eines Fragebogens wirklich aussieht, so mit Schriftgrössen und so, da hatten wir uns ja schon mal was überlegt, entspricht es dem ungefähr?

Kopiere es von oben nochmal hier rein:
-------------------------------------------------------------------------------------------
Einheitliches Layout
(Schriftgrösse // Abstand // Absatz vor/nach neuem Absatz // Ausrichtung // Feld in Limesurvey)

Headline:
(21.5 // 1.0 // (0/10) // links // Umfragetitel)
2. Headline:
(21.5 // 1.0 // (0/0) // links // Titel der Fragegruppe)
Instruktionstext:
(13.5 // 1.15 // (0/10) // (links) // Beschreibung d. Fragegruppe)
Fragentext:
(13.5 // 1.15 // (0/10) // links // Fragefelder)
Antwortkategorien:
(13.5 // 1.0 // (0/10) // zentriert, unten // Antwortfelder)
Hinweise:
(13.5 // [1.0 // (0/0) // links ] // Hilfetext)

Spezialformate:

Pflichtfragen: Kennzeichnung * nicht anzeigen oder in unauffälliger Farbe darstellen (z.B. weiss)
einzelne Wörter hervorheben: Text
------------------------------------------------------------------------------------------------
Muss man den Fragecode denn angeben, denn der Patient muss ja bei der Eingabe nicht wissen das es sich um VMEB001 handelt?

**Comment by ottigerb** [comment]
Smile - ja, ein lieber Januar-Weihnachtsmann!  👍 

Fragencode muss nicht angegeben werden - kann beides "versteckt" werden. Doch dann wirkt die Pflichtangabe Kennzeichnung * irgendwie verloren.  Doch as you want!

M.E. entspricht es den Vorstellungen bei `<h3>Frage</h3>`

Ich schau mal ob ich die `Pflichtangabe Kennzeichnung *` in diesem CSS finde. Falls ja, ändere ich es auf "unauffällig" - weiss würde ich nicht gerade, da es ja schon interessant ist, was eine Pflichtangabe ist und was nicht.

**Comment by ottigerb** [comment]
Ich habe folgendes gefunden:

```html
<!-- Question title -->
<div class="row question-wrapper question-title-container">
    <div class="col-sm-12 questiontext">
        <div class="qnumcode question-text">
            {QUESTION_MANDATORY} {QUESTION_NUMBER} {QUESTION_CODE} {QUESTION_TEXT}
        </div>
    </div>
</div>
```

verändert nach:

```html
<!-- Question title -->
<div class="row question-wrapper question-title-container">
    <div class="col-sm-12 questiontext">
        <div class="qnumcode question-text">
        <span style="color:#333333 !important;font-size: 12px !important;">
            {QUESTION_MANDATORY}
        </span> 
        {QUESTION_NUMBER} {QUESTION_CODE} {QUESTION_TEXT}
        </div>
    </div>
</div>
```

=> Ohne Erfolg!  Keine Ahnung von wo dieses `{QUESTION_MANDATORY}` kommt und wie dies formatiert wird:  Giving up!

**Comment by SonjaKaufmann** [comment]
Okidoky. 
Spielt wahrscheinlich auch nur beim Act-Info eine Rolle und bei den Datumsangaben, oder?

**Comment by ottigerb** [comment]
Alle „Mussfragen“.   :-)

**Comment by SonjaKaufmann** [comment]
Hmmm, bei uns ja doch alle Mussfragen bis auf ein paar wenige im Act-Info. In allen anderen Bögen muss doch alles ausgefüllt werden. Heisst das dass dann bei allen einzelnen Fragen z.B, vom BSCL dort immer so eine Nummer vor der Frage steht?

**Comment by schoenenb** [comment]
Look LS V2:
Limesurvey-Skeleton verändern, nicht Optinomic-Skeleton
