### ISSUE TITLE
Aktueller Fehler

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#160]
Oben ist die FID und der Fall zu sehen und unten was passiert, wenn ich versuche den Fall zu öffnen. Da es immer den vorherigen Patietnen in der Kopfzeile noch einblendet und ich nicht verwirren wollte, habe ich den Namen entfernt (wollte nicht verwirren)
![image](https://user-images.githubusercontent.com/20124244/35278408-3308db8c-004a-11e8-9616-d75984fbd858.png)

**Comment by ottigerb** [comment]
?

Es sieht so aus als würde die API keine Daten liefern:  Was hast Du versucht?  Abmelden/Neu Anmelden?  F5 Seite aktualisieren?  Anderer Patient/Fall funktioniert?

**Comment by ottigerb** [comment]
Patientin hat keinen Fall (vgl. http://optinomic.cust.local/client.new/#/patient/3525) zugeteilt => Entsprechend kann nicht zum letzten Fall "/latest_stay" weitergeleitet werden.

**Comment by ottigerb** [comment]
Fall ist nun wieder hier :: http://optinomic.cust.local/client.new/#/patient/3525/stay/1766
=>  Es scheint als wäre die API kurzfristig "blockiert" gewesen. M.E. nun alles "back to normal"!

**Comment by SonjaKaufmann** [comment]
Super, funktioniert wieder.
Was ich versucht hatte war: Abmelden, Cache leeren, nochmal versucht.
Andere Patienten gingen. Ist eine Patientin gewesen, bei der kürzlich war geändert wurde wegen Abbruch Klinik, vielleicht hat das zu dem Problem geführt.
