### ISSUE TITLE
Daten in Optinomic ändern - Annotations - POST

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#161]
Nach Anpassungen in den Daten in OptinomicV2 werden die Daten nicht mehr angezeigt:
http://optinomic.cust.local/client.new/#/patient/2981/stay/1393/app/ch.suedhang.apps.actinfo_ein.production/template/ActInfo
![image](https://user-images.githubusercontent.com/15833792/35498801-11817048-04d0-11e8-84ce-53b4054aa2e8.png)
Letzte Woche hatte ich auch schon so einen Fall, allerdings waren die Daten wieder da, als ich das Issue eröffnen wollte - ging aber relativ lange, bis die Änderung in Optinomic angezeigt wurde.

Soll man bei Änderungen, die die calculation nicht betreffen, gar nicht erst die Daten neu berechnen?

**Comment by ottigerb** [comment]
Die "Calculations" müssen/können manuell angestossen werden um neu berechnet zu werden:
https://demo.optinomic.org/api/#/admin/tools

![bildschirmfoto 2018-01-29 um 09 28 34](https://user-images.githubusercontent.com/2470873/35500457-d00105d2-04d6-11e8-8e60-f7765ae2b257.png)

Gemäss der Dokumentation (https://doc.optinomic.org/V2/Developers/api.html#post-patientspatientidcalculationsmoduleidentifiercalculationidentifierrecompute):

Methode: **POST**
patient_id: Die Optinomic PID des Patienten
module_identifier: Aus Auswahl
calculation_identifier: z.B. another_calculation

bei
```
[calculation another_calculation javascript]
__opapp_include(calculations/actinfo_aus_calc.js)
```

**Comment by schoenenb** [comment]
Genau, das habe ich gemacht für den Eintritt. Nun werden die Daten aber nicht mehr angezeigt, bzw. nur die vom Austritt.

**Comment by schoenenb** [comment]
Die Frage wegen nicht neu berechnen, wenn calculation nicht betroffen ist, habe ich gestellt, weil ich nur die Institution wechseln musste (31 -> 03).

**Comment by ottigerb** [comment]
Hmmm...  wie lange ist es her seit dem `POST .../recompute`?  Keine Fehlermeldung in der Console?
=> Allenfalls noch etwas "Geduld" haben - der Daemon arbeitet. Versuche mal hier einzutauchen.

M.E. ist ein solches `POST .../recompute` bei z.B. Institution wechseln (31 -> 03) nicht benötigt.

**Comment by schoenenb** [comment]
Jetzt sind die Daten da... Ich würde behaupten, ich habe während 30 Minuten immer wieder neu geladen. Allerdings habe ich noch ein zweites Mal recomputed, weil ich erst 3 statt 03 eingegeben hatte und dachte, dass es ev. deswegen nicht lädt.

**Comment by ottigerb** [comment]
Ja, habe ich soeben auch gesehen - ich bin dran an einer "Verbesserung".  Das "Problem" war nicht die Calculation - sondern an deren Zuordnung...  Fix sollte bald unterwegs sein - damit in Zukunft dies "schnell" und "problemlos" funktioniert.  Hopefully!  ;-)

**Comment by ottigerb** [comment]
https://github.com/Optinomic/apps/commit/7a7364697f1435a4db87539eb659777149732b68 sollte diesbezüglich eine deutliche Verbesserung darstellen.
=>  Close!

**Comment by schoenenb** [comment]
Bin mir grad nicht sicher, ob ich wieder dasselbe Problem habe:
Bei 
 http://optinomic.cust.local/client.new/#/patient/1429/stay/580/app/ch.suedhang.apps.bscl_anq.production/template/BSCL
habe ich den Erhebungszeitpunkt von 2 (da kein Austritt vorhanden, Anzeige: "unknown") auf 3 gesetzt. Seitdem ist irgendwas am rechnen - das ist wohl die automatische Aktualisierung, die in einem Issue auf therapyserver diskutiert wurde?
Jedenfalls zeigt es mir in der Console folgende Fehlermeldung an (falls das was damit zu tun hat):
![image](https://user-images.githubusercontent.com/15833792/39989194-98b301da-5769-11e8-996b-ec70c71e3456.png)

Wobei beim Klicken auf den Link "BSCL: 2781" folgende Zeile angefärbt wird:
![image](https://user-images.githubusercontent.com/15833792/39989341-f4b7f58a-5769-11e8-8a10-db939b78afde.png)

**Comment by schoenenb** [comment]
http://optinomic.cust.local/client.new/#/patient/3638/stay/5542/app/ch.suedhang.apps.whoqol.production/template/WHOQOL
![image](https://user-images.githubusercontent.com/15833792/40038614-588acca0-5813-11e8-9908-70069e54edda.png)

Gleiche "Fehlermeldung" auch hier - die Änderung haben wir gestern ca. 15 Uhr vorgenommen...

**Comment by ottigerb** [comment]
...interessant.  Ich habe den gleichen Fehler auch [@ demo - Server | z.B.](https://demo.optinomic.org/client.new/#/patient/1713/stay/731/app/com.optinomic.apps.whoqol/template/WHOQOL) festgestellt.  Hast Du Patienten/Fälle wo der WHOQOL funktioniert?

Kurzdiagnose: Irgendwie scheint die `Calculation` abzubrechen mit einem Fehler. Entsprechend kann der Task "Klinikstichprobe" erstellen nicht beendet werden - dies könnten wir schon "verbessern" doch ohne Calculation wäre die Darstellung ebenfalls "mager".  In der Console ist das Objekt  `.../survey_responses/....whoqol.../full` interessant. Key:  `found_all` wird wohl auf false sein, da die Calculation fehlt.  

Ich nehme an, dass Du ein "Recompute" bereits versucht hast.  WHOQOL für diesen Patienten. Or?

Versuche heute Abend diesbezüglich etwas zu erreichen.

**Comment by ottigerb** [comment]
### Solution
http://optinomic.cust.local/client.new/#/patient/3638/stay/5542/app/ch.suedhang.apps.whoqol.production/template/WHOQOL   is fixed  by:

http://optinomic.cust.local/api/#/admin/tools

<img width="677" alt="bildschirmfoto 2018-05-15 um 10 06 19" src="https://user-images.githubusercontent.com/2470873/40044477-c095207a-5827-11e8-9fa7-5d5c199ad57f.png">

Nach Änderungen wie Messzeitpunkt muss dies noch "manuell" angestossen werden. Wir werden bald eine Möglichkeit haben - Daten zu bearbeiten, welche dann gleich das "Recompute" anstösst!

**Comment by ottigerb** [comment]
http://optinomic.cust.local/client.new/#/patient/1429/stay/580/app/ch.suedhang.apps.bscl_anq.production/template/BSCL  is also fixed:

gleicher `POST` & `1429` bei `BSCL-ANQ` & `scores_calculation`.

**Comment by schoenenb** [comment]
Ah voilà - aufs manuelle POSTen habe ich verzichtet, weil bereits nach der Änderung etwas von Berechnung stand und ich daraus schloss, dass es das jetzt automatisch macht... Sorry!!

**Comment by ottigerb** [comment]
## :-)   

Wenn alles soooo einfach ginge!
