### ISSUE TITLE
Fragebogen anderer Person zuordnen

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#162]
Wir haben wieder mal einen "speziellen" Fall:
Ein BSCL wurde bei /patient/3461/stay/1735 ausgefüllt, gehört aber eigentlich zu /patient/3275/stay/1709.
Weil der Fehler vor dem Limesurvey-Backup nicht erkannt wurde, sind die Daten dort schon weg.
Kann ich die Daten per SQL über den Event anders zuordnen? Wird die Patientenangabe dann auch bei der survey_response geändert, oder muss die dort auch angepasst werden? 
```
UPDATE event SET patient_uses_module = 21145
UPDATE event SET patient = 3275
WHERE id = 31721
```
ev. 

```
UPDATE survey_response SET patient = 3275
WHERE id = 18683
```
...oder gibt's eine noch einfachere Lösung, die ich nicht sehe?
...oder kann man Fragebögen nur innerhalb einer Person zwischen zwei Fällen verschieben? (D.h. zwischen 2 Personen geht nicht, der Fragebogen müsste neu eingegeben werden?)

**Comment by ottigerb** [comment]
Prinzipiell klappt via SQL auch ein Verschieben zwischen 2 Personen. Sicher nicht ganz trivial... ich wollte doch mal so eine Daten-App dafür bauen... Reminder an mich!  :-)

Prinzipiell sollte das Vorgehen gleich wie in folgender Anleitung sein:
https://github.com/Optinomic/apps/wiki/Anleitung-::-Daten-einer-Applikation-in-einen-anderen-Fall-verschieben

Zusätzlich jedoch noch wie beschrieben:
```
UPDATE survey_response SET patient = 3275
WHERE id = 18683
```
=>  Gut "aufpassen" mit den PUM's - dass diese auch dem richtigen Patienten/Fall zugeordnet sind.

Good luck!  :-)

**Comment by schoenenb** [comment]
Ach ist das kompliziert ;-)
Bis jetzt funktioniert's nicht - ev. muss ich's noch damit versuchen.
`UPDATE events SET patient_uses_module_id = 123456 WHERE id IN (SELECT event.id FROM event LEFT JOIN survey_responses AS sr ON sr.event_id = event.id WHERE sr.something = 'some value');`

**Comment by ottigerb** [comment]
...ja, die gesamte Kette gilt es zu "modifizieren".  

Musst Du sowas oft machen?  Response anderem Fall zuweisen etc.?

**Comment by schoenenb** [comment]
Ich hoffe, dass es bei dem Einzelfall bleibt oder nur sehr selten vorkommt. Es hat aber glaube ich noch ein paar (ältere) Fälle, die falsche Zuordnungen haben, bei Übergängen von EP -> TK und ähnlich, allerdings innerhalb einer Person.
Und meinen Fehler habe ich eben entdeckt - _id habe ich vergessen. :/
