### ISSUE TITLE
BSCL-Anzeige fehlerhaft

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#166]
Wie wir heute gemerkt haben, gibt die BSCL-Ausgabe nur noch die Werte der 1. Erhebung an, jedoch so oft, wie tatsächlich Antworten vorhanden sind. 
Ein paar Beispiele:
http://optinomic.cust.local/client.new/#/patient/3220/stay/1551/app/ch.suedhang.apps.bscl_anq.production/template/BSCL
http://optinomic.cust.local/client.new/#/patient/3232/stay/1673/app/ch.suedhang.apps.bscl_anq.production/template/BSCL
http://optinomic.cust.local/client.new/#/patient/3437/stay/1706/app/ch.suedhang.apps.bscl_anq.production/template/BSCL

**Comment by ottigerb** [comment]
FIXED by: https://github.com/Optinomic/apps/commit/05204f7e202f8ee13ede66e3685db3b3293a5b96

...war ein FIX vom FIX!  Na ja... back to normal!   :-)
