### ISSUE TITLE
HoNOS scheint nicht zu funktionieren über den Link aus dem Mail

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#167]
Die Therapeuten haben sich gemeldet, dass der HoNos sich nicht mehr über den Link aus den Mails öffnen lässt. Hier die angezeigte Fehlermeldung:
![image](https://user-images.githubusercontent.com/20124244/35861651-f79d3dd6-0b48-11e8-8e50-1e57b2dac102.png)
Was soll ich Ihnen sagen um den Fehler zu beheben?

**Comment by ottigerb** [comment]
## Fragen
Hmm...  was ich auf dem Screenshot entnehmen kann hat es etwas mit `sendgrid` dem Emailer zu tun.   Ist dies nur bei HoNOS?  Oder auch andere Apps?  Wie lautet die URL innerhalb des Mails?  Kannst Du mir allenfalls ein solches Mail weiterleiten?  Allenfalls ist nur ein DNS (nicht Optinomic) aus und wird sich wieder erholen. Funktionierte ja bis anhin einwandfrei - oder?

## Zur Überbrückung:  

1.)  Anmelden in http://optinomic.cust.local/client.new/#/login
2.) Zum jeweiligen Patienten/Fall navigieren:  Z.B.: 
http://optinomic.cust.local/client.new/#/patient/1/stay/1/app/ch.suedhang.apps.honos.production/start

3.)  Aufgabe ausführen / manuell starten: 

<img width="640" alt="bildschirmfoto 2018-02-06 um 14 32 09" src="https://user-images.githubusercontent.com/2470873/35862135-c71c1a90-0b4a-11e8-8a27-6c819c0d03b4.png">
=> Einfach durch "Klick" auf das Häckchen den Fragebogen starten.

oder
<img width="637" alt="bildschirmfoto 2018-02-06 um 14 32 45" src="https://user-images.githubusercontent.com/2470873/35862134-c6f96ec8-0b4a-11e8-8211-0d1f937d6ad2.png">
=>  Falls keine Aufgabe vorhanden wäre (s0llte nicht sein, da ja ein Mail versendet wurde):  [Jetzt...]


### Hope that helps!

**Comment by SonjaKaufmann** [comment]
Lieber Beat,

habe die die Mail mit dem Link aufs Mail getan. Danke für die schnelle Hilfe.

**Comment by ottigerb** [comment]
### Kurzer Workaround:


Der Link vom Mail sieht z.B. wie folgt aus:
```
https://u2582464..ct.sendgrid.net/wf/click?upn=dAvk2O4iM0XW3XkOR1TL5prLm936m2QbifVbIrejOzlA8953lAGcg6CVOj1K5bqiJpQEFB798O67CGG-2Bq43LQs-2B1Gh1f9foKkJOistn4i7rH5W3B0PP43UmwJw6yiq69vUBa2cOmSXN8t4-2BLREc0Pqs-2Bl3Z3F84iN8pCmMvLCXO778oBG-2BvGRo-2BkrOxZB87PzRdCkpL2-2BP0vv-2B7zPFJ4Vwrn6du5bPCQ9Yg2mvlo9SD6xvexc9RLH-2FjVcUrZBIbSoKyZpsrDtQW4Ut2gGegX5A-3D-3D_iuWMrNMHugUHvUZjLeFMrubeCsc9drgXN8ivXi1kk1Hvp56GfgkP3i35nqzqPSPlOCclBVRUb-2Fgp2aPL-2F92iWGMANHTGQrnTzZmzFqtqo-2FdU3RzQbbGr6aVW9vnSam-2BO-2BNdkLVT-2B-2FFF-2FI9MLGr-2FRQmXjyQzBaYAzS5chxBlbZOyhplDNS7Jpm-2BHBTMxXwU3-2BJ9Bsa1-2FbWxtcQ2toGMSFZm1NTLICSU2YpUwi9N9f4aw-3D
```

Bei einem "Not Found" kann der Link wie folgt angepasst werden:

```
https://u2582464.ct.sendgrid.net/wf/click?upn=dAvk2O4iM0XW3XkOR1TL5prLm936m2QbifVbIrejOzlA8953lAGcg6CVOj1K5bqiJpQEFB798O67CGG-2Bq43LQs-2B1Gh1f9foKkJOistn4i7rH5W3B0PP43UmwJw6yiq69vUBa2cOmSXN8t4-2BLREc0Pqs-2Bl3Z3F84iN8pCmMvLCXO778oBG-2BvGRo-2BkrOxZB87PzRdCkpL2-2BP0vv-2B7zPFJ4Vwrn6du5bPCQ9Yg2mvlo9SD6xvexc9RLH-2FjVcUrZBIbSoKyZpsrDtQW4Ut2gGegX5A-3D-3D_iuWMrNMHugUHvUZjLeFMrubeCsc9drgXN8ivXi1kk1Hvp56GfgkP3i35nqzqPSPlOCclBVRUb-2Fgp2aPL-2F92iWGMANHTGQrnTzZmzFqtqo-2FdU3RzQbbGr6aVW9vnSam-2BO-2BNdkLVT-2B-2FFF-2FI9MLGr-2FRQmXjyQzBaYAzS5chxBlbZOyhplDNS7Jpm-2BHBTMxXwU3-2BJ9Bsa1-2FbWxtcQ2toGMSFZm1NTLICSU2YpUwi9N9f4aw-3D
```


Also:  `u2582464.ct.sendgrid.net/...` statt `u2582464..ct.sendgrid.net/...`.  
=> Tom kämpft bei Gelegenheit (https://github.com/ottigerb/therapy-server/issues/493) gegen diesen unnötigen Extradot. M.E. ist dies jedoch ein Sendgrid-Thema.

**Comment by SonjaKaufmann** [comment]
Lieber Beat, 
leider verstehe ich es nicht ganz, es scheint aus irgendeinem Grund ein Punkt zuviel im Link zu sein. Und wenn ich es richtig verstehe wird sich Tom diesem Thema annehmen. Hast Du eine Ahnung, warum der Fehler auf einmal auftaucht und vorher nicht da war? Komisch komisch, hoffen wir das es sich bald löst.  Passiert natürlich immer in Noras Ferien sowas, vielleicht ist das ja ein Fasnachts-Dot!

**Comment by ottigerb** [comment]
Genau.  Es gilt einen Punkt zu löschen  -  kann so ev. den Therapeuten kommuniziert werden.

Warum?  Wieder mal eine "gute Frage"!  ;-)

**Comment by SonjaKaufmann** [comment]
Hm, im Moment lasse ich die Therapeuten wohl eher auf Papier ausfüllen als ihnen das zu erklären und hoffe das es sich bald löst. Man könnte ja auch aus dem Optinomic die Aufgabe öffnen und erledigen, so wie von Dir schon beschrieben. Was denkst Du wie lange dauert es bis der Doppeldot-Fehler gelöst ist?Geht es um Tage oder um Wochen?

**Comment by ottigerb** [comment]
Papier ausfüllen!?  Nö!

> We do not create such links in Optinomic so this looks like a bug from Sendgrid.

Wie vermutet:  Der Fehler liegt bei Sendgrid. Habe dort mal ein Issue plaziert. 
Bitte prüft dieses Issue immer mal wieder.  Danke.

**Comment by ottigerb** [comment]
Sind die URL's in den Emails nun wieder korrekt?

**Comment by schoenenb** [comment]
Letzten Donnerstag ging's noch nicht - ich nehme aber an, wenn es heute bei meinem Testpatienten funktioniert, dann stimmen auch die Adressen bei den anderen. :+1:
