### ISSUE TITLE
Error beim Öffnen ohne Rechte

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#168]
Therapeut PB konnte nicht auf einen Fall einer anderen Therapeutin zugreifen LO. Er berichtete mir, dass immer ein Fehler erschien und er die Patientin daher nicht öffnen konnte. Ich habe leider keine Screenshots von Fehlern und weiss nicht warum ihm der Zugriff verwehrt wurde. Ich konnte Patientin problemlos öffnen, aber ich habe ja auch Administratorenrechte. Vielleicht findest Du ja etwas im Verlaufsprotokoll.

**Comment by ottigerb** [comment]
**Grundsätzlich:** Therapeuten `ObL` & `PB` haben auf jeden Fall die gleichen "Berechtigungen" bzgl. Implizitem/explizitem Behandlungsauftrag. 

**Fehler:**  Wie ich die Sache analysiert habe aus den Logs (bzgl. diesem Vorfall etwas knapp):  

Die "Sitzung" von `PB` war abgelaufen (aktuell auf 90 Minuten eingestellt). Da er Optinomic nicht mehr als "aktives Browserfenster" geöffnet hatte, konnte Google Chrome ihn nicht sauber abmelden. Entsprechend hat er wohl auf "401 - Errors" gesehen beim Versuch weitere Daten von Optinomic zu beziehen. 

=> Ich habe den Errorhandler diesbezüglich verbessert (https://github.com/ottigerb/therapy-server/commit/5b4e83d8459ce877a7dca91736543eb1ad9ca400): 

- Der User wird in einem solchen Fall mit folgender Fehlermeldung "beglückt" und zur Neuanmeldung weitergeleitet:  "Uuups, Ihre Sitzung ist abgelaufen. Besten Dank für Ihre Neuanmeldung.". Zudem sollten nun deutlich weniger Fehlermeldungen "ausgegeben" werden. Auch wurde die [NEWS](http://optinomic.cust.local/client.new/#/news/detail/8a929c60-c686-45f6-9fcd-b586d54f0b75) kommuniziert.
