### ISSUE TITLE
[Diskussion]  Besprechungstermin | Freitag, 28.10

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#17]
### Termin

Wir treffen uns doch diesen Freitag, 28.10 | ab 9h im Südhang - bestätigt?
### Inhalt / Traktanden
- [ ] Apps: Alle V2-Apps durchgehen und Issues eröffnen.
- [ ] Apps: Namensgebungen der Apps |  Production / Dev. 
- [ ] Dokumentation: Inhaltsverzeichnis erstellt.

**Comment by SonjaKaufmann** [comment]
Ja das ist für mich auch gut. Ich habe von 7:30 bis 16.15 Uhr Zeit.
- [ ] - Vielleicht können wir mit Thömu und der Arbeitsintegration noch einen Termin abmachen um uns die ganze Sache mal gemeinsam auf den Laptops anzuschauen bzw. was es da noch braucht.
