### ISSUE TITLE
BSCL-Export funktioniert nicht

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#170]
Der BSCL-Export in der Export-ToolboxV2 lädt und lädt - gibt aber nie Daten aus.
Stimmt da vielleicht was an den Export-Syntaxen nicht, oder gibt's ein Problem auf App-Seiten?

![image](https://user-images.githubusercontent.com/20124244/36670200-c7c981dc-1af7-11e8-9784-e00b9ffcd6e9.png)

**Comment by ottigerb** [comment]
Ich habe einige "Verbesserungen" an der App ([org.optinomic.export.toolbox.v2.suedhang](https://raw.githubusercontent.com/Optinomic/apps/master/org.optinomic.export.toolbox.v2.suedhang-1.0.opapp)) vorgenommen:  Bei einem Fehler wird ein "Error" ausgegeben. Somit wird deutlich angezeigt, dass das "Warten" ohne Erfolg bleibt.  Vgl.: https://github.com/Optinomic/apps/commit/c349d66df1fddf6693c16f24c9fc25f086c59179


Die User-App-Calculation lief in einen Error:  
Dies konnte ich wie folgt beheben: 

http://optinomic.cust.local/api/#/admin/tools

### Annotations

`POST`  `http://optinomic.cust.local/api/#/admin/tools` 

`User-App: Export-Toolbox (V2)`  `bscl_ua_calc`


### Fixed
![bildschirmfoto 2018-02-26 um 13 51 09](https://user-images.githubusercontent.com/2470873/36671540-34db1160-1afc-11e8-9e37-52c7b5c3fb14.png)

**Comment by schoenenb** [comment]
Die BSCL-Exporte funktionieren wieder nicht - wenn alle 3 BSCL-Exporte betroffen sind, heisst das dann, dass in der Definition der Datenquelle (https://github.com/Optinomic/apps/blob/master/org.optinomic.export.toolbox.v2.suedhang/elements/behavior-export-toolbox.html#L50-L55) etwas nicht stimmt? Ich weiss aber leider nicht was, weil die Angaben zu den anderen Apps für mich gleich aussehen, und die funktionieren ja...

**Comment by ottigerb** [comment]
Es scheint als wäre die Datenmenge doch ordentlich grooooos - entsprechend läuft die Calculation in ein 504 Timout!  

=>  Tom will fix this @ https://github.com/ottigerb/therapy-server/issues/537

**Comment by ottigerb** [comment]
### Confirmed - Fixed

![bildschirmfoto 2019-01-18 um 08 53 19](https://user-images.githubusercontent.com/2470873/51372805-ae4fee00-1afe-11e9-860f-20717c461e6d.png)
