### ISSUE TITLE
Login funktioniert nicht

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#171]
Manche Therapeuten (bekannt von Miriam Schneeberger und meinem Sonja Kohls Account) können sich nur für 1 Sekunde einloggen und dann kommt die Meldung: Sie sind aufgrund von Zeitüberschreitung ausgeloggt worden, ....
Somit können die Bögen nicht ausgefüllt werden, da die Therapeuten gar nicht ins Programm reinkommen.

**Comment by ottigerb** [comment]
Habe es soeben getestet =>  Funktioniert hier einwandfrei.  Auch mit einem "Therapeuten-Login".
=>  Bitte versucht mal mit "Seite aktualisieren" / "Clear cache" / Browser neu starten.

**Comment by ottigerb** [comment]
The [chrome documentation](https://support.google.com/chrome/answer/157179?hl=en&topic=25799&rd=2) says:

## Reload the current page, ignoring cached content:
 `Shift` + `F5` 
or 
 `Ctrl` + `Shift` + `r`

**Comment by SonjaKaufmann** [comment]
Da die Therapeutin jetzt besetzt ist und ich nachher nicht mehr da bin können wir dem erst morgen weiter nachgehen.
Komme beim 2. Kommentar auch nicht ganz drus, soll man jetzt Clear cache und Browser neu starten oder Shift mit F5 machen oder beides probieren?

**Comment by ottigerb** [comment]
...gemäss der Chrome Dokumentation sollte ein Shift + F5  or Ctrl + Shift + r  genügen um die Seite nochmals neu zu laden. Falls dies nichts bringen sollte => Clear cache, Neustart.  

...soll ich diesen Tipp als "News" veröffentlichen?

**Comment by SonjaKaufmann** [comment]
Ach ja, bei mir hat es jetzt funktioniert. Aber ich glaube bei mir hatte es das neue Passwort nicht genommen und ich habe es in V2 nochmal neu gesetzt. War etwas dumm dies zu kombinieren, so bin ich dem Fehler nicht wirklich auf die Schliche gekommen :-( Sorry.

**Comment by ottigerb** [comment]
...easy!  Oh jaaa - da war was mit PW ändern. Stimmt - Maaaan, die Arbeit wird wohl nie weniger!  ;-)

...versucht es morgen nochmals & schliesst dieses Issue falls alles i.O. ist!  Hinweis welcher Affengriff der richtige war:  Shift + F5 or Ctrl + Shift + r  wäre auch interessant.

Thanks!

**Comment by SonjaKaufmann** [comment]
Mhhh, ich weiss nicht. Im Moment wird auf solche Vorschläge etwas allergisch reagiert. Aber es schadet ja nichts es drauf zu setzen, aber wenn wir die Möglichkeit haben sollten wir eher vorbeigehen und es machen. Zumal die betroffenen ja gar nicht zu den News gelangen, wenn sie sofort wieder ausgeloggt werden.

**Comment by ottigerb** [comment]
Auf die NEWS kann auch ohne Login zugegriffen werden - doch sehen werden Sie dies wohl kaum. Anyway:  Ich habe mal ein Eintrag hinterlassen: http://optinomic.cust.local/client.new/#/news/detail/64db4779-795a-4122-abf0-70c451b4daaf

Falls dieser nicht passt, kann er ja jederzeit durch Euch gelöscht werden.

**Comment by schoenenb** [comment]
Die Therapeutin (65) hat mir gestern Nachmittag gesagt, dass sie sich immer noch nicht anmelden könne. In den logfiles finde ich aber ein "erfolgreiches Login" am 1.3., die letzte Fehlermeldungen zu ihrem Login am 27.2. Gäb's noch einen anderen Weg rauszufinden, was nicht klappt, ausser daneben zu stehen, wenn sie sich anmeldet?

**Comment by schoenenb** [comment]
Vorgehen:
1. neues PW setzen bei User - kein Zugang (403 - Forbidden)
2. Browsercache löschen - mit neuem PW probieren - kein Zugang (403 - Forbidden)
Falls es nicht nur um den Code geht, hier ein Ausschnitt der Console:
![image](https://user-images.githubusercontent.com/15833792/36894640-5b88cd94-1e0c-11e8-9784-231380227f64.png)
3. Archivieren - kein Zugang (401 - Unauthorized) - ist ja eigentlich klar
4. Archivierung aufheben - kein Zugang (403 - Forbidden)
5. Mail-Adresse nochmals abspeichern
alle Schritte wurden in client.new vorgenommen

Weil Sonja ihr PW ja auch in V2 gesetzt hat, habe ich das nun auch probiert.
6. Anmeldung nach PW-Rücksetzung in V2 - Zugang funktioniert bei mir.

Nebenbeobachtung: die Mailadresse wird nicht mehr "gespeichert", obwohl autofill im Browser an ist -
 oder geht das über eine andere Funktion?

**Comment by ottigerb** [comment]
Jep, dieses Issue ging etwas aus den Augen.  PW bitte vorerst in  V1 ändern.  
=>  client.new  wird diesbezüglich gefixt.

**Comment by schoenenb** [comment]
Ist der Zeitraum bis zur Abmeldung nun doch länger als 90 Minuten? Ich habe mich extra im Citrix mit ID 65  eingeloggt, Fenster zugemacht und nach mehr als 90 Minuten Optinomic wieder geöffnet und ich war noch immer angemeldet...

**Comment by ottigerb** [comment]
... ich habe mal diesen Zeitpunkt erhöht.  Auch scheint - Chrome - irgendwie die "Session" abzuschalten - dann greift der Zeitpunkt (90 Minuten) anscheinend nicht mehr. Anscheinend tut dies Chrome um Memory zu sparen.

... gelang es somit - sich mit dem User anzumelden?  Anderer Compi?  Cache leeren?

**Comment by ottigerb** [comment]
## Fixed
Ich konnte den Fehler reproduzieren.  Bei einer Session-Timeout war ein Array mit Errors gefüllt. Bei einer Neuanmeldung werden diese "Errors" nun zuerst sauber gelöscht.  Somit sollte kein Login-Loop mehr entstehen.  Yes!  Übrigens :: Login-Loop konnte mit einem Clear-Cache behoben werden - dieser setzte das Error-Array wieder auf [].

## Hinweis :: Passwort ändern in /client.new
1. Passwort ändern in /client.new  funktioniert nun einwandfrei. 
2. "unassigned_patients_user_email" wurde auf "QM-Assi@suedhang.ch" gesetzt.


-> ich werde die FIXes auf Südhang pushen!

**Comment by schoenenb** [comment]
Vielen lieben Dank!

**Comment by schoenenb** [comment]
Nur für meine Notizen, falls es das Problem wieder mal gibt: es war ein Problem mit den Google-Einstellungen bzw. waren im Zielort der Links, welche ich den anderen zur Verfügung gestellt habe, meine Angaben zum Cache gespeichert (oder so).

**Comment by schoenenb** [comment]
Kann es doch was "Zentrales" mit Optinomic bzw. mit einer Änderung in Optinomic sein?
Heute waren es 4 TherapeutInnen, bei welchen sich das gleiche Muster abgespielt hat. Bei der einen konnte ich es lösen mittels Rücksetzung der Seiteneinstellungen, ev. lag es aber auch daran, dass ihr Account locked war. Beim Nachschauen unter den Benutzern war aber sonst niemand gesperrt...

**Comment by ottigerb** [comment]
Hmm...  zu doof, dass ich den Effekt nicht mehr zu reproduzieren komme.  

### UserCache aktiv löschen
Anyway :: New try:  https://github.com/ottigerb/therapy-server/commit/a5237183b9821a24db5b45526d5f36fa7605b984

Ich lösche nun aktiv den UserCache bei einem SessionTimout - somit dürfte das Thema wohl hoffentlich behoben sein. Daumendrück.  New stable is currently building & wird dann auf Südhang gepushed.

**Comment by ottigerb** [comment]
...ah interessant - Frage:  Können sich solche Therapeuten normal anmelden mit dem `[x] Dies ist ein öffentlicher Computer`?  Falls Du dies bei einem Fall testen könntest - would be great!  👍

**Comment by ottigerb** [comment]
https://github.com/ottigerb/therapy-server/commit/a5237183b9821a24db5b45526d5f36fa7605b984  ist im Südhang angekommen. 

Betroffene User sollen nochmals versuchen - Browser schliessen und neu starten.  Auch ein `Ctrl`+ `Shift`+ `R` könnte helfen.

**Comment by ottigerb** [comment]
Ach noch was: Die betroffenen User sehen ein "Sitzung ist abgelaufen" und gelangen in ein Login Loop nach der neuen Anmeldung - or?  Nicht etwa ein "Uuups, falsche Login Informationen". Dann wäre eine Passwortänderung angebracht.

**Comment by schoenenb** [comment]
Die sind grad alle besetzt... Ich schau nachher kurz, ob bei Sonja das gleiche Problem ist, die anderen sind besetzt oder haben bereits die Einstellungen zurückgesetzt, sodass sie wieder reinkommen...

**Comment by ottigerb** [comment]
OK!

Vielleicht wäre ein `[Clear Cache]` Knopf auf der Login-Seite eine Idee. So könnte der User alle gespeicherten Daten per Knopfdruck löschen. What do you think?

**Comment by schoenenb** [comment]
Wenn das wirklich öfters vorkommt, dass sie den leeren müssen, wäre das auch eine Option. Aber eigentlich widerspricht das Cache-Löschen doch dann der Idee, dass sie die Grafiken möglichst schnell laden können sollten...?
Entweder hat dein Wirken bereits gefruchtet, oder die Anmeldeprobleme waren doch nicht bei allen da - Aleksandra konnte sich um ca. 13.15 Uhr ohne Probleme einloggen...

**Comment by ottigerb** [comment]
...ja, dieser "Löschen-Knopf" wäre ja so eine Art "Backup" falls es mal nicht klappen würde. Sollte jedoch nicht oft vorkommen. Und ja:  Bei gelöschtem Cache muss alles wieder neu geladen werden - doch auch dann sollte die Performance ganz gut sein.   Anyway:   Ich habe den Knopf gebaut und können mal Erfahrungen damit sammeln.  

<img width="681" alt="bildschirmfoto 2018-03-07 um 13 49 26" src="https://user-images.githubusercontent.com/2470873/37093112-7febdf72-220e-11e8-90fc-57f2e059c8ed.png">

Dieser "Kübel - Button" =>  Clear Cache & User-Storage :: Also ganz "jungfräulich"!    :-)


https://github.com/ottigerb/therapy-server/commit/213f66a9c402166746db38397cd36358ecef9e22  sollte in wenigen Minuten bei Euch ankommen. 


...freut mich, wenn das Login geklappt hat - vielleicht hatte Sie auch erst mein gestriger Bugfix erhalten.  Anyway:  CLOSE - falls es nochmals auftaucht -> REOPEN

**Comment by ottigerb** [comment]
Zur Info:  `Clear Cache & User-Storage`  Knopf ist auf http://optinomic.cust.local/client.new/#/login angekommen und funktioniert einwandfrei - dieser kann als eine Art "Notfallknopf" kommuniziert werden.  Bei Anmeldeproblemen oder anderen "eigenartigen" Situationen.

**Comment by schoenenb** [comment]
Tiptop, merci für die schnelle Hilfe!
Wenn's noch Performance-Probleme gibt (es war die Sprache von 4 Min. warten, bis man einen Fragebogen ausfüllen kann..?), kann das an der überfüllten Limesurvey-Datenbank liegen? Die wurde drum schon ein Weilchen nicht mehr geleert, weil Noëmi nicht dazu kam.

**Comment by ottigerb** [comment]
...ja, macht schon Sinn - limeSurvey immer mal wieder zu "leeren"!   Dies jedoch mehr um die Ergebnisse schnell in Optinomic einlesen zu können.  Vielleicht mussten sie 4 Minuten warten, damit die Ergebnisse in Optinomic sichtbar wurden - dies kann schon sein.  Jedoch nicht beim Fragebogen ausfüllen:   Aktuell scheint alles i.O. zu sein - actInfo kann ich bei Demo Muster umgehend starten.  Hmmm.

**Comment by schoenenb** [comment]
Ich weiss eben nicht so genau, was sie gemacht haben, es ging wohl eher um den HoNOS, aber ich werde da mal mit dem Zuständigen schauen. :)

**Comment by ottigerb** [comment]
Confirmed:  Fix hat gefruchtet:

1. CITRIX Anmeldung.
2. Optinomic Login
3. CITRIX Abmeldung ohne Optinomic Logout & Browser schliessen
4. Warten 1 Tag oder so
5. CITRIX Anmeldung
6. Korrekte Fehlermeldung:  Session Timeout
7. Login Funktioniert einwandfrei!

=>  Der CLEAR-CACHE Button auf der Login-Seite kann trotzdem immer mal wieder hilfreich sein.  Bitte benutzt diesen als `FIRST-LEVEL-Support`!   Thanks!  :-)
