### ISSUE TITLE
Patient aus Liste wählen - vorheriger Patient wird angezeigt

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#173]
Heute habe ich mal eine etwas konkretere Rückmeldung zu Problemen beim Fragebogenausfüllen von Seiten Therapeuten erhalten:
Beim Auswählen eines Patienten aus der Liste erscheinen die Angaben einer vorher geöffneten Person.

Das ist mir glaube ich auch schon passiert, allerdings nur, dass mindestens in der "Kopfzeile" der vorherige Patientenname noch stand, bei erneutem Laden durch Enter in der Browseradresse (weil ich die Opti-ID kannte und damit bestätigte) hat's dann geklappt.

Irgendwelche Ideen, woran das liegen kann?

**Comment by ottigerb** [comment]
M.E. kann dies nur sein, wenn z.B. die API keine Daten liefert. Dies sollte m.E. ebenfalls mit der "Session Timeout" Geschichte behoben sein:  Sobald kein Zugriff mehr besteht wird zur Neuanmeldung aufgefordert. Vorher wurde zwar ein 401 Fehler angezeigt, jedoch wurde nicht "abgebrochen". Somit war es wohl möglich, dass solche Effekte auftraten.  

=>  CLOSE

**Comment by schoenenb** [comment]
So wie ich dich verstehe, sollte das somit heute nicht mehr vorkommen - die Rückmeldung kam aber von einem Fall heute Vormittag...

**Comment by ottigerb** [comment]
...öhm - hier müsste ich mehr Informationen haben. Ich habe einen solchen Effekt nie gesehen. Aus welchen "Listen"?  Allenfalls hat der Patient kein Fall und der direkte Klick auf den "latest Stay" Link versagt dadurch?  Vielleicht sowas?

**Comment by schoenenb** [comment]
Ich werde noch nachfragen und dich wieder informieren, wenn ich mehr weiss.

**Comment by schoenenb** [comment]
Bin zwar bisher nicht dazugekommen nachzufragen, aber bei mir kam es heute wieder vor, wenn auch nur kurz, bevor es den richtigen Patientennamen angezeigt hat.
Kann es was mit dem "Saved | User-State" zu tun haben?
![image](https://user-images.githubusercontent.com/15833792/37451837-1e6b4cf8-2833-11e8-9926-611bcde8b3b4.png)

**Comment by ottigerb** [comment]
...der Patienten-Name im Header wird über ein "Property" zurückgegeben. Somit ist die Anzeige etwas "verzögert".  Auf der Patienten/Fall-Seite wird der Patient ja ebenfalls angezeigt...

...kann mal überlegen, ob ich diesen Header "anders" befüllen kann.

**Comment by schoenenb** [comment]
Möglicherweise war folgendes vorgefallen (war vorhin bei der Therapeutin, die mir das gemeldet hatte, weil wieder was nicht funktioniert hat):
Wenn man über die Liste "alle Patienten" geht und den Patienten mit der Suchfunktion ausliest und öffnet, wird nichts angezeigt und in der Browser-Adresszeile steht "http://optinomic.cust.local/client.new/#/patient/0" - in der "Kopfzeile" wird aber der Name des zuletzt geöffneten Patienten angezeigt...
Drum wäre hier die Frage: weshalb kann man den Patienten auswählen, wird dann aber trotzdem nicht auf dessen Seite geleitet?

**Comment by schoenenb** [comment]
Möglicherweise hängt dies auch noch mit Folgendem zusammen:
Obwohl der User eingeloggt ist, wird sein Name nicht angezeigt, stattdessen steht dort nur ().
![image](https://user-images.githubusercontent.com/15833792/37466465-1ea4753e-285e-11e8-9bba-ec1858e3c4e8.png)
Wie man dem "(!!!) Storage full: nothing saved" entgegenwirken kann weiss ich auch nicht, falls es überhaupt was damit zu tun hat.

**Comment by ottigerb** [comment]
Jep!  Issue ist umstellt - gut eingekreist!  `(!!!) Storage full: nothing saved` - dies ist auch der Grund warum die `http://optinomic.cust.local/client.new/#/patients/all` Liste wieder verschwindet @ https://github.com/Optinomic/apps/issues/174.  Tauch mal hier ab.

**Comment by ottigerb** [comment]
Hierbei hilft übrigens auch der "Mülleimer" auf der Login-Seite.  Sie soll sich mal abmelden - Mülleimer betätigen und neu anmelden.

**Comment by ottigerb** [comment]
Closed because of https://github.com/ottigerb/therapy-server/commit/0fd850080aeb3f30bc51438105e0d767b84a92ce.

Ich denke, das dürfte eine gute Lösung darstellen:  Keine Daten werden aus dem State gelöscht - wie vorher `Alle Patienten` Liste. Bei `isQuotaExceeded` wird ein minimaler State zwischengespeichert =>  Bei einem Page-Reload werden dann `Alle Patienten` oder weitere Daten frisch angefordert.

**Comment by ottigerb** [comment]
Wieso haben wir in Optinomic nun 3376 Patienten?  Wenn ich bei http://optinomic.cust.local/client.new/#/patients/filter  `In aktueller Behandlung` selektiere erhalte ich 1906 Patienten!  Sind dies ambulante Patienten?

**Comment by ottigerb** [comment]
https://github.com/ottigerb/therapy-server/commit/0fd850080aeb3f30bc51438105e0d767b84a92ce ist im Südhang angekommen.  Kann keine "solchen Effekte" mehr erkennen.  Fix scheint zu greifen. Yes!

**Comment by schoenenb** [comment]
https://github.com/Optinomic/apps/issues/173#issuecomment-373483903 - stimmt, das ist mir auch schon aufgefallen, aber ich hab's immer wieder hinten angestellt. Seit dem Fix von Tom, dass 1.1.1970 als Eintrittsdatum angegeben wird, wenn es (was weiss ich nicht mehr) nicht erkennt, hat es ganz viele solche Fälle reingespült und ich bin davon ausgegangen, dass es Ambifälle sind.

**Comment by ottigerb** [comment]
https://github.com/Optinomic/apps/issues/173#issuecomment-373620829  ::  Meines Erachtens kein Problem. Somit haben wir auch diesen bug erkannt und konnten ihn fixen https://github.com/ottigerb/therapy-server/commit/0fd850080aeb3f30bc51438105e0d767b84a92ce

**Comment by schoenenb** [comment]
Bin mir nicht sicher, ob es auch was damit zu tun hat: wenn ich die Links aus https://github.com/Optinomic/apps/issues/172#issuecomment-373698258 in einem neuen Tab öffnen will (http://optinomic.cust.local/client.new/#/patients/group/26 und 27) ,
 zeigt es mir eine andere Gruppe (http://optinomic.cust.local/client.new/#/patients/group/15) an. Wahrscheinlich weil ich die als letztes geöffnet hatte...

**Comment by ottigerb** [comment]
...ich denke, Du hattest die neuen Fallgruppen noch nicht geladen.  Geh doch mal zuerst auf http://optinomic.cust.local/client.new/#/patients/group/all   :-)

**Comment by schoenenb** [comment]
habe ich nun gemacht (glaube ich zumindest) - bei beiden, QuEA und PTS zeigt es mir nun alle an (QuEA und PTS) - das hattest du glaube ich auch so angekündigt. Nur macht es irgendwie gar nicht mehr so Sinn, beide Gruppen zu führen, wenn sie ja doch identisch sind..?

**Comment by ottigerb** [comment]
...die Gruppen:  `Zugriff: EAS` & `Zugriff: EP` können wir danach löschen.   Aktuell sind beide Gruppen `26` & `27` identisch. Doch allenfalls wollen sie dann doch noch "spezielle" Einschränkungen für die beiden Abteilungen und dann können wir nur noch die Gruppe bearbeiten - done.
