### ISSUE TITLE
Patientensuche - Ansicht verschwindet

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#174]
Bei der Patientensuche http://optinomic.cust.local/client.new/#/patients/all
wird die Liste von Patienten nicht zuverlässig ausgegeben.
Zuerst hat es alle angezeigt und nach ein paar Sekunden verschwinden sie alle aufs Mal.
Mit abmelden und wieder anmelden hat es erst geklappt. Als ich Optinomic in einem zweiten Tab geöffnet habe, um einen zweiten Patienten zu suchen, hat sich das Spiel wiederholt.

Falls die beiden Warnungen in der Console was damit zu tun haben:
![image](https://user-images.githubusercontent.com/15833792/37450040-c87f2bc6-282c-11e8-9572-45371a65b547.png)

**Comment by ottigerb** [comment]
Close because of https://github.com/Optinomic/apps/issues/173#issuecomment-373444558
