### ISSUE TITLE
Fehlermeldung bei gesperrtem User

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#175]
Ist es möglich, als Anzeige sowas wie
`Ihr Benutzerzugang / Account /... wurde gesperrt. Bitte wenden Sie sich an Nora Schönenberger oder die QM-Abteilung.`
anzuzeigen, wenn der User gesperrt ist? User 28 hat sich eben gemeldet, weil er sich nicht anmelden konnte. Als Fehlermeldung erschien nur `Bitte überprüfen Sie Ihre Eingabe`, was in dem Fall etwas irreführend ist.

**Comment by ottigerb** [comment]
### Fixed

https://github.com/ottigerb/therapy-server/commit/40405a67dd2be43d733d478fe869b326dc434bf6

Wird mit dem "next Stable" an Südhang verteilt.  Diesbezüglich muss ich noch Tom fragen - da sind einige Änderungen im Gange, welche ich nicht ohne weiteres im Südhang publishen möchte.
