### ISSUE TITLE
Serverumstellung - Auffälligkeiten

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#178]
Bin dabei, die Funktionen zu testen und habe folgende Änderungen festgestellt:
- Fragebogenauswertung / Fallkonferenz + TMT sind nicht druckbar, als Übersicht http://old.optinomic.suedhang.ch/client.new/#/patient/3568/stay/5532/app/ch.suedhang.apps.fallkonferenz.production/template/overview
![image](https://user-images.githubusercontent.com/15833792/40605797-c96ce1ba-6263-11e8-8881-26fb4bb4a19e.png)
 wie auch als Einzel-App http://old.optinomic.suedhang.ch/client.new/#/patient/3568/stay/5532/app/ch.suedhang.apps.tmt.production/template/TMT - kann es was mit der Fehlermeldung in der Console zu tun haben?
![image](https://user-images.githubusercontent.com/15833792/40605881-fbf76bdc-6263-11e8-85a5-226adf428e7f.png)

**Comment by ottigerb** [comment]
http://old.optinomic.suedhang.ch/client.new/#/patient/2294/stay/1089/app/ch.suedhang.apps.fallkonferenz.production/template/overview
=>  Funktioniert.

[TMT von PID 3568](http://old.optinomic.suedhang.ch/client.new/#/patient/3568/stay/5532/app/ch.suedhang.apps.tmt.production/template/TMT) crashed weil die Stichprobe 70 – 74, Anderer Messzeitpunkt, <= 12 Jahre... wohl keine Einträge hat.  Dies ist ein TMT Thema - schaue ich mir bei Gelegenheit an um solche Effekte abzufangen.

**Comment by schoenenb** [comment]
Ah Mann, hab ich wieder nicht schön getestet - tut mir Leid!

**Comment by ottigerb** [comment]
Fixed by `optinomic-0.1.34` (Leere KS führen nicht mehr zum Crash.)
