### ISSUE TITLE
HoNOS Dropout

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#179]
In meinem Verständnis sollte bei einem Dropout beim HoNOS der Grund angezeigt werden.
Siehe Template:
https://github.com/Optinomic/apps/blob/master/ch.suedhang.apps.honos/templates/table.html ab Zeile 157

Bei http://old.optinomic.suedhang.ch/client.new/#/patient/3789/stay/5684/app/ch.suedhang.apps.honos.production/template/scores_table ist die Anzeige jedoch "einfach leer":
![image](https://user-images.githubusercontent.com/15833792/40779664-184a03a2-64d6-11e8-8d71-388d5eda94ff.png)

Kannst du das dann mal anpassen?

**Comment by ottigerb** [comment]
=>  Da war wohl die Calculation noch nicht berechnet => Scheit nun zu funktionieren.  z.B.: http://optinomic.suedhang.ch/client.new/#/patient/1/stay/1/app/ch.suedhang.apps.honos.production/template/scores_table

**Comment by schoenenb** [comment]
http://optinomic.suedhang.ch/client.new/#/patient/3789/stay/5684/app/ch.suedhang.apps.honos.production/template/scores_table
zeigt "nichts" an, weil die Angaben falsch gemacht wurden. Ich konnte bisher nicht rausfinden, weshalb jemand ein Dropout 2 ohne Textangabe machen konnte. Im old.optinomic... habe ich den Dropoutgrund nun auf 1 angepasst, in optinomic.suedhang.ch erscheint es aber natürlich nicht. Werden die Daten bei der definitiven Migration nochmals geholt?
In optinomic.suedhang.ch habe ich es in den Daten auch versucht anzupassen, Fehlermeldung "Failed with status code: 400 ".

**Comment by ottigerb** [comment]
...genau - aktuell alle Modifikationen in old.optinomic vornehmen. Die Daten wird Tom am Samstag ins optinomic.suedhang.ch übernehmen. 

...und ja - das Daten-Tab "Bearbeiten" hat noch ein bekannter Fehler - irgendwas mit den API Commands - PUT - scheint ein Problem zu haben. Auch hier wird Tom fixes vornehmen.
