### ISSUE TITLE
Manuelles Austrittsdatum V2 - client.new

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#180]
Wenn ich das Austrittsdatum manuell in der V2-Umgebung ändere, übernimmt es in client.new das Datum des Vortages. Kann man das noch ändern? Oder wird es eh überschrieben, falls die Pabs-Falldaten noch reinkommen?

Edit: Beispiel vergessen:
http://old.optinomic.suedhang.ch/api/#/patient/3796/stay/5670 - Austritt am 1.6.
http://old.optinomic.suedhang.ch/client.new/#/patient/3796/stay/5670 - Austritt am 31.5.

**Comment by ottigerb** [comment]
...Schnittstelle (PABS) überschreibt die Daten.  Der alte Client ist wird bald nicht mehr unterstützt => Close!
