### ISSUE TITLE
Logfiles

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#181]
Im Log erscheinen aktuell "leere" Einträge - "failed login attempt" ohne E-Mail-Angabe:
![image](https://user-images.githubusercontent.com/15833792/41285051-6e34ceaa-6e3b-11e8-8922-580c9d2d88eb.png)

Wenn ich mich "falsch" einlogge, legt es die Info aber richtig ab... Sollte mir das irgendwas sagen?

**Comment by ottigerb** [comment]
Öhhm - dann wurde schlicht keine `Email` eingetragen.

**Comment by schoenenb** [comment]
...ohne Eingabe im E-Mail-Feld ist der Anmelden-Knopf nicht anwählbar...

**Comment by ottigerb** [comment]
...stimmt - jedoch ein "Leerschlag" unter Email scheint "genug" zu sein um den Login-Button zu zeigen. Ich könnte mir vorstellen, dass die Autovervollständigung nicht korrekt ausgewählt wurde.

=>  OPEN: https://github.com/ottigerb/therapy-server/issues/527

**Comment by schoenenb** [comment]
Nö, es reicht sogar mit gar nichts drin, solange ein PW eingegeben wird. Alles klar, merci für die Aufklärung. :)
