### ISSUE TITLE
Apps nicht deaktivierbar

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#184]
Apps können aktuell nicht deaktiviert werden. D.h. man klick auf den Button, der dann aber gleich wieder nach rechts springt.
[Früher kam das auch schon vor, dass die Buttons erst wieder zurückgesprungen sind, jedoch wurden die Apps im Endeffekt trotzdem deaktiviert.]
Dem Problem auf die Spur kam Noëmi, weil sie jeweils die Apps deaktiviert und neu aktiviert hat, um die Erhebung in der Patientenansicht auszulösen.
Liegt das an der neuen Struktur? Wenn ich auf die deaktivierten Apps gehe, sind da alle aufgeführt mit der Pfad-Endung .production, bei den aktivierten Apss ist die Endung .production/start...

**Comment by ottigerb** [comment]
Interessant:  Ich habe dies kurz auf Demo getestet und dort funktioniert die Deaktivierung. Hmm.. 
 Versuche Genaueres zu ergründen.

**Comment by ottigerb** [comment]
```
(✔) Success ::  1169 594 ch.suedhang.apps.case.production  deactivated
```
...die App scheint erfolgreich deaktiviert zu werden - jedoch wird diese dann irgendwie doch nicht als "deaktiviert" markiert. Werde hier mal "abtauchen".

**Comment by ottigerb** [comment]
Soweit funktioniert das Deaktivieren wieder - werde hier jedoch noch weitere Improvements anbringen.

**Comment by schoenenb** [comment]
Merci - nehme an aktivieren danach geht dann auch wieder ;)

**Comment by ottigerb** [comment]
Weitere Verbesserungen vorgenommen: https://github.com/ottigerb/therapy-server/commit/0c76d54cdc896cc38d00caf01482383ba328b4f4

De-/Aktivieren Switch sollte nun nicht mehr "hin und her" flippern.
