### ISSUE TITLE
ASRS + TMT: Failed with status code 500 

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#189]
Ich weiss grad nicht wo ansetzen mit der Fehlersuche. Die Fehlermeldung erscheint, wenn man den ASRS ausführen will. Gleiches passiert auch beim TMT - ein ng-Survey-Problem?

**Comment by ottigerb** [comment]
Kannst Du nochmals versuchen?   Bei mir scheint nun alles i.O. zu sein!

**Comment by schoenenb** [comment]
Super - es tut. Ich versuche nachher noch einen zu speichern und einzusehen, denke aber, das klappt.
