### ISSUE TITLE
Gruppen via bot_pabs_odbc_pabs_stays

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#190]
Ist es möglich, dass mit dem pabs-bot was nicht tut, dass die Gruppenzuteilung zu den PG 10 +11 fehlschlägt?
```
LEFT JOIN stay ON(p.id = stay.patient) 

WHERE EXISTS (
    SELECT 1 
    FROM ch_suedhang_bot_pabs_odbc.ch_suedhang_bot_pabs_odbc_pabs_stays AS pabs
    WHERE pabs.org_short = 'PTS' AND stay.cis_fid::varchar = pabs.cis_fid
)
```

**Comment by ottigerb** [comment]
Hmm...  hat PABS was geändert?  Sind denn die Tabellen via ODBC erreichbar?

**Comment by schoenenb** [comment]
Jep. Allerdings finde ich die bot-pabs-odbc-App nicht im Repo, wenn ich mich nicht verschaut habe... Oder ist die sonstwo untergebracht?

**Comment by ottigerb** [comment]
Jep - was?  ODBC funktioniert?
Repo wäre diese:  https://github.com/Optinomic/ch.suedhang.bot.pabs.odbc/

**Comment by schoenenb** [comment]
Ja, odbc funktioniert. Stimmt, da war noch eine 2. Frage am Anfang - ich wüsste nicht, dass die was geändert haben.

**Comment by ottigerb** [comment]
...hmmm - da müsste ich wohl tiefer "reinknien" - heute bin ich leider "dicht an dicht". Werde am Freitag mal "kuck".  Du kannst vorübergehend die entsprechenden Patienten in eine "manuelle Gruppe" übernehmen - welche die Apps aktiviert schieben.

**Comment by ottigerb** [comment]
Nur zur Info:  Habe mal Tom diesbezüglich angefragt - vielleicht sieht er hier was!  => https://github.com/ottigerb/therapy-server/issues/536

**Comment by schoenenb** [comment]
Genau. Merci!
War mir heute auch nicht sicher, ob es nicht mehr alle HoNOS exportiert, oder ob tatsächlich seit 7 Tagen keine mehr ausgefüllt wurden. Einen vom Oktober musste ich drum manuell "einlesen", weil der Austrittshonos nicht übernommen worden war. Falls du da am Freitag auch kurz reinschauen könntest, wäre das super!

**Comment by ottigerb** [comment]
Habe mal den „scheduler“ erfolgreich restarted durch: 
```
sudo systemctl restart therapyserver-scheduler.service
```
=> Vielleicht ist es jetzt schon gelöst!  Doch wie gesagt - werde Freitags mal genauer schauen & wäre um jedes Feedback dankbar. Ob es jetzt vielleicht schon wieder läuft.

**Comment by ottigerb** [comment]
Für mich sieht alles wunderbar aus - auch PG11'er wurden "befüllt".  Falls mal wieder CIS-Importer nicht mehr läuft oder irgendwelche "Scheduler" nicht laufen wie sie sollten - give sign:
`restart therapyserver-scheduler.service`  does the trick!
