### ISSUE TITLE
Grafiken werden nicht mehr befüllt

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#192]
Seit gestern werden die Grafiken folgender Apps werden nicht mehr ausgegeben:
- AASE-G (Beschriftungen werden angegeben)
- BSCL (Meldung: "Erstelle Klinikstichprobe aus letzter Messung...")
- BDI-II (Endpunkte werden angegeben)
- ISK-K (Meldung: "Erstelle Klinikstichprobe aus letzter Messung...")
- SCI (Meldung: "Erstelle Stanine Scores...")
- WHOQOL-BREF (Meldung: "Erstelle Klinikstichprobe aus letzter Messung.")

Zudem fehlt der Knopf zum Drucken des PDFs der Fallkonferenz-App (die einzelnen Apps, die Grafiken ausgeben, kann man auch weiterhin aus der Fallkonferenz-App drucken/speichern).

Es betrifft allerdings nur diejenigen PatientInnen, welche gestern einen (oder mehrere) Fragebögen ausgefüllt haben.

**Comment by schoenenb** [comment]
Ich habe bei Fridolin Müller einen neuen BDI-Fragebogen ausgefüllt. Die Daten sind drin, eine Ausgabe kommt aber auch da nicht.
Die Console-Ausgabe gibt folgende Fehlermeldungen aus:
![image](https://user-images.githubusercontent.com/15833792/54590242-e48aea80-4a27-11e9-95ae-098cc4fd2794.png)
![image](https://user-images.githubusercontent.com/15833792/54590252-ee145280-4a27-11e9-8f38-8a246ef448b8.png)

**Comment by schoenenb** [comment]
Allerdings gibt es folgende Fehlermeldungen auch aus, wenn die Daten dargestellt werden (hier bei Demo Muster):
![image](https://user-images.githubusercontent.com/15833792/54590430-60853280-4a28-11e9-8008-43a2f4e7c180.png)
![image](https://user-images.githubusercontent.com/15833792/54590462-785cb680-4a28-11e9-9c9b-4b27fd071b02.png)

**Comment by schoenenb** [comment]
Betroffene PatientInnen wären:
http://optinomic.suedhang.ch/client.new/#/patient/4334/stay/6047
http://optinomic.suedhang.ch/client.new/#/patient/4371/stay/6049
http://optinomic.suedhang.ch/client.new/#/patient/4376/stay/6062
http://optinomic.suedhang.ch/client.new/#/patient/4315/stay/6078

**Comment by ottigerb** [comment]
Hmmm... irgendwas scheint mit `Calculations` nicht mehr zu funktionieren. Keine Ahnung was dies wieder für ein komischer Effekt ist!  Uff...  
=> Anyway - Issue konnte etwas eingegrenzt werden & is delegiert an Tom:  https://github.com/ottigerb/therapy-server/issues/547

**Comment by schoenenb** [comment]
..und scheint schon gelöst - die vermissten Resultate werden wieder abgebildet! Merci für den schnellen Fix!

**Comment by ottigerb** [comment]
### Gerne!

Gemäss https://github.com/ottigerb/therapy-server/issues/547#issuecomment-474447835 :

> PostgreSQL got jammed. It's back to normal. If it happens again, restarting postgresql.service might help.

**Comment by schoenenb** [comment]
@ottigerb Könntest du den postgresql.service neu starten? Habe gerade die Rückmeldung erhalten, dass die Grafiken nicht mehr angezeigt werden.

**Comment by ottigerb** [comment]
```
optinomic@srv-appl-05:~$ sudo systemctl restart postgresql.service
optinomic@srv-appl-05:~$ sudo systemctl restart therapyserver-calculations.service
optinomic@srv-appl-05:~$ sudo systemctl restart therapyserver-scheduler.service
```

OK - Restarted!  Kannst Du mal beobachten, ob sich die Situation "auflöst".

**Comment by ottigerb** [comment]
...soeben geschaut - sieht für mich gut aus. CIS Verzeichnis scheint abgearbeitet und DB läuft soweit stabil.  Close?

**Comment by schoenenb** [comment]
Sorry, war in Sitzungen und hab's vergessen rückzumelden. Merci!!

**Comment by ottigerb** [comment]
Easy!  Hauptsache hat geklappt.  👍

**Comment by schoenenb** [comment]
Wir sind leider wieder mal soweit - die Grafiken werden wieder nicht angezeigt... Den restart kann ich nicht selber machen, oder?!

**Comment by ottigerb** [comment]
```
optinomic@srv-appl-05:~$ sudo systemctl restart postgresql.service
optinomic@srv-appl-05:~$ sudo systemctl restart therapyserver-calculations.service
optinomic@srv-appl-05:~$ sudo systemctl restart therapyserver-scheduler.service
```

OK - Restarted!  Kannst Du mal beobachten, ob sich die Situation "auflöst". 

> Den restart kann ich nicht selber machen, oder?!

Nein. Vielleicht könnten wir mal ein solcher "Restart" als Executable implementieren.

**Comment by schoenenb** [comment]
Merci wieder mal für den schnellen Support! Einer der genannten Fälle hat schon Daten, beim anderen wurde noch nichts abgefüllt. Wie lange braucht's ungefähr, bis alle Daten durchgelaufen sind?

**Comment by ottigerb** [comment]
> Merci wieder mal für den schnellen Support! Einer der genannten Fälle hat schon Daten, beim anderen wurde noch nichts abgefüllt. Wie lange braucht's ungefähr, bis alle Daten durchgelaufen sind?

Gerne!   Gute Frage - ich denke sollte bald mal "abgeschlossen" sein.  `Close` sobald alle Daten da sind. Danke!

**Comment by schoenenb** [comment]
Mittlerweile sind alle Daten da, kann aber nicht sagen, wie lange es gebraucht hat. Nach dem Mittag waren die Grafiken der gesuchten Fälle jedenfalls wieder mit Inhalt gefüllt.
