### ISSUE TITLE
Import NAV-Daten gestoppt?

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#193]
Die letzten Daten im SAVE-Verzeichnis stammen vom 21.6., im Schnittstellenordner sind noch 500 Files die anscheinend nicht verarbeitet worden sind. Gibt es ein fehlerhaftes File, das den Prozess blockiert, oder ist der Service ausgestiegen?

**Comment by schoenenb** [comment]
PS: Auch der HoNOS-Export scheint seither nicht mehr zu tun. Letzter Export ebenfalls vom 21.6. Das kann ich aber von Hand lösen...

**Comment by ottigerb** [comment]
Hmm....

...ich hab mal wieder die Services restarted - analog dem Issue "Grafiken" werden nicht geladen. Danke für kurzes Feedback ob, die Imports wieder "angestossen" werden.  Ich denke postgresql dienst "schiesst" immer mal wieder ab.

**Comment by schoenenb** [comment]
Die Daten sind nicht mehr im Schnittstellenordner, allerdings kann ich's nicht überprüfen, weil ich mich nicht mehr einloggen kann. Eben hat mir auch jemand anderes gemailt, dass ihr PW nicht mehr geht (und die vergisst sowas eigentlich nicht).

**Comment by ottigerb** [comment]
...Login funktioniert - habe ich soeben getestet. Darf ich Dich nochmals bitten kurz zu prüfen. Danke!

**Comment by schoenenb** [comment]
Ahja, sorry, es ging auch bei mir. :)
Danke vielmals!!
