### ISSUE TITLE
Clean-up Apps

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#24]
Nicht mehr benötigte Apps, die gelöscht werden könnten (Ziel: nur noch Apps in develop-repo, an denen noch gearbeitet wird oder die so verwendet werden können):

- [x] ch.suedhang.apps.aase_doing (id = ch.suedhang.apps.aase)

- [x] ch.suedhang.apps.honos_kurzverlauf (id = ch.suedhang.apps.honos_kurzverlauf)

- [x] ch.suedhang.apps.honos_kurz_2 (id = ch.suedhang.apps.honos_kurz_2)

- [x] ch.suedhang.apps.neuroanamneseV2 (id = ch.suedhang.apps.neuroanamneseV2)

- [ ]  ch.suedhang.apps.neuroanamnese_todo (id = ch.suedhang.apps.neuroanamnese)

- [x] ch.suedhang.apps.tmt (id = ch.suedhang.apps.tmt_new)

- [x] ch.suedhang.apps.tmt_doing (id = ch.suedhang.apps.tmt)

**Comment by schoenenb** [comment]
...vielleicht hat's Prio 1 nicht verdient, aber es würde mir sehr helfen, den Überblick zu behalten!

**Comment by ottigerb** [comment]
...solche Apps können einfach auf dem Produktions-System schlicht nicht 'Aktiviert' werden.  
=>  Ich verstehe das Issue nicht!

**Comment by schoenenb** [comment]
Es geht mir nicht um das, was auf Optinomic zur Verfügung gestellt wird, sondern um all die Versionen im Repo. Ich kann sie auch einfach rauslöschen, wenn das nicht zum Absturz führt. In Optinomic deaktiviert sind sie bereits.

**Comment by ottigerb** [comment]
...wenn nicht mehr benötigt - easy.  App deaktivieren - falls nicht schon erledigt.  
In Github Desktop:  Sync - Apps löschen - Sync again!

**Comment by schoenenb** [comment]
Tiptop. Dann mach ich das so. Letztes Mal gab's ein Gnusch, drum wollte ich nicht einfach reinpfuschen.
