### ISSUE TITLE
[ch.suedhang.apps.bscl_anq] :: BSCL - open issues

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#25]
- [ ]  Hilfetext auf beiden Seiten

**Comment by ottigerb** [comment]
Info's bzgl.: Normstichprobe / Klinikstichporbe:  https://github.com/Optinomic/apps/issues/6

**Comment by ottigerb** [comment]
## EAS oder EP

### EAS
- Eintritt in:  1 Entzugsbehandlung
- Austritt aus:  1 Entzugsbehandlung
- Messzeitpunkt:  3 Übertritt in die Entwöhnungsbehandlung

### EP
- Eintritt in:  2 Entwöhnungsbehandlung
- Austritt aus:  2 Entwöhnungsbehandlung
- Messzeitpunkt:  3 Übertritt in die Entwöhnungsbehandlung


## Eintritt oder Austritt

### Eintritt 
- Messzeitpunkt:  1 Eintritt
- Messzeitpunkt:  3 Übertritt in die Entwöhnungsbehandlung

### Austritt 
- Messzeitpunkt:  2 Austritt
- Messzeitpunkt:  3 Übertritt in die Entwöhnungsbehandlung

**Comment by schoenenb** [comment]
Das führt zur folgenden "Kombi-Dimension" bestehend aus den 3 Variablen

Messzeitpunkt: q501V04 (1 = Eintritt / 2 = Austritt / 3 = Übertritt)

Eintritt in: Eintrittsort (1 = EAS / 2 = EP)

Austritt aus: Austrittsort (1 = EAS / 2 = EP)

mit den folgenden 4 Ausprägungen / Gruppen:
- Eintritt EAS (q501V04 = 1 + Eintrittsort = 1)
- Austritt EAS (q501V04 = 2 + Austrittsort = 1 oder q501V04 = 3)
- Eintritt EP (q501V04 = 1 + Eintrittsort = 2 oder q501V04 = 3)
- Austritt EP (q501V04 = 2 + Austrittsort = 2)

**Comment by ottigerb** [comment]
Wir haben ja folgende Tabelle um die Z-Scores zu berechnen:

![](https://cloud.githubusercontent.com/assets/20124244/19923840/9d06e356-a0e9-11e6-8a36-4c7398e0d0b6.png)


#### Fragen
Psychotizismus = ISOL?
=> Stimmt folgende Übersetzung:  
  


```JS
        calc.score_answer = [{
            "scale": 0,
            "description": "GSI (Global Severity Index)",
            "description_short": "GSI",
            "result": calc.cloneObj(calc.variables)
        }, {
            "scale": 1,
            "description": "Psychotizismus",
            "description_short": "ISOL",
            "result": calc.cloneObj(calc.variables)
        }, {
            "scale": 2,
            "description": "Paranoides Denken",
            "description_short": "PARA",
            "result": calc.cloneObj(calc.variables)
        }, {
            "scale": 3,
            "description": "Phobische Angst",
            "description_short": "PHOB",
            "result": calc.cloneObj(calc.variables)
        }, {
            "scale": 4,
            "description": "Aggressivität/ Feindseligkeit",
            "description_short": "AGGR",
            "result": calc.cloneObj(calc.variables)
        }, {
            "scale": 5,
            "description": "Ängstlichkeit",
            "description_short": "ANGS",
            "result": calc.cloneObj(calc.variables)
        }, {
            "scale": 6,
            "description": "Depressivität",
            "description_short": "DEPR",
            "result": calc.cloneObj(calc.variables)
        }, {
            "scale": 7,
            "description": "Unsicherheit im Sozialkontakt",
            "description_short": "UNSI",
            "result": calc.cloneObj(calc.variables)
        }, {
            "scale": 8,
            "description": "Zwanghaftigkeit",
            "description_short": "ZWAN",
            "result": calc.cloneObj(calc.variables)
        }, {
            "scale": 9,
            "description": "Somatisierung",
            "description_short": "SOMA",
            "result": calc.cloneObj(calc.variables)
        }];
```

**Comment by ottigerb** [comment]
Ich bin bezüglich der **Tabelle 22** etwas verwirrt:

Beispiel:  Ein Mann  hat z.B. beim  GSI einen:  sum_score=100 / scale_score: 1.8867
Mean und SD ist gemäss Tabelle: `0.28, 0.23` 

Wie wird nun Z-Score berechnet / resp. was ist x (sum.. oder scale_score) ?

```
(x - mean) / standard_deviation;
```
Daraus würde sich ein Z-Score von   433.56 resp. 6.98 ergeben, was mir etwas 'spanisch' vorkommt.

 Ist diese **Tabelle 22** korrekt oder verstehe ich hier was falsch?  Danke für Eure Aufklärung.

**Comment by ottigerb** [comment]
Zudem haben wir eine Variable `Zusatz` in der bisherigen Berechnung:

```
Zusatz = parseInt(result['BSCL[sq504V11]']) + parseInt(result['BSCL[sq504V25]']) + parseInt(result['BSCL[sq504V39]']) + parseInt(result['BSCL[sq504V52]']);
```
=>  Ist dies noch nötig?  Welche Skala wäre dies in der **Tabelle 22**?

**Comment by SonjaKaufmann** [comment]
Der BSCL hat die beschriebenen Skalen. Neben dem gibt es noch einige Items die nur im GSI mit einbezogen werden: die Zusatzitems. Wenn man den GSI berechnet so wird er aus der Summe der Skalenwerte gebildet, inklusive der Zusatzitems. Um dann den Mean zu erhalten muss man noch durch die Anzahl der Items teilen und das sind 53.  Allerdings findet bei Summe durch 53 werden quasi die fehlenden Werte nicht ersetzt, wie wenn man im SPSS den mean der Skala berechnen lässt und dann mit der Anzahl der Items der Skala multipliziert. Daher wird dies in der Regel auch so für die Skalen bemacht und dann daraus inklusive der Zusatzitems-Skala eine Gesamtskala addiert und durch die Anzahl der Gesamtitems geteilt.

Also das x ist der scale_score. Und somit wäre dies ein sehr belasteter Patient mit einem Z-Wert von 6.98. Kann beim SCL durchaus vorkommen.

Ich habe schon gemerkt, dass ich bei den Skalenberechnungen für die Klinischen Stichproben in SPSS gemacht habe, aufpassen musste, das ich mit dem Skalenmean/Anzahl Items der Skala rechne und nicht mit den Skalenmean-Rohwerten. Denn die Normen beziehen sich auf die Skalenmittelwerte!

Wenn unklar, dann frag bitte nochmal nach!

**Comment by SonjaKaufmann** [comment]
Ich weiss nicht wie die Ersetzung fehlender Werte in Optinomic funktioniert, bzw. da kann man ja gar nicht speichern wenn noch eine Angabe fehlt, dann kann man sicher einfach die Summe nehmen und durch die Anzahl der Skalenitems teilen.

**Comment by ottigerb** [comment]
### Danke!  
- Zusatzitems habe ich nun verstanden!  
- Z-Score also aus `scale_score` berechnen!


###  Welche Skala 

Psychotizismus = ISOL in der Tabelle?

```
{
            "scale": 1,
            "description": "Psychotizismus",
            "description_short": "ISOL",
            "result": calc.cloneObj(calc.variables)
        }
```

###  53 Items
Diesbezüglich bitte ich Euch noch um folgende Überprüfung:   Wo ist hier der Fehler

```
            myResults.sum_scores = {};
            myResults.sum_scores.aggr = parseInt(result['BSCL[sq504V06]']) + parseInt(result['BSCL[sq504V13]']) + parseInt(result['BSCL[sq504V40]']) + parseInt(result['BSCL[sq504V41]']) + parseInt(result['BSCL[sq504V46]']);
            myResults.sum_scores.angst = parseInt(result['BSCL[sq504V01]']) + parseInt(result['BSCL[sq504V12]']) + parseInt(result['BSCL[sq504V19]']) + parseInt(result['BSCL[sq504V38]']) + parseInt(result['BSCL[sq504V45]']) + parseInt(result['BSCL[sq504V49]']);
            myResults.sum_scores.depr = parseInt(result['BSCL[sq504V09]']) + parseInt(result['BSCL[sq504V16]']) + parseInt(result['BSCL[sq504V17]']) + parseInt(result['BSCL[sq504V18]']) + parseInt(result['BSCL[sq504V35]']) + parseInt(result['BSCL[sq504V50]']);
            myResults.sum_scores.paranoid = parseInt(result['BSCL[sq504V04]']) + parseInt(result['BSCL[sq504V10]']) + parseInt(result['BSCL[sq504V24]']) + parseInt(result['BSCL[sq504V48]']) + parseInt(result['BSCL[sq504V51]']);
            myResults.sum_scores.phobisch = parseInt(result['BSCL[sq504V08]']) + parseInt(result['BSCL[sq504V28]']) + parseInt(result['BSCL[sq504V31]']) + parseInt(result['BSCL[sq504V43]']) + parseInt(result['BSCL[sq504V47]']);
            myResults.sum_scores.psychot = parseInt(result['BSCL[sq504V03]']) + parseInt(result['BSCL[sq504V14]']) + parseInt(result['BSCL[sq504V34]']) + parseInt(result['BSCL[sq504V44]']) + parseInt(result['BSCL[sq504V53]']);
            myResults.sum_scores.somat = parseInt(result['BSCL[sq504V02]']) + parseInt(result['BSCL[sq504V23]']) + parseInt(result['BSCL[sq504V29]']) + parseInt(result['BSCL[sq504V30]']) + parseInt(result['BSCL[sq504V33]']) + parseInt(result['BSCL[sq504V37]']);
            myResults.sum_scores.soz = parseInt(result['BSCL[sq504V20]']) + parseInt(result['BSCL[sq504V21]']) + parseInt(result['BSCL[sq504V22]']) + parseInt(result['BSCL[sq504V42]']);
            myResults.sum_scores.zwang = parseInt(result['BSCL[sq504V05]']) + parseInt(result['BSCL[sq504V15]']) + parseInt(result['BSCL[sq504V26]']) + parseInt(result['BSCL[sq504V27]']) + parseInt(result['BSCL[sq504V32]']) + parseInt(result['BSCL[sq504V36]']);
            myResults.sum_scores.zusatz = parseInt(result['BSCL[sq504V11]']) + parseInt(result['BSCL[sq504V25]']) + parseInt(result['BSCL[sq504V39]']) + parseInt(result['BSCL[sq504V52]']);

            myResults.scale_scores = {};
            myResults.scale_scores.aggr = parseFloat(myResults.sum_scores.aggr / 5);
            myResults.scale_scores.angst = parseFloat(myResults.sum_scores.angst / 6);
            myResults.scale_scores.depr = parseFloat(myResults.sum_scores.depr / 6);
            myResults.scale_scores.paranoid = parseFloat(myResults.sum_scores.paranoid / 5);
            myResults.scale_scores.phobisch = parseFloat(myResults.sum_scores.phobisch / 5);
            myResults.scale_scores.psychot = parseFloat(myResults.sum_scores.psychot / 5);
            myResults.scale_scores.somat = parseFloat(myResults.sum_scores.somat / 7);
            myResults.scale_scores.soz = parseFloat(myResults.sum_scores.soz / 4);
            myResults.scale_scores.zwang = parseFloat(myResults.sum_scores.zwang / 6);
            myResults.scale_scores.zusatz = parseFloat(myResults.sum_scores.zusatz / 4);
```

=>  Da scheint noch ein Fehler zu sein:  Beispiel `myResults.sum_scores.somat` sind nur 6 Items es wird jedoch `/7` gerechnet.  Hmmm...  Fehlt hier bei der Berechnung ein Item?

**Comment by ottigerb** [comment]
Hmm... ich wiederhole mich:  Ich traue dieser **Tabelle 22** nicht. Ist diese gesichert?

Beispiel: 

![bildschirmfoto 2016-11-21 um 18 12 48](https://cloud.githubusercontent.com/assets/2470873/20492728/313bf01c-b016-11e6-8613-bc28c6f8c958.png)

=>  Es kann doch nicht sein, dass der `T-Score = 80` ist und der `Z-Score = 7.22`.  Oder doch?


Beim Suchen bin ich auf folgende Ressourcen gestossen:
- https://www.unifr.ch/ztd/HTS/inftest/WEB-Informationssystem/de/4de001/d8f0aaf1d7844fb6865f10e3023ffcfd/hb.htm
- http://www.unifr.ch/ztd/HTS/inftest/WEB-Informationssystem/de/4de001/e0a6bb92a0554a238eda784bf8e02b0a.pdf

**Comment by ottigerb** [comment]
@schoenenb  Zu Deiner "Kombi-Dimension" https://github.com/Optinomic/apps/issues/25#issuecomment-261520783:  
Falls `q501V04 = 3` könnte es sowohl **Austritt EAS**  als auch **Eintritt EP** sein. Oder? 
Falls ja:  Nicht gut ->  Wir müssen hier 'eindeutig' bleiben!  Allenfalls Fragebogen überarbeiten.

**Comment by SonjaKaufmann** [comment]
Die Formel für die Berechnung der Skala Somatisierung ist folgende:
Skalenwert Somatisierung:
BSCL 02  + **BSCL 07**  + BSCL 23  + BSCL 29  + BSCL 30  + BSCL 33  + BSCL 37 / 7
Da ist wohl ein Item verloren gegangen.

Bzgl. der Normwerte: Ich werde dem nachgehen. Aber man muss aufpassen, denn wir verwenden eigentlich nicht den SCL-90, denn der hat 90 Items, sondern den BSI (Brief Symptom Index) den der ANQ aus irgendeinem Grund nicht so nennt, sondern den Titel BSCL verwendet. Daher braucht man die Normen des BSI oder BSCL und das sind die die ich gesendet habe, also Tabelle 22. Aber ich prüfe das noch weiter! Brauch dafür aber ein wenig Ruhe und Hirnschmalz ;-)

**Comment by ottigerb** [comment]
... Danke und gutes Gelingen!

Am 22.11.2016 08:26 schrieb "SonjaKaufmann" notifications@github.com:

**Comment by SonjaKaufmann** [comment]
Die Tabelle 22 ist die richtige. 
Am einfachsten ist es aber, wenn ich konkrete Beispiele zur Prüfung nachrechnen kann. Hast Du Beispielfälle mit der FID und MZP und dem errechneten Z-Wert?

**Comment by ottigerb** [comment]
Meine 'Berechnung' ist noch nirgends integriert. Ich kann heute Nachmittag an Optinomic arbeiten.  

Anbei der Export des BSCL - zur Beispielberechnung: 
[bscl_export.xlsx](https://github.com/Optinomic/apps/files/610973/bscl_export.xlsx)

#### Fragen:
- Psychotizismus = ISOL in der Tabelle?  


- Z-Scores 

Für mich wirkt es so als hätten wir eine andere Norm für die T-Score Berechnung genommen. Diese stammt m.W. von Katrin Schläfli.  Gemäss folgender Tabelle müsste doch ein T-Score von 80 ein Z-Score von +3 ergeben. Nicht wie in meinem Beispiel https://github.com/Optinomic/apps/issues/25#issuecomment-262006835 ein 7.2.  

![normal_distribution_and_scales](https://cloud.githubusercontent.com/assets/2470873/20594523/d8eb2a54-b236-11e6-9d3f-08ba1ea61631.gif)

=>  Können wir nicht per einfachem 3-Satz  T-Score in Z-Werte umrechnen?  Sind wir 'Normalverteilt'?  Da wir grösser n = >30 => Ja, oder?

**Comment by schoenenb** [comment]
> @schoenenb Zu Deiner "Kombi-Dimension" #25 (comment):
Falls q501V04 = 3 könnte es sowohl Austritt EAS als auch Eintritt EP sein. Oder?
Falls ja: Nicht gut -> Wir müssen hier 'eindeutig' bleiben! Allenfalls Fragebogen überarbeiten. <

@ottigerb Ja, das ist so. Weil es sich um eine Verlaufsmessung handelt, die zum Zeitpunkt Austritt EAS bzw. Eintritt EP stattfindet. Ich sehe nicht ganz, wo das Problem liegt. Kann der Wert so nicht in die Berechnung der Vergleichsstichprobe aufgenommen werden? Kann in der Anzeige keine Vergleichsstichprobe dargestellt werden, weil die Zuteilung nicht eindeutig ist?

**Comment by schoenenb** [comment]
> Psychotizismus = ISOL in der Tabelle?

```
{
            "scale": 1,
            "description": "Psychotizismus",
            "description_short": "ISOL",
            "result": calc.cloneObj(calc.variables)
        }
```
eher description_short = PSYCH

**Comment by ottigerb** [comment]
=> PSYCH gibt es in der Tabelle 22 nicht.

**Comment by schoenenb** [comment]
Ah DARUM ging es! Ja, die Werte von ISOL müssten dann wohl dem Psychotizismus zugewiesen werden.

**Comment by schoenenb** [comment]
> => Es kann doch nicht sein, dass der T-Score = 80 ist und der Z-Score = 7.22. Oder doch?

Ja, das geht. Weil die T-Wert-Darstellung nur von 20-80 geht, also Mean +-3SD; alles was über z = 3 hinausgeht entspricht T = 80 nach unten gibt's kaum T-Werte < 40, weil fast nur Werte bis z = -1 erreicht werden können (siehe folgendes)

> => Können wir nicht per einfachem 3-Satz T-Score in Z-Werte umrechnen? Sind wir 'Normalverteilt'? Da wir grösser n = >30 => Ja, oder?

Die Normdaten sind eher nicht normalverteilt:

- die SD ist teilweise grösser / gleich dem Mean

- mit den kleinen Werten (<1) ist Mean - 1 SD oftmals < 0

-  der Fragebogen kann keine Werte < 0 annehmen, weil der kleinste zu vergebende Wert 0 ist.

Eine Umrechnung von z- in T-Werte wäre z-Wert*10 + 50, wobei eben der Maximalwert 80 ist.

**Comment by schoenenb** [comment]
[01 Beschriftung BSCL.docx](https://github.com/Optinomic/apps/files/627052/01.Beschriftung.BSCL.docx)

**Comment by schoenenb** [comment]
- [ ] Unterhalb der Grafikdarstellung der z-Werte sollten noch die Zusatzitems, welche einen Wert > 0 haben, mit Angabe der Intensität erscheinen (1 = ein wenig, 2 = ziemlich, 3 = stark, 4 = sehr stark).

**Comment by schoenenb** [comment]
- [ ] Für den Eintrittsbericht Darstellung von Ein- & Übertritt, falls Fall = EAS+EP

**Comment by schoenenb** [comment]
Minimal-/Maximalwerte der z-Werte-Darstellung: -1.35 bis 16.05
- SOMA: -0.844 - 11.656
- ZWAN: -1.181 - 7.909
- UNSI: -0.977 - 8.326
- DEPR: -0.757 - 10.054
- ANGS: -1 - 10.765
- AGGR: -0.971 - 10.794
- PHOB: -0.625 - 16.042
- PARA: -0.872 - 9.385
- ISOL: -0.679 - 13.607
- GSI: -1.348 - 16.043

**Comment by ottigerb** [comment]
Daaanke!  Unglaublich hohe Maximalwerte.   :-)

Z-Werte beim BSCL habe ich mal 'zurückgestellt' - verstehe ein Error nicht, den ich habe - mach doch alles gleich wie beim ISK:  Hmm...

**Comment by schoenenb** [comment]
Die Maximalwerte sind einfach, wenn jemand bei allen Items der Skala 4 angeben (habe ich so noch nie gesehen).
Weil sie aber tatsächlich so hoch sind, müssten wir uns ev. überlegen, ob wir z.B. nur bis 10 gehen, oder bis zu +1SD (+0.5) der Vergleichsstichprobe und dann halt nur die Wertangabe den genauen Wert darstellt.

**Comment by schoenenb** [comment]
Austritts-Vergleichsstichprobe (Patienten) wird nicht mehr angezeigt?!

**Comment by ottigerb** [comment]
...genau:  Dies ist aufgrund der 'nicht migrierten BSCL' Daten in der Demo-Umgebung.

**Comment by schoenenb** [comment]
macht Sinn :)

**Comment by ottigerb** [comment]
**Zusatzitems** sind wie folgt umgesetzt:

![bildschirmfoto 2016-12-28 um 15 51 22](https://cloud.githubusercontent.com/assets/2470873/21524332/9cd2a548-cd15-11e6-9636-15c7bffe780c.png)

**Comment by schoenenb** [comment]
- [ ] Angaben zur Normstichprobe - Autor(en)? (Franke 2000?)

**Comment by ottigerb** [comment]
Close issue :: Ich erkenne keine offenen Punkte.
