### ISSUE TITLE
[ch.suedhang.apps.isk] :: ISK - open issues

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#26]
- [x] Legende / Interpretation anpassen

**Comment by schoenenb** [comment]
...zu viel Text (v.a. bei geringer Ausprägung) --> Text oder Zeilenbreite anpassen

**Comment by SonjaKaufmann** [comment]
Hier ist das folgende Blatt die Idee wie es aussehen soll und wie beschriftet sein.
[ISK_Skizze.pdf](https://github.com/Optinomic/apps/files/589039/ISK_Skizze.pdf)
Also es soll eine Einteilung geben in 4 Unterblöcke und dazu die Unterüberschriften, die den Zielbereich beschreiben.

**Comment by SonjaKaufmann** [comment]
Bezüglich der Normen müssen wir noch suchen. Leider, aber kommen asap!

**Comment by schoenenb** [comment]
![image](https://cloud.githubusercontent.com/assets/15833792/20618357/d4dce714-b2ee-11e6-9552-9f3d79a741b0.png)

**Comment by schoenenb** [comment]
- [x] Legende oberhalb Grafik weg

- [x] Angabe ober-/unterhalb Grafik: Stanine

- [x] Zahlen kleiner darstellen (max. Grösse wie Datum)

ev. müssen wir den Text dann noch überarbeiten

**Comment by ottigerb** [comment]
Überarbeitung vorgenommen.  Wirkt m.E. übersichtlicher als die "X-Darstellung". 

![bildschirmfoto 2016-11-25 um 10 36 38](https://cloud.githubusercontent.com/assets/2470873/20620677/223cfe84-b2fb-11e6-9540-5d9ed80f0920.png)


=> Kann dieses Issue geschlossen werden?

**Comment by SonjaKaufmann** [comment]
- [x] Nein, denn es sollen wie in der Skizze beide Seiten beschriftet sein. Sonst müssen wir sie für die Z-Darstellung ja nochmal ändern. Ich dachte eigentlich wir hätten uns auf einen Graphiktyp geeinigt und zwar auf die Balkengraphik mit rechts und links Platz für Beschriftung. 

- [x] Die Zahlen in der Graphik klein darstellen, wie Stanine oder Datum

**Comment by ottigerb** [comment]
Dachte wir zeigen direkt die Interpretation an. Na ja.

Die Anpassung 'beide Seiten' beschriften kann leicht vorgenommen werden. Ich werde somit analog dieser Grafik https://github.com/Optinomic/apps/issues/27#issuecomment-262956373 vorgehen. OK?

Die Zahlen in der Grafik:  Wurde bereits verkleinert.  Zu klein, darf diese Zahl jedoch auch nicht werden, da sich die Zahl/Text innerhalb der Grafik je nach Platz 'verzieht'.

**Comment by ottigerb** [comment]
Änderungen gemäss PDF von Sonja übernommen:

http://demo.optinomic.org/api/#/patient/1120/stay/1008/app/ch.suedhang.apps.isk

![bildschirmfoto 2016-11-28 um 11 54 57](https://cloud.githubusercontent.com/assets/2470873/20665866/a425c49a-b561-11e6-9c2a-47192600cbbe.png)

**Comment by SonjaKaufmann** [comment]
-Ja das kann ich verstehen mit der Interpretation und für einen Text finde ich dies auch sinnvoll. Wenn der Therapeut dem Patienten die Auswertung erklären soll, dann sollte er aber Erklärungsspielraum haben und den Gegenpol erklären können.
- Merci hast Du es nochmal und so schnell geändert. Sehr gut sind jetzt nur noch die Stanine oben angegeben.
- Kannst Du das Eintritt/Austritt mit Datum noch vom Text absetzen und den Summenwert auf der rechten Seite rausnehmen? 
- Meinetwegen müsste dann beim Austritt der Text gar nicht wiederholt werden, da er ja nicht ändert könnte man ja beim Eintritt lesen. Wäre doch einfacher und platzsparend, oder?
Zu den Zahlen: Ich finde einfach sie lenken das Auge auf das Falsche, denn der Wert steht ja schon oben angeschrieben und man muss ihn gar nicht nochmal lesen. Es soll eher ein Augenmerk darauf gerichtet werden wo liegt der Patient in der Verteilung oder dem Vergleich.

**Comment by SonjaKaufmann** [comment]
Hier sind die Normen und Berechnungsformeln für den ISK! Auf zu schönen Z-Werten :-)
[Normen ISK_Handbuch.pdf](https://github.com/Optinomic/apps/files/619240/Normen.ISK_Handbuch.pdf)
Vielen Dank Nora!

**Comment by ottigerb** [comment]
### Z-Score Darstellung ist umgesetzt:   **:-)**

Für mich ist die Darstellung so gelungen: Keine Wiederholungen vom Text | Messungen sortiert etc.

![bildschirmfoto 2016-12-04 um 11 43 50](https://cloud.githubusercontent.com/assets/2470873/20865601/1ce18c2a-ba17-11e6-9ffb-ce995c508686.png)

Beispiel:
http://demo.optinomic.org/api/#/patient/1144/stay/587/app/ch.suedhang.apps.isk



- [ ] Prüfen & Issue Schliessen!

**Comment by SonjaKaufmann** [comment]
Ich finde es super klappt das mit den Z-Werten.

Die Lösung mit den "Überschriften" gefällt mir nicht. Sorry wenn ich immer als Motzi daher komme, doch mir sind die Graphiken und die einfache Lesbarkeit für Patienten halt sehr wichtig. Der Text sollte neben die Graphik wie beim SCI und auch so wie es beim BSCL angedacht ist. Dafür kann auch die Graphik ruhig gestaucht werden. Anscheinend ist dies aber schwierig wegen den Wiederholungen. Aber wenn wir den Graphikoutlook möglichst einheitlich halten wollen, dann ist dies auch keine Lösung, denn spätestens beim BSCL geht es so nicht auf oder bei jeder Skala muss die Graphik getrennt werden und es wird endlos lang. Ich finde der SCI (auch wenn noch nicht als Z-Graphik, weil seine Zukunft sonst noch unklar) ist eher die Vorlage. Mir sind dann Wiederholungen weniger wichtig, als eine kompakte und einheitliche Darstellung. Wenn es nicht geht "nur bei Eintritt" den Seitentext anzuzeigen und bei Eintritt und Austritt den ausführlichen Text nur beim Eintritt und somit die Wiederholung direkt untereinander zu vermeiden, dann soll sich der Text halt wiederholen. 
Es ist mir klar, dass der ISK spezieller ist als die anderen Bögen, weil es auch die Beschreibung des Zielbereiches, also des mittleren Bereiches braucht und dies ja in der neuen Skalenuntertiteln drin steckt. Aber ansonsten sollte die Graphik von der Einteilung aufgebaut sein wie beim SCI und so auch der BSCL. Quasi bestehen aus Platz für Beschriftung rechts, Graphikteil und Platz für Skalenbeschriftung links. Auch wenn beim BSCL nur die rechte Seite Text enthalten wird, so kann links der Skalentitel rein. Generell bräucht es dann wie beim SCI nur einmal die (z-)Wert-Skalierung und die auch nur oben. Und um welchen Messzeitpunkt es sind handelt, das kann über die Graphik und wird ja auch schon durch den Hintergrund der klinischen Stichprobe angegeben. Ich mache mal eine Skizze für den "generellen Graphikaufbau.

**Comment by ottigerb** [comment]
...Danke für Deine Skizze & Überlegungen.   Dein 'Motzi' ist durchaus willkommen - schliesslich wollen wir 'tolle Optinomic-Apps!'  :-)    Nur zur Info: Ich hatte mit 'Text links/rechts' experimentiert und war unglücklich damit - wirkte sehr 'gestaucht' und irgendwie überladen.   Anyway:  Solche 'Anpassungen' können wir dann laufend anpassen/verbessern.  :-)    Frohes Schaffen!

**Comment by SonjaKaufmann** [comment]
[Generelle Graphikskizze.pdf](https://github.com/Optinomic/apps/files/630624/Generelle.Graphikskizze.pdf)

Merci dass der Kern von Motzi verstanden und willkommen geheissen wird :-)
Wünsche auch frohes Schaffen. 

Ich denke wenn es zu komisch und schwierig ist, die Messzeitpunkte zu mischen (Streifenhörnchen-Version), dann müssen wir die Austrittsmessung vielleicht doch nochmal als separate Graphik überlegen und dann muss bei Austritt halt beides untereinander drauf. Dann haben wir kein Streifenhörnchen mehr und es braucht mehr Platz, aber die Option ist auch nicht ausgeschlossen für mich. Für die Lesbarkeit bzw. Interpretation würde ich das Streifenhörnchen aber nach wie vor vorziehen.

**Comment by schoenenb** [comment]
![image](https://cloud.githubusercontent.com/assets/15833792/22818758/180b6b5c-ef6f-11e6-844e-6d01516bd43e.png)
Stimmt die Beschriftung nun, oder müsste noch was angepasst werden? (Kompromisslosigkeit)

**Comment by SonjaKaufmann** [comment]
Mhhhh, muss ich noch googlen, habe es im Manual nicht finden können, weil dort die Kurzform nicht so genau beschrieben ist. Melde mich nochmal.

**Comment by SonjaKaufmann** [comment]
Also, die Kompromisslosigkeit ist dort  falsch. Leider finde ich nirgendwo Beschreibungen der Skalen des ISK-K. Falls Du noch was in Unterlagen findest, dann sag mir bitte Bescheid. 
Auf jeden Fall gehört die Kompromisslosigkeit auf die andere Seite, auf der Rechten Seite ist eher "zu schnelle Kompromissbereitschaft" und "andere mehr beachten als sich selber".

Ich weiss auch nicht mehr wo die Skalenbeschreibungen her waren, denn in den Manualen waren eher die Langformen beschrieben. Falls Du noch einen Text zum ISK-K findest mit Skalenbeschreibungen wäre ich noch so froh.

**Comment by schoenenb** [comment]
Ich glaube für die Kurzform gelten einfach nur die Beschreibungen der "Oberkategorien", für die weiteren Subskalen der Vollversion gäbe es noch detailliertere Beschreibungen..
