### ISSUE TITLE
[ch.suedhang.apps.sci] :: SCI - open issues

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#27]
- [x] Einrücken des Hilfstexts "wenig" bzw. "viel/ausgeprägt"

- [x] Zusatztext anpassen?

**Comment by SonjaKaufmann** [comment]
Sorry, hier stimmt die Beschriftung noch nicht ganz, was an meinen verwirrenden Vorgaben liegt. Ich hänge nochmal die Seite an, wo die richtige Beschriftung dargestellt ist!
[02 SCI_neu.pdf](https://github.com/Optinomic/apps/files/589001/02.SCI_neu.pdf)

Da wir Wenig und viel/Ausgeprägt jetzt schon drin haben, können natürlich die Bewertungen im Text an den Seiten noch weggekürzt werden , sprich die Gut und die Ungünstig können weggelassen werden.
Und die Überschrift des ersten Blocks ist nicht Verlust sondern negative Ereignisse. 
Es fehlen auch noch die kurzen Texte zu den günstigen und der ungünstigen Strategie.

Zudem sollte der Text unten drunter erstmal noch weggelassen werden. Die Textauswertung soll doch nach Einführung V2 erst kommen.

**Comment by schoenenb** [comment]
Textanpassungen
- [x] Überschrift 1. Item "Stress durch negative Ereignisse"
- [x] Text anhand Vorlage "02 SCI_neu.pdf"
- [x] gut / ungünstig wegstreichen

Textauswertung
- [x] ausschalten

**Comment by schoenenb** [comment]
![image](https://cloud.githubusercontent.com/assets/15833792/20431090/6ac5fdee-ad98-11e6-91c1-2d15cefac036.png)

**Comment by schoenenb** [comment]
![image](https://cloud.githubusercontent.com/assets/15833792/20431110/8741f194-ad98-11e6-971b-426b7ad3d238.png)

**Comment by SonjaKaufmann** [comment]
Beim 2. und 3. Baustein ist das Wenig und Viel/Ausgeprägt wieder weiter nach oben gerutscht. Es sollte so sein wie im ersten Block neben Statnine.
Sonst sieht es super aus!
Ich frage mich noch wie die Austrittswerte dann abgebildet werden, denn es wäre sinnvoll sie in der gleichen Graphik anzuzeigen. Wahrscheinlich wären dies dann Kreuze in einer anderen Farbe?

**Comment by schoenenb** [comment]
1. Abwarten, was ThL dazu meint
2. Grafik anpassen: Austritts-Kreuze in gleicher Grafik möglich? (z.B. weiss / kleinere Kreuze)
3. für Austritts-Bericht weglassen, nur bei Eintritt anzeigen

**Comment by ottigerb** [comment]
1. ThL = Wer ist das?
2. Möglich ist grundsätzlich alles - doch diese `Stanine` Darstellung soll ja nicht mehr weiter verwendet werden. Entsprechend ungern passe ich diese an.
3. Was wenn beide Kreuze im gleichen Feld liegen?

**Comment by SonjaKaufmann** [comment]
Lieber Beat, 
sorry das war erstmal eine Gedankenstütze für uns und gar nicht an Dich gerichtet. 
Es ist noch unklar, ob wir den SCI weiter verwenden wollen, da er uns kaum Informationen liefert. Leider! Das kläre ich gerade mit der Therapieleitung und das dauert noch einen kleinen Moment. Wenn wir ihn weiter verwenden, dann müssten wir nämlich die Auswertung für 650 Euro kaufen, denn sonst kommen wir nicht an die Normwerte. Und da dies noch unklar ist, wollten wir ihn erstmal noch so drin lassen wie er jetzt im Moment ist, also mit den neuen Beschriftungen und Einteilungen, aber halt auf Staninebasis und ggf. erst später mit Z-Werten nachziehen. Das ist der aktuelle Stand. 
Also hier gerade nichts zu tun, bis ich mehr weiss.

**Comment by ottigerb** [comment]
Gemäss ISK:  **report_only** Version:   
=> Keine Karussell-Ansicht im Report:  http://demo.optinomic.org/api/#/patient/1120/stay/1008/report/print_ready

![bildschirmfoto 2016-11-25 um 14 19 13](https://cloud.githubusercontent.com/assets/2470873/20626471/41a7c12c-b31a-11e6-8a27-20681e34826b.png)

**Comment by schoenenb** [comment]
> Also hier gerade nichts zu tun, bis ich mehr weiss.

Wurde das mal fertig besprochen?

**Comment by schoenenb** [comment]
Sonja: Nein, bisher nicht.

- [x] Grafische Darstellung innerhalb App und für den Bericht so wie im letzten Beispiel (Balken, statt X-Tabelle).

**Comment by ottigerb** [comment]
Was heisst das:

> Grafische Darstellung innerhalb App und für den Bericht so wie im letzten Beispiel (Balken, statt X-Tabelle).

**Comment by schoenenb** [comment]
Das sollte heissen, dass auch in der App die Anzeige wie im Bericht sein soll, also deine neue Darstellungsversion für print_ready - ich weiss leider nicht, wie man einzelne Comments verlinkt..

**Comment by schoenenb** [comment]
- [x] Summenzeichen entfernen
- [x] Umlaute wieder anzeigen

**Comment by SonjaKaufmann** [comment]
Es hat sich nur ein kleiner Fehler eingeschlichen und zwar beim SCI. Dieser zeigt in der Graphik nicht die richtige Skala „Alkohol und Zigarettenkonsum“ unter den ungünstigen Strategien an, sondern wiederholt die Hilfreichen Copingskalen. Im Bericht ist allerdings alles richtig drin. Nehme an dies ist ein easy fix.

**Comment by ottigerb** [comment]
> **Ungünstige Copingstrategie**
> Diese erhöht oder verlängert die möglichen körperlichen und psychischen Stressreaktionen, welche nicht gesund sind. Hohe Ausprägungen sind nicht günstig. (...)

=>  Wird nun wieder dargestellt.

Weitere Fixes:
=>  Auch sind Umlaute drin und die Summenangabe entfernt.


Ich schliesse dieses Issue.  Falls noch was auftaucht - Reopen!  :-)
