### ISSUE TITLE
Funktionalität von Optinomic 2.0

### ISSUE THREAD

**Issue by HansaYohaku** [Optinomic/apps#28]
Hoi zusammen, 
ich versuche hier gerade die Funktionalität von Optinomic 2.0 schmackhaft zu machen:

1.	Alle Fragebögen sind vorhanden, fehlerfrei und ergonomisch (gute Lesbarkeit) aufbereitet
2.	Flexible und schnelle Erstellung (innerhalb weniger Stunden) neuer Fragebögen möglich
3.	Zwischen den einzelnen Fragen sind Bedingungsabfragen möglich: Wenn Frage x mit „Ja“ und Frage y mit „Nein“ beantwortet wurde, starte Fragebogen xy
4.	Für alle Fragebögen, die ausgefüllt werden, existieren Normierungen
5.	Alle Fragebögen liefern instantan eine grafische Auswertung (zB psychisches Profil), Patienten können sofort sehen, was bei der Messung herauskommt
6.	Exportfunktion: Es lassen sich beliebige Teile oder ganze Fragebögen aus der Datenbank in mehrere gängige Formate exportieren (Excel, .csv, tab- oder pipe-delimited txt, SPSS usw.)
7.	Die Fragebögen lassen sich in Gruppen zusammenfassen, zB ANQ-Gruppe, act-info-Gruppe, Entzugsgruppe, Entwöhnungsgruppe usw.
8.	Spezifische Exporte für jede Institution, zB GD will pipe-delimited, GD will tab-delimited
9.	Automatische Pop-up oder Erinnerungs-Funktion der Fragebögen: Sobald der Fragebogen fällig ist, poppt eine Nachricht auf und teilt dem Benutzer mit, welcher Fragebogen auszufüllen ist. Wird der Fragebogen nicht ausgefüllt, wird die Meldung intensiviert (Ampelfunktion: aus grün wird gelb wird rot)
10.	Es gibt eine „Controller“-funktion: Der Controller kann sofort sehen, welche Fragebögen fällig und noch nicht ausgefüllt sind.

Habt Ihr noch etwas zu ergänzen?
LG,
Hans

**Comment by ottigerb** [comment]
Ich liste einfach mal 'Funktionen' auf, welche m.E. interessant & noch nicht erwähnt sind:
- Rollenaufgaben 
- Merklisten / Patientenlisten
- Patientengruppen mit automatischer App Aktivierung/ Deaktivierung: Sicherstellung von Prozessen etc.
- Bald auch Behandlungsgruppen:  Analog Patientengruppen doch statt Patienten mit Merkmalen / Fälle mit Merkmalen.
- Berichte:  Zusammenfassungen von wichtigen Ergebnissen zur schnellen Übersicht
- Journalfunktionalität:  Zusammenzug von Ereignissen auf einer Timeline
- User-Apps:  Auswertungen nicht pro Patient sondern von Patientengruppen.
- Klinikstichproben:  Werte mit Klinikstichproben vergleichen.
- Export Toolbox:  Applikation / Zeitraum / Falltypen:

<img width="757" alt="bildschirmfoto 2016-11-09 um 14 03 36" src="https://cloud.githubusercontent.com/assets/2470873/20139243/6e88865a-a685-11e6-9d7e-c1f2640ff56f.png">

**Comment by SonjaKaufmann** [comment]
Ich ergänze auch noch:
- Bericht wird relativ einfach ausdruckbar, so dass die Zusammenfassung mit den Graphiken direkt mit dem Patienten ab Papier besprochen werden kann und ggf. mitgegeben. 
- Dazu mögliche Vereinheitlichung der Graphiken um diese leichter erklären zu können = leichterer Einbezug in Therapie möglich.
  -Vergleichbarkeit mit eigenen klinischen Normen in Form von Z-Wert Graphiken, wenn die Klinik genug Daten gesammelt hat oder alternativ ist auch das Eingeben anderer klinischer Stichprobenkennwerte möglich, z.B. aus Papern oder Kooperationen :-)
- Wirklich schöne Export-Toolbox für Joghurt-User (Bezeichnung von Sonja Stutz für Benutzer die nur einen Klick machen wollen und nicht in die Programmierung einsteigen).
- **zu Punkt 4 von Hans:** Das hängt natürlich davon ab, welche Fragebogen man programmiert, wenn man nur normierte Fragebogen auswählt, dann trifft dies zu. Wenn man aber andere will oder die Normen aufgrund von fehlenden Lizenzen nicht hat oder so, dann trifft dies natürlich nicht zu. Das ist quasi "up to the clinic"
- **zu Punkt 5 von Hans:** Auch das ist abhängig von der Klinik und beinhaltet Programmierarbeit. Es ist auf jeden Fall machbar mit Beat, aber nicht unaufwendig. Denn man muss ja festlegen wie die Graphik aussehen soll, was angeschrieben sein soll... Bei uns läuft das im Team mit Beat, der das dann auf Umsetztbarkeit prüft und auch die Hauptprogrammierung macht. Ich würde diesen Punkt aber nicht als so klar gegeben sehen, das hängt auch von Eurer vereinbarten Zusammenarbeit ab.

**Comment by ottigerb** [comment]
Close 
=>  Nothing to do here!
