### ISSUE TITLE
[ch.suedhang.apps.aase-g]  ::  AASE- Neue Graphik

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#29]
Hier müssen wir noch die neue Darstellung überlegen. Eventuell verwenden wir eine neue Fragebogen-Version -> Kurzform des alten Bogens. Müssen aber noch alles dazu suchen und festlegen.

**Comment by ottigerb** [comment]
Calculations von AASE-G  beinhaltet nun noch folgende Subcodes:
- negativer_affekt
- soziale_situationen
- somatisches_unwohlsein
- entzugserscheinungen

Dies lässt m.E. eine Interessante Übersicht / Reihenfolge zu, auf welche "Themen" besonders geachtet werden sollte.

Anbei der Code:

``` JS
            // Subscores - Info from:
            // https://books.google.ch/books?id=r0niDAAAQBAJ&pg=PA19&lpg=PA19&dq=AASE-G+diagnostik&source=bl&ots=Cnrm0EsN_2&sig=Ho5o3-EX6Ck5BkvTN5wew2-WQ2U&hl=de&sa=X&ved=0ahUKEwix3ca7i_TPAhUJMBoKHZ5vAicQ6AEIHDAA#v=onepage&q=AASE-G%20diagnostik&f=false
            // [Frage] Sollten es nicht je 5 Items sein?




            //  AASE3: Wenn ich mich traurig fühle
            //  AASE5: Wenn ich um jemanden besorgt bin
            //  AASE6: Wenn ich sehr beunruhigt bin und mir Sorgen mache
            //  AASE14: Wenn ich so frustriert bin, dass ich in die Luft gehen könnte
            //  AASE16: Wenn ich das Gefühl habe, dass bei mir alles schief läuft
            //  AASE18: Wenn ich ärgerlich bin
            var score_negativer_affekt = 0;
            score_negativer_affekt = score_negativer_affekt + parseInt(result['AASE[AASE3]']);
            score_negativer_affekt = score_negativer_affekt + parseInt(result['AASE[AASE5]']);
            score_negativer_affekt = score_negativer_affekt + parseInt(result['AASE[AASE6]']);
            score_negativer_affekt = score_negativer_affekt + parseInt(result['AASE[AASE14]']);
            score_negativer_affekt = score_negativer_affekt + parseInt(result['AASE[AASE16]']);
            score_negativer_affekt = score_negativer_affekt + parseInt(result['AASE[AASE18]']);
            myResults.score_negativer_affekt = calc.roundToOne(score_negativer_affekt);
            myResults.mean_negativer_affekt = calc.roundToOne(score_negativer_affekt / 6);




            //  AASE4: Wenn ich im Urlaub bin und mich entspannen möchte
            //  AASE8: Wenn ich in einer sozialen Situation ein alkoholisches Getränk angeboten bekomme
            //  AASE15: Wenn ich andere in einer Gaststätte oder bei einer Feier trinken sehe
            //  AASE17: Wenn Menschen, mit denen ich früher getrunken habe, mich zum Alkoholtrinken auffordern
            //  AASE20: Wenn ich voller Freude bin oder mit anderen feiere
            var score_soziale_situationen = 0;
            score_soziale_situationen = score_soziale_situationen + parseInt(result['AASE[AASE4]']);
            score_soziale_situationen = score_soziale_situationen + parseInt(result['AASE[AASE8]']);
            score_soziale_situationen = score_soziale_situationen + parseInt(result['AASE[AASE15]']);
            score_soziale_situationen = score_soziale_situationen + parseInt(result['AASE[AASE17]']);
            score_soziale_situationen = score_soziale_situationen + parseInt(result['AASE[AASE20]']);
            myResults.score_soziale_situationen = calc.roundToOne(score_soziale_situationen);
            myResults.mean_soziale_situationen = calc.roundToOne(score_soziale_situationen / 5);




            //  AASE2: Wenn ich Kopfschmerzen habe
            //  AASE12: Wenn ich körperlich erschöpft bin
            //  AASE13: Wenn ich körperliche Verletzungen oder Schmerzen habe
            var score_somatisches_unwohlsein = 0;
            score_somatisches_unwohlsein = score_somatisches_unwohlsein + parseInt(result['AASE[AASE2]']);
            score_somatisches_unwohlsein = score_somatisches_unwohlsein + parseInt(result['AASE[AASE12]']);
            score_somatisches_unwohlsein = score_somatisches_unwohlsein + parseInt(result['AASE[AASE13]']);
            myResults.score_somatisches_unwohlsein = calc.roundToOne(score_somatisches_unwohlsein);
            myResults.mean_somatisches_unwohlsein = calc.roundToOne(score_somatisches_unwohlsein / 3);




            //  AASE1: Wenn es mich quält, dass ich mit dem Trinken aufgehört habe oder Entzugserscheinungen habe
            //  AASE7: Wenn ich den Drang verspüre, nur ein einziges alkoholisches Getränk zu probieren, um zu sehen, was dann passiert
            //  AASE9: Wenn ich davon träume, ein alkoholisches Getränk zu mir zu nehmen
            //  AASE10: Wenn ich meine Willenskraft über das Trinken testen möchte
            //  AASE11: Wenn ich ein körperliches Bedürfnis oder ein starkes Verlangen nach Alkohol verspüre
            //  AASE19: Wenn mich ganz unerwartet das Verlangen oder der Drang trifft, etwas Alkoholisches zu trinken
            var score_entzugserscheinungen = 0;
            score_entzugserscheinungen = score_entzugserscheinungen + parseInt(result['AASE[AASE1]']);
            score_entzugserscheinungen = score_entzugserscheinungen + parseInt(result['AASE[AASE7]']);
            score_entzugserscheinungen = score_entzugserscheinungen + parseInt(result['AASE[AASE9]']);
            score_entzugserscheinungen = score_entzugserscheinungen + parseInt(result['AASE[AASE10]']);
            score_entzugserscheinungen = score_entzugserscheinungen + parseInt(result['AASE[AASE11]']);
            score_entzugserscheinungen = score_entzugserscheinungen + parseInt(result['AASE[AASE19]']);
            myResults.score_entzugserscheinungen = calc.roundToOne(score_entzugserscheinungen);
            myResults.mean_entzugserscheinungen = calc.roundToOne(score_entzugserscheinungen / 6);
```

**Comment by schoenenb** [comment]
- [x] Implementierung der neuen Skalen in Grafiken
- [x] Balkendarstellung; Text links "keine Versuchung" - Text rechts "starke Versuchung"
- [x] Skala von 0-80 (bisher: 20-100)
- Umcodierung der Items in 
- [ ] Limesurvey_V2 und auf 
- [x] limesurvey.optinomic:
- 0 = gar nicht
- 1 = wenig
- 2 = mässig
- 3 = sehr
- 4 = äusserst

**Comment by schoenenb** [comment]
Falls dieser Teil aus den calculations:

**Comment by schoenenb** [comment]
Falls dieser Teil aus den Calculations:
![image](https://cloud.githubusercontent.com/assets/15833792/21384860/8d44ddfc-c76c-11e6-952b-8d285b1572dc.png)
für die Migration zuständig ist - könnte man gleich dort die Umkodierung vornehmen? Für die neue Optinomic-Version werden wir die Berechnungen ja an den Originalfragebogen anpassen. Dafür müssten alle bisherigen (Werte -5 )*-1 gerechnet werden. (Also bisher 5 = 0, bisher 4 = 1, bisher 3 = 2 usw.)

**Comment by schoenenb** [comment]
@ottigerb: hab dich dazugenommen wegen der Frage oben...

**Comment by ottigerb** [comment]
Nur zum Verständnis:  
- Sämtliche AASE1..20  sollen umkodiert werden?
- Fragebogen auf http://limesurvey.optinomic.org/index.php/admin/questions/sa/answeroptions/surveyid/526942/gid/33/qid/409 ist so wie er verwendet werden soll?
![bildschirmfoto 2016-12-28 um 12 26 35](https://cloud.githubusercontent.com/assets/2470873/21520971/f1d9eee2-ccf8-11e6-9413-5d3609b98fe1.png)
- Falls 2x Ja:  Die Umkodierung wäre dann schlicht ein `(5-Wert)`:  Eine 5 wird ein 0, eine 4=1, 3=2, 2=3, 1=4, 0=5


Dies sollten wir einmalig via unserem [Data-Migration-SQL](https://github.com/Optinomic/apps/blob/master/lib/sql/search_replace_sql.sql) vornehmen. Also kein Code-Hack gemäss Bild `V1 Compatible`.

**Comment by ottigerb** [comment]
...ich bin mir unsicher, ob sich dieser Aufwand lohnt - dann müssen wir alle Calculations etc. neu überdenken. Wäre es nicht einfacher, nur beim Export diese Umkodierung vorzunehmen?  Dann wäre der Export gemäss Originalfragebogen und unsere Apps/Calculations wären unberührt?

**Comment by SonjaKaufmann** [comment]
Die AASE in V1 müssten umkodiert werden. Wir erheben damit derzeit die Versuchung auf der Papierversion mit 1=sehr starke Versuchung, 2, 3 ,4 ,5=gar keine Versuchung.
Im Optinomic V1 sieht das so aus:
![image](https://cloud.githubusercontent.com/assets/20124244/21522078/d59038f4-cd02-11e6-8846-9fa27aabe1d7.png)
Für die Auswertung wäre allerdings richtig: Keine Versuchung=0, Wenig Versuchung=1, Mässige Versuchung=2, Sehr starke Versuchung =3, Äusserst starke Versuchung=4
Das heisst, das es in V1 wahrscheinlich falsch programmiert war, da in der Auswertung auch Zuversicht dargestellt ist, was allerdings mit dem 2 Teil des Fragebogens erfasst würde, welchen wir derzeit nicht verwenden. Das wollten wir in V2 jetzt korrigieren, dann stellt sich aber das Problem, wie wir mit den alten Werten verfahren. Daher die Idee dies bei der Datenmigration zu machen, damit alles gleich gespeichert ist in V2.

**Comment by schoenenb** [comment]
JAAA genau! Einmalige Umcodierung bei der Datenmigration! Ich wusste, dass die Berechnung irgendwie nicht stimmt, aber meine Perspektive halt wieder...

Calculation muss sonst nicht angepasst werden - der Summenwert soll ja nach wie vor gebildet werden, nur der Range und die Interpretation fallen anders aus.

**Comment by schoenenb** [comment]
![image](https://cloud.githubusercontent.com/assets/15833792/21567903/3a658866-ceb0-11e6-832b-ee9661d7e263.png)

Funktioniert nun auch mit anderen Substanzen ;)

**Comment by ottigerb** [comment]
Kann dies geschlossen werden?

**Comment by ottigerb** [comment]
Nochmals bzgl. RECODE:

Stimmt dies:
```SQL
RECODE every AASE-Score with:  
=> 4=0, 3=1, 2=2, 1=3, 0=4 
```
Eine 4 wird eine 0, 3=1 etc.

**Comment by SonjaKaufmann** [comment]
Ich dachte es sei 5=0 4=1 3=2 2=3 1=4 und 0=5.
Könntest Du bitte noch verifizieren Nora? Merci!

**Comment by ottigerb** [comment]
Ja, dachte ich auch - doch im FB sehe ich:

![bildschirmfoto 2017-01-04 um 16 18 40](https://cloud.githubusercontent.com/assets/2470873/21647181/7eabafcc-d299-11e6-942f-9f7a955c7108.png)

**Comment by ottigerb** [comment]
Im SQL sieht dies dann wie folgt aus:

Pushed: https://github.com/Optinomic/apps/commit/8d2c59dede1d278200877aafb2aa8c29604f835f. So we now have in https://github.com/Optinomic/apps/blob/master/lib/sql/search_replace_sql.sql : 

```SQL
-- RECODE every AASE-Score with: 
---- => => 4=0, 3=1, 2=2, 1=3, 0=4  

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"4"', '"AASE[\1]":"ZERO"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"3"', '"AASE[\1]":"ONE"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"1"', '"AASE[\1]":"3"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"0"', '"AASE[\1]":"4"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"ZERO"', '"AASE[\1]":"0"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"ONE"', '"AASE[\1]":"1"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

```

**Comment by SonjaKaufmann** [comment]
Ist das vielleicht schon der neue Bogen den Nora gemacht hat? Das muss wohl Nora beantworten. Sorry, stifte wahrscheinlich sonst nur Verwirrung.

**Comment by schoenenb** [comment]
Ja, das ist bereits der neue Bogen!
![image](https://cloud.githubusercontent.com/assets/15833792/21710146/13c67698-d3e7-11e6-88b2-ecce752b27f9.png)
 wird zu 
![image](https://cloud.githubusercontent.com/assets/15833792/21710171/49c08720-d3e7-11e6-8cba-916ffc9bdbbf.png)

Weil die Interpretation anders rum ist - bisher gaben wir mit einem hohen Wert eine hohe Abstinenz**zuversicht** an, neu entspricht ein hoher Wert einer hohen **Versuchung**. Vorher war der Werterange 1-5, nun ist er von 0-4, darum:
1 -> 4 | 2 -> 3 | 3 -> 2 | 4 -> 1 | 5 -> 0

```UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"5"', '"AASE[\1]":"ZERO"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"4"', '"AASE[\1]":"ONE"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"3"', '"AASE[\1]":"2"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"2"', '"AASE[\1]":"3"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"ONE"', '"AASE[\1]":"4"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"ZERO"', '"AASE[\1]":"0"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';

UPDATE "survey_response" 
SET response = regexp_replace(response, '"AASE\[(\w+)\]":"ONE"', '"AASE[\1]":"1"', 'g')
WHERE module = 'ch.suedhang.apps.aase-g';```

**Comment by schoenenb** [comment]
falscher Knopf...
Den Fragebogen im Opti-Limesurvey habe ich angepasst, damit ich die definitive Ausgabe für V2 bereits richtig zusammenstellen kann...

**Comment by schoenenb** [comment]
Wenn mit dem Recode alles klar ist, kann das Issue geschlossen werden

**Comment by ottigerb** [comment]
RECODE every AASE-Score :: Änderungen im Script übernommen.
https://github.com/Optinomic/apps/commit/80d40d0f408cf78f478fa8b3dee90811b9ae94da
