### ISSUE TITLE
Abfrage/Liste aus Polypoint | Austrittsart

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#3]
Ich brauche eine Liste aus dem Polypoint mit der Info aus dem Feld Austrittsart vom Blatt Austritt von Dok Psychologie. Habe hier ein Bild von dem Feld gemacht.

Da ich diese Info immer wieder brauche, wäre ich froh um eine Liste analog zur Liste Statistiken/QM: Austritte stat. Fälle für BfS-Statistik
Wenn es möglich wäre hätte ich in der Liste auch gerne noch das Geschlecht. Ansonsten gleich.
Als Namen für die Liste wäre "Austrittsart stationäre Fälle" gut.
[Dok2.docx](https://github.com/Optinomic/apps/files/538480/Dok2.docx)

**Comment by ottigerb** [comment]
...nicht ganz "einfach" - doch ich werde dies irgendwie lösen!  Daumendrück!

**Comment by SonjaKaufmann** [comment]
ja eigentlich gehört es ja nicht in den App-Ordner

**Comment by ottigerb** [comment]
...doch über 7 Ecken auch Optinomic!  :-)

**Comment by SonjaKaufmann** [comment]
Der Daumen wird ganz fest gedrückt

**Comment by SonjaKaufmann** [comment]
Lieber Beat,
könntest Du dich Mal an diesem Punkt versuchen, brauche die Liste um mit den Normen weiterarbeiten zu können.

**Comment by ottigerb** [comment]
Im actInfo - Austittsfragebogen haben wir ja folgende Frage:

_Welches ist der Hauptgrund für die Beendigung der Behandlung, Beratung oder Betreuung?_ 
http://limesurvey.optinomic.org/index.php/survey/index/action/previewquestion/sid/469455/gid/106/qid/3202#

=>  Daraus könnten wir eine Patientengruppe bilden - dann können wir eine Klinikstichproben-Dimension daraus bilden - z.B.:  Abbrecher / Planmässige / Andere Gründe

Lass uns dies am Freitag besprechen.

**Comment by SonjaKaufmann** [comment]
Wir können dies am Freitag besprechen.
Die Liste brauche ich allerdings nicht für die Zukunft sondern für die bisherigen Daten und das Polypoint ist die zuverlässigere Quelle, da immer vom Fallführenden ausgefüllt und zudem gibt es für EAS-Patienten kein Act-Info, also fehlen mir da viele Angaben.

**Comment by ottigerb** [comment]
Anbei ein Export als `xlsx` File.  
=>  Vgl. Email

Diese Felder zeigen die `Interne FID`. 
![image](https://cloud.githubusercontent.com/assets/2470873/19999388/5acc539c-a272-11e6-9fd0-d8ca63731907.png)

Ein 'besserer' Export kann ich leider nicht erstellen - hoffe dies ist so i.O.!  Ansonsten wird es schwierig für mich - Polypoint lässt grüssen. Versuche die FID / PID auszugeben scheiterten - verstehe nicht wieso!  Hmm...
