### ISSUE TITLE
Count down Einführung V2!

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#30]
Wir haben jetzt noch ca. 6 Wochen!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Wir sollten uns eine Timeline zulegen.

Ich habe einen Count down mit Kapazitäten- und Aufgabenzuteilung erstellt. Denn ich habe den Eindruck wir müssen Mal wieder die Zeit im Auge behalten.

Ich bitte Euch Eure Kapazitäten und Verfügbarkeiten einzutragen und auch die Aufgaben zu verteilen. Da die Hauptarbeit bei Euch liegt, kann ich nur meine Kapazität anbieten und damit eventuell Sachen von Nora  übernehmen.

Den Plan sollten wir immer Ende der Woche bzgl. Aufgaben (issues) aktualisieren. Weiss nicht ob wir den so in GitHub ablegen könnnen, dass wir ihn alle bearbeiten können oder ob wir ihn Ende jeder Woche neu hier ablegen müssen.

[Count down V2.xlsx](https://github.com/Optinomic/apps/files/610707/Count.down.V2.xlsx)

@Beat: Wie ist deine Einschätzung der Zielerreichung bis zur Einführung?

Ich denke wir müssen gut auf die Prioritäten achten. Für mich sind zwei wichtige Ziele bis zur Einführung, das die Graphiken überarbeitet sind (es muss nicht jede Kleinigkeit stimmen) und das die Berichte ausgedruckt werden können.

Nora & Ich haben überlegt, ob Du Beat nochmal nach Kirchlindach kommen könntest an einem Freitag, damit ihr zusammen an 2 PC`s (Non Mac) an den Graphiken arbeiten könntet. Wäre dies von Dir aus möglich? Nora wäre auch bereit zu Dir zu kommen, aber von der Ausstattung wäre es bei uns im Büro wahrscheinlich hilfreicher. Ich müsste vorher Bescheid wissen, damit ich meinen Laptop auf der Dockingstation lasse.

Für morgen wünsche ich Euch gute Programmierenergie und dann ein gutes Wochenende.

**Comment by SonjaKaufmann** [comment]
Was ich noch vergessen habe. In der Regel habe ich Freitags zwar private Termine, aber ich bin auch immer Mal wieder frei und erreichbar. Wenn ihr meine Meinung für irgendetwas braucht, dann könnt ich mir auf sonja.kaufmann1@gmx.ch eine Mail schreiben und/oder eine Nachricht auf WhatsApp (0765085298). WhatsApp sehe ich eher, wenn Mail, dann bitte mit WhatsApp-Nachricht in soll in Mail.

**Comment by ottigerb** [comment]
Die Einführung ist m.E. gut im Plan. limeSurvey (neue Version) steht und nun können wir App für App - welche wir für 'gut' empfinden in eine 'production' app verwandeln und im Live - System hochladen.

Zu den genannten Prios:   
- Grafiken überarbeitet: Dies ist mir irgendwie noch immer unklar.  Allenfalls 'kleinere Issues' hier eröffnen bzgl. den Grafiken. Diesbezüglich müssen wir ein Gleichgewicht finden bzgl. dem Aufwand:  Es macht kaum Sinn viel Arbeit in ein z.B. Stanine-Chart zu stecken, wenn diese bald mit Z-Scores ersetzt wird. 
- Druckbar:  Ich beginne mal mit 'report_only' Templates für die Apps, welche mit 'Karussell-Darstellung' ausgestattet sind. 

_Count down V2.xlsx_  File:  Uff - bitte nicht!   Aufgaben eröffnen wir hier als Issues und die Verteilung wird über 'Assignees' gesteuert.  Issues können auch sehr klein sein - im Sinne von Grafik hier so und so anpassen'.  Excel Files hin und herschieben mag ich nicht.
=> Ferienabwesenheit bin ich wie Sonja - ausser der 6.1.

**Comment by schoenenb** [comment]
Mir hilft die Tabelle den Überblick zu behalten, an welchen Issues aktuell gearbeitet wird bzw. werden kann. Dann bleibt sie SH-intern und es gibt keine Probleme mit der Aktualisierung.

**Comment by schoenenb** [comment]
Ich gehe davon aus, dass darüber nicht mehr diskutiert wird und schliesse das Issue.
