### ISSUE TITLE
Stammdaten - Export

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#31]
Können die Angaben in der bestehenden Stammdaten (Fall) - App für Exporte genutzt werden?
So dass z.B. jeder Fall nach den jeweils angewählten Programmen 
- nur EAS = 1
- nur EP = 2 und
- EAS & EP = 3 codiert wird?

**Comment by ottigerb** [comment]
Jep, das geht!  

Ich habe mir Gedanken gemacht, wie die jeweilige Stammdaten-App's automatisch befüllt werden können.  Die Prozedur müsste jedoch manuell gestartet werden: Also eine User-App öffnen und dann ein [Stammdaten-Apps befüllen] drücken.  Dies würde ein Polypoint-Lookup durchführen und die jeweiligen `_Stammdaten` Patienten-Apps mit den aktuellen Daten abfüllen. Wie klingt dies?  Vielleicht kriegen wir es gar hin, dass dieser Lookup automatisch - in der Nacht z.B. durchgeführt wird. Ich "spiele" mal damit rum. OK?

**Comment by schoenenb** [comment]
Hat sich mit der _Belegung - App #10 erledigt.
