### ISSUE TITLE
Generelles zu Graphiken

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#32]
Nachdem es anscheinend Unklarheiten bezüglich der Graphiken gibt, fasse ich hier meine Annahmen zusammen:
- Ich bin davon ausgegangen, dass wir für alle Graphiken eine Z-Wert-Darstellung machen.
-Nun haben wir noch nicht alle Normdaten, weil Manuale teilweise ausgeliehen oder Normwerte nicht enthalten, daher dachte ich dort können wir mit Dummies arbeiten. 
- Da noch entschieden wird, ob der SCI überhaupt im Paket bleibt und wir dort die Normen kaufen müssten wollten wir dort als Ausnahme zuwarten und schon Mal soweit überarbeiten, dass nur noch Graphikteil (also Staninewerte oder Z-Werte) gewechselt werden müssen. Die Beschriftung an den Seiten und die Einteilung sollte aber schon stimmen.
- Den BDI könnte man im groben so lassen wie er ist, da dort eine Z-Wert-Graphik wenig Sinn macht.
- Den AASE müssen wir noch abändern, da er nur eine von 2 wichtigen Skalen erfasst. D.h. wir müssen die Vorlage ändern und auch die Auswertung. Beschreibe ich noch in einem separaten Issue. Da es ein suchtspezifischer Fragebogen ist, brauchen wir ihn nicht mit unserer Klinischen Stichprobe Südhang vergleichen, sondern nur mit der Klinischen Norm als Normierungsnorm.
-Ich dachte wir stellen generell auf Balkendiagramme um und daher ist es möglich die Graphiken beidseitig zu beschriften. Auf der Grundlage habe ich die Skizzen erstellt.

**Comment by ottigerb** [comment]
Z-wert-Darstellung ist das Ziel. Genau.  Die anderen Punkte habe ich zur Kenntnis genommen.

Zur Klärung:  Unsere Arbeit vom Freitag bzgl. Grafikdarstellungen ist hauptsächlich um den "Print" sicherzustellen =>  keine "Karussell-Darstellung" mehr.  Die bisherige Stanine-Darstellung war somit nicht mehr 'praktikabel'.  

Ich entferne: "Priorität 1", da ich aus diesem Issue keinen konkreten Auftrag ablesen kann.

**Comment by SonjaKaufmann** [comment]
Bin froh haben wir das gleiche Ziel :-) 
Das mit der Prio ist gut, können das Issue auch schliessen, wollte nur sichergehen, dass es gelesen wird vorm weiterschaffen.
