### ISSUE TITLE
[ch.suedhang.apps.honos] :: HoNOS - open issues

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#34]
Darstellung nicht mittels timeline, sondern als Tabelle wie bis anhin:
![image](https://cloud.githubusercontent.com/assets/15833792/20838137/83a466d8-b8a7-11e6-89a6-25195584ec22.png)

**Comment by schoenenb** [comment]
Ev. kann das Template "table.html" bereits verwendet werden.

**Comment by schoenenb** [comment]
Lässt sich ev. sogar der Verlaufs-HoNOS in der gleichen App programmieren und darstellen?
Das wären dann 3 Werte (H1, H2 & H5) 2 Wochen nach Eintritt.

**Comment by ottigerb** [comment]
Verlaufsfragebogen als 2. Fragebogen innerhalb der gleichen App:  
Bitte upload zu http://limesurvey.optinomic.org/

**Comment by schoenenb** [comment]
ist auf Limesurvey & im Repo (survey_markups)

**Comment by ottigerb** [comment]
#### HoNOS - Verlauf - Fragebogen ist in die App integriert und wird in der HoNOS - Tabelle wie folgt angezeigt:




![bildschirmfoto 2016-12-09 um 16 21 10](https://cloud.githubusercontent.com/assets/2470873/21053875/98bf1340-be2b-11e6-8f9f-3180e6c901ed.png)

**Comment by schoenenb** [comment]
- [x] E-Mail analog DASS gestalten uns austesten
- [x] Summe durch Summenzeichen ersetzen --> läuft in H1 rein bei kleineren Bildschirmen

**Comment by schoenenb** [comment]
Summe durch Summenzeichen ersetzen --> läuft in H1 rein bei kleineren Bildschirmen

**Comment by schoenenb** [comment]
Anzeige bei Item 8:
![image](https://cloud.githubusercontent.com/assets/15833792/22070375/120016d4-dd9c-11e6-846f-aca880e3e6d8.png)
"Undefiniert" durch "" ersetzen?

**Comment by schoenenb** [comment]
Anzeige bei Dropout - Dropoutgrund
![image](https://cloud.githubusercontent.com/assets/15833792/22339267/ae6852f4-e3e9-11e6-9f0b-72b7002fb657.png)

**Comment by ottigerb** [comment]
...erneut:  Welcher patient id hat diesen Dropout?  Thanks!

**Comment by schoenenb** [comment]
Ah, das waren eigentlich bloss Aufgabenvorlagen für mich, damit ich das ev. analog zum BSCL umsetzen kann.
Aber z.B. patient/1482/stay/1216

**Comment by ottigerb** [comment]
...na dann:  Gutes Gelingen!  

**Hinweis:**  HoNOS hat ja eine HTML-Tabelle als Ausgabe. Die einzelnen Zellen können mittels `HTML <td> colspan Attribute` (http://www.w3schools.com/tags/att_td_colspan.asp) zu einer "breiten Spalte" werden.

**Comment by schoenenb** [comment]
Hatte noch sowas im Hinterkopf, von der Grafik in V1 her...

**Comment by schoenenb** [comment]
Merci für die schöne Vorlage - musste nur fürs Dropout die "!" wegnehmen...

**Comment by ottigerb** [comment]
...perfect!  Close?

**Comment by schoenenb** [comment]
Bin noch am "undefined"

**Comment by schoenenb** [comment]
undefined weg --> close
