### ISSUE TITLE
[Bericht]  Eintritt | Austritt

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#35]
Bei "Eintritt" nur Eintrittsmessungen darstellen, bei "Austritt" alle Messungen darstellen.

#### Eintritt

- [x] Act-Info Eintritt
- [x] TMT
- [x] BSCL
- [x] AASE-G
- [x] BDI-II
- [x] ISK-K
- [x] SCI
- [x] WHOQOL nur Text (Nora)

#### Austritt
- [x] Act-Info Ein- & Austritt; nur Fagerström in Textform (Nora)
- [x] TMT
- [x] BSCL
- [x] AASE-G
- [x] BDI-II
- [x] ISK-K
- [x] SCI
- [x] WHOQOL nur Text (Nora)

**Comment by ottigerb** [comment]
### Ich habe wohl die Lösung bzgl. dem Printing gefunden!  Yes!

Wir können nun ‚relativ‘ komfortabel PDF’s erstellen.  Zeilenumbrüche etc. etc. kann ich hier gut kontrollieren. Schaut Euch doch mal folgende App an:   
http://demo.optinomic.org/api/#/patient/1/stay/144/app/com.optinomic.test.pdf_make

[Reporting psychologisches Assessment V3.docx](https://github.com/Optinomic/apps/files/647513/Reporting.psychologisches.Assessment.V3.docx)

**Comment by SonjaKaufmann** [comment]
Auf jeden Fall hört sich das sehr gut an! 
Ich weiss nicht genau was Du möchtest in der Reporting-Vorlage, weil genau sie Sachen drauf sollen die Nora oben angegeben hat und da genau die Graphiken drauf sollen, die auch im Optinomic angezeigt werden, allerdings die Z-Werte wo wir welche haben. Also eigentlich nichts neues. Sag mir oder Nora (ab Montag wieder) was Du genau wissen willst.

**Comment by ottigerb** [comment]
... eine möglichst genaue Vorlage um nicht das Ganze 2x vorzunehmen. Doch
glaube soweit einen gute Idee zu haben. Trotzdem - Texte etc. sind sehr
hilfreich.

SonjaKaufmann <notifications@github.com> schrieb am Di., 13. Dez. 2016,
14:22:

**Comment by SonjaKaufmann** [comment]
Lieber Beat, so ganz verstehen tue ich das mit der tollen Druckfunktion nicht. Löst dass das Issue 7 Bericht drucken als pdf?
Was ist die Ready to print Ansicht? Warum sieht die so anders aus als unsere Graphiken?
Zu den Auswertungsberichten: Diese werden wohl mehrere Seiten lang, es wird nicht möglich sein alles auf so wenig Platz zu komprimieren, wenn wir die Graphiken so nehmen wir wir sie jetzt gemacht und beschriftet haben. Was eventuell weggelassen werden kann sind die mehrfachen Beschriftungen der Klinischen Stichprobe. Die Patienten müssen dies nicht wissen und wenn es in der Computeransicht drin ist, dann reicht das. Ansonsten kommen einfach die z-Graphiken in der oben genannten Reihenfolge untereinander, ausser SCI (da ja keine z-Werte) und bei denen wo Nora beisteht, da gibt es nur Text.

**Comment by ottigerb** [comment]
Genau, dies ermöglicht 'wirkliche' PDF's zu erstellen. Nicht nur den Inhalt des Browsers in ein PDF drucken. Ich habe damit versucht Seitenumbrüche etc. zu kontrollieren - mit mässigem Erfolg. 

Die bisherigen Grafiken, Darstellungen sind HTML und können nicht einfach in das 'PDF' genommen werden. Hier müssen wir erneut eine z.B. Z-Score Darstellung 'bauen'. Entsprechend froh und dankbar wäre ich um eine klare Vorlage:  als Word-Dokument. 

Auch denke ich sollten wir vermehrt nach Inhalt Gruppieren:  Z.B. Alkoholabhängigkeit.  Also Alles, was dazu gehört dort anzeigen vs.  actinfo / CASE etc als eigene 'Überschrift'.

**Comment by SonjaKaufmann** [comment]
Lieber Beat,
dann soll die Darstellung so aussehen wie wir sie bis anhin definiert haben für die Bildschirmdarstellung! Es gelten die gleichen Vorlagen und die Reihenfolge habe ich schon mit Nora besprochen (s.o.) und die Bögen wo wir auf Text (WHOQoL und BDI) gehen oder nicht drauf nehmen sind ja auch vermerkt.  Bei den Graphiken kann man einzig die Klinische Stichprobenlegende kürzen oder weglassen. Sonst ist es 1:1 das Gleiche. Genau dafür sind die Graphiken entwickelt! Es wird mit dem Ausdruck gearbeitet werden und nicht mit dem Patienten am Bildschirm und in der Fallbesprechung werden die Bildschirmgraphiken verwendet oder in der Falleinarbeitung, aber ggf. auch mit Ausdrucken. M.E. haben wir dies jetzt schon oft genug besprochen, dass wir das so verwenden wollten, drum verstehe ich das gerade nicht. Ich werde jetzt nicht alle bisher erstellten Graphiken auf Word nochmal nachbilden. Vor allem sollten dazu zuerst alle Auswertungsgraphiken fertig sein bevor wir die Bericht-Zusammenfassung machen. Sorry, aber im Entwicklervertrag sind auch "Druckerfreundliche Formate von Auswertungen und Charts" ausformuliert.  Wenn dies bis zum geplanten Einführungstermin nicht möglich ist, dann teile dies bitte in einem separaten Mail dem Wale und mir mit, dann müssen wir überlegen wie wir mit dem Einführungstermin umgehen.

**Comment by ottigerb** [comment]
"Druckerfreundliche Formate von Auswertungen und Charts" ist m.E. bereits heute erfüllt. Für eine 'pixel perfect' PDF Variante (welche nie versprochen resp. vertraglich bestätig wurde) kann bestehendes nicht 'übernommen' werden - benötigt also nochmals Arbeit, welche ich trage und über die 'Vertragsbedingung' deutlich hinausgehen.

**Comment by ottigerb** [comment]
#### Ich komme hier weiter!    

Folgende Dokumente wurden von [dieser App](http://demo.optinomic.org/api/#/patient/2000/stay/878/app/com.optinomic.test.pdf_make) heruntergeladen: 

[2016_12_19__austritts_assessment__thompson_zoey.pdf](https://github.com/Optinomic/apps/files/661900/2016_12_19__austritts_assessment__thompson_zoey.pdf)
[2016_12_19__eintritts_assessment__thompson_zoey.pdf](https://github.com/Optinomic/apps/files/661901/2016_12_19__eintritts_assessment__thompson_zoey.pdf)

**Comment by schoenenb** [comment]
Das sieht schon ganz gut aus!
Aber ich habe selbstverständlich auch hier bereits wieder Anmerkungen:
- im Austritts-File müssten noch mehr Daten drin sein - liegt das daran, dass die Daten noch nicht migriert wurden? Oder werden die falschen Daten ausgewählt?
- die Zahlenbeschriftung der Z-Wertdarstellungen ist in der Mitte verzogen, z.B. 
![image](https://cloud.githubusercontent.com/assets/15833792/21381881/1ba2601a-c75e-11e6-8b64-4ac46c9ac9ba.png) - wie kann man das anpassen?
- Die Darstellung sollte eigentlich genau umgekehrt sein - von Somatisierung oben links bis GSI unten rechts. Kann man das für die PDF-Ausgabe umdrehen? Ich nehme an, es wird so dargestellt, weil sie in der App in der Reihenfolge erscheinen, da die Grafik von unten her aufgebaut ist?! 
- Bei Austritt sieht die BSCL-Darstellung nicht so hübsch aus, weil es den Titel der letzten beiden Skalen nicht auf die nächste Seite zieht. Könnte da etwas mehr Beschreibungstext helfen, damit die runterrutschen?
- @SonjaKaufmann  Sollen für die Auswertung auch die Beschriftungen an die Seite? Dann wäre die Ausgabe etwas weniger Platzsparend, also eine Subskala pro Zeile... @ottigerb wie/wo kann das angepasst werden?
- Der Block "Act-Info" soll beim Austritt nicht mehr ganz angezeigt werden, nur die Fagerström-Werte, diese aber für beide Messzeitpunkte.
- BDI sollte die ganze Abbildung rein, allerdings müsste ich da noch die Grafik anpassen, weil sie im Moment noch zu überladen ist.

**Comment by ottigerb** [comment]
1. Mehr Daten:  Genau, die BSCL-Daten wurden nicht migriert. 
2. `- Werte` sind links, 0 = zentriert `+-Werte` rechtsbündig. Versuche dies noch etwas zu optimieren.
3. Umgekehrte Reihenfolge - dies lässt sich lösen.
4. Verstehe nicht ganz: Überschrift ist noch auf einer Seite, die Grafik auf der Folgeseite? Diesbezüglich habe ich "Tests" laufen - voraussichtlich kann ich die Überschrift und die Grafik in eine "unsichtbare Tabelle"  setzen. Dann wird der ganze Block auf die neue Seite 'gezogen'.
5. Act-Info Austritt:  Alles klar.
6. BDI-Abbildung. Diese müsste ich ebenfalls noch entwickeln für die PDF-Darstellung. Kommt.

Auch fehlen noch die Norm- / Klinikstichproben - Beschriftungen für die Z-Werte. Kommt.

**Comment by schoenenb** [comment]
4. bei http://demo.optinomic.org/api/#/patient/1/stay/144/app/com.optinomic.test.pdf_make hat es 2 Messungen im BSCL, drum schneidet es die Grafik ab
![image](https://cloud.githubusercontent.com/assets/15833792/21383900/492d9220-c768-11e6-9917-c143bc79b808.png)
An sowas hab ich auch gedacht, wär super wenn das mit der unsichtbaren Tabelle funktioniert!
6. Habe ich das in dem Fall richtig verstanden, dass du alle Grafiken nochmals neu aufgezogen hast für die PDF-Darstellung?

**Comment by ottigerb** [comment]
**Erledigt:**   BSCL :: Umgekehrte Reihenfolge

- Genau, die "Grafiken" mussten nochmals "neu" für die PDF-Darstellung entwickelt werden. Doch dies ist eigentlich ganz gut machbar.  Vgl. dazu: https://github.com/Optinomic/apps/blob/master/com.optinomic.test.pdf_make/playground.js der Inhalt dieses Files kann in http://pdfmake.org/playground.html kopiert werden um Grafiken, Darstellungen etc. zu entwickeln.  Plain JSON - gefällt!  :-)
- Allenfalls kann ich auch folgendes prüfen:  Bei 2 Messungen - Zeilenumbruch hier einfügen, Bei 3 Messungen früher etc. etc. |  Vielleicht fast "besser" als die "unsichtbaren Tabellen".  Wobei - die Tabellen wären sicher flexibler... hmmm...  will test & try!

**Comment by schoenenb** [comment]
mhm, die Tabellen gefallen mir etwas besser, stelle ich mir das so richtig vor:
![image](https://cloud.githubusercontent.com/assets/15833792/21384420/cce383ac-c76a-11e6-8a63-e755d06e25be.png)
in Tabellen wäre das dann entsprechend so (nur ohne sichtbare Linien):
![image](https://cloud.githubusercontent.com/assets/15833792/21384513/1f3d1cf8-c76b-11e6-8d08-4d407c1b43ed.png)

**Comment by ottigerb** [comment]
BSCL - Ich verabschiede mich also von der 2 Spalten Darstellung - OK!

**Comment by schoenenb** [comment]
Ich gehe zumindest davon aus, dass die Beschreibung auf der rechten Seite noch hin soll.

**Comment by ottigerb** [comment]
...BSCL hat nur eine `Beschreibung rechts`  oder?   Links ist jeweils die Skala z.B. `Psychotizismus`.
Falls ja, könnten wir diese Beschriftung auch unter der Überschrift setzen:

____

#### Psychotizismus
Beschreibung rechts - laaaaaanger Text
[         Grafik          ]

**Comment by schoenenb** [comment]
Nein, das soll eben rechts stehen, weil es nur auf die Werte rechts zutrifft. Weiss grad nicht, wie das grafisch aussähe, ev. wäre die Grafik sogar ohne Überschrift denkbar:
Skalenname - [ Grafik ] - Beschreibung für hohe Werte

**Comment by ottigerb** [comment]
OK.  Setze ich um - Einspaltig. Und versuche dort `pageBreak` clever zu lösen.

**Comment by schoenenb** [comment]
Die neue "Version" ist TOP!!!

**Comment by ottigerb** [comment]
Wie erkenne ich einen "Nichtraucher" in den actInfo's?  Auch wäre die `WHOQOL nur Text (Nora)` interessant. Danke!  Heute werde ich nicht mehr viel 'Optinomic-Zeit' finden.

**Comment by schoenenb** [comment]
1. Das müsste dem Teil hier aus meinem letzten Commit gestern ( https://github.com/Optinomic/apps/commit/3af59d0578358c004de9bb079edd87308c81c7b3 ) entsprechen:
```
Wenn VZAT010 = 1 NichtraucherIn
Wenn VZAT020 = 999 Keine Angaben zum Zigarettenkonsum vorhanden.
Wenn VZAT020 = 777 PatientIn raucht, aber keine Zigaretten.

                <div ng-if="response.calculations[0].calculation_result.response.data.response.VZAT010 === 1">
                   <h4 class="md-subhead">PatientIn raucht nicht</h4>
                </div>
                <div ng-if="response.calculations[0].calculation_result.response.data.response.VZAT020 === 999">
                    <h5 class="md-subhead">Keine Interpretation möglich</h5>
                    <p class="md-caption">Kein Fagerström-Score vorhanden.</p>
                </div>
                <div ng-if="response.calculations[0].calculation_result.response.data.response.VZAT020 === 777">
                    <h5 class="md-subhead">Keine Interpretation möglich</h5>
                    <p class="md-caption">PatientIn raucht ein anderes Tabakprodukt als Zigaretten.</p>
                </div>
```

**Comment by schoenenb** [comment]
2. "relativ simpel" (bzw. auch in #36 zu finden):
#### Eintritt:
Bei Eintritt wurde die **psychische** Lebensqualität auf [_Eintrittswert_] von 100 eingeschätzt.
Bei Eintritt wurde die **körperliche** Lebensqualität auf [_Eintrittswert_] von 100 eingeschätzt.

#### Austritt:
Bei Eintritt wurde die **psychische** Lebensqualität auf [_Eintrittswert_] von 100 eingeschätzt.
Bei Austritt wurde die **psychische** Lebensqualität auf [_Austrittswert_] von 100 eingeschätzt.

Bei Eintritt wurde die **körperliche** Lebensqualität auf [_Eintrittswert_] von 100 eingeschätzt.
Bei Austritt wurde die **körperliche** Lebensqualität auf [_Austrittswert_] von 100 eingeschätzt.

**Comment by schoenenb** [comment]
Plus wahrscheinlich noch ein wenig Einleitungstext, was bei den Skalen erfragt wurde.

Fliesstext: Niedrige Ausprägung weist auf geringe Lebensqualität hin, hohe Ausprägung auf hohe Lebensqualität.

**Comment by schoenenb** [comment]
Und ich war davon ausgegangen, dass bei dir heute bereits die "Weihnachts-Pause" beginnt.

**Comment by schoenenb** [comment]
bzgl. BSCL siehe auch #25:

- [x] Zusatzitems inkl. Ausprägung müssen mit drauf
- [x] beim Eintritts-Bericht soll - falls vorhanden - auch Zeitpunkt 3 (Übertritt) mit drauf

**Comment by ottigerb** [comment]
BSCL - Zusatzitems sind nun auch im PDF.  Auch konnte ich die zu grossen Spaces nach dem ersten Wort so ziemlich eliminieren. Der Trick ist jeweils einfach ein "Leerschlag" vor den String stellen im Sinne von:

```JS
"text": " " + text
```

**Comment by schoenenb** [comment]
Habe einige Kleinigkeiten ändern können:
 - act-info: Substanztabelle ohne "Titel" und Linien
 - act-info: Anpassungen im Text zu AUDIT + Fagerström
 - TMT: 2. Block bei Beschreibung (`description_full`) nur bei Eintritt
 - BSCL: Vollständige Beschreibung bei Ein- + Austritt
 - SCI: Titel :)
 - AASE: Textanpassungen in Titel und Beschreibung
 - WHOQOL-BREF: "Vorbereitung" - irgendwas mit den calc-Verknüpfungen scheine ich wieder verwurstelt zu haben, weshalb die Ausgabe nicht funktioniert.

**Comment by ottigerb** [comment]
Ich denke die Berichte sind soweit i.O. - resp. ich sehe keine offenen Issues mehr:
[2017_01_03__austritts_assessment__ottiger_patient.pdf](https://github.com/Optinomic/apps/files/682932/2017_01_03__austritts_assessment__ottiger_patient.pdf)
[2017_01_03__eintritts_assessment__thompson_zoey.pdf](https://github.com/Optinomic/apps/files/682933/2017_01_03__eintritts_assessment__thompson_zoey.pdf)


Falls wir eine "Kompakte" Vatiante wünschen, ist dies wohl eine gute Idee:
[2017_01_03__austritts_assessment__ottiger_patient_kompakt.pdf](https://github.com/Optinomic/apps/files/682934/2017_01_03__austritts_assessment__ottiger_patient_kompakt.pdf)

**Comment by ottigerb** [comment]
Ich schliesse dieses Issue aufgrund der Übersichtlichkeit. Falls noch weitere Änderungen gewünscht werden:  Neues Issue Eröffnen z.B: "_[PDF] Austrittsbericht - BDI_"
