### ISSUE TITLE
[com.optinomic.apps.whoqol] :: WHOQOL - open issues

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#36]
Für Bericht folgende "Textauswertung":
- [ ] Bei Eintritt wurde die psychische Lebensqualität auf *Eintrittswert* von 100 eingeschätzt.
- [ ] Bei Austritt wurde die psychische Lebensqualität auf *Austrittswert* von 100 eingeschätzt.
- [ ] Bei Eintritt wurde die körperliche Lebensqualität auf *Eintrittswert* von 100 eingeschätzt.
- [ ] Bei Austritt wurde die körperliche Lebensqualität auf *Austrittswert* von 100 eingeschätzt.

**Comment by ottigerb** [comment]
Done
