### ISSUE TITLE
[ch.suedhang.apps.actinfo] :: act-info Ein- & Austritt - open issues

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#37]
### Darstellung Eintrittsbericht

- [x] Substanzkonsum letzte 30 Tage

- [x] AUDIT - Grafik

- [x] Fagerström: "Bei Eintritt in die Entwöhnungsbehandlung bestand keine / eine *Ausprägung*
Nikotinabhängigkeit."

### Darstellung Austrittsbericht

- [x] Fagerström: "Bei Eintritt in die Entwöhnungsbehandlung bestand keine / eine *Ausprägung*
Nikotinabhängigkeit."

- [x] Fagerström: "Bei Austritt aus der Entwöhnungsbehandlung bestand keine / eine *Ausprägung*
Nikotinabhängigkeit."

**Comment by schoenenb** [comment]
### Austritt

- [x] Summenausgabe Fagerström
- [x] Textausgabe "Nichtraucher"
- [x] Textausgabe "Rauchverhalten nicht bekannt"

**Comment by schoenenb** [comment]
@SonjaKaufmann: Angabe zu "Abstinenzmotivation" aus act-info mit angeben -> "nein, aber ich will aufhören" anständig ausformuliert (Veränderungsmotivation vorhanden), "ja ohne Erfolg" ()
![image](https://cloud.githubusercontent.com/assets/15833792/21520254/6183ad9c-ccf3-11e6-8294-268a78cedfad.png)

**Comment by schoenenb** [comment]
![image](https://cloud.githubusercontent.com/assets/15833792/21520603/d6f663e2-ccf5-11e6-9543-5761f6f5886a.png)

**Comment by schoenenb** [comment]
- [x] Substanz + Häufigkeit analog Titel Substanzkonsum
- [x] keine Linien

**Comment by SonjaKaufmann** [comment]
![image](https://cloud.githubusercontent.com/assets/20124244/21538752/81d78de0-cda0-11e6-934e-2660290bc646.png)
Für die Fälle bei denen es sich um einen Raucher handelt gilt:
Ich habe während der Behandlung nicht geraucht= Erfolgreicher Rauchstop im Behandlungszeitraum
Nein ich will nicht aufhören = Aktuell keine Motivation zum Rauchstop vorhanden
Nein, aber ich möchte aufhören = Motivation zum Rauchstop vorhanden, Planung weiterer Schritte sinnvoll
Ja, aber ohne Erfolg = Erste Schritte zum Rauchstop unternommen, Planung weiterer Schritte sinnvoll
Ja, mit Erfolg =Erfolgreicher Rauchstop im Behandlungszeitraum

Ich weiss nicht ob wir so auch den Fall abgedeckt haben bei Eintritt Nichtraucher, bei Austritt Raucher, aber ich denke es hängt ja allein am Austritts-Act-Info, daher sollte es abgedeckt sein, oder?

**Comment by ottigerb** [comment]
Die Texte sind gemäss Angaben drin.  Im Beispiel wie folgt:

![bildschirmfoto 2017-01-03 um 16 53 58](https://cloud.githubusercontent.com/assets/2470873/21613409/637a9a48-d1d5-11e6-9053-0638df30e761.png)

![bildschirmfoto 2017-01-03 um 16 54 12](https://cloud.githubusercontent.com/assets/2470873/21613408/637a063c-d1d5-11e6-842e-d29745bb134a.png)


=>  Ich schliesse dieses Issue.  Falls noch Änderungen gewünscht sind: Reopen.
