### ISSUE TITLE
To Do Liste erstellen

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#4]
Fände es hilfreich, wenn wir eine allgemeine To Do Liste hätten oder ist es die Idee alle vergessenen Aufgaben nochmals hier einfüllen und dann über die Prioritäten zu gehen?
Habe noch nicht herausgefunden wie ich die Zuständigkeit und die Prioritäten bei der Aufgabenerstellung angeben kann.

**Comment by ottigerb** [comment]
...genau - alles "Vergessene" als neues Issue eröffnen.

Auf der rechten Seite gibts es hier:  Labels & Assignees - einfach auswählen.

**Comment by SonjaKaufmann** [comment]
Da kann ich nicht auswählen

**Comment by ottigerb** [comment]
https://github.com/Optinomic/apps/invitations

=> Du solltest wohl die Anmeldung annehmen.  Noch immer offen.
