### ISSUE TITLE
Patienten-Assessment:  Zugangsdaten und Beschreibung drucken.

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#40]
#### Ich habe uns ein kleines Weihnachtsgeschenk:

Diese Applikation ermöglicht das Drucken der Zugangsdaten sowie einer Kurzeinführung für das Optinomic Patienten-Assessment:
http://demo.optinomic.org/api/#/user_app/com.optinomic.user.apps.assessment

Patientengruppe selektieren / PDF öffnen oder speichern erstellt folgendes PDF:

[assessment_zugangsdaten.pdf](https://github.com/Optinomic/apps/files/648661/assessment_zugangsdaten.pdf)

### Issue
Bitte prüft den Text - allfällige Wünsche etc.  Falls alles i.O. ist - Issue schliessen.

**Comment by SonjaKaufmann** [comment]
Lasse ich noch offen bis Nora es auch angeschaut hat. Für mich in Ordnung, vielleicht ist ab und zu ein Leerschlag zuviel.
Super Sache.

**Comment by ottigerb** [comment]
... das sind keine Leerschläge - hab mich auch schon geärgert
diesbezüglich. Irgendwie Blocksatz oder sowas. Na ja - doch ziemlich
Pixel-Perfect.   :)

SonjaKaufmann <notifications@github.com> schrieb am Di., 13. Dez. 2016,
14:23:

**Comment by SonjaKaufmann** [comment]
Ach es könnte ruhig öfter Weihnachten sein ☺
Miss Pixelperfect

Von: Beat Ottiger [mailto:notifications@github.com]
Gesendet: Dienstag, 13. Dezember 2016 14:29
An: Optinomic/apps
Cc: Kaufmann Sonja; Assign
Betreff: Re: [Optinomic/apps] Patienten-Assessment: Zugangsdaten und Beschreibung drucken. (#40)

... das sind keine Leerschläge - hab mich auch schon geärgert
diesbezüglich. Irgendwie Blocksatz oder sowas. Na ja - doch ziemlich
Pixel-Perfect. :)

SonjaKaufmann <notifications@github.com> schrieb am Di., 13. Dez. 2016,
14:23:

**Comment by ottigerb** [comment]
Die Einladung kann ab sofort auch von der Patienten-App: com.optinomic.test.pdf_make erstellt werden:  http://demo.optinomic.org/api/#/patient/1/stay/144/app/com.optinomic.test.pdf_make

=>  Damit kann manuell der Patient ausgewählt werden und dann die Einladung gedruckt werden.

PDF File eines 'einzelnen' Patienten sieht dann wie folgt aus:
[file.pdf](https://github.com/Optinomic/apps/files/649255/file.pdf)

**Comment by ottigerb** [comment]
...boah - beachtet die tollen 'filenames' beim Download:  Freude!  :-)

**Comment by schoenenb** [comment]
Ich staune nur! Sieht super aus, die PDF-Ausgabe - grosses Kompliment!!

- Eine Anmerkung zu diesem Abstand: mir scheint es kein Blocksatz zu sein, weil der etwas grössere Abstand nur immer nach dem ersten Wort im Absatz erscheint... Das nur am Rande, solange der Rest stimmt, kann man sich das auch später mal noch anschauen.

**Comment by ottigerb** [comment]
Freut mich sehr zu lesen - werde entsprechend weiterarbeiten. Falls Änderungswünsche zu den einzelnen Abschnitten vorhanden sind - give sign.  Ja, diese Abstände ärgern noch - irgendwann finde ich diesbezüglich die Lösung - Daumendrück.

**Comment by schoenenb** [comment]
Änderungswünsche zu den Abschnitten siehe #35  :)

**Comment by ottigerb** [comment]
Erledigt - falls noch Änderungswünsche vorhanden sind:  Reopen.

**Comment by schoenenb** [comment]
Kurze Nachfrage: Die User-App, mit der für eine ganze Gruppe das Blatt mit den Zugangsdaten gedruckt werden kann, gibt's nicht mehr in optinomic.cust.local, richtig?

> Diese Applikation ermöglicht das Drucken der Zugangsdaten sowie einer Kurzeinführung für das Optinomic Patienten-Assessment:
http://demo.optinomic.org/api/#/user_app/com.optinomic.user.apps.assessment

**Comment by ottigerb** [comment]
...die haben wir wohl deaktiviert gehabt. Hab sie wieder aktiviert:
http://optinomic.cust.local/api/#/user_app/com.optinomic.user.apps.assessment

...bitte nur Patientengruppen wählen mit nicht zu vieeeeelen Patienten - ansonsten dauert das erstellen des PDF's laaaaaange.

...auch gilt es im `main.js` die Texte zu "pflegen":

```JS
var text_1 = 
var text_2 = 
var text_3 = 
````

**Comment by schoenenb** [comment]
Merci :)
Es sind i.d.R. 3-6 Patienten, max. 10 in Ausnahmefällen
main.js muss ich mir nachher anschauen

**Comment by ottigerb** [comment]
Gerne!  
- 10 Patienten sollte problemlos funktionieren.  Nur nicht über "alle Patienten" ein PDF erstellen lassen.   :-)
