### ISSUE TITLE
[Optinomic] event: type = once_after_x_days?

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#42]
Weil beim HoNOS nun ja nicht mehr alle 14 Tage, sondern nur noch einmalig 14 Tage nach Eintritt die Verlaufs-Version ausgefüllt werden muss - müsste dafür eine neue Event-Typ-Kategorie geschaffen werden, oder kann z.B. die Kategorie "once" nicht nur als spezifisches Datum festgelegt, sondern an ein Datum geknüpft (z.B. entry + 14 days) werden?
 [Doc - 3.02 - Events](https://doc.optinomic.org/V2/Developers/app_spezifikation.html#event-optional-can-have-many)

**Comment by ottigerb** [comment]
Ja, lösen wir mit den bisherigen Event-Typen wirklich nicht elegant.  Habe folgendes Issue eröffnet:
https://github.com/ottigerb/therapy-server/issues/384

**Comment by schoenenb** [comment]
Hat sich erledigt, sorry!
Sonja hat heute von Wale erfahren, dass ab 2017 KEINE 14-tägliche Erhebung mehr benötigt wird. :/

**Comment by ottigerb** [comment]
...also auch kein Verlauf mehr? OK!

**Comment by ottigerb** [comment]
Nur zur Info:  Wir haben nun neue Event-Typen:
https://doc.optinomic.org/V2/Developers/app_spezifikation.html#event-optional-can-have-many

type specifies when the event is triggered. Possible values are:
daily: once a day at a specific time;
weekday: on a specific day of the week at a specific time;
every_x_days: every N days at a specific time;
before_exit: N days before the end of the stay at a specific time;
after_exit: N days after the end of the stay at a specific time;
before_entry: N days before the start of the stay at a specific time;
after_entry: N days after the start of the stay at a specific time;
unplanned: never;
on_activation: when the module is activated for a patient;
on_deactivation: when the module is deactivated for a patient;
once: on a specific date and time;
on_new_entry: when a survey is filled;
every_x_entries: every N survey responses filled.
on_annotation: every time an annotation for this module and a patient is changed;
every_x_annotations: every X times an annotation is changed.
