### ISSUE TITLE
[Optinomic] Anrede - Herr Herrn XY

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#43]
![image](https://cloud.githubusercontent.com/assets/15833792/21516711/f13ea2ee-ccd9-11e6-88d2-c1de8e7997f5.png)

Keine Ahnung, weshalb das zweimal auftaucht. Wenn man's jedoch ganz weglässt (Name + Adresse) erledigt sich das Problem von selbst. ;)
Ev. hat's was mit der Schnittstelle zu tun, bei den händig angelegten Patienten (Ottiger Patient + Fridolin Müller) gibt es diese zweifache Anrede nämlich nicht.

**Comment by ottigerb** [comment]
Lustigerweise hatten Frauen als Titel "Frau" drin. Die Männer wurde nicht "geadelt" durch Mann. Wohl beim Datenimport auf Demo entstanden.  Habe aus dem Adress-Block den Titel entfernt - sollte somit kein Thema mehr sein. Auf der Südhang Umgebung sollten die Titel stimmen - or?

**Comment by schoenenb** [comment]
Nope. Sonst hätte ich's nicht als Issue eröffnet.
Die Adresse kann ganz weg - muss auch nicht unter der "Übersicht" stehen.
![image](https://cloud.githubusercontent.com/assets/15833792/21518922/d970d85c-cce9-11e6-9d46-06c15bb1bc23.png)

**Comment by schoenenb** [comment]
![image](https://cloud.githubusercontent.com/assets/15833792/21518938/f0c9f470-cce9-11e6-95e1-4daf0ffc4e0a.png)

soll ganz weg - da oben
![image](https://cloud.githubusercontent.com/assets/15833792/21518949/02da871a-ccea-11e6-993f-8e0ba8b58ba3.png)

ja bereits alles vorhanden ist.

**Comment by ottigerb** [comment]
Was auf der Startseite eines Patienten (http://demo.optinomic.org/api/#/patient/387) oder auf der Fall-Startseite (http://demo.optinomic.org/api/#/patient/387/stay/43) steht kann mittels:  "Bearbeiten Layout" angepasst werden. Falls Ihr die Adresse auf Eurem System nicht wollt: Delete.

![bildschirmfoto 2016-12-28 um 10 42 26](https://cloud.githubusercontent.com/assets/2470873/21519008/77024d6c-ccea-11e6-99b6-8231491eb4be.png)

**Comment by schoenenb** [comment]
Perfekt - Merci!
