### ISSUE TITLE
Aktuelle Informationen

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#44]
Lieber Beat,

ich hätte noch einige Änderungen, da von den gemeinsam erarbeiteten Graphiken viel verloren gegangen ist, wie Du meinem Mail entnehmen konntest. Diese Änderungen habe ich mit Nora besprochen und es ist schade konntest ihr Euch diesbezüglich am Freitag nicht absprechen. 
Ich kann mit den Berichten vorläufig so leben, auch wenn sie nicht mehr den Stand haben, den wir für die App-Graphiken zusammen erarbeitet haben. Es erstaunt mich nach wie vor, dass Du die Unterschiede nicht siehst. 
Also je nach verbleibender Zeit hat es noch Änderungen. Dann eröffne ich für die grundlegensten Punkte halt neue Issues.

**Comment by ottigerb** [comment]
Nicht hilfreich:  Kein eigentliches Issue!

**Comment by SonjaKaufmann** [comment]
Das stimmt und ich hätte ihm gerne das Label Information gegeben, aber ich weiss nicht wie man ein Label anlegt. Finde es wichtig wenn wir über Github arbeiten, wenn wir uns auch da austauschen können, damit alle auf dem gleichen Stand sind, da wir ja zu verschiedenen Zeiten arbeiten und ich sonst Infos per Mail zwischen Dir und Nora hin und her mailen muss und Mail dann vergessen gehen oder untergehen.
Könntest Du das Label Information für mich anlegen und für dieses Issue vergeben?

**Comment by ottigerb** [comment]
Issues sind `Task's` welche abgearbeitet werden können. Informationen haben hier 'nichts' zu suchen - ansonsten haben wir dann bald 100te Issues welche nie geschlossen werden können. Falls du Informationen hinterlegen möchtest: Eröffne ein WIKI :: https://github.com/Optinomic/apps/wiki und verlinke ein Issue zur entsprechenden Information / Wiki.
