### ISSUE TITLE
[PDF] Assessment :: Hintergründe Z-Graphiken

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#45]
Die grundlegensten Änderungen betreffen die Hintergründe bei den Z-Graphiken (TMT, BSCL, ISK) und ihre Beschriftung. Die Beschriftung mit 1.) und 2.) und so. Da sollte doch eigentlich die klinische Norm bei Eintritt und Austritt mit einer anderen Farbe dargestellt werden und die Legende dazu zum einen gekürzt und zum andern mit der Farbe dargestellt werden.

**Comment by ottigerb** [comment]
- Farbe kann natürlich gesetzt werden - dachte wir wollten sauber "Greyscale" bleiben, damit wir auch auf S/W Print gut aussehen.

- Gekürzte Legende:  Die Texte z.B.:   _Altersgruppe: 35 – 44 | Ausbildungsgrad: > 12 Jahre | Messzeitpunkt: Eintritt | Geschlecht: Alle | Behandlungsart: Alle (N=40)_  stammen aus der Stichprobenberechnung.  Diese können nicht so ohne weiteres gekürzt werden.  Höchstens _Alle_ Angaben könnten weggelassen werden.  Doch dies ist nicht sooo einfach.

**Comment by SonjaKaufmann** [comment]
- Zu den Farben: ja schwarz weiss ist gut, aber es können ja auch hinreichend unterschiedliche Graustufen sein oder auch Blaustufen.

- Eigentlich interessiert für den Ausdruck nur, wie gross die Vergleichsstichprobe war. Für die App kann es ausführlicher sein. Aber für den Bericht würde reichen: Eintritt Suchtpatienten N=xy, und Austritt Suchtpatienten N=xy . Beim BSCL wäre natürlich noch zu unterscheiden Eintritt EAS und Eintritt EP, wenn wir beides darstellen können. Da bin ich nicht sicher wie der Stand ist.

**Comment by ottigerb** [comment]
- Hintergrundfarbe nun wie in App.
- Vergleichsstichprobe:  Nur noch diejenigen "Dimensionen" welche tatsächlich gesetzt sind. Also keine Angaben mehr für z.B. "Behandlungsart: Alle Patienten" mehr.

=> Close!
