### ISSUE TITLE
Stanine und Graphische Darstellungen von Summenwerten

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#46]
Ich dachte wir hätten uns für alle Graphiken und der Einheitlichkeit halber auf Balkengraphiken geeinigt und diese komischen Schiebergraphiken und Punkte nicht geplant.

Dies würde dann den AASE, BDI, und SCI betreffen.

Auch den WHOQL, aber den stellen wir im Bericht  ja nur im Text da.

**Comment by ottigerb** [comment]
Closed because of https://github.com/Optinomic/apps/issues/47

**Comment by SonjaKaufmann** [comment]
Das in 47 sind eben alles andere Graphiken, und keine Balkengraphiken.

**Comment by ottigerb** [comment]
?

**Comment by SonjaKaufmann** [comment]
Wo ist im SCI ein Balken?
Im BDI ist eine Schiebergraphik und im AASE auch. 
Wie gesagt, wenn die Zeit nicht langt, dann später.
