### ISSUE TITLE
AASE und BDI Graphiken in Bericht

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#47]
Diese Bögen sollten im Bericht auch graphisch dargestellt werden.

**Comment by ottigerb** [comment]
Einfache Score-Darstellung für PDF's erstellen:
![bildschirmfoto 2017-01-04 um 11 22 37](https://cloud.githubusercontent.com/assets/2470873/21639431/4217065c-d270-11e6-926a-366b1e9fbf99.png)

Score-Darstellung mit "Ranges" für PDF's erstellen:
![bildschirmfoto 2017-01-04 um 11 23 22](https://cloud.githubusercontent.com/assets/2470873/21639432/422028c2-d270-11e6-89c2-227e01c98aef.png)

**Comment by ottigerb** [comment]
Versuch - `<Z-Score> Grafik` als "Simple-Score" zu verwenden:
![bildschirmfoto 2017-01-20 um 11 31 39](https://cloud.githubusercontent.com/assets/2470873/22146390/c94886d2-df04-11e6-97ac-a207041ecf67.png)

**Comment by SonjaKaufmann** [comment]
Ja genau das meine ich mit Balkengraphik! Nur wenn der Wert angeschrieben ist, dann kann die Skalierung auf jeden 10 Wert oder auf kritische Intervalle z.B. bei BDI angeschrieben werden.

**Comment by ottigerb** [comment]
Wunderbar, dann habe ich "Balkengrafik" verstanden.  :-)

Dazu folgende Anmerkungen:

- PDF-Version:   Hier ist keine Textangabe für den Wert möglich. Diesbezüglich habe ich im `pdfmake`-Projekt ein `+1` für ein bestehendes Issue abgegeben:  https://github.com/bpampuch/pdfmake/issues/674  Ihr könntet hier ebenfalls ein `+1` hinterlassen um die Wichtigkeit zu "forcieren". 

- Selbstverständlich können wir links/rechts | darüber/darunter den Score angeben.  Wie z.B. die Z-Score Grafiken im PDF.

Das Ziel ist ja - PDF & App - einheitlich zu gestalten.  Somit schlage ich folgendes Vor:

- Balkengrafik (ohne Score Angabe)
- Wertstriche:     

1. Es kann gewählt werden, ob `alle "Schritte"` eine Linie bekommen. Gemäss "Versuch - <Z-Score> Grafik als "Simple-Score" zu verwenden"  jedoch ohne die Zahlenangaben 0 ... 80. Allenfalls kann ich auch folgendes versuchen - falls >50 Schritte - nur noch jeden 2. Schritt zeichnen - oder sowas.
2. Es kann `Prozentuale-Schritte` gewählt werden.  z.B.  0,10,20,30,40,50,60,70,80,90,100%.  

- Score
2. Es kann gewählt werden ob das Score dargestellt wird.  Dies `links` (gleich neben der 0)  oder `rechts` (gleich neben der 80).


Das würde dann irgendwie so aussehen:
<img width="1129" alt="bildschirmfoto 2017-01-23 um 11 27 12" src="https://cloud.githubusercontent.com/assets/2470873/22200337/f7bce330-e15e-11e6-8b4f-a4df76723d30.png">

=>Bsp.: Score: links & Prozentuale-Schritte.   Was denkt Ihr?

**Comment by SonjaKaufmann** [comment]
Ich finde wir sollten generell nochmal überlegen, wie und wo wir die MZP anschreiben. Wenn wir es immer drüber oder drunter schreiben, dann nimmt es so viel Platz weg und die Graphiken rücken zu weit auseinander. **Dies gilt allerdings generell.** Ich glaube ich mach da noch ein Issue zu :-)
**Für den AASE:**
hier kann ich mit eine Prozentuale Darstellung gut vorstellen. Dabei müssten eigentlich auch nur die Viertel beschriftet werden. Also 0, 25%, 50%, 75%, und 100%. Dann braucht man den Rohwert gar nicht. Allerdings würde ich die Graphik links benennen wollen, also da bräuchte es eine Textspalte und rechts müsste auch noch Text hin oder oben das auf dieser Seite Maximale Versuchung ist. Also gering und maximal müsste noch dran.  Die Skalierung würde ich oben an die Graphik setzen, dann könnte man die Skalen näher aneinander setzen und nur einmal beschriften. Moment ich mache eine Skizze:
![image](https://cloud.githubusercontent.com/assets/20124244/22734021/79e6fcb4-edf4-11e6-8319-266df7fde830.png)
Dabei fällt mir ein, die Prozentangabe könnte auch nach unten und oben dann die Angabe zur Bedeutung der Ausprägung (Geringe Versuchung, sehr starke Versuchung).

**Zum BDI:**
fände ich es am besten, wenn es so oder so ähnlich wäre:
![image](https://cloud.githubusercontent.com/assets/20124244/22734595/8b7eacea-edf6-11e6-9347-ce27ff7db9a1.png)
Die Beschriftung unten könnte natürlich auch oben sein.
Allerdings machen Prozentangaben hier wenig Sinn, da die Therapeuten so an die Werte gewöhnt sind. Und auch für Berichte braucht man i. d. R. den Rohsummenwert.

**Comment by schoenenb** [comment]
Kann man davon ausgehen, dass dies mit der Neu-Erstellung des PDFs erledigt sein wird?

**Comment by ottigerb** [comment]
Yep. => Close
