### ISSUE TITLE
Textdarstellungen im Bericht

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#48]
Wenn Ergebnisse in Text dargestellt werden, dann muss dennoch folgende Information Enthalten sein:

- Wieviel Punkte von welchem Maximum

- Wofür die Minimal- und die Maximalwerte stehen

**Comment by ottigerb** [comment]
...und das wäre?

**Comment by SonjaKaufmann** [comment]
Da ja aktuell der WHO der einzige in der Art sein sollte, wäre das z.B.: 
80 von 100 möglichen in psychischen Wohlbefinden. Hohe Werte weisen auf ein hohes Wohlbefinden hin.
