### ISSUE TITLE
Keine BSCL

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#50]
Habe mir nochmal die Pdf`s von Patienten anschauen wollen und dabei festgestellt, dass keiner einen BSCL angehängt hat. Ist das richtig so oder muss da noch was gefixt werden. 
Wenn ja dann bitte Issue und sonst schliessen,

**Comment by ottigerb** [comment]
Genau, BSCL-Daten wurden nicht nach demo importiert.  Das ging damals "vergessen".  Entsprechend sind die Klinikstichproben auch nicht "dargestellt" - resp. höchstens mit 2 Messungen oder sowas.

Klappt am 14 bestimmt!
