### ISSUE TITLE
Kriege das pdf nicht in Wiki

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#51]
Habe ein Wiki geöffnet (genereller Aufbau für z-Wert Graphiken), kann aber das folgende pdf nicht dort hineinziehen. Was mache ich falsch?

[Generelle Graphikskizze.pdf](https://github.com/Optinomic/apps/files/686702/Generelle.Graphikskizze.pdf)

**Comment by ottigerb** [comment]
...Du kannst Dir ein Wiki wie ein Word-File vorstellen. Da würdest Du ebenfalls nicht versuchten ein PDF einzufügen. JPG/PNG Bilder einsetzen.  :-)

Bilder kannst Du z.B. via https://postimage.org/ veröffentlichen und dann den "Direktlink" als Bild-URL verwenden.

Ich hab dies mal gemacht:
https://github.com/Optinomic/apps/wiki/Z-Wert-Grafik-::-Genereller-Aufbau

**Comment by SonjaKaufmann** [comment]
Merci!
