### ISSUE TITLE
Data Migration :: V1 => V2

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#52]
Können wir folgende Tabelle nochmals "verifizieren" - nicht dass hier etwas "vergessen" geht!

V1 app | V2 app
--------|--------
BSCL – ANQ (Brief Symptom Checklist) | ch.suedhang.apps.bscl_anq.production
A. ZüPaz | ch.suedhang.apps.zuepaz.production 
Health of the nation outcomes scales (HoNOS) | ch.suedhang.apps.honos.production
A. CASE | ch.suedhang.apps.case.production
The World Health Organization Quality of Life (WHOQOL) – Phys / Psych | ch.suedhang.apps.whoqol.production
act-info - Austritt | ch.suedhang.apps.actinfo_aus.production
Trail Making Test (TMT) | ch.suedhang.apps.tmt.production
Patientenzufriedenheit (Südhang) | _No app_
CASE | ch.suedhang.apps.case.production
Beck-Depressions-Inventar (BDI-II) | ch.suedhang.apps.bdi.production
Inventar sozialer Kompetenz (ISK-K) | ch.suedhang.apps.isk.production
Stress- und Copinginventar (SCI) | ch.suedhang.apps.sci.production
act-info - Eintritt | ch.suedhang.apps.actinfo_ein.production
Alcohol Abstinence Self-Efficacy Scale (AASE) | ch.suedhang.apps.aase-g.production
Screening-Test für Alkoholabhängigkeit (CAGE) | _No app_
Alcohol Use Identification Test (AUDIT) | _No app_
Clinical Global Impression (CGI) | _No app_
A. Einzelassessment |  ch.suedhang.apps.neuroanamnese.production
A. TMT | ch.suedhang.apps.tmt.production
Sozialassessment (Test) | _No app_
Einzelassessment – weitere Angaben | _No app_

Danke!

**Comment by schoenenb** [comment]
- In Patientenzufriedenheit hat's glaube ich keine Daten, da A.ZüPaz denselben Bogen verwendet
- für den CASE ist die id ch.suedhang.apps.case.production - hab aber case.new als parent angegeben, sollte also aufgehen
- WHOQOL hätte ich die id auch auf Südhang gesetzt (also ch.suedhang.apps.whoqol.production)

**Comment by SonjaKaufmann** [comment]
Ist der CGI nicht an den CASE drangehängt und sollte auch mit in die V2 CASE App?

**Comment by ottigerb** [comment]
Tabelle in OP gemäss Angaben Nora überarbeitet.

**Comment by schoenenb** [comment]
@SonjaKaufmann der CGI ist beim HoNOS (stationär) bzw. den act-infos (TK) angehängt.
