### ISSUE TITLE
Planung Einführung

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#53]
Lieber Beat,

die Einführung geht ja von 15:30 -17 Uhr. Ich bräuchte ca. 10 Minuten um die Z-Graphiken vorzustellen und das würde ich gerne einschieben, wenn  Du bei den graphischen Auswertungen bist. Ist das okay für Dich?
Brauchst Du noch irgendwas für die Präsentation? Müssen wir noch irgendwas ausdrucken? Wann kommst Du im Südhang an?

Freue mich auf die Einführung.

**Comment by ottigerb** [comment]
- Genau: "Erklärung der Z-Grafiken" überlasse ich gerne Dir. 
- Ankommen werde ich 13:53 oder 14:23.
- Benötigen:  Ich wüsste nichts - nehme meinen Laptop mit. Hatte gut funktioniert.
- Ausdrucken:  Gute Frage.  M.E. macht es keinen Sinn ein "[Handbuch](https://doc.optinomic.org/)" auszudrucken.   
Allenfalls ein Blatt für die Zugangsdaten:   
Anmeldung unter:  http://optinomic.cust.local/api/#/login
Dokumentation unter: https://doc.optinomic.org/

**Comment by ottigerb** [comment]
...schon NEWS ob das Video etwas "geworden" ist?  

Ich schliesse dieses Issue.
