### ISSUE TITLE
Fehlermeldung bei Anmeldung

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#54]
![image](https://cloud.githubusercontent.com/assets/20124244/21986071/25a05720-dbfe-11e6-87c1-c3e0079722cc.png)

**Comment by SonjaKaufmann** [comment]
+ gateway time out 504
Lieber Beat, 
irgendwie kann ich mich gerade nicht mehr einloggen und Nora hat tricky die Fehlermeldungen für mich kopiert.

**Comment by ottigerb** [comment]
...ja, sehe ich auch - aktuell ist das System wieder "seeeehr langsam" - wir kämpfen gerade mit den fehlenden Klinikstichproben.  Das System berechnet "heiss".  Auch sind schon einige "Optimierungen" in der Pipeline!

=>  Abmelden - Seite: http://optinomic.cust.local/api/#/login neu laden und nochmals anmelden. Doch wie gesagt - sloooow!

**Comment by ottigerb** [comment]
Ich telefoniere mal mit IN4U:

_I noticed the VM is out of memory resulting in calculations failing and restarting sometimes. Is there anyway they could increase the RAM? The VM is using the swap space. It's usually making the whole system very slow so that could be the reason._

**Comment by ottigerb** [comment]
...System musste neu gestartet werden. Wir haben nun  4 CPU / 8 GB RAM!   Bereits meeeerklich schneller!  :-)

**Comment by ottigerb** [comment]
...Anmeldung sollte nun wieder problemlos funktionieren!  :-)    Retry!

**Comment by schoenenb** [comment]
Bin mir nicht sicher, ob's generell wieder langsamer läuft. Weil's vorhin bei neuen Daten laden eine gefühlte Ewigkeit gerädelt hat und ich daneben keinen zweiten Tab für eine neue Person öffnen konnte, habe ich mich abgemeldet.
Bei der Anmeldung kam erst ein gateway timeout 504, kurz darauf erschien trotzdem der Startbildschirm. Falls das was hilft, zwei Auszüge aus der Console (XHR kommt mir Spanisch vor und ob die "Violation" relevant ist weiss ich auch nicht):
![image](https://cloud.githubusercontent.com/assets/15833792/26493899/584ac758-421c-11e7-9f44-6147f2a0769f.png)
![image](https://cloud.githubusercontent.com/assets/15833792/26493831/10649e6e-421c-11e7-841d-58482c717d47.png)

**Comment by ottigerb** [comment]
...ich habe einen "Service" neu gestartet => Sollte nun wieder i.O. sein.

**Comment by schoenenb** [comment]
Oder auch nicht:
http://optinomic.cust.local/api/#/patient/790/stay/471/app/ch.suedhang.apps.aase-g.production
gibt mir diese Nachricht aus:
Diese Website ist nicht erreichbar

Die DNS-Adresse des Servers von optinomic.cust.local wurde nicht gefunden.
Auf Google nach optinomic cust local api suchen
ERR_NAME_NOT_RESOLVED

**Comment by schoenenb** [comment]
Oder doch nicht - im Citrix drin funktionierts.

**Comment by ottigerb** [comment]
Hmm... dieser Link läuft hier einwandfrei. Browser neu starten?
