### ISSUE TITLE
Link in Berichtsübersicht korrigieren

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#55]
Wenn ich auf so einen Bericht klicke
![image](https://cloud.githubusercontent.com/assets/20124244/22012557/e4f4b2c4-dc94-11e6-96f7-7eb094eb5a7c.png)
Dann macht er nicht den gewünschten Bericht auf, sondern springt zu Fridolin Müller. Passiert das wenn der Fall geschlossen ist oder ist das ein allgemeiner Fehler, meine gestern konnte ich Berichte anschauen.

**Comment by ottigerb** [comment]
**Confirmed** :: Link ist "korrupt". Wird gelöst.

Bis dahin:  Anstatt auf "Berichte" zu klicken - direkt auf "Ein- & Austritts-Assessment" Link klicken - dieser Link funktioniert einwandfrei.  Oder auch direkt auf App "_Druckvorlagen".

**Comment by SonjaKaufmann** [comment]
Bei alten Patienten kommen im Moment gar keine Berichte z.B. der Bericht vom 1. Aufenthalt dieses Patienten ist leer, obwohl Bögen vorhanden: Nyffeler Ernst 4.10-27.12.2016
Kann das sein oder mache ich etwas falsch oder ist das vorübergehend?

**Comment by ottigerb** [comment]
...bitte Issues nicht `durchmischen`:  https://github.com/Optinomic/apps/issues/58 eröffnet.

**Comment by ottigerb** [comment]
Fixed with new stable https://github.com/ottigerb/therapy-server/commit/01fbc4a9762c3457ac4f04c7cc0fa7d9d4946db0.
