### ISSUE TITLE
RAP-Verknüpfung: Optinomic V1

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#56]
Hattest du am Donnerstag nicht gesagt, dass der Link bei den Patienten im RAP auf V2 geht?
Nicht so bei Pat. 1391...

**Comment by ottigerb** [comment]
...tatsächlich:  Das hatte funktioniert.  Hmm... habe dieses Issue erneut bei Tom eröffnet.

**Comment by ottigerb** [comment]
Wird morgen durch TOM erledigt.

**Comment by ottigerb** [comment]
Optinomic-Knopf innerhalb Polypoint leitet nun wieder korrekt an V2 weiter.  Yes!
