### ISSUE TITLE
Falsche Messungen bei Patientenfall mit mehreren Aufenhalten

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#59]
Lieber Beat,

bitte schau Dir Mal Pat. 1234 an. Beim aktuellen Fall werden ältere Fälle in den Graphiken mit ausgegeben und bei den Berichten werden unter Austrittsbericht auch ganz viele Fälle in den Graphiken dargestellt.

**Comment by ottigerb** [comment]
...genau.  Wie gesagt, ein V1 - Bug der "geerbt" wurde.  Hier gilt es wie folgt vorzugehen:
https://github.com/Optinomic/apps/wiki/Anleitung-::-Daten-einer-Applikation-in-einen-anderen-Fall-verschieben

...allenfalls müssen wir alle aktuellen Fälle durchgehen und diese gemäss Anleitung "bereinigen".

**Comment by SonjaKaufmann** [comment]
Das ist nicht dein Ernst, oder? 
Der Fehler taucht bei allen aktuellen Fällen auf, die waren doch vorher in Ordnung. Zudem verstehe ich deine Anleitung nicht und habe jetzt etwas Panik, denn ab morgen müssen die aktuellen Fälle eingesehen werden. Ich schicke es mal Nora weiter, die eventuell noch etwas Zeit hat heute am Nami, allerdings auch nur 1-2 Stunden.

**Comment by ottigerb** [comment]
...V1 hatte keine "klare" Falltrennung.  

Allenfalls können wir über das "Messdatum" ein "likely" erzeugen. Im Sinne von:  Wenn die Messung innerhalb von einem "Fallzeitraum" war gehört diese mit hoher Wahrscheinlichkeit zu diesem Fall. Oder gar über die FID in den Fragebögen. Ich kann hier mal eintauchen - habe heute aber ebenfalls wenig Zeit:  Morgen.

**Comment by ottigerb** [comment]
...habe TOM ein Issue eröffnet - hoffe er kann hier was "rausfummeln" um diese Zuordnung möglichst automatisch durchzuführen.

**Comment by SonjaKaufmann** [comment]
Hoffe Nora kann noch etwas nach der Anleitung korrigieren, zumindest für die Fälle die morgen besprochen werden, denn sonst ist der Start mit der V2 für die Therapeuten nicht sehr glücklich. Mhhh und die Therapieleitung muss ich wohl auch vorwarnen, das sie auf die Daten achten müssen. Also dann immer einen Schritt nach dem anderen. Wäre super wenn es eine andere Lösung gibt als alle per Hand zu ändern, denn Fälle von 2 Jahren ist ja doch recht viel Arbeit.

**Comment by ottigerb** [comment]
Kleiner Zwischenstand:

> I'm looking at assigning events to the PUM wich stay is the closest to the event's created_at column. That could be done with a plpgsql function. I'll look at FIDs after but that looks more complicated already.

=>  Wir planen nun die Daten aufgrund dem zugrundeliegenden Event zuzuordnen:  Wenn der Event  innerhalb von stay.start - stay.stop + 14 Tage stattgefunden hat, gehört dieser "most-likely" zu diesem Fall.  Hoffe dies klappt!  Daumendrück in Richtung: Tom!

**Comment by ottigerb** [comment]
Unser `most-likely` Script wurde erfolgreich ausgeführt. Der Server musste dazu zwischenzeitlich - unterbrochen werden - nur falls "Stockungen" deutlich wurden.  

M.E. sieht es nun gut aus - YES - vgl.:
http://optinomic.cust.local/api/#/patient/1234
http://optinomic.cust.local/api/#/patient/609

Prüft doch noch die aktuellen Patienten - welche morgen "angeschaut" werden, ob diese nun soweit stimmen. 

Falls noch irgendwelche "Zuweisungsfehler" vorliegen würden - können wir nun "manuell" migrieren.  Daumendrück, dass es jetzt stimmt.

Falls soweit i.O. =>  CLOSE!

**Comment by schoenenb** [comment]
Leider nein. Ich habe mich eben nochmals abgemeldet, Browser geschlossen, Browser geöffnet und angemeldet: bei den oben aufgeführten Patienten werden nach wie vor alle Messungen im aktuellen Fall angezeigt. Sowohl in der App wie auch in den Berichten.

**Comment by schoenenb** [comment]
PS: Bei den Fällen, welche morgen angeschaut werden, gibt es nur einen Fall, der einen bestehenden Fall hatte. Dafür ist dort der aktuelle Fall noch nicht geladen... Ob alle Daten richtig angezeigt werden, kann ich aber erst nach dem Assessmenttermin sagen, wenn ich die Daten eingegeben habe (ca. 17 Uhr).

**Comment by schoenenb** [comment]
Noch ein Hinweis:
Es werden auch alle Daten (auch die aktuellen) im früheren Fall dargestellt.
Vielleicht zur Verdeutlichung: welchem Fall der Event bzw. ein Fragebogen zugeordnet ist beinhaltet für uns auch, dass die Resultate nur dort dargestellt werden. (V.a. wenn am oberen Rand der App noch der Filter mit dem aktuellen Aufenthalt drin ist.)

**Comment by ottigerb** [comment]
... Genau - beide Fälle zeigen alle Daten.  Darum wird wieder neu
'berechnet'. Calculations sind mit dem Fall verbunden. Es rechnet übrigens
schon. Immerhin sind schon mal die Apps in den alten Fällen.

... Schnittstelle ist Tom dran.

schoenenb <notifications@github.com> schrieb am Mi., 18. Jan. 2017, 14:42:

Leider nein. Ich habe mich eben extra nochmals abgemeldet, Browser
geschlossen, Browser geöffnet und angemeldet: bei den oben aufgeführten
Patienten werden nach wie vor alle Messungen im aktuellen Fall angezeigt.
Sowohl in der App wie auch in den Berichten.

—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/Optinomic/apps/issues/59#issuecomment-273478013>, or mute
the thread

**Comment by schoenenb** [comment]
ok, dann halte ich mich mal zurück mit noch mehr Kommentaren

**Comment by ottigerb** [comment]
### Unser Procedere funktioniert:

http://optinomic.cust.local/api/#/patient/609/stay/1152/app/ch.suedhang.apps.actinfo_aus.production
http://optinomic.cust.local/api/#/patient/609/stay/202/app/ch.suedhang.apps.actinfo_ein.production
vs.
http://optinomic.cust.local/api/#/patient/609/stay/1152/app/ch.suedhang.apps.actinfo_ein.production
http://optinomic.cust.local/api/#/patient/609/stay/202/app/ch.suedhang.apps.actinfo_aus.production

=>  Korrektem Fall zugeordnet und jeder Fall zeigt nur seine zugehörigen Daten.

wobei hier die `calculations` noch nicht durch sind:
http://optinomic.cust.local/api/#/patient/609/stay/1152/app/ch.suedhang.apps.bscl_anq.production
resp.
http://optinomic.cust.local/api/#/patient/609/stay/202/app/ch.suedhang.apps.bscl_anq.production

=>  Alle Daten resp. Fehler.



### Calculations:
Von über 6000 sind nun noch ca. 4850 übrig. =>  Morgen früh sollte somit "alles gut" sein.  Daumendrück!

**Comment by ottigerb** [comment]
...och: nun scheint es als ob die "falsch" zugeordneten Messungen ihre `calculations` ungelöscht zurücklassen - auch nach der Neuberechnung. D.H. alle Apps welche über ng-repeat über `calculations` betreiben zeigen noch immer zu viel Daten an - obwohl `survey_responses` soweit korrekt ist.  

...Zudem sind die Daten von Patienten mit > 2 Fällen noch immer nicht korrekt zugeordnet worden:  Hier benötigen wir wohl noch "etwas" Zeit - Tom ist orientiert.   Hoffe wir haben diese "Zuordnungs - Hürden" ebenfalls bald gemeistert.  Falls Euch noch was auffällt :: Danke für Feedback.

Wir bleiben dran.   

Idea: Habt Ihr morgen Rapport für welches Ihr Optiomic benötigt?  Falls ja: Allenfalls wäre es eine Idee die Berichte schon vorher abzuspeichern, damit diese direkt vom File her geladen werden können.  Nur damit es nicht während des Rapports "stockt".

**Comment by SonjaKaufmann** [comment]
Oh oh, da läuft ja viel! Ich bleibe beim Daumen drücken! Ist ja schon mal gut, dass nun jeder Patient mit seinen Fällen da ist.

**Comment by ottigerb** [comment]
Dieses Issue kann geschlossen werden zugunsten von: https://github.com/Optinomic/apps/issues/62

M.E. haben nun alle "Fälle" die entsprechenden Apps & Daten sind da. Falls nun noch "falsche" Zuordnungen sind, müssen wir manuell "zuweisen"!  

Noch werden immer zu viele Daten - bei bestimmten Apps - angezeigt. Meine Angabe (vgl. oben) bzgl. "zu viele Calculations" ist Quatsch.  Anyway: https://github.com/Optinomic/apps/issues/62
