### ISSUE TITLE
[Generell] Graphikdarstellungen

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#6]
Graphikdarstellung: 
- ISK
  -BSCL
  -SCI
  -AASE
  
  gemäss den gesendeten Skizzen, aber erst sinnvoll, wenn die Z-Sachen funktionieren, sonst müssen wir es ja zweimal machen.
  Oder findest Du es sinnvoll eine T-Wert/Stanine-Darstellung zu haben und äquivalent eine Z-Wert-Darstellung?
  [02 SCI.pdf](https://github.com/Optinomic/apps/files/538588/02.SCI.pdf)
  [03 ISK-K.pdf](https://github.com/Optinomic/apps/files/538592/03.ISK-K.pdf)
  [BSCL_Skizze.pdf](https://github.com/Optinomic/apps/files/538590/BSCL_Skizze.pdf)
  [ISK_Skizze.pdf](https://github.com/Optinomic/apps/files/538589/ISK_Skizze.pdf)
  [SCI_Skizze.pdf](https://github.com/Optinomic/apps/files/538591/SCI_Skizze.pdf)

**Comment by ottigerb** [comment]
...sobald wir die Klinikstichproben #8  haben - hoffentlich bald.  Gehen wir die Z-Wert Darstellung an. 

=> Idealerweise eröffnen wir für jede App ein einzelnes Issue.  Werde dies sobald #8  geschlossen ist vornehmen.

**Comment by ottigerb** [comment]
Beat mitteilen, Normstichproben mitteilen. Wie wird Z-Wert errechnet?

**Comment by SonjaKaufmann** [comment]
Das sind die Normen für den BSI, es wird getrennt nach Männern und Frauen.

![image](https://cloud.githubusercontent.com/assets/20124244/19923840/9d06e356-a0e9-11e6-8a36-4c7398e0d0b6.png)

Die Klinischen Gruppen sollen eingeteilt sein in : 
1. Männer oder Frauen
2. EAS oder EP
3. Eintritt oder Austritt

Für die Gruppe Eintritt EP ist zu beachten, das diese aus den Übertritten EAS->EP (bei Kombiprogramm) und den Eintritten "nur EP" besteht.

**Comment by ottigerb** [comment]
Cool - Danke!  BSI wohl BSCL - oder?

#### Klinikstichporbe:

Zu 1.)  Klar      

Zu 2. / 3.) Wir haben folgende Fragen im Fragebogen: 

<img width="931" alt="bildschirmfoto 2016-11-02 um 11 02 04" src="https://cloud.githubusercontent.com/assets/2470873/19924385/f9b075f2-a0eb-11e6-9207-ea8d9ad9924d.png">

http://limesurvey.optinomic.org/index.php/survey/index/action/previewquestion/sid/693172/gid/6/qid/70/lang/de#

und

<img width="937" alt="bildschirmfoto 2016-11-02 um 11 01 38" src="https://cloud.githubusercontent.com/assets/2470873/19924371/eccf358a-a0eb-11e6-9465-90ccfe7d2552.png">

http://limesurvey.optinomic.org/index.php/survey/index/action/previewquestion/sid/693172/gid/6/qid/70/lang/de#

Wie ich verstanden habe soll hier für 2./3. eine Kombinatorik aus diesen Fragen erstellt werden - oder?    Bin unsicher, wie _Für die Gruppe Eintritt EP ist zu beachten, das diese aus den Übertritten EAS->EP (bei Kombiprogramm) und den Eintritten "nur EP" besteht._ verstanden werden soll.

**Comment by schoenenb** [comment]
Ja genau, BSI = BSCL :)
Wenn ich's richtig verstehe sollen für die Vergleichsstichprobe der EP sowohl die Daten von Personen mit MZP = Eintritt && Eintritt in... = Entwöhnungsbehandlung || MZP = Übertritt mit einbezogen werden.

@ Sonja: das hiesse dann auch, dass Personen mit Kombiprogramm zwei Mal in der Stichprobe "auftauchen" werden, oder?!

**Comment by SonjaKaufmann** [comment]
Also ich kann nur sagen wie ich es für die Berechnungen der Klinischen Normen mit Excel gemacht habe. Vielleicht hilft das ja.
Dort brauchte ich Werte Eintritt EAS und da konnte ich ja einfach den Messzeitpunkt Eintritt in Entzug nehmen.
Dann brauchte ich die Werte mit denen die Patienten in die Entwöhnung starten und das sind zum einen die Patienten die vom Entzug in die Entwöhnung wechseln und einen Übertrittsmesszeitpunkt haben und die Patienten die nur die Entwöhnung bei uns machen, also Eintritt "nur EP".
Beim Austritt ist es ähnlich, denn da tritt Mann/Frau ja entweder aus EAS aus oder wenn sie übertreten, dann ist der Übertrittswert der Austrittswert aus EAS, also wieder 2 Gruppen zusammengenommen und dann git es noch Austritt EP.
Die Patienten, die im Kombiprogramm sind tauchen tatsächlich 2 Mal auf, bzw. sind zum einen mit ihrem Eintrittswert in EAS enthalten und bei EP mit ihrem Übertrittswert. Und sie sind auch mit mit dem Übertrittswert in Austritt EAS enhalten und dann nochmal mit ihrem Austritt EP-Wert.

Alternativ müssten wir sonst nach unseren 3 Behandlungsgruppen (EAS, EP und Kombi) einteilen können und da haben wir ja keinen Zugriff drauf. Wobei mit Kombinatorik wäre das ja aus dem BSCL-Daten herauszuholen, aber ich glaube es reicht wenn wir die  2 Programme vergleichen, denn nach meinen anderen Analysen unterscheiden sich die Eintritts- und Austrittswerte  von Kombi Eintrtitt in die EP und nur EP nicht sehr stark. Also reichen die 2 MZP.

**Comment by ottigerb** [comment]
Label `wontfix`:  Da dieses Issue zu Generell ist 
=>  Inhalte auf :  Einzelne App-Issues verteilen:  BSCL:  z.B. nach:   https://github.com/Optinomic/apps/issues/25

**Comment by schoenenb** [comment]
Kann man dieses Issue schliessen, oder braucht jemand von euch die Unterlagen mit den Skizzen / Normangaben für den BSCL?
