### ISSUE TITLE
Patienten haben keine Startseite

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#60]
z.B. http://optinomic.cust.local/api/#/patient/2451
Eintritt am 16.1., sollte also aktiviert sein, nicht?!

Anzeige:
![image](https://cloud.githubusercontent.com/assets/15833792/22064097/4b5e8e7a-dd82-11e6-8c43-05007a02eb79.png)

**Comment by ottigerb** [comment]
...abmelden.  Login Seite neu laden und erneut anmelden.   Allenfalls auch einfach Seite aktualisieren.

**Comment by schoenenb** [comment]
und wenn das alles nicht funktioniert?

**Comment by ottigerb** [comment]
Browser komplett schliessen und wieder starten.

**Comment by schoenenb** [comment]
Habe zuerst neu geladen via F5, dann mit dem Refresh innerhalb Optinomic, dann abgemeldet und neu angemeldet - nix.
Die Therapeutin hat heute auch schon 15 Minuten dran rumversucht...

**Comment by ottigerb** [comment]
...oh, dies bezieht sich wohl nur auf patient:  2451.   Findet Ihr diesen unter "alle Patienten" suchen?  Allenfalls hat die Schnittstelle diesen resp. den Fall nicht exportiert.  Versuch in PABS am Fall etwas zu verändern, damit die Schnittstelle neu exportiert.

**Comment by ottigerb** [comment]
...aktuell ist das System wieder sehr langsam ->  Calculations müssen nun aufgrund des Fallwechsels wieder neu berechnet werden.  Ufff....   und auch dies lösen wir... irgendwie!  :-)

**Comment by schoenenb** [comment]
Ja, unter alle Patienten habe ich ihn gefunden, sonst hätte ich die Seite auch gar nicht aufrufen können...

**Comment by schoenenb** [comment]
http://optinomic.cust.local/api/#/patient/2482 ebenfalls - dort müsste ich heute die Assessment-Daten eingeben können

**Comment by schoenenb** [comment]
Ist es möglich, dass es ab einer bestimmten Nummer keine Daten mehr geladen/ Patienten erstellt hat?

**Comment by ottigerb** [comment]
...genau so einem Verdacht sind wir auf der Spur:  Schnittstelle allenfalls noch in V1 geschrieben oder sowas.

**Comment by ottigerb** [comment]
> Oh yes, you're right. There were two CIS importer running every 10 minutes: one for V1 and one for V2. I guess the importer of V1 stole the data before the one for V2 had a chance to read them.

=>  Wird wiederhergestellt.

**Comment by schoenenb** [comment]
Innert nützlicher Frist oder braucht das länger?

**Comment by ottigerb** [comment]
...ich denke das Schnittstellenproblem "schaffen" wir!  

...das Thema Fallzuordnung muss wohl nochmals "vertieft" werden... sorry for trouble!

**Comment by schoenenb** [comment]
erstmal ginge es mir "nur" um die Schnittstelle - aufräumen kann man immer noch, aber je später die aktuellen Fälle kommen, umso mehr muss ich nachtragen und da schon aufräumen :)

**Comment by ottigerb** [comment]
YEP - dies sollte klappen!  

...wir müssen dann wieder einmal "recalculate" - damit die Berechnungen wieder mit den neuen Fällen/Daten übereinstimmen - in sync ist quasi.

**Comment by schoenenb** [comment]
Kann so was auch mal am Wochenende / ausserhalb der Arbeitszeiten gemacht werden? Lässt sich einfach fordern, wenn man selber nicht betroffen ist, aber wär halt schon gäbig...

**Comment by ottigerb** [comment]
...prinzipiell ja schon.  Dies ist "normalerweise" auch nicht nötig - doch da wir nun doch so einige Daten "verschieben" mussten - nötig.  Ansonsten werden "wirre" Daten angezeigt, was ja wohl auch nicht gewünscht ist.  Wird guuut - baaaaald!   Ich wünsche es mir!   Freu mich auf "Migration" finally done!

**Comment by ottigerb** [comment]
V2 Schnittstelle funktioniert nun einwandfrei. 
### :-)  

Daten welche dummerweise noch in der V1 "gelandet" sind, sind ab sofort in der V2 verfügbar.

Bsp.:
http://optinomic.cust.local/api/#/patient/2451
http://optinomic.cust.local/api/#/patient/2482


Keine "Startseite" bedeutete - kein Fall vorhanden. 
=>  Close

**Comment by ottigerb** [comment]
=>  Jetzt haben die Patienten ihr "Geschlecht" verloren.  Hurra!  *würg*

**Comment by ottigerb** [comment]
Mann/Frau ist gesetzt: We now have 773 women and 1637 men!
