### ISSUE TITLE
Apps :: Alle Falldaten :: Do not loop over calculations!

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#62]
"Rewriting" some parts of the apps needed:  

Loop über `calculations` vermeiden:  Stattdessen über `survey_results`!  Ansonsten werden zu viele Daten im entsprechenden Fall ausgegeben.  `calculations` sind immer ein "patient/module pair". Allenfalls später erweitern auf "patient/stay/module pair".  Doch vorerst: rewrite apps!

**To Do** : Stand
- [x] ch.suedhang.apps.aase-g.production
- [x] ch.suedhang.apps.bdi.production
- [x] ch.suedhang.apps.bscl_anq.production
- [x] ch.suedhang.apps.case.production
- [x] ch.suedhang.apps.neuroanamnese.production
- [x] ch.suedhang.apps.isk.production
- [x] ch.suedhang.apps.sci.production
- [x] ch.suedhang.apps.tmt.production
- [x] ch.suedhang.apps.whoqol.production
- [x] actInfo Ein & Aus
- [x] ch.suedhang.apps.sci.production
- [x] ch.suedhang.apps.honos.production

**Comment by ottigerb** [comment]
Apps zeigen ab sofort nur noch zugehörige Daten.  Juhuuu!   Das ich/wir diesen Effekt nicht schon früher erkannt haben - unglaublich.  Na ja - viel gelernt!  :-)

PDF:  TMT/BSCL/ISK/SCI sicher auch - werde ich jedoch nochmals genauer prüfen.  Ich glaube "Datenmigration" ist bald abgeschlossen! YES!

**Comment by SonjaKaufmann** [comment]
Auf jeden Fall ist schon viel mehr da und auch nicht mehr zuviel, es wird immer besser.
Habe aber zufällig einen Fall gefunden, dessen Daten verschwunden sind. Die Optinomic ID 1702 hat beim stationären Aufenhalt unter der FID 11411 Fall 02 das ganze Assessment ausgefüllt und ist auch in unseren letzten Backups von V1 enthalten. In V2 hat sie nur Act-Info Daten.
Kann das sein?
Sonst müssen wir Exporte machen und mit den Back-up-Dateien abgleichen. Oder was meint ihr?

**Comment by ottigerb** [comment]
Kann das sein?  
=>  Jein!   Guter Fund - Danke!    :-)


### Analyse:
http://optinomic.cust.local/api/#/patient/1702/stay/721/apps

```SQL
SELECT  * 
FROM survey_response 
INNER JOIN patient ON(survey_response.patient = patient.id) 

WHERE patient.id = '1702'
```

=>  Alle Daten sind grundsätzlich da:  Export-Toolbox würde somit alle vorhandenen Daten erfolgreich exportieren. Keine Daten sind "verloren"!  Soweit ja schon mal gute Nachricht.


```SQL
SELECT  * 
FROM event 
INNER JOIN patient ON(event.patient = patient.id) 

WHERE patient.id = '1702'
```
=>  Zeigt nun lediglich 8 "events" an.  Hier müssen wir wohl noch "Fake event for migration to V2" erstellen. Tom ist informiert und schaut sich dies nochmals an.

**Comment by ottigerb** [comment]
Tom hat erneut gezaubert:

> There were 651 missing events on survey responses where the module was not activated for the patient. Hopefully it should be fine now.


Aktuell zeigt z.B.
http://optinomic.cust.local/api/#/patient/1702/stay/721/app/ch.suedhang.apps.bdi.production
noch "Keine Daten vorhanden" an.

Die neu aktivierten Apps werden Ergebnisse darstellen sobald die `calculations` dafür durchgeführt sind.  M.E. sind nun alle Daten "sichtbar" und "korrekt" dem entsprechenden Fall zugeordnet. Auch zeigen die Apps nur noch entsprechende Daten an.  Ich habe viel über "Optinomic" gelernt.  :-)


=>  Calculations abwarten & dann `Close`.

**Comment by SonjaKaufmann** [comment]
Tom ist Mr. Magic :-)

**Comment by ottigerb** [comment]
Wirklich!   👍

**Comment by ottigerb** [comment]
Done - Confirmed :: Alle Daten sind da und "berechnet".
