### ISSUE TITLE
Druckvorlage: Patientenassessment

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#63]
Sie finden auf unserer Fragebogen-Plattform einige Fragebögen, in denen Sie Aussagen zu
verschiedenen Themen und Zeiträumen einschätzen sollen. Am Anfang jedes Fragebogens
finden Sie eine kurze Anleitung. Lesen Sie diese bitte sorgfältig durch. Achten Sie dabei auf die
hervorgehobenen Angaben zu den Zeiträumen, auf die sich die Fragen und Aussagen beziehen.
Diese können von Fragebogen zu Fragebogen unterschiedlich sein.

Alle Fragebögen enthalten Aussagen. Ihre Aufgabe ist zu bewerten, inwieweit diese Aussagen
auf Sie bzw. Ihre Situation zutreffen. Antworten Sie möglichst spontan – es gibt keine richtigen
oder falschen Antworten. Wichtig ist, dass die jeweilige Antwort für Sie persönlich stimmt. 
Wir bitten Sie, die aufgeführten Fragebögen in der bestehenden Reihenfolge lückenlos zu
bearbeiten. Zum starten JEDES EINZELNEN Fragebogens klicken Sie am rechten Rand des
angegebenen Fragebogens auf „START“.
Wenn Sie einen Fragebogen fertig bearbeitet und abgeschickt haben, schliessen sie den entsprechenden Tab und gelangen somit wieder auf die Startseite.

Falls Sie Fragen nicht verstehen oder etwas unklar ist, wenden Sie sich an die anwesende
Betreuungsperson.

**Comment by ottigerb** [comment]
Text gemäss Angabe in Druckvorlage übernommen:

![bildschirmfoto 2017-01-23 um 08 47 18](https://cloud.githubusercontent.com/assets/2470873/22195496/9d3a007a-e148-11e6-8923-45370667a4e7.png)

**Comment by schoenenb** [comment]
Oh, danke! Daran wollte ich mich eben setzen.

**Comment by SonjaKaufmann** [comment]
Ich bin nicht sicher, ob jeder Patient weiss was ein Tab ist. Auch das absenden finde ich fraglich, bessere wäre m.E. abschliessen.
Dann noch ein kleiner Fehler: 2. Zeile Sollen.Am Anfang -> Da fehlt die Lücke nach dem Punkt
Dann noch 2. Abschnitt 2.Satz: Ihre Aufgabe ist **es** zu bewerten, inwieweit...
