### ISSUE TITLE
Limesurvey: Fragebogen-Darstellung gleich

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#64]
- [x] AASE-G
- [x] BDI-II
- [x] BSCL
- [x] ISK-K
- [x] SCI
- [x] WHOQOL-BREF
- [x] ZüPaZ

- [x] CASE
- [x] HoNOS
- [x] Neuroanamnese (Einzelassessment)

- [ ] Act-info Eintritt
- [x] Act-info Austritt

**Comment by schoenenb** [comment]
Wie wär's damit?
![image](https://cloud.githubusercontent.com/assets/15833792/24050402/01fce238-0b2f-11e7-897b-6b423b1d663a.png)

links bisher - rechts mit Anpassungen

**Comment by ottigerb** [comment]
Du meinst in Bezug auf https://github.com/Optinomic/apps/issues/103?  Die `Anzahl Therapieabbrüche` zu erfassen wäre natürlich ein easy-one.  Und falls dies bereits ausreicht: Perfekt!  :-)

**Comment by schoenenb** [comment]
Nope, geht nur ums Layout (Kasten um Eingabefeld) - im Beispiel halt der CASE (der wird nur beim Eintritt gemacht, drum beinhaltet das glaube ich die Frage in #103 nicht) :)

**Comment by ottigerb** [comment]
...jä so.   Sonja wird es wohl gefallen.  Ich find's gut wenn's Euch gefällt!  ;-)

**Comment by SonjaKaufmann** [comment]
Stimmt, ich finde es super!

**Comment by schoenenb** [comment]
Das Limesurvey-Layout ging irgendwie etwas vergessen. Macht es noch Sinn für dich @SonjaKaufmann das anzupassen, oder wollen wir das vergessen und an der Umsetzung zu ng-surveys arbeiten?
