### ISSUE TITLE
BSCL durcheinander

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#65]
Im Bericht von 2482 und wahrscheinlich auch bei den anderen sind mir 2 Probleme aufgefallen:

- [x] im Eintrittsbericht haben die Graphiken des BSCL die klinische Norm schwarz dargestellt. 
![image](https://cloud.githubusercontent.com/assets/20124244/22200348/0703ca98-e15f-11e6-8c22-f31c5760a842.png)

- [x] In der Graphik der App (nicht im Bericht, da ist es richtig) BSCL ist die Reihenfolge der Ergebnisskalen verkehrt herum. es sollte mit Somatisierung anfangen und mit dem GSI aufhören.

**Comment by ottigerb** [comment]
Fixed  -  check:
http://optinomic.cust.local/api/#/patient/2482/stay/1208/app/ch.suedhang.apps.pdf_druckvorlagen
http://optinomic.cust.local/api/#/patient/2482/stay/1208/app/ch.suedhang.apps.bscl_anq.production


**Beschreibung**:  Wir hatten Farben nicht für alle Messzeitpunkte definiert:

Falls die Farben angepasst werden sollen in `main.js` in der Function: `$scope.changeClinicSample` :
```JS
// Austritt EP / Übertritt EP / Austritt EAS / Austritt EP
var cs_color = ['#9E9E9E', '#EEEEEE', '#E8EAF6', '#BDBDBD', '#BDBDBD'];
```
