### ISSUE TITLE
Patientenassessment: Zuweisung der Fragebögen

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#66]
Wie lange bleibt die Zuweisung der Fragebögen bestehen?
Ich habe zur Vorbereitung des Assessments heute Mittag um 13 Uhr für alle Patienten die Fragebögen als Aufgabe patient_via_assessment zugewiesen.
15 Minuten später: Surprise - bei der Anmeldung sind keine Aufgaben mehr offen!?
Auch die Zuweisungen danach bricht es immer wieder ab.

Wo liegt das Problem???

**Comment by ottigerb** [comment]
Hmmm.... die erstellten Events sollten "ewig" bestehen. 

Confirmed:: Something is wrong here:  https://github.com/ottigerb/therapy-server/issues/412

**Comment by ottigerb** [comment]
### Fixed!  

Gemäss Aussage von Tom benötigen "Events" ein `due-date` was anscheinend bei "manuell erzeugten - Patienten-Assessment Events" nicht "korrekt" gesetzt wurde.  Dies hatte auf jeden Fall funktioniert - keine Ahnung sei wann dies nicht mehr funktionierte...   anyway:

-  Solche "Patienten-Assessment" Tasks sollen wie lange "gültig" sein?   
=>  24h oder 2 Wochen?

**Comment by ottigerb** [comment]
Aussage von Tom:   **Jäää sooo!**

> Okay I've increased it to 2 weeks. A new stable is building.
Actually it's slightly more complicated than that. After 2 weeks, the overdue reminder will pick the event and look at the value in the column overdue. For OverdueIgnore, it will mark the event as aborted, for OverdueIgnoreAsOf, it will mark it only after the specified delay, for OverdueSendReminder it will send an email and for OverdueSendReminderOnce it will send an email and change the value to OverdueIgnore so next time it runs, it will be aborted.


=>  Die manuellen Events halten somit 2 Wochen was m.E. gut ist.   
       Close!

**Comment by schoenenb** [comment]
Merci!!! :+1: 
Gute Aussichten für den zweiten Anlauf am Mittwoch!

**Comment by ottigerb** [comment]
Gerne:  Wird klappen am Mittwoch!   :1st_place_medal:
