### ISSUE TITLE
Optinomic: Fall-Startseite

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#67]
![image](https://cloud.githubusercontent.com/assets/15833792/22207112/2c9cab70-e17e-11e6-9d26-5f4e37dedb9f.png)

...komische Aussage. Herr Herrn hatten wir glaube ich schon. Dafür sollte statt 0. Tag, 1. Tag der Behandlung stehen.

**Comment by ottigerb** [comment]
Fixed: https://github.com/ottigerb/therapy-server/commit/92484b1c08691e5d53cd1c71c7f4caeff23f5bb6

=>  Wird mit dem nächsten "Stable-Build" verteilt.
