### ISSUE TITLE
Berichte extrem langsam und Zusammenstellung wie früher

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#68]
Lieber Beat,

ist Optinomic im Moment noch etwas am verarbeiten und bis wann dauert das ungefähr? Denn die Berichte sind im Moment urlangsam, so dass sich die Therapeutischen Leiter und Therapeuten das alte Optinomic V1 zurückwünschen! Weil es so lange dauert die Berichte zu laden, hätten sie gerne eine Zusammenstellung der Ergebnisgraphiken wie früher, also alle App-Graphiken untereinander. Soweit ich mich erinnern kann, sollte es ja eigentlich möglich sein die Graphiken die man z.B. regelmässig für die Fallkonferenz braucht einmalig zusammenzustellen (ähnlich dem druckbaren Bericht) und auf dem Bildschirm anzuschauen und es sollte schneller gehen als der druckbare Bericht, oder? Könntest Du so eine Vorlage "**Fallkonferenz EP**" mit den folgenden Graphiken:
- Trinkmenge und Audit und Fagerströmwert aus Act-Info
- TMT
- BSCL
- HoNOS
- BDI
- ISK
- SCI 
- AASE
- WHOQOL 
zusammenstellen und für die "**Fallkonferenz EAS**" 
- TMT
- BSCL  
- HoNos
Oder noch besser wäre natürlich, wenn Du mir eine Anleitung geben könntest, wie ich solche Vorlagen erstellen kann. Für uns ist es nicht wünschenswert, wenn dies jeder Psychologe selber machen kann, aber als Admin-Rolle wäre es gut zu wissen.
Am besten wäre noch, wenn sie es diesen Donnerstag verwenden könnten, damit sie nicht noch mehr abhängen bei V2!

**Comment by SonjaKaufmann** [comment]
Ach die EAS haben ja gar keinen TMT, sorry!

**Comment by ottigerb** [comment]
...Performance ist m.E. aktuell sehr gut.  Berichte laden hier schnell.   Unter "Berichte" können wir einzelne "Views" von verschiedenen Apps anordnen.  

...Für eine Fallkonferenz ist es auch denkbar, die einzelnen "Assessment-PDF" für alle relevanten Patienten bereits zu öffnen/speichern.

**Comment by SonjaKaufmann** [comment]
Genau solche Views meine ich, denn sie wollen sich nicht lange vorbereiten oder Berichte schon speichern, sondern in der Konferenz draufklicken und nicht lange warten und nicht jeden Bogen einzeln anklicken.
Und so Views sollten ja schneller gehen als ein druckbarer Bericht, oder. Wenn man es für einen Patienten macht, dann geht das mit der Wartezeit, aber in dieser Konferenz ist es sonst mühsam.
Also wie kann man die oben beschriebenen Views "Fallkonferenz EP" und "Fallkonferenz EAS" unter ertsellen? Eben sie müssen nicht zum Ausdrucken sein, daher hätte ich sie nicht unter Berichte gesehen, sondern eher unter einem Punkt wie **Zusammenfassung**.

**Comment by SonjaKaufmann** [comment]
Lieber Beat,

vielen herzlichen Dank! Super hast Du das schon umgesetzt. Es ist interessant, es braucht länger zum laden als der druckbare Bericht, das hatte ich nicht erwartet, aber beides finde ich verhältnismässig schnell ! Vor allem der TMT scheint "lange" zum laden zu brauchen, aber eben ich denke es ist im Rahmen einer möglichen Wartezeit. Heute morgen haben Berichte noch vieeeeeeeeeeeeeeeeeeel länger gebraucht.

Mir ist noch aufgefallen, dass bei manchen Patienten z.B. 2273 beim Fagerström erscheint, dass der Wert 999 sei. Ich nehme an, dies ist eine alte Missing-Codierung oder steht für Nicht-Raucher. Das müssten wir noch korrigieren. Sonst steht da nämlich bei den Nicht-Rauchern 999 und damit Extrem starke Abhängigkeit.

**Comment by ottigerb** [comment]
...Gerne!  Versucht mal ob diese "Berichte" praxistauglicher sind.  Diese sind ziemlich aufwändig und der Server wird ordentlich mit Anfragen befeuert.  


Speed:
-  Ich denke es ist wichtig - nicht jedes Mal im Polypoint auf den Optinomic Knopf zu drücken. Navigiert von Patient zu Patient innerhalb der Fallkonferenz direkt in Optinomic.  Ansonsten wird die ganze Initialisierung jedes Mal neu vorgenommen.

- ISK :: Habe ich ein Fehler korrigiert. Da gab es wohl solche ohne "Messzeitpunkt" - allenfalls hatte auch dies zu Verzögerung geführt. Da der Messzeitpunkt nicht korrekt erkannt wurde. Aktuell wird _Druckvorlagen sehr schnell geladen.


Hintergrund:
-  Tom hatte noch etwas "vergessen" - entsprechend musste/muss der Server wieder "arbeiten".  Dies ist nun hoffentlich endgültig "beendet" und das System kann sich stabilisieren.


Bzgl. actInfo => Neues Issue eröffnen - Danke!  :-)

**Comment by SonjaKaufmann** [comment]
Einen Moment später habe ich die Fallskonferenz-Berichte auch Mal für Austritte angeschaut und festgestellt, dass dort wieder diese Karusell-Graphiken (wie Nora sie nennt) drin sind. Ich dachte die hätten wir abgeschafft. Ich weiss gar nicht warum wir die überhaupt haben, ich finde dies in keinem Fall übersichtlich oder hilfreich.
Ist es für die Fallkonferenz-Zusammenstellungen auch möglich die Messzeitpunkte die vorhanden sind so wie im druckbaren Bericht und wie früher untereinander darzustellen und keine Karuselle zu verwenden? So müssen sie, wenn sie einen Austritt besprechen wollen ja nochmals zusätzlich zu den anderen Messzeitpunkten klicken und haben die MZP nicht beieinander im Blick. 
Sorry, aber unsere Therapeuten sind von V1 bzgl.  alles auf einen Blick bzw. nur mit abbescrollen verwöhnt. Und das wollen wir mit V2 ja noch irgendwie toppen!

**Comment by SonjaKaufmann** [comment]
Die Geschwindigkeit mit der Du in V2 Sachen umsetzen kannst ist schon phänomenal!

**Comment by ottigerb** [comment]
Karusell-Grafiken:  Ja, das ist so - noch einige Apps verwenden diese. Natürlich können diese "umgebaut" werden.  Können wir ja als Issue planen.  Und Daaaanke für das Kompliment:  Dein Phänomenal tut mir gerade seeeehr gut!  Yes!

Ich schliesse dieses Issue.

**Comment by SonjaKaufmann** [comment]
In den Austritten die gestern ihr Austrittsassessment hatten ist der Austrittszeitpunkt im ISK als undefined angeschrieben: 2294, 2225, 1184, 2372

**Comment by SonjaKaufmann** [comment]
Neues Issue für den Punkt eröffnet, daher wieder geschlossen.
