### ISSUE TITLE
Fagerströmwert aus Act-Info

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#69]
Bei manchen Patienten wird der Wert 999 im Fagerstöm ausgegeben und sie werden als extrem Nikotinabhängig klassifiziert.
z.B.  Patienten 2273
Ich nehme an, dies ist eine alte Missing-Codierung oder steht für Nicht-Raucher. Das müssten wir noch korrigieren. Sonst steht da nämlich bei den Nicht-Rauchern 999 und damit extrem starke Abhängigkeit.

**Comment by ottigerb** [comment]
Soweit "fixed" - lediglich beim Austritt PDF muss ich wohl noch genauer hinschauen. Wenn die Abstinenzmotivation missing is z.B. 
=> Doch schon mal etwas besser.

**Comment by ottigerb** [comment]
### Done:

http://optinomic.cust.local/api/#/patient/2273/stay/1039/report/ein____austritts_assessment
<img width="714" alt="bildschirmfoto 2017-01-25 um 10 33 07" src="https://cloud.githubusercontent.com/assets/2470873/22284978/032624de-e2ea-11e6-991a-d8bd00e805cb.png">

http://optinomic.cust.local/api/#/patient/2294/
<img width="655" alt="bildschirmfoto 2017-01-25 um 10 32 21" src="https://cloud.githubusercontent.com/assets/2470873/22284979/03276b96-e2ea-11e6-8407-a2e354005285.png">
