### ISSUE TITLE
[Dokumentation]  Bericht als PDF-Drucken (via Browser)

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#7]
In der Berichtfunktion sollte eine fixe Vorlage mit bestimmten Graphiken festgelegt werden. (BSCL, ISK, SCI, BDI, TMT, AASE)
- Bericht Eintritt: mit den besagten Eintrittswert-Graphiken
- Bericht Austritt: Mit Eintritt und Austrittswert-Graphiken
- Das Ganze sollte dann im **Hochformat** einen "Bericht" liefern, den man dann **ausdrucken** kann. Dabei sollen die Graphiken natürlich nicht verzogen werden.
- Es sollte für die Therapeuten eine **kurze Anleitung** geben, wie sie den Graphik-Bericht aus dem Browser drucken können (solange wir kein drucken-Icon einbauen können).

**Comment by ottigerb** [comment]
...das ist nur via Apps möglich.  

Reporte resp. Berichte wie: http://demo.optinomic.org/api/#/patient/1/stay/144/report/assessment 
zeigen "Templates" der gewählten Apps an.  Die "Reporte" sind somit "dumm" - d.h.: falls nur "Eintrittsmessungen" angezeigt werden sollen - muss die entsprechende App ein solches Template zur Verfügung stellen.  Eine solche Logik muss somit in den jeweiligen Apps vorgenommen werden.

### Issue here is

Dokumentation:  "Bericht drucken (via Browser)" erstellen und unter Berichte 'verlinken'.

**Comment by SonjaKaufmann** [comment]
Das habe ich jetzt nicht ganz verstanden mit den Apps. Weiss auch nicht ob ich es verstehen muss. 
Auf jeden Fall dachte ich die Berichte-Sache wäre dafür da. Wohl nicht, mhhh.
Wie machen wir es, dass die Therapeuten einen übersichtlichen Ausdruck der Ergebnisse bekommen, welchen sie bei Eintritt und auch bei Austritt mit dem Patienten besprechen und sogar ggf. dem Patienten abgeben können? Das ist mir extrem wichtig, ein absolutes Must!
Kriegst Du oder Du und Nora das hin?

**Comment by schoenenb** [comment]
Ich hatte das so verstanden, dass wir die bestehenden "flexiblen" Templates als _report_only-Templates mit statischem Inhalt abändern können. Und da bei Eintritt noch keine Austrittswerte vorhanden sind, sollten entsprechend auch nur die Eintrittswerte angezeigt werden. 
Was ich allerdings nicht bedacht habe: wenn wir die Grafiken so anpassen, dass sie ein "schönes" Eintritts-Reportingsheet ergeben, kann es dies bei zusätzlichen Werten bei Austritt wieder verziehen. Weiss grad nicht, wie wir das schlau lösen können.

**Comment by schoenenb** [comment]
aufgrund #35 geschlossen
