### ISSUE TITLE
Keine Karusellgraphiken mehr

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#70]
Bei Apps die noch Karusellgraphiken enthalten diese durch eine kompakte Darstellung der Ergebnisse untereinander ersetzen.

Gilt für (zu ergänzen):

- [x] BDI
- [x] AASE

**Comment by ottigerb** [comment]
**BDI - Done**:
http://demo.optinomic.org/api/#/patient/1/stay/144/app/ch.suedhang.apps.bdi

**Comment by ottigerb** [comment]
**AASE - Done:**
http://optinomic.cust.local/api/#/patient/1234/stay/1051/app/ch.suedhang.apps.aase-g.production

Noch nicht überprüft bzgl.:
```JS
if (parseInt(response.Substanz) === 1) {
    substanz_text = "Alkohol";
};
if (parseInt(response.Substanz) === 2) {
    substanz_text = response.SubstAndere;
};
```
=>  Ich finde keinen mit `SubstAndere`.  Bitte überprüfen und falls i.O. schliessen!

**Comment by schoenenb** [comment]
http://optinomic.cust.local/api/#/patient/2311/stay/1096/app/ch.suedhang.apps.aase-g.production
--> funktioniert eigentlich, nur dass es jetzt natürlich alle mit anderen Substanzen falsch anzeigt (alte Daten hatten nur 1 Variablenbezeichnung, welche nun für Substanz = Alkohol verwendet wird). 
Dies hatten wir jeweils in den Patientennotizen vermerkt.
Für die Fälle müsste man wohl nochmals einen neuen Fragebogen generieren und mit den bestehenden Antworten ausfüllen und die Problemsubstanz wie in den Patientennotizen vermerkt erfassen.

**Comment by schoenenb** [comment]
Gilt das mit dem "Entkarussellen" auch für den WHOQOL?

**Comment by schoenenb** [comment]
Ach doof, ich habe letzte Woche anscheinend nicht gesehen, dass du gar nicht mehr zugewiesen bist @SonjaKaufmann 
Gilt das mit dem "Entkarussellen" auch für den WHOQOL?

**Comment by schoenenb** [comment]
Hat sich m.E. auch erledigt.
