### ISSUE TITLE
Farbige Balken in den Graphiken

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#71]
Die Einfärbung der Balken in den Graphiken in rot und grün ist etwas durcheinander und entspricht aktuell nicht der Bedeutung die bestimmt Werte haben.
Für Graphiken für welche wir z-Werte haben sollte sich die Balkenfarbe bei den Z-Werten  +/- 2 ändern. Denn dann weichen die Patienten signifikant von den Gesunden ab. 
- [x] Für den BSCL wäre dies bei >= +2 =rot, sonst die normale Farbe
- [x] Für den ISK wäre dies für die Bereiche >= +2 und <= -2 auf beiden Seiten die Farbe rot, sonst die Normale Farbe. Zwischen -1 bis +1 wären die Werte grün.
- [x] Beim TMT wäre es bei >=+2 die Farbe rot und bei <=-2 die Farbe grün, sonst normal.

Wie Du dem entnehmen kannst Bezieht sich die Bewertung auf den Vergleich mit den gesunden und nicht auf den Vergleich mit der klinischen Stichprobe.
- [x] Beim SCI hätten die Extremwerte je nach Skale eine Farbe. Also für die ersten beiden Skalen wären die Stanine 8-9 rot und die die Stanine 1-2 grün. Für die hilfreichen Copingstrategien wären die Stanine 8-9 grün und die Stanine 1-2 wären grün. Für das ungünstige Coping wären die Stanine 8-9 rot und die Stanine 1-2 wären grün.

Vielleicht muss das Programm dann ja auch ein bisschen weniger rechnen wenn die Werte fix definiert sind und nicht von der Klinischen Stichprobe abhängen :-)

**Comment by ottigerb** [comment]
**BSCL:**  App & PDF
http://optinomic.cust.local/api/#/patient/609/stay/1152/app/ch.suedhang.apps.bscl_anq.production

**ISK:**  App & PDF
http://optinomic.cust.local/api/#/patient/1381/stay/1221/app/ch.suedhang.apps.isk.production

**TMT:**  App & PDF
http://optinomic.cust.local/api/#/patient/1381/stay/1221/app/ch.suedhang.apps.tmt.production

**SCI:**  App & PDF
http://optinomic.cust.local/api/#/patient/1381/stay/1221/app/ch.suedhang.apps.sci.production


**Hinweis**
Ich konnte in der App auch den "Schieberegler" entfernen.  Dies kann gesteuert werden durch: `show-value-slider`.  Default = True;

<score-threshold score="data.stanine" min="1" max="9" scale-ranges="d.scale_ranges_unguenstig" show-percent-scale="true" show-min-max="false" show-bottom-bar="false" show-value-slider="false"></score-threshold>

Die Farben können via `scale-ranges` mitgegeben werden - Bsp.::

```JS
$scope.d.scale_ranges = {
            "ranges": [{
                "from": 1,
                "to": 1.5,
                "result": "Stanine 1",
                "result_color": "#4CAF50"
            }, {
                "from": 1.5,
                "to": 2.5,
                "result": "Stanine 2",
                "result_color": "#4CAF50"
            }, {
                "from": 2.5,
                "to": 3.5,
                "result": "Stanine 3",
                "result_color": "#5C6BC0"
            }, {
                "from": 3.5,
                "to": 4.5,
                "result": "Stanine 4",
                "result_color": "#5C6BC0"
            }, {
                "from": 4.5,
                "to": 5.5,
                "result": "Stanine 5",
                "result_color": "#5C6BC0"
            }, {
                "from": 5.5,
                "to": 6.5,
                "result": "Stanine 6",
                "result_color": "#5C6BC0"
            }, {
                "from": 6.5,
                "to": 7.5,
                "result": "Stanine 7",
                "result_color": "#5C6BC0"
            }, {
                "from": 7.5,
                "to": 8.5,
                "result": "Stanine 8",
                "result_color": "#F44336"
            }, {
                "from": 8.5,
                "to": 9,
                "result": "Stanine 9",
                "result_color": "#F44336"
            }]
        };
```

**Comment by SonjaKaufmann** [comment]
Habe jetzt auch im ISK gesehen, dass die Farben nicht mehr stimmen. Habe das GEfühl die Korrekturen sind  alle wieder weggefallen!

**Comment by ottigerb** [comment]
Tatsächlich:  Beim BSCL hatte ich statt _rot_ fälschlicherweise _grün_ gefärbt.  Fixed: https://github.com/Optinomic/apps/commit/bb07336e79064465eea1e082059ebfd4a2d4470d 
Die anderen Färbungen sind m.E. nun korrekt.
