### ISSUE TITLE
ISK Zuordnung MZP

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#72]
In den Austritten die gestern ihr Austrittsassessment hatten ist der Austrittszeitpunkt im ISK als undefined angeschrieben: 2294, 2225, 1184, 2372

**Comment by schoenenb** [comment]
Das liegt daran, dass diese Variable den Patienten nicht angezeigt wird und von mir nachgetragen werden müsste.

**Comment by ottigerb** [comment]
...kann allenfalls ein "Defaultwert" gesetzt werden für die "versteckte" Frage?  Allenfalls eine gute Idee!

**Comment by schoenenb** [comment]
Nope. Es geht um Eintritt oder Austritt... Ausser es geht über die event-creation? Also wenn der Event ausgelöst wurde durch "activation", dann ist es Eintritt, wenn er ausgelöst wurde durch "x_days_before_exit", dann ist es eine Austrittserhebung... Das wär natürlich sehr praktisch. :)

**Comment by ottigerb** [comment]
...OK!    Wie trägst Du den MZ nach?  Innerhalb Optinomic - denke ich - or?   Dann baue ich im "Daten-Tab" noch einen Knopf [calculation erneut ausführen] ein.  Damit Deine Änderungen auch in den "Berechnungen" ankommen.

**Comment by schoenenb** [comment]
hmm, hab's jetzt für die von gestern im limesurvey nachgetragen und dann bei einem Patienten auf neue Ergebnisse geprüft. Danach waren bei allen andern auch bereits die Austritte als solche drin gespeichert.

**Comment by ottigerb** [comment]
...funktioniert also perfekt.  Check for Results prüft jeweils für Alle - das ist ein "limeSurvey-Thema" welches in diesem Fall wohl positiven Effekt zeigt.

**Comment by ottigerb** [comment]
> Nope. Es geht um Eintritt oder Austritt... Ausser es geht über die event-creation? Also wenn der Event ausgelöst wurde durch "activation", dann ist es Eintritt, wenn er ausgelöst wurde durch "x_days_before_exit", dann ist es eine Austrittserhebung... Das wär natürlich sehr praktisch. :)

Das ist prinzipiell möglich:

Wir könnten mehrere "gleiche" Fragebögen verwenden mit unterschiedlichen Defaults für die MZ-Frage und dann sowas:

```
[survey]
id = isk_on_activation
type = lime
responsibility = patient_via_assessment
name = Eintritt - Inventar Sozialer Kompetenzen
host = limesurvey_v2
survey_id = 824558
...

[survey]
id = isk_before_exit
type = lime
responsibility = patient_via_assessment
name = Austritt - Inventar Sozialer Kompetenzen
host = limesurvey_v2
survey_id = ...
...


[event activation]
type = on_activation
time = 08:00
due_after = 86400
overdue = ignore
description = Eintritt: Schätzen Sie Ihre persönlichen Verhaltensweisen und Gewohnheiten im Umgang mit anderen Personen ein.
survey = isk_on_activation

[event activation]
type = before_exit
days = 7
time = 08:00
due_after = 86400
overdue = ignore
description = Austritt: Schätzen Sie Ihre persönlichen Verhaltensweisen und Gewohnheiten im Umgang mit anderen Personen ein.
survey = isk_before_exit
```
