### ISSUE TITLE
_Belegung - Gruppenzuordnung

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#73]
Die Zuordnung zur Gruppe "Belegung: EP (aktuell)" beinhaltet, dass im RAP-Abgleich bzw. der App _Belegung ein stationärer Fall registriert ist.
Bei den heute eingetretenen Fällen 1381 und 2493 gibt's jedoch wieder mal eine Ausnahme:
- Bei 2493 war zwar _Belegung aktiviert, jedoch mit folgendem "Inhalt":
![image](https://cloud.githubusercontent.com/assets/15833792/22254914/2c0c0cae-e256-11e6-8935-49b54da6951a.png)

Entsprechend nicht in der Gruppe und entsprechend auch keine Apps aktiviert (habe ich vorhin von Hand gemacht).

Wann wird jeweils ein RAP-Abgleich gemacht? Je nachdem nehme ich die App-Aktivierung vorläufig lieber zur manuellen Gruppe der Eintritte mit hinzu...

Eventuell ein anderes "Problem":
- Bei 1381 ist _Belegung **nicht** aktiviert, dafür alle anderen Apps. (Ev. anderes Problem --> _Belegung sollte ja bei allen aktiviert sein, wenn 1=1 --> ev. doch nicht, weil bereits ein anderer Fall bestand und nicht auf den Fall, sondern den Patienten gegangen wird?)

**Comment by ottigerb** [comment]
`_Belegung` wird um 12:00 & 00:00h  abgefragt.   Bzgl. Aktivierung - was Dir "wohler" ist.

**Comment by ottigerb** [comment]
Die genannten Fälle: 1381 und 2493 haben nun ebenfalls Daten in der "_Belegung". Wie gesagt - jeweils 12:00 & 00:00h wird aktualisiert.

Aktivierung der "_Belegung" & "_Druckvorlage" habe ich auch der PG: `Behandlung: Aktuell | Alle`
 (http://optinomic.cust.local/api/#/patient-group/17) hinzugefügt.  Eine App-Aktivierung kann nur vorgenommen werden, wenn ein Fall "offen" resp. nicht "archiviert" ist.  Sollte nun klappen.

=>  Close.
