### ISSUE TITLE
Dateiname und Endung von Exportfiles

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#74]
Im Moment werden Exportfiles sehr kompliziert benannt. Siehe Beispiele
![image](https://cloud.githubusercontent.com/assets/20124244/22292015/9a01457c-e309-11e6-8222-03dd27df4bfd.png)
Muss das so sein oder könnten auch die Exporteinstellungen als Namensgeber diesen z.B.
Modul_Fallart_Datum von-bis: Also z.B. BDI_Alle_170101-170301 oder so in der Art.
Zudem wäre es noch gut, wenn die Datei eine Dateiendung hätte, also .csv

**Comment by ottigerb** [comment]
### Dateiendung
Hmm... 
...die Files haben die ".csv" Dateiendung - Bsp.: `bd1d4bdb-dec0-45c4-8943-fd2be8cb3e20.csv`.   
- Allenfalls ist dies ein Windows - Thema:  Dort werden Dateiendungen nicht immer angezeigt. Kann irgendwo eingestellt werden, ob immer Dateiendungen angezeigt werden sollen.
- Versucht doch mal unter http://demo.optinomic.org/api/#/admin/tools/export ein Export auszuführen.  Ist es dort "anders"?   
- Von der lokalen Ebene vs. innerhalb CITRIX - Unterschiede?

### Filename
Der Filename könnte allenfalls ein Datums-Tag tragen - ein "BDI-Alle" ist wohl kaum möglich. Da die Toolbox eigentlich "dumm" ist und lediglich ein SQL ausführt.

**Comment by ottigerb** [comment]
Tatsächlich - keine `.csv` Extension. Dies ebenfalls wenn ich innerhalb von CITRIX auf demo zugreife. Direkt - resp. ausserhalb CITRIX - funktioniert dies.  Hat also irgendwas mit Windows/CITRIX zu tun.  Anyway - ich habe mal ein Issue eröffnet - vielleicht kann ja Tom diesbezüglich etwas "zaubern".

**=>Eröffnet:**  https://github.com/ottigerb/therapy-server/issues/419

**Comment by SonjaKaufmann** [comment]
Das wäre schon Mal super. Und das mit dem Datums-Tag und der Fallart (die Info hat SQL doch auch, oder) würde mir auch sehr viel besser gefallen.

**Comment by SonjaKaufmann** [comment]
Das mit dem löschen der Optinomicfelder ist kein Problem, wäre nur chicer gewesen mit der anderen Möglichkeit zum Weglassen der Optinomicfelder. Das kann man ja Problemlos rauslöschen. Da ist die Reihenfolge wirklich viel viel wichtiger!
Nur z.B. beim BDI-2-Calculations werden am Ende noch einige Felder exportiert, welche wohl auf den Therapeuten und so zugreifen sollten, aber diese sind nach dem Export alle leer. (
![image](https://cloud.githubusercontent.com/assets/20124244/22415388/4c848a54-e6c7-11e6-8d8a-fa5262c57c41.png), ausser das Feld Class, dort steht überall S3 drin. Woran liegt das?

Und bei den Optinomic-Ausfülldatum-Angaben werden verschiedene Datumsformate exportiert:
![image](https://cloud.githubusercontent.com/assets/20124244/22415362/f5030440-e6c6-11e6-8c7e-367d3bb06fa8.png)
Ist nicht extrem wichtig, da dies nur bei dem Optinomic-Ausfülldatum der Fall ist, aber ist irgendwie komisch.

**Comment by ottigerb** [comment]
**YES!**  Files werden nun korrekt mit Extension erstellt und als Filename dient ein Datestamp:
`201701301223.csv` 


### Zu den weiteren Kommentaren:

Bzgl. Exportfelder:  Dies sind "Stay-Fields" welche wohl ebenfalls ausgegeben werden.  Dies kann jeweils innerhalb der `create_view` festgelegt werden. Nora weiss Bescheid und hat m.W. bereits "aufgeräumt".  Falls die Änderungen von Nora nicht sichtbar wären, gilt es unter  http://optinomic.cust.local/api/#/app-store die entsprechende App zu deaktivieren und wieder neu zu aktivieren =>  Dies aktualisiert die Export-Toolbox View.

Bzgl. dem Datumsformat `Optinomic-Ausfülldatum-Angaben`:  Dieses Feld stammt aus limeSurvey:  Allenfalls wurde dort das Datumsformat definiert - und nun werden ab sofort diese Formate genommen.  Dies ist für Optinomic kein wichtiges Feld.
