### ISSUE TITLE
[ch.suedhang.apps.bscl.production] open issues BSCL

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#75]
Ich brauche wieder mal einen Input oder gleich die Lösung zum folgenden Problem:

Wie kommen die Resultate vom BSCL-Admin in die BSCL-Auswertungen rein?

Bei SCI und AASE hatte ich ja nur neue Gruppen gemacht und die calculations entsprechend angepasst. Nun habe ich aber für den BSCL-Admin einen kompletten Fragebogen "neu" gemacht (allerdings mit den gleichen Variablenbezeichnungen, da Kopie von BSCL-ANQ) und dachte, dass die genauso berechnet werden sollten, da sich an den Bezeichnungen nichts ändern sollte...

Beim HoNOS + HoNOS-Verlauf hattest du das gemacht und ich habe nicht in die Codes reingeschaut, drum habe ich gerade keinen Durchblick...

**Comment by ottigerb** [comment]
...bei welchem Patienten hast Du BSCL-Admin erfasst?  Hilft beim "Debugging". Thanks!

**Comment by schoenenb** [comment]
Sorry: 
2452
1482
2215 stay 1214

**Comment by ottigerb** [comment]
Fixed:  Check https://github.com/Optinomic/apps/commit/da4fccddad9a0574cc3d4d122ce3af9702877dbb

### Daten sind hier:
http://optinomic.cust.local/api/#/patient/2452/stay/1201/app/ch.suedhang.apps.bscl_anq.production
http://optinomic.cust.local/api/#/patient/2215/stay/1214/app/ch.suedhang.apps.bscl_anq.production

### Wir müssen wohl "Dropout-Codes" beachten - vgl.:
http://optinomic.cust.local/api/#/patient/1482/stay/1216/app/ch.suedhang.apps.bscl_anq.production

=>  Welche Variablen sollen wir prüfen resp. dann ausgeben?

**Comment by ottigerb** [comment]
Vorschlag: 
Wenn `q501V05 (ID: 2063)` !== 0  `q501V06 (ID: 2064)` anzeigen.  OK?

**Comment by schoenenb** [comment]
Wenn `q501V05 (ID: 2063)` !== 0  `q501V05 (ID: 2063)` anzeigen.
Wenn `q501V05 (ID: 2063)` === 8  `q501V06 (ID: 2064)` anzeigen. 
...wäre noch besser.
Brauchst du die Dropoutgründe (1-7) nochmals ausgeschrieben, oder sind die noch irgendwo?

**Comment by ottigerb** [comment]
...jep:  Soeben gesehen:  8 = `Nein, anderer Grund`.  Codes sind http://optinomic.cust.local:8000/limesurvey_v2/index.php/admin/questions/sa/answeroptions/surveyid/264947/gid/81/qid/2063  
=>  Ich mach mal.

**Comment by ottigerb** [comment]
**Done::** Innerhalb der App:
http://optinomic.cust.local/api/#/patient/1482/stay/1216/app/ch.suedhang.apps.bscl_anq.production

![bildschirmfoto 2017-01-26 um 17 23 07](https://cloud.githubusercontent.com/assets/2470873/22339980/246a192c-e3ec-11e6-93de-213a3e2ad079.png)

=>  Versuche nun im PDF eine "Lösung" zu finden.

**Comment by ottigerb** [comment]
**Done::** Innerhalb der PDF's:


![bildschirmfoto 2017-01-26 um 17 46 07](https://cloud.githubusercontent.com/assets/2470873/22340952/6dff8fa6-e3ef-11e6-8cea-1f24d85101cb.png)


Diese "Dropout" Ausgabe ist "anstelle" der Z-Score Grafik. Ansonsten bleibt die Darstellung unverändert.  Alles Andere wäre zu Komplex - dann müssten wir prüfen, ob es mindestens eine "gültige" Messung gibt etc. etc.  =>  Hope this is "acceptable".

**Comment by schoenenb** [comment]
Naja... Ich find's schon sehr überladen, wird vorläufig aber so funktionieren müssen.
Die Datenprüfung vorzuschieben geht nicht? Also z.B. wenn Dropout -> direkt unter dem Titel Datum + Dropoutgrund, wenn kein Dropout -> z-Wert-Grafik

**Comment by ottigerb** [comment]
...ich denke auch: So belassen.  Ansonsten hätten wir zu viele "Sonderfälle".  Auch wird wohl bei einem "Dropout" kaum ein Assessment-PDF erzeugt und mit dem Pat. besprochen.

**Comment by schoenenb** [comment]
Datum = q504V00 --> wird Datestamp verwendet, weil beim TMT kein Erhebungs-Datum gesetzt wird?

**Comment by ottigerb** [comment]
Done `Datum = q504V00`:  Innerhalb App & PDF

**Comment by schoenenb** [comment]
Sortierung scheint noch nicht oder nicht mehr zu stimmen siehe z.B. http://optinomic.cust.local/api/#/patient/2940/stay/1363/app/ch.suedhang.apps.bscl_anq.production

**Comment by schoenenb** [comment]
Und soll beim GSI gewollt der graue Bereich der Kontrollstichprobe nicht angezeigt werden? Wenn man an den Einstellungen rumschraubt erscheint der Bereich, sonst nicht...

**Comment by schoenenb** [comment]
Wollte das Issue schliessen und dazu die Grafik überprüfen - keine Anzeige im Südhang:
![image](https://user-images.githubusercontent.com/15833792/30365548-5fe0b994-9868-11e7-93f2-22e64d4e1f30.png)
Darum Link auf pdfmake in base.opapp.m4 entfernt

**Comment by schoenenb** [comment]
Kontrollstichprobe fehlt nach wie vor, bis man sie manuell aktiviert - hat sich aber mit der neuen Version erledigt, würde ich meinen. Brauchst also nur noch dran zu denken, wenn du das pdfmake wieder einfügen möchtest, dass es auch in der ch.suedhang.apps.bscl_anq.production app funktioniert. (Da hätte ich jedenfalls Freude dran. :))

**Comment by ottigerb** [comment]
@schoenenb   Jä so - guter Hinweis!  https://github.com/Optinomic/apps/commit/aa0f33c3c705171eb0b30e94233b1dee7cece35c sollte das [Problem](https://github.com/Optinomic/apps/issues/75#issuecomment-329088296) beheben. Die calculation `pdfmake` hat die bisherige calculation als Basis => Entsprechend müssen wir diese in der `.production` nochmals überschreiben:

```
[calculation pdfmake javascript ch.suedhang.apps.bscl_anq.production ch.suedhang.apps.bscl_anq.production:scores_calculation]
include(calculations/pdfmake.js)
```

**pdfmake.js**  ist dann identisch bei `.production` & `demo`.
