### ISSUE TITLE
activation: before exit

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#76]
Kein einziger Fragebogen war bei keinem einzigen Austritt aktiviert - obwohl eine Aktivierung 10 Tage vor Austritt ausgelöst werden sollte.
Stimmt etwas an der Event-Aktivierung nicht?

```
[event exit]
type = before_exit
days = 10
time = 08:00
due_after = 259200
overdue = ignore
description = Austritt: Abstinenzselbstwirksamkeit - Versuchung durch Substanz
survey = aase
```

- muss immer [event exit] oder sogar [event before_exit] stehen?
- müssten die Tage auch in Sekunden angegeben werden?
- gibt's ein Durcheinander mit dem Event vom parent:

```
[event activation]
type = before_exit
days = 7
time = 08:00
due_after = 86400
overdue = ignore
description = AASE-G ausfüllen.
survey = aase
```

**Comment by ottigerb** [comment]
Konfiguration war m.E. so i.O. - vgl. https://doc.optinomic.org/V2/Developers/app_spezifikation.html#event-optional-can-have-many


Ich habe einen potentiellen Fehler gefunden:  https://github.com/Optinomic/apps/commit/179bb95e4e72f5de80991e2370e7c6bf0b412a44
=> Parent hatte keinen `exit` event - somit konnte das Kind diesen nicht überschreiben.


War dies nur beim AASE-G der Fall?

**Comment by schoenenb** [comment]
Nein, dann wahrscheinlich bei allen. Ich hatte das meines Wissens nur bei den production-Apps angepasst.

**Comment by ottigerb** [comment]
`before_exit` funktioniert ab sofort wie erwartet:

> I fixed the bug, it was a logical error affecting all stay-dependent events. I'm surprised we haven't noticed it before.


Danke fürs Aufdecken dieses Bugs!  :-)

**Comment by schoenenb** [comment]
Ist es möglich, dass wieder der gleiche Fehler vorliegt, oder war ich zu ungeduldig?
Hatte heute vertretungsweise Austrittsassessment von Patienten mit Austritt am 24.12. - bei Aktivierung 10 Tage vor Austritt (wie gewohnt) müssten die FBn doch aktiviert sein?
Ich musste jedoch jeden Fragebogen einzeln als neuen Event generieren...

**Comment by ottigerb** [comment]
Hmm…  wie sieht es denn bezüglich CIS-Import aus?  Sind da ebenfalls uneingelesene Fälle/Patienten da?  
Zur Info:  Mittels „PATIENT-GROUPS“ als Executable lässt sich diese Zuteilung manuell starten.

**Comment by schoenenb** [comment]
Da war ich wohl zu unpräzise:
Die Module sind bereits beim Eintritt aktiviert worden, müssen also nicht mehr aktiviert werden. Allerdings würde ich erwarten, dass der Austrittsevent am 14.12./15.12. aktiviert wird nach der Definition in der [base.opapp](https://github.com/Optinomic/ch.suedhang.apps.bscl_anq.production/blob/master/base.opapp):
```[event exit]
type = before_exit
days = 10
time = 08:00
due_after = 259200
overdue = ignore
description = BSCL - Austritt
survey = bscl_anq```

Der Schnittstellenordner schaut i.O. aus - es sind keine offenen Files drin.

**Comment by ottigerb** [comment]
...hat dies nun mit den "verzögerten" Mails zu tun - oder werden Events nicht ausgelöst?   Habe bei sendgrid (genutzter Service) geschaut - sieht soweit alles i.O. aus.

**Comment by schoenenb** [comment]
Für die Assessment-Fragebögen werden keine Mails verschickt, sollte also unabhängig davon sein.
Ich gehe drum davon aus, dass die Events nicht ausgelöst werden.

**Comment by ottigerb** [comment]
Jä so - dies soll so sein:  Vgl. https://doc.optinomic.org/V2/Developers/app_spezifikation.html

> patient_via_assessment: the patient won't receive email, he/she is supposed to do them in the "assessment room"

=>   Close - or?

**Comment by schoenenb** [comment]
Glaube nicht - das Problem ist ja, dass die Austritts-Events nicht ausgelöst werden. D.h. sie werden auch nicht auf der Patientenplattform angezeigt.
Es geht hier "nur" um die Assessment-Apps (AASE, BDI, BSCL, ISK, SCI, WHOQOL und momentan ZüPaZ).

Das Mail-Problem kann nur beim HoNOS vorkommen.
Dort wurde mir aber auch schon rückgemeldet, dass für den Austritt kein Mail verschickt wurde. Das wäre dann der Fall, wenn der exit-Event nicht generiert wird - keine Aufgabe = kein Mail.

**Comment by ottigerb** [comment]
Hmmm....

``` 
before_exit: N days before the end of the stay at a specific time;
```

Beispiel:  N=10;   Kann es sein, dass der Austritt so gesetzt wird, dass dieser bereits <= 10 ist und somit die Bedingung N=10 niemals erfüllt? Könnten wir 10 auf vielleicht 5 reduzieren?

**Comment by ottigerb** [comment]
...also es gilt einen Fall zu beobachten welcher das Austrittsdatum gesetzt hat und dieses > 10 Tage ist. Wird Event ausgelöst?  Ich würde vermuten: Ja!   Falls dem so wäre müsste wir Änderungen lancieren:  `<= N days before the end of the stay at a specific time & only if not already created`.

**Comment by ottigerb** [comment]
...ich denke - wir sollten den `overdue` nutzen.  Vielleicht `send_reminder_once` @ Austittsdatum.

**Comment by schoenenb** [comment]
3 Austritte am 3.1.19, so bereits eingetragen. -10 Tage = Event müsste am 24.12. ausgelöst werden
patient/2957/stay/5966
patient/4140/stay/5886
patient/2859/stay/5964

5 Tage reicht nicht, weil das Assessment 8 Tage vor Austritt stattfindet, dann sollten die Events also generiert sein.

Beim HoNOS wird der exit-Event jedoch 3 Tage vor Austritt ausgelöst.
Hier habe ich einen Kandidaten gefunden, der am 21.12. geht:
patient/4296/stay/6011

Gestern um Mitternacht wurde bereits der Austritts-Event ausgelöst:
![image](https://user-images.githubusercontent.com/15833792/50147638-fccb5c00-02b6-11e9-966c-799103aac041.png)
(days = 3, time = 00:00 - dann nimmt es wohl den 18.12. 00:00, mit der Zeitverschiebung wirds dann wohl dem 17.12. zugerechnet.)

Im Logfile finde ich diesen Event aber nicht. 
![image](https://user-images.githubusercontent.com/15833792/50147792-47e56f00-02b7-11e9-8c5e-96bcdf0cc1e3.png)

**Comment by ottigerb** [comment]
...das würde meine Vermutung bestätigen.  Somit gilt es sicherzustellen, dass das Austrittsdatum >=10 Tage vor Austritt bestimmt ist. Für diejenigen, welche dann doch "unverhoffter" austreten, muss allenfalls "survey scheduled manually" durchgeführt werden. 

...aber beobachten wir mal die genannten Fälle.

**Comment by schoenenb** [comment]
Die Kontrolle am 24.12. habe ich leider verpasst, weil ich nicht gearbeitet habe.
Entweder seh ich's nicht, oder aber die Austritts-Fragebögen wurden tatsächlich nicht ausgelöst.
Bsp:
http://optinomic.suedhang.ch/client.new/#/patient/2859/stay/5964
http://optinomic.suedhang.ch/client.new/#/patient/2957/stay/5966

Ich kann mir für den 31. nochmals vornehmen, nachzuschauen, ob die before_exit-events für die Austritte vom 8.1. ausgelöst werden.

**Comment by schoenenb** [comment]
Interessanterweise wurden jedoch für BSCL + Züpaz bei einem QuEA-Patienten mit gleichem Austrittstag (4.1.) ausgelöst:
http://optinomic.suedhang.ch/client.new/#/patient/4302/stay/6017

**Comment by schoenenb** [comment]
Letzte Beobachtung dazu:
Es wurden zwar alle Fragebögen ausgelöst, jedoch abgebrochen:
![image](https://user-images.githubusercontent.com/15833792/50477260-d6e73b00-09cb-11e9-9176-4afc2bc112fa.png)
In den Logs (Filter: 2859) findet sich der letzte Eintrag vom 21.11.

**Comment by schoenenb** [comment]
Zwischenstand 31.12.:
Bei den Austritten vom 8.1. wurde für jeden Austritts-Fragebogen eine Aufgabe ausgelöst (2 days ago). Bisher sind einzig die Act-Info Austritte bei allen abgebrochen worden.

**Comment by ottigerb** [comment]
Also das Issue ist, dass Events fälschlicherweise "aborted" werden?  Really strange!  
=> Tom wird mal "debugging"!

**Comment by ottigerb** [comment]
Ich denke ich habe den Effekt durchschaut:  Vgl. auch https://github.com/ottigerb/therapy-server/issues/538#issuecomment-453510923


Wie in der [Dokumentation](https://doc.optinomic.org/V2/Developers/app_spezifikation.html#event-optional-can-have-many) steht - sobald `due date` erreicht wird `ignore: the event is aborted`.  Im Falle von ActInfo_Austritt ist dieser mit `due_after = 129200` definiert. =>  Nach 1.5 Tagen werden diese Events "aborted". 

**Lösungsvorschlag:**  `due_after = 864000` erhöhen - somit ist dieser 10 Tage offen!  Oder auf `432000` setzen mit `overdue = send_reminder_once` - dann wird nach 5 Tagen erinnert und danach ist der Event nochmals 5 Tage offen.

Ich habe mal die Variante 1 der Lösungen [gesetzt](https://github.com/Optinomic/ch.suedhang.apps.actinfo_aus.production/commit/7a1181770798ea058e03ce50682928979f989099). Du kannst jederzeit hier anpassen: 
https://github.com/Optinomic/ch.suedhang.apps.actinfo_aus.production/blob/master/base.opapp#L41-L42

**Comment by ottigerb** [comment]
Nachdem ich [die Änderung gesetzt ](https://github.com/Optinomic/ch.suedhang.apps.actinfo_aus.production/commit/7a1181770798ea058e03ce50682928979f989099) hatte erschien ca. 10 Minuten später ein Update in http://optinomic.suedhang.ch/client.new/#/admin/app-store.  Dieses habe ich ebenfalls durchgeführt. => Problem solved!

**Comment by schoenenb** [comment]
Viel Lärm um nichts... Danke Sherlock! :)
