### ISSUE TITLE
Graphiken fehlen

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#77]
Lieber Beat,

die Graphiken für den BDI und den AASE und den WHOQOL fehlen im Moment gänzlich, da ist irgendetwas falsch gelaufen!

Grüssli
Sonja

**Comment by ottigerb** [comment]
...fixed.

actInfo's haben wohl aktuell einen Fehler in der Berechnung. Ich versuchte bei "calculation - errors" die Anzeige auszuschalten. Doch wohl etwas zu viel "Errorhandling". 

Den actInfos gehe ich ebenfalls bei Gelegenheit nach.
