### ISSUE TITLE
[App] actInfo Ein&Austritt

### ISSUE THREAD

**Issue by ottigerb** [Optinomic/apps#78]
Die `calculations` von actInfo Ein&Austritt konnte ich fixen.  Die Daten werden nun nochmals neu berechnet inklusive `answers`.    :-)     

@schoenenb   In Zukunft  sehr vorsichtig mit "Calculations" sein.  Ich kann Dir mal bei Gelegenheit zeigen, wie Du diese "ausprobieren" kannst bevor diese in die Apps gelegt werden.

**Comment by ottigerb** [comment]
Die Apps benötigen wohl auch noch eine "Nichtraucher" Angabe (im PDF bereits umgesetzt).

Example: http://optinomic.cust.local/api/#/patient/2441/stay/1166/app/ch.suedhang.apps.actinfo_ein.production

**Comment by schoenenb** [comment]
Genau, zu den Nichtrauchern und Nicht-Zigarettenrauchern bin ich noch nicht gekommen.
Da wäre ich sehr froh drum - ich "muss" ja immer alles direkt ausprobieren...

**Comment by schoenenb** [comment]
Wenn VZAT010 = 1 NichtraucherIn
Wenn VZAT020 = 999 Keine Angaben zum Zigarettenkonsum vorhanden.
Wenn VZAT020 = 777 PatientIn raucht, aber keine Zigaretten.

                <div ng-if="response.calculations[0].calculation_result.response.data.response.VZAT010 === 1">
                   <h4 class="md-subhead">PatientIn raucht nicht</h4>
                </div>
                <div ng-if="response.calculations[0].calculation_result.response.data.response.VZAT020 === 999">
                    <h5 class="md-subhead">Keine Interpretation möglich</h5>
                    <p class="md-caption">Kein Fagerström-Score vorhanden.</p>
                </div>
                <div ng-if="response.calculations[0].calculation_result.response.data.response.VZAT020 === 777">
                    <h5 class="md-subhead">Keine Interpretation möglich</h5>
                    <p class="md-caption">PatientIn raucht ein anderes Tabakprodukt als Zigaretten.</p>
                </div>

**Comment by schoenenb** [comment]
![image](https://cloud.githubusercontent.com/assets/15833792/23065359/7109f92a-f515-11e6-893f-d14df887af73.png)
z.B. bei http://optinomic.cust.local/api/#/patient/532/stay/238/app/ch.suedhang.apps.actinfo_aus.production
--> Grund für fehlende Interpretierbarkeit angeben

**Comment by schoenenb** [comment]
VZET010 = 999 hat gefehlt --> angepasst

**Comment by ottigerb** [comment]
Great!  :)

schoenenb <notifications@github.com> schrieb am Fr., 17. Feb. 2017, 16:33:
