### ISSUE TITLE
Austrittsassessment-Bericht

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#79]
Im Austrittsbericht wird  nur der TMT-Eintritt dargestellt. Das scheint mir falsch. 

Und das System ist gerade wieder urlangsam und die Berichte kommen gar nicht. Läuft gerade wieder etwas im Hintergrund? 
Am Donnerstag sollte nichts laufen, denn da sind die Fallkonferenzen, wo die Auswertungen angeschaut werden. Wenn es da so lange braucht, dann wird wieder nach V1 verlangt :-(!

**Comment by ottigerb** [comment]
### TMT
Ich kann den TMT-Fehler nicht reproduzieren:
Bsp:: http://optinomic.cust.local/api/#/patient/2294/stay/1089/app/ch.suedhang.apps.pdf_druckvorlagen

![bildschirmfoto 2017-02-01 um 17 50 14](https://cloud.githubusercontent.com/assets/2470873/22516713/faa60820-e8a6-11e6-83d6-1a0f03ffba9b.png)

### Geschwindigkeit
Jep, die actInfo Calculations mussten neu "berechnet" werden. Wenn die "calculation" ändert, müssen alle "gespeicherten" Ergebnisse "aktualisert" werden. Dieser `calculation-daemon` wird optimiert, dass er sich nicht mehr so "Ressourcenhungrig" zeigt. Grundsätzlich sollten sich ja die "Calculations" nicht sehr oft ändern. In Zukunft gilt es diese "koordinierter" zu aktualisieren. 

Anyway:  Das System scheint sich wieder "erholt" zu haben: Daumendrück für die Fallkonferenz. Navigiert von Patient zu Patient innerhalb Optinomic - falls immer ein neues Fenster via Polypoint aufgerufen wird, muss sich die ganze Applikation erst "initialisieren". Diese Ladezeit kann ausgelassen werden, wenn innerhalb der App zum nächsten Patienten gesprungen wird. Allenfalls ist ja der "Presentation-Modus" https://doc.optinomic.org/V2/Users/patient_presentation_mode.html hilfreich.

=>  Close?

**Comment by ottigerb** [comment]
Ich konnte noch einen Fehler im PDF finden:  Falls der Patient im ActInfo Eintritt "keine Problemsubstanzen" hatte - wieso auch immer - hat sich das PDF geöffnet und gleich wieder geschlossen (ohne anzuzeigen). Behoben mit der Ausgabe: _Keine Angaben zu Problemsubstanzen vorhanden._

**Comment by SonjaKaufmann** [comment]
Super konntest Du noch den Fehler mit den Problemsubstanzen beheben.

**Zum TMT-Fehler:**
Ich konnte den Fehler wohl replizieren.
Habe einen Bericht von einem Patienten aufgetan, der diese Woche sein Austrittsassessment hatte und in allen Bögen auch Austrittswerte hat, ausser im TMT: siehe Bild von seinem Austrittsbericht:
![image](https://cloud.githubusercontent.com/assets/20124244/22732872/1857975a-edf0-11e6-84c5-ec595c003342.png)

**Comment by ottigerb** [comment]
...welcher Patient/Fall - Danke für die ID's.  Scheint ein Sonderfall zu sein - bin ja gespannt welcher - meine "Tests" sind alle i.O.!

**Comment by SonjaKaufmann** [comment]
Jetzt weiss ich woran es liegt :-)
Wahrscheinlich hatte der Patient noch kein Einzelausstrittsassessment oder die Daten sind noch nicht eingegeben und daher sind natürlich auch keine TMT-Werte drin. Mit dieser Konstellation hat sich mein Hirni schon einige Male verheddert. 
Sehr gut, Optinomic funktioniert besser als mein Hirn :-(
