### ISSUE TITLE
ngSurvey / TMT - ng-if?

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#80]
Kann man beim Programmieren des ng-Survey bestimmte Fragen aufgrund der Beantwortung vorangehender Fragen anzeigen / verstecken?
Konkret soll die Anzahl Ausbildungsjahre bei Austritt nicht mehr erfasst werden.
Geht das z.B. mit:
`29   <p ng-if = "result.Messzeitpunkt !== 2" class="md-headline">Ausbildung</p>`
`30   <md-input-container ng-if = "result.Messzeitpunkt !== 2" class="md-block">`
?

**Comment by ottigerb** [comment]
**Zur Frage:**

Genau - mittels `ng-if` kann gesteuert werden, ob das jeweilige `<div>` angezeigt wird - bsp:

```html
<md-input-container class="md-block" ng-if="result.Messzeitpunkt === `1` || result.Messzeitpunkt === 1">
    <label>Ausbildungsjahre</label>
    <input required type="number" step="any" name="edu_years" ng-model="result.Ausbildungsjahre" min="6" max="40">
    <p class="md-caption">Ausbildungsjahre meint Schuljahre und Jahre der ersten Berufsausbildung (resp. bei Zweitausbildungen zählt die jeweils höher qualifizierende), z.B. 9 Jahre Schule + 3 Jahre Berufslehre gibt 12 Ausbildungsjahre, oder 12 Jahre Schule (z.B. Matur) + 5 Jahre Studium gibt 17 Ausbildungsjahre. Bei der Schule zählt die Anzahl Jahre, die man üblicherweise für den jeweiligen Schultyp benötigt, d.h. wenn jemand eine Klasse wiederholen muss, sollte dieses Jahr nicht gezählt werden. Das gleiche gilt für die Berufsausbildung, insbesondere bei Studiengängen: wenn jemand aus persönlichen Gründen 8 Jahre für einen Studienabschluss benötigt, den man eigentlich in 5 Jahren erreichen könnte, werden 5 Jahre gezählt, etc. Berufliche Weiterbildungen und Zusatzqualifikationen werden nicht mehr zur Ausbildung gezählt.</p>
    <div ng-messages="surveyForm.edu_years.$error" multiple md-auto-hide="false">
        <div ng-message="required">
            Hier fehlt die Angabe der Ausbildungsjahre.
        </div>
        <div ng-message="min">
            Sind Sie sicher, dass der Patient keine obligatorische Schule abgeschlossen hat?
        </div>
        <div ng-message="max">
            Mehr als 40 Ausbildungsjahre sind sehr unwarscheinlich.
        </div>
    </div>
</md-input-container>

```


**Im konkreten Beispiel - TMT:**

Diese Idee / Issue war mir damals auch aufgefallen. `edu_years` wird mehrfach erhoben und kann unterschiedliche Werte pro Erfassung aufweisen.  Hmm...

...den Fragebogen also "ein/ausblenden" lassen is easy - doch:  Unsere `calculation` verlangt die Variable um die Berechnungen auch für Klinikstichprobe vorzunehmen. 

```JS
result.edu_years = result.Ausbildungsjahre;
```

Diese `edu_years` könnte auch "Global" durch einen eigenen Fragebogen oder innerhalb der App durch z.T. den Therapeuten einmalig erfasst werden. Dies führt wieder zur nächsten Schwierigkeit: Was wenn diese "Grundangabe" noch nicht vorliegt nachdem ein TMT erfasst wurde?  Defaultwert ziehen?  Events erst auslösen nachdem diese `edu_years` erfasst wurden? Lösbar wäre dies in Optiomic - doch wir müssten nochmals genauer den Aufbau der App "studieren".  Wie auch immer - der Ertrag innerhalb TMT steht in keinem Verhältnis zum Aufwand - welchen wir in die App stecken müssten.  Zukünftige Anwendungen "designen" wir cleverer. Versprochen.

**Comment by schoenenb** [comment]
Können wir ev. morgen noch anschauen? Die "Vorgabe" war ja mal, dass es auch bei Austritt die Angabe vom Eintrittswert nimmt... (Ich bin davon ausgegangen und tue es noch immer, dass dies auch so läuft!?) Damit wird die Ausgabe aus dem Austritts-TMT überflüssig...

**Comment by schoenenb** [comment]
Ich schliesse dieses Thema, weil sich hier meiner Einschätzung nach nichts ändern lässt.
