### ISSUE TITLE
Fall-Erkennung bei parallelen Fällen

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#81]
Aktuell haben wir 1 Pat. mit Aufenthalt in TK (stay 1140; bis 6.2.17) und seit 1.2.17 auf der EAS - den EAS-Fall hat's jedoch (noch) nicht erkannt. Any idea, woran das liegen könnte?
http://optinomic.cust.local/api/#/patient/1363/

...wo kein Fall, können auch keine Daten erfasst werden...

**Comment by schoenenb** [comment]
Bei obengenanntem Fall gab's grundsätzlich ein "Puff" - der TK-Fall enthält auch die Austrittsmessung vom HoNOS vom vorangehenden EAS-Fall... Ich muss mich wohl wirklich da reinlesen, wie ich die Fälle manuell anpassen kann, dachte das könne ich umgehen nach dem gelungenen Verknüpfen via `most-likely`-Skript...

**Comment by ottigerb** [comment]
Fehlender EAS-Fall:   Hast Du mal versucht im PABS eine Änderung zu provozieren, damit die Schnittstelle den Fall erneut sendet?  Kann es wirklich sein, dass ein Patient sich aktuell in "parallelen Fällen" befindet - entzieht sich mir irgendwie jeder Logik.  
http://optinomic.cust.local/api/#/patient/1363/stay/1140/app/com.optinomic.init.poly_stay zeigt auf TK :: 5.12.2016 - 6.2.2017 | 63 Tage  ->  Somit hat auch Polypoint ein "puff" - nicht?

Anyway:

Ich schlage vor: 
- Innerhalb von PABS die beiden Fälle zu einem Schnittstellenexport provozieren. 
=> Falls nicht übernommen wird:
- Allenfalls müssen wir in Optinomic den TK-Fall manuell "als beendet" setzen. 
=> Nochmals Schnittstellenexport durchführen. TK-Fall manuell wieder auf 6.2. oder so setzen.

Sobald dann die Fälle vorhanden sind können die Daten anhand https://github.com/Optinomic/apps/wiki/Anleitung-::-Daten-einer-Applikation-in-einen-anderen-Fall-verschieben zu den entsprechenden Fällen zugeteilt werden.

**Comment by ottigerb** [comment]
Kannst Du mal überprüfen - ob bei diesen "Spezialfällen" allenfalls Therapeuten/Ärzte zugeordnet sind, welche es in Optinomic nicht gibt.  Thanks.

**Comment by ottigerb** [comment]
Yep - das wars:   Falls Therapeuten/Ärzte nicht bekannt sind - wird nun "Admin Optinomic" zugeordnet.  Dieser User hatte `CIS_UID = 0`  anstatt `CIS_UID = 1`.  Die Schnittstelle weist bei "unbekannt" diesem 1 zu.  

Tadaaa  ->  http://optinomic.cust.local/api/#/patient/1363
=>  Alle Schnittstellenfiles sind nun korrekt eingelesen.

**Comment by schoenenb** [comment]
Aah, daher weht der Wind! Vielen lieben Dank! Ich frage nachher bei der Patientenadmin nach, weshalb das nicht eingetragen wurde, bzw. in welchen Fällen das nicht eingetragen wird...

**Comment by ottigerb** [comment]
... oder auch einen Therapeuten/Arzt hat, welcher nicht in Optinomic
erfasst ist oder die falsche cis_uid trägt.

schoenenb <notifications@github.com> schrieb am Fr., 3. Feb. 2017, 10:00:

**Comment by schoenenb** [comment]
Es war tatsächlich niemand eingetragen. Wenn Herr Flück krank ist fällt alles zusammen. ;)
Aber super, dass die Schnittstelle nun trotzdem importiert - dann kann ich's auch im Optinomic direkt nachtragen - oder wär's dann trotzdem bereits zu spät für die richtige Zuordnung des Event-Mails?

**Comment by ottigerb** [comment]
...smile!

Innerhalb von Optinomic kann natürlich nachgetragen werden, jedoch die `on_activation` Mails würden dann ins Nirvana "gesendet" werden. Allenfalls können wir einen weiteren Admin-User anlegen mit z.B. Deiner E-Mail Adresse und diesem mit `cis_uid=1` versehen.  Dann würdest Du diese Mails erhalten und könntest diese dann weiterleiten. What do you think?

**Comment by schoenenb** [comment]
Das wäre eine Lösung :+1:  oder wenns dann den Wechsel gibt, ev. auf das Mail der neuen HiWis. Weiss aber noch nicht, ob die eine gemeinsame oder individuelle Mails besitzen werden..

**Comment by ottigerb** [comment]
http://optinomic.cust.local/api/#/user/66
=>  Wurde erstellt.    Frau Nicht Zugewiesen (?)   |  Nora.Schoenenberger@suedhang.ch

**Comment by schoenenb** [comment]
Perfekt! Wenn was wechselt, kann ich's selber nachtragen. Merci :+1:
