### ISSUE TITLE
Export-Toolbox für Non-Admins

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#82]
Freigabe z.B. für Forschung, QM-Mitarbeiter wünschenswert

**Comment by ottigerb** [comment]
Ich habe ein `client_permissions` Object eingeführt: Jede Klinik kann ab sofort `client_permissions` festlegen.  

z.B.:

```
"client_permissions": {
    "access_export_toolbox": {
        "Forschung": { "allowed": true },
        "QM": { "allowed": true }
    }
},
```

Aktuell stehen folgende Möglichkeiten zur Verfügung:

```JS
all_permissions = [
                'arrange_home_page',
                'arrange_patient_page',
                'arrange_stay_page',
                'reports_create',
                'reports_edit',
                'access_export_toolbox'
            ];
```

**Default:**  `Admin` hat immer ein `{ "allowed": true }` ausser wenn explizit überschrieben würde - macht m.E. kein Sinn. Andere Rollen haben ein `{ "allowed": false }` als Standard. 

=>  Wird mit dem nächsten Stable verteilt.

**Comment by schoenenb** [comment]
D.h. die client_permissions mit Zugriff auf die Export-Toolbox für Forschung & QM wird auch gleich so verteilt, oder bleiben die vorläufig auf allowed: false?

**Comment by ottigerb** [comment]
Genau:  Wird wie folgt verteilt:

```JS
"client_permissions": {
    "access_export_toolbox": {
        "Forschung": { "allowed": true },
        "QM": { "allowed": true }
    }
}
```

**Comment by schoenenb** [comment]
Perfect - merci!!!

**Comment by schoenenb** [comment]
Gilt das auch für die neuste Version? 8-)
Momentan haben die betroffenen Personen, welche Exporte machen müssen, einen Admin-Zugang, weil die Export-Toolbox in V2 ja nicht mehr funktionierte und sie auf SQL umsteigen mussten...

**Comment by ottigerb** [comment]
Nein.  Export-Toolbox ist ja jetzt eine APP und deren Zugang wird nicht über `client_permissions` gesteuert.

**Comment by schoenenb** [comment]
Thank youu!
