### ISSUE TITLE
id-error?

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#83]
Mail einer Therapeutin (TK, falls relevant)
> Jetzt habe ich noch ein Problem mit den act-info Ein- und Austritt bei Pat. 2308, es kommt immer ein id-error, sodass ich die Fragebögen nicht öffnen kann. 

> Ich komme auf die Pat.-Seite und wenn ich auf Fragebogen ausführen gehe, kommt die Fehlermeldung und der act-info-Bogen öffnet sich nicht.

Daraufhin habe ich ihr bei dem Patienten eine Aufgabe zugeteilt und sie konnte den Fehler nicht mehr reproduzieren um mir einen Screenshot zu schicken.

Gibt's bereits eine Sammlung von Fehlermeldungen, die angezeigt werden? Müsste man die Fälle mal noch beschreiben, was als Fehlermeldung ausgegeben werden soll, damit die User auch nachkommen, was nun falsch lief - ev. auch mit einer Aufforderung, die Seite neu zu laden, sich neu abzumelden, Handstand an die Wand.....

**Comment by ottigerb** [comment]
...ich kann diesen `id-error` Fehler ebenfalls nicht reproduzieren. Habe es bei einer TK-Patientin versucht [Jetzt manuell ausführen]. Funktioniert einwandfrei - auch der erstellte Event lässt sich einwandfrei ausführen.  
...bei Pat. 2308 waren beide Events i.O. - ausgefüllt wurde der "erste Event" - also nicht den, den Du erstellt hattest. 

=>  Vielleicht während sich das System auf https://github.com/ottigerb/therapy-server/commit/f4b4646432e7abf2533886a5381e6caf359f93c5 angehoben hatte verblieb Ihre Sitzung in einem "undefinierten" Zustand.

...eine Fehlermeldungs-Liste existiert nicht. Wäre allenfalls eine Idee für das Doc. Ein Standardprocedere für "eigenartige Effekte" wäre sicher:  Abmelden, Browser schliessen, Neu anmelden & erneut versuchen.
