### ISSUE TITLE
Austrittsdatum korrigieren

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#84]
Als Austrittsdatum wird nun ein Tag später angezeigt (bei http://optinomic.cust.local/api/#/patient/37 jedenfalls, in allen vorhandenen Fällen) - ich vermute, dass es mit dem Verbleib in der Gruppe Behandlung: Aktuell | Stationär zu tun hat - das sollte aber m.E. wieder korrigiert werden.

**Comment by ottigerb** [comment]
...Problem erkannt. Tom hat ein "Problem" gelöst, welches nun diesen "Folgeschaden" bewirkt.

**Comment by schoenenb** [comment]
Hab ich mir eben gedacht... Kann man #423 in dem Fall auch anders beheben?

**Comment by ottigerb** [comment]
Finally!
