### ISSUE TITLE
App: offene Aufgaben

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#85]
Wie ist es möglich, dass bei jemandem 23 Aufgaben offen sind im Optinomic?! (Alle zum gleichen Zeitpunkt) - kann das durch den event generator passieren, oder hat da jemand so oft draufgeklickt?

**Comment by ottigerb** [comment]
...könnte ausgelöst sein durch die "Behebung" vom "before_exit" bug.  Nur bei diesem Patienten?  Die Events zeigen, ob sie manuell oder "automatisch" erstellt wurden.

**Comment by schoenenb** [comment]
stimmt - bisher scheduled manually...
Ich lösch sie jetzt einfach. Falls das "massenhaft" geht, wär ich froh um die Info - ich mach's jetzt halt von Hand.

**Comment by schoenenb** [comment]
Ev. doch ein Problem: jedes Mal, wenn auf den Pfeil für manuelles Ausfüllen gedrückt wird, wird ein Event ausgelöst - ich werde den Therapeuten heute noch schreiben, dass sie die Pop-up-Blockierung aufheben sollen, damit der Fragebogen aufgeht. Bis dahin gibt es aber je nach Geduld der Anwender x Aufgaben pro Fragebogen. Kann das via SQL (z.B. delete * FROM event where patient = 12345 and done = eventstatustobedone [ich glaube der Begriff war kürzer, aber ist nur zu Demonstrationszwecken hier]) auf einmal gelöscht werden?

**Comment by ottigerb** [comment]
...genau:  Jedes mal bei [manuelles ausfüllen] wird ein Event eröffnet.  Ah ja: `Pop-up-Blockierung` ist ein guter Punkt. Kann ev. auch "global" durch Thömu / IN4U eingestellt werden.

...löschen von Events ***VORSICHT***: 


```SQL
SELECT
  *
FROM event
WHERE 
done = 'EventStatusToBeDone'  
AND patient = '2225'
AND module = 'ch.suedhang.apps.honos.production'
AND description = 'Survey scheduled manually.'
```

=>  Zuerst mit SELECT die entsprechenden Events "rauslesen" und "prüfen".


```SQL
DELETE
FROM event
WHERE 
done = 'EventStatusToBeDone'  
AND patient = '2225'
AND module = 'ch.suedhang.apps.honos.production'
AND description = 'Survey scheduled manually.'
```
=> Dann kann direkt gemäss SELECT gelöscht werden.

```SQL
DELETE
WHERE 
id IN (24028,  24037)
```
=> Vielleicht die "sicherere" Variante.  Alle zu löschenden `id` rauslesen und in dieses IN statement setzen.


**EDIT:**  Die `DELETE`Statements zeigen einen "Error" in  http://optinomic.cust.local/api/#/admin/tools/sql an.  Doch funktioniert. Kann mit dem SELECT nochmals verifiziert werden.

**Comment by schoenenb** [comment]
Tiptop. Habe den Ablauf bzw. die Codes in eine "Anleitung" eingeschleust. Danke für die Übersicht. :)
