### ISSUE TITLE
Text Behandlung

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#86]
![image](https://cloud.githubusercontent.com/assets/15833792/22651135/4043eb70-ec82-11e6-8fb3-30bc06f76111.png)

Zwar eine Kleinigkeit, aber "die behandelnde Therapeutin WAR Frau XY" erscheint mir die sinnvollere Ausdrucksweise.

Bsp. von http://optinomic.cust.local/api/#/patient/2279/stay/1172

**Comment by ottigerb** [comment]
Fixed with new stable https://github.com/ottigerb/therapy-server/commit/01fbc4a9762c3457ac4f04c7cc0fa7d9d4946db0.

**Comment by schoenenb** [comment]
Dann hätte ich aber noch was ähnliches - bei Personen mit Aufenthalt:
Bsp. http://optinomic.cust.local/api/#/patient/2808/stay/1261

![image](https://cloud.githubusercontent.com/assets/15833792/23058279/89478712-f4f4-11e6-8f4a-b4a4540f0d78.png)

Woher kommt das 

> Heute ist der 87. Tag der Behandlung.

?

> ist **vor 3 Tagen** am 14.2.2017 eingetreten.

steht ja bereits...

**Comment by ottigerb** [comment]
Fixed with https://github.com/ottigerb/therapy-server/commit/3975591c5544741040b62f479c618d03f4adc8a7.   
=>  Wird beim "next stable" verteilt.

**Comment by schoenenb** [comment]
Merci!!
