### ISSUE TITLE
Anzeige vs. Export : Divergenz

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#87]
Bei Pat. http://optinomic.cust.local/api/#/patient/1364 ergibt sich eine interessante Kombination aus Daten, welche in Optinomic innerhalb der Apps angezeigt werden, jedoch nicht im Export erscheinen - woran kann das liegen?
z.B. http://optinomic.cust.local/api/#/patient/1364/stay/818/app/ch.suedhang.apps.bscl_anq.production und
http://optinomic.cust.local/api/#/patient/1364/stay/977/app/ch.suedhang.apps.bscl_anq.production zeigen jeweils 2 Fälle, im Export (vielleicht liegt der Fehler auch dort?) kommen diese jedoch nicht vor.
```
SELECT

-- START:  Optinoimc Default |  Needed for Export-Toolbox
  survey_response_view.patient_id as optinomic_patient_id,
  survey_response_view.stay_id as optinomic_stay_id,
  survey_response_view.event_id as optinomic_event_id,
  survey_response_view.survey_response_id as optinomic_survey_response_id,
  survey_response_view.filled as optinomic_survey_filled,
  ((cast(response AS json))->>'id') as optinomic_limesurvey_id,
  -- END:  Optinoimc Default |  Needed for Export-Toolbox

  stay.cis_fid as cis_fid,
  stay.cis_fid/100 as FID,
  patient,
  ((cast(response AS json))->>'id') as id_limesurvey,
  ((cast(response AS json))->>'Eintrittsort') as eintrittsort,
  ((cast(response AS json))->>'Austrittsort') as austrittsort,
  ((cast(response AS json))->>'PID') as pid,
  ((cast(response AS json))->>'datestamp') as datestamp,
  NULL as lieferung_ab_hier,
  'PB' as rekordart,
  71286515 as betriebsnummer_bur,
  ((cast(response AS json))->>'FID') as fid_survey,
  ((cast(response AS json))->>'q501V04') as zeitpunkt_bscl,
  ((cast(response AS json))->>'q501V05') as dropoutcode_bscl,
  ((cast(response AS json))->>'q501V06') as spezifikation_dropout_bscl_andere,
  TO_CHAR(TO_DATE(((cast(response AS json))->>'q504V00'), 'YYYY-MM-DD'), 'YYYYMMDD')  as datum_erhebung_bscl
FROM "survey_response_view" 
LEFT JOIN patient ON(survey_response_view.patient_id = patient.id) 
LEFT JOIN stay ON(survey_response_view.stay_id = stay.id)
WHERE module = 'ch.suedhang.apps.bscl_anq.production' AND patient = 1364
```

Keine Ahnung, ob es nur diesen Patienten & diese App betrifft, oder ob noch mehr solche Fälle da sind...

**Comment by ottigerb** [comment]
```SQL
SELECT * FROM "survey_response_view"
WHERE module = 'ch.suedhang.apps.bscl_anq.production' AND patient_id = 1364
```

=>  Diese Abfrage liefert folgenden 10 Antworten:


![image](https://cloud.githubusercontent.com/assets/2470873/22731291/6363e736-edea-11e6-9462-cbacb3c3df62.png)

=>  Der SQL von Nora liefert nur 7 Resultate.  Dies - da wohl einige "survey_responses" keine stay_id besitzen und somit nicht durch `LEFT JOIN stay ON(survey_response_view.stay_id = stay.id)` berücksichtigt werden. 

Issue:
-  Ich werde meine Analyse noch vertiefen - vorerst sieht es so aus als würde dies nur "V1-Daten" betreffen.  ->  Da muss wohl Tom nochmals ran.  
-  Auch werde ich mit `LEFT JOIN` spielen - vielleicht hilft schon ein `OUTER JOIN` oder sowas um sicherzustellen, dass auch in solchen Fällen alle Ergebnisse exportiert werden.

**Comment by ottigerb** [comment]
Issue eröffnet:  https://github.com/ottigerb/therapy-server/issues/426

**Comment by SonjaKaufmann** [comment]
Ich weiss nicht ob das in die gleiche Richtung geht, aber der Export der BSCL von 2016 weisst sehr viele C-Fälle auf und es macht den Eindruck als ob dies auch unklare Fälle wären, denn Daten sind vorhanden und C-Fälle haben wir in der Regel keine.
[BSCL 2016 Export.xlsx](https://github.com/Optinomic/apps/files/766899/BSCL.2016.Export.xlsx)
BEim Export der ISK-Daten erhielt ich nur 22 C-Fälle aus dem letzten Jahr. Irgendwie funktioniert das noch nicht so gut.

**Comment by ottigerb** [comment]
`survey_response_view` wurde angepasst - sollte nun klappen!  :-)

**Comment by ottigerb** [comment]
Fix scheint noch nicht "angekommen" zu sein. =>  New stable!

**Comment by ottigerb** [comment]
> Suedhang is now at the latest version and CI is fixed.

Spuckt nun folgender SQL 10 Ausgaben aus?

```SQL
SELECT

-- START:  Optinoimc Default |  Needed for Export-Toolbox
  survey_response_view.patient_id as optinomic_patient_id,
  survey_response_view.stay_id as optinomic_stay_id,
  survey_response_view.event_id as optinomic_event_id,
  survey_response_view.survey_response_id as optinomic_survey_response_id,
  survey_response_view.filled as optinomic_survey_filled,
  ((cast(response AS json))->>'id') as optinomic_limesurvey_id,
  -- END:  Optinoimc Default |  Needed for Export-Toolbox

  stay.cis_fid as cis_fid,
  stay.cis_fid/100 as FID,
  patient,
  ((cast(response AS json))->>'id') as id_limesurvey,
  ((cast(response AS json))->>'Eintrittsort') as eintrittsort,
  ((cast(response AS json))->>'Austrittsort') as austrittsort,
  ((cast(response AS json))->>'PID') as pid,
  ((cast(response AS json))->>'datestamp') as datestamp,
  NULL as lieferung_ab_hier,
  'PB' as rekordart,
  71286515 as betriebsnummer_bur,
  ((cast(response AS json))->>'FID') as fid_survey,
  ((cast(response AS json))->>'q501V04') as zeitpunkt_bscl,
  ((cast(response AS json))->>'q501V05') as dropoutcode_bscl,
  ((cast(response AS json))->>'q501V06') as spezifikation_dropout_bscl_andere,
  TO_CHAR(TO_DATE(((cast(response AS json))->>'q504V00'), 'YYYY-MM-DD'), 'YYYYMMDD')  as datum_erhebung_bscl
FROM "survey_response_view" 
LEFT JOIN patient ON(survey_response_view.patient_id = patient.id) 
LEFT JOIN stay ON(survey_response_view.stay_id = stay.id)
WHERE module = 'ch.suedhang.apps.bscl_anq.production' AND patient = 1364
```

**Comment by schoenenb** [comment]
Jawoll :)

**Comment by ottigerb** [comment]
Close!  :-)

**Comment by schoenenb** [comment]
Fast... Macht es Sinn, für jede App noch rauszusuchen, wo noch keine Stays zugewiesen sind? Beim BSCL gibt's z.B. immer noch einen Fall...

**Comment by ottigerb** [comment]
...ah ja?  Klar - solche "Effekte" sind interessant.  M.E. ist dies "V1-geschuldet".

**Comment by schoenenb** [comment]
Denke schon. Habe den SQL aus https://github.com/ottigerb/therapy-server/issues/426 verwendet - dort sind z.B. alle Patientennotizen drin, jedoch keinem Patienten zugeordnet...

**Comment by ottigerb** [comment]
### Issue 
Tatsächlich -  _"module": "patient_notes"_ |  Davon war in der Datenmigration nie die Rede.

```SQL
SELECT * 
FROM "survey_response_view" 
WHERE survey_response_id = 12759
```

```SQL
SELECT * 
FROM "survey_response" 
WHERE id = 12759
```
=>  
```JSON
{
  "rows": [
    {
      "response": {
        "therapist_name": "Nora Schönenberger",
        "note_text": "<p>Auch bei Austritt wurde die englische Version von BSCL und BDI verwendet.</p>",
        "user_id": 25
      },
      "random_hash": "",
      "scheduled": "2017-01-04 16:34:46.138843",
      "module": "patient_notes",
      "id": "12759",
      "patient": "2295",
      "filled": "2017-01-04 16:34:46.138843"
    }
  ],
  "headers": [
    "id",
    "patient",
    "module",
    "scheduled",
    "filled",
    "response",
    "random_hash"
  ]
}
```

Insgesamt haben wir 70 rows für:
```SQL
SELECT * 
FROM "survey_response" 
WHERE module = 'patient_notes'
```
=>  Wir haben keine V2-App 'patient_notes':  Entsprechend kann nicht zugeordnet werden. 

### Vorgehen
Wir könnten eine neue V2-App 'patient_notes' erstellen. Dann müsste überall noch diese App aktiviert werden - wo ein Eintrag vorliegt. => Viel Tom-Aufwand: Ich tendiere diese "Notes" schlicht zu "vergessen" oder die relevanten per Hand zu kopieren und im entsprechenden Modul unter Notizen ablegen.  What do you think?

**Comment by schoenenb** [comment]
Nein, ja nicht noch eine App nur für alte Kommentare!
Ich gedenke auch eher, die von Hand zuzuweisen.

Die Frage wäre dort eher, weshalb die Daten überhaupt in V2 drin sind... Es sind auch alle anderen Daten vorhanden, die keiner App zugeordnet sind, ist das Absicht? Bzw. kann man die eigentlich löschen...

**Comment by ottigerb** [comment]
...bei der Migration wurde natürlich nichts gelöscht - wäre zu "gefährlich" gewesen.
=> Wir können diese `patient_notes` gerne löschen - doch wie gesagt:  Tendenz diese schlicht zu "ignorieren" - die "funken" nirgends rein.

**Comment by schoenenb** [comment]
Dann bleibt's so. Bzw. ich muss nur noch den wenigen nachgehen, welche einer App zugewiesen sind.

**Comment by schoenenb** [comment]
ähm, wenn ich die stays zuordnen will - muss ich da über die PUM gehen (also FROM patient_uses_module) oder über diese survey response view (FROM "survey_response_view")?

**Comment by ottigerb** [comment]
Jeder PUM (patient_uses_module) sollte einem stay zugeordnet sein.
`_view` ist jeweils nur eine Zusammenstellung.

**Comment by schoenenb** [comment]
done :)
