### ISSUE TITLE
Übersichtlichere Graphikzusamenstellung in Berichten 

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#88]
Der Bericht in PDF ist mir zu lang und zu wenig übersichtlich. 
Gerade wenn die Austrittsmessung hinzukommt verlieren wir viel Platz durch Lücken, Überschriften die sich doppeln und Abstände. Auch muss m.E. nicht so viel Platz auf der ersten Seite für Name und Anschrift vergeben werden. Eher im Gegenteil. Da wir den Bericht nicht versenden sondern ggf. dem Patienten abgeben, müsste nur irgendwo sehr klein der Name drauf sein oder die FID-Nr, damit der Therapeut die Bögen nicht durcheinanderbringen kann. Aber so gross der Name drauf und dann noch die Anschrift lässt leicht Datenschutzbedenken aufkommen. Vielleicht kann man noch eine Variante Bericht Versand erstellen, aber eigentlich brauchen wir das derzeit nicht. Die Anleitungstexte könnten kleiner, aber die Interpretation durch die Skalenbeschriftung und die Pole müsste noch erleichtert werden.

Also ich denke wir sollten uns dazu Mal Gedanken machen.

**Comment by ottigerb** [comment]
Die Idee der Anschrift war lediglich, dass das Dokument in ein Fenstercouvert passt - damit eben die Übergabe an den Patienten "vertraulich" stattfinden kann. Auch denke ich, dass die Klinikinfos ersichtlich sein sollen ->  Vertrauensbildend.  Adresse/Klinikinfos weglassen wäre übrigens ein "No-Brainer".  Ansonsten bin ich für klare Vorstellungen offen.

**Comment by SonjaKaufmann** [comment]
Ah ja, an so eine Umschlag-Übergabe habe ich gar nicht gedacht. Wäre eine Option, aber die Therapeuten drucken es aus und besprechen es und könnten sonst ein Couvert ohne Fenster zur Mitnahme aushändigen. Es macht das Dokument sonst sooooo lang.
Klinikinfos gebe ich Dir voll recht, die würde ich auch oben auf die erste Seite tun, nur etwas kleiner und auf der letzten Seite würde ich das Optinomiclogo wegnehmen (hoffe das ist jetzt keine heilige Kuh die ich gerade anlange) oder kleiner.
Da es ein Recht komplexes Issue ist und es auch um die generellen Graphikdarstellungen (wo steht bei allen Graphiken der MZP, wo steht das Datum, wo die Beschriftung) geht, würde ich dies gerne Mal mit Dir besprechen, denn Du hast ja viel ausprobiert bei den Graphikerstellungen. Vielleicht können wir uns Freitag diesbezüglich kurz absprechen, wie wir dieses Issue aufteilen können. Ich hätte nach wie vor gerne so etwas wie ein Graphikskeleton, aber aufgrund der Diversität der Fragebogenauswertugnen ist das halt recht schwierig.
