### ISSUE TITLE
[ch.suedhang.apps.zuepaz] :: ZüPaZ - keine Antwort

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#89]
Ich passe gerade den Limesurvey-Fragebogen an, so dass ich auch Fragebögen erfassen kann, welche nicht vollständig ausgefüllt wurden.

Gehe ich richtig in der Annahme, dass ich in den calculations (sorry, schon wieder Änderungen dort - könnte das z.B. übers Wochenende laufen, wenn ich's heute anpasse?) folgende Anpassung vornehmen kann:
```
        if (d.Q00019 === "kA" || d.Q00019 ==="999") {
            anz_anworten_behandlung = anz_anworten_behandlung - 1;
        } else {
            if (parseInt(d.Q00019) === 0) {
                full_score = full_score + 0;
```
...bei den beiden Antworten, wo bereits eine Option mit keiner Angabe besteht bzw.
```
        if (d.Q00006 === "999") {
            anz_anworten_behandlung = anz_anworten_behandlung - 1;
        } else {        
        full_score = full_score + parseInt(d.Q00006);
```
für alle anderen Items?

**Comment by schoenenb** [comment]
PS: Ich änder's wohl nochmals ab - analog act-info, dass zu anz_antworten nur addiert wird, wenn eine Antwort vorliegt...

**Comment by ottigerb** [comment]
Mit Deinem https://github.com/Optinomic/apps/commit/c8d61118f09afef220705e7029b3472c3fb2556e  Commit hast Du die "Calculation" bereits verändert => Optinomic erkennt die Änderung und "Invalidated" alle Züpaz-Calculations und beginnt neu zu berechnen.  

In Zukunft schlage ich vor, dass Du Änderungen in einem anderen File vornimmst. Kopiere doch die `another_calculation.js` in ein Zuepaz_neu.js und mach die Änderungen dort. Stelle einfach sicher, dass die Änderungen nicht im OPAPP referenziert ist:

```
[calculation another_calculation javascript]
include(calculations/another_calculation.js)
```

Sobald Du die Änderungen hast - kann ich diese "Validieren" und in der OPAPP referenzieren und somit übers WE neu berechnen lasen.

**Comment by ottigerb** [comment]
Die aktuelle Version von `another_calculation.js` wird nun mit "Error" abbrechen:

Ersteindruck:
```JS
if (d.Q00002 === "999") {
            anz_anworten_eintritt = anz_anworten_eintritt - 1;
        } else {
        full_score = full_score + parseInt(d.Q00002);
```
Der else-Fall muss unbedingt mit `}` geschlossen werden.

Wie gesagt:  Calculations vorerst in einem "unreferenzierten" File als Kopie anpassen und diese durch mich "verifizieren" lassen. Ich zeig Dir mal bei Gelegenheit wie ich dies mache.

**Comment by schoenenb** [comment]
Na toll, und ich dachte, solange ich in Optinomic die App nicht aktualisiere passiere nichts :/

**Comment by ottigerb** [comment]
Ah, das ist so!

**Comment by schoenenb** [comment]
ich hab sie jetzt trotzdem reverted und lege sie in einem neuen file ab

**Comment by schoenenb** [comment]
Kannst du den austauschen, wenn die calculations fehlerfrei arbeiten? Anschliessend sehe ich hier keinen Handlungsbedarf mehr. :)

**Comment by ottigerb** [comment]
OK - ich prüfe `zuepaz_neu.js` & falls i.O. werde ich diese Berechnung als "aktiv" schalten.

**Comment by ottigerb** [comment]
...noch nicht erledigt.  :-)

**Comment by schoenenb** [comment]
ahso, du brauchst dies tatsächlich als Pendenzenliste - sorry!

**Comment by ottigerb** [comment]
Done!

@schoenenb  Perfekt, Deine Calculation war einwandfrei. Ich habe nun diese Aktiviert und werde es auf dem Südhang aktualisieren => Neuberechnung der ZüPaz-Calulations.

**Comment by schoenenb** [comment]
Merci! Ich habe nun bei 2 Pat. die neue Version ausgefüllt, Anzeige gibt es leider keine (bzw. alle Striche bei < 0) - laufen die Berechnungen noch, oder muss das Template noch angepasst werden?

**Comment by ottigerb** [comment]
...Berechnungen werden wohl noch laufen.  
=>  Reopen mit Links zu Deinen 2 Erfassungen: Zu prüfen ob diese Berechnungen angekommen sind.

**Comment by schoenenb** [comment]
Sorry! Die wollte ich eigentlich vorhin schon beifügen..
http://optinomic.cust.local/api/#/patient/2294/stay/1089/app/ch.suedhang.apps.zuepaz.production
http://optinomic.cust.local/api/#/patient/2225/stay/1074/app/ch.suedhang.apps.zuepaz.production

**Comment by ottigerb** [comment]
Calculation-Daten sind erfolgreich angekommen!

**Comment by schoenenb** [comment]
![image](https://cloud.githubusercontent.com/assets/15833792/23057050/a7863b0c-f4ee-11e6-85f5-89085afb7406.png)

möchte ich noch anpassen:
6 Punkte bei {counts} von {AnzFragen - fix je Bereich} ausgefüllten Antworten

**Comment by schoenenb** [comment]
Für mich passt es so:
![image](https://cloud.githubusercontent.com/assets/15833792/23070112/46e7a4fc-f52a-11e6-8617-36b74081b737.png)
Allenfalls wieder öffnen, falls das überhaupt nicht geht.
