### ISSUE TITLE
Habe Patient mit 3 TMT

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#92]
das kann ja irgendwie nicht sein.
![image](https://cloud.githubusercontent.com/assets/20124244/22919354/b5dd174a-f28f-11e6-9aa9-ae5ccd01e707.png)

**Comment by schoenenb** [comment]
Doch, in dem Fall kann das sogar tatsächlich sein - bei den kognitiven Screenings wird meines Wissens auch der TMT durchgeführt, von den Daten her macht das also Sinn.
