### ISSUE TITLE
Farben im BSCL stimmen nicht

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#93]
![image](https://cloud.githubusercontent.com/assets/20124244/22919598/05486360-f291-11e6-8a21-d5b81b5f0258.png)

Das hatten wir je eigentlich schon korrigiert, aber nun bin ich über einen Patienten gestolpert, der hohe Werte in einer BSCL-Skala hat und dessen Balken grün statt rot erscheint.

**Comment by ottigerb** [comment]
Closed - https://github.com/Optinomic/apps/issues/93 is still open!

**Comment by schoenenb** [comment]
(Du meintest wahrscheinlich #71)
