### ISSUE TITLE
Anzeigen von Fallnummer

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#96]
Ist es nicht möglich auch die Fallnummer aus dem PABS mit den Aufenthaltsdaten zu kopieren? Denn in den Exporten ist ja auch die Fallnummer drin und im PABS ist ja neben dem Eintrittsdatum und Austrittsdatum auch die Fallnummer abgelegt.
Das würde es für alle vereinfachen, denn man ist sich von Polypoint und den Exporten gewöhnt mit der Fallnummer zu arbeiten und nicht mit dem Eintritts und Austrittsdatum.

Wäre es nicht möglich in der Explorerleiste z.B.
(03) 27.3.2016-15.04.2016 
angezeigt zu bekommen für den 3. Fall dieses Patienten?

**Comment by ottigerb** [comment]
Eine _(03) 27.3.2016-15.04.2016_ Darstellung der Fälle ist nicht möglich.

![bildschirmfoto 2017-02-17 um 12 35 04](https://cloud.githubusercontent.com/assets/2470873/23063983/d24499a0-f50d-11e6-8375-a8b3f7d9ddc9.png)

Im Subheader wird der jeweilige Fall angezeigt. **4872** wäre hier die PID und das **09** der Fall.

**Comment by SonjaKaufmann** [comment]
Schade geht das nicht, aber so ist ja besser als Nichts!
Trotzdem habe ich Mal wieder eine Frage, warum muss Optinomic da immer noch 2 Nullen dranhängen?

**Comment by ottigerb** [comment]
...dies wird von PABS so gesendet.

**Comment by ottigerb** [comment]
Innerhalb der Optoinomic-Apps bei folgendem Element die `cis_fid / 100` darstellen:
 
<img width="234" alt="bildschirmfoto 2017-03-10 um 09 54 26" src="https://cloud.githubusercontent.com/assets/2470873/23788622/9b3bbffe-0577-11e7-9b79-3950390ca6e0.png">
