### ISSUE TITLE
Gruppenzuordnung?

### ISSUE THREAD

**Issue by schoenenb** [Optinomic/apps#97]
Ist immer noch irgendwas korrupt bei der Gruppenzuordnung?
Ich habe diverse Fälle, wo falsche Fragebögen aktiviert wurden. Spätestens beim TK-Fall http://optinomic.cust.local/api/#/patient/819/stay/1268 kann etwas nicht stimmen, denn es sind alle vorhandenen Apps aktiviert worden (und ich glaube nicht, dass die Therapeuten extra alles aktivieren, um mir nachher Mails zu schreiben, dass sie Erinnerungen erhalten für Fragebögen, die sie in der TK gar nicht ausfüllen müssen).

Ich weiss, dass das schon mal Thema war, aber ich mag grad nicht nach dem Issue suchen...

**Comment by ottigerb** [comment]
### Issue
Unter  http://optinomic.cust.local/api/#/logs kann nachvollzogen werden, was "vorgeht".   
Beispiel: `target_patient_id: 819`.  

=> Hier wird deutlich, dass er Patient @ 16.2.2017, 10:00 in die Gruppe "[EP (Aktuell)](http://optinomic.cust.local/api/#/patient-group/11)" aufgenommen wurde. Korrekterweise wurden dann alle EP-Applikationen zugewiesen. Um 16.2.2017, 11:30 wird er aus der EP-Gruppe entfernt und in die TK Gruppe aufgenommen.  Es liegt also **kein Optinomic-Fehler** vor.

### Fragen
=> Kann es sein, das PABS den Fall als "EP" eröffnet und erst später als "TK" markiert?   Sieht für mich zumindest so aus.  

### Vorgeschlagenes Procedere
Sprecht Euch doch mal mit der Patientenadministration ab.  Interessant wären auch TK-Fälle zu beobachten, welche in der Zukunft liegen - also bekannter TK "Direkteintritt".  Ich werde ja analog zu "Patientengruppen" auf "Fallgruppen" erstellen. Dies wird jedoch dieses Issue nicht erschlagen.

**Comment by schoenenb** [comment]
Perfekt, so was hab ich mir gewünscht, mit den logs! Werde dem mal nachgehen.

**Comment by schoenenb** [comment]
Grundsätzlich wird ein neuer Fall von der Patientenadmin gleich am richtigen Ort abgelegt - einzig TKAK wird ambulant abgelegt (kein "Problem", da es dadurch nicht in Optinomic landet) und Abbrüche EAS innerhalb 1 Tag werden von stationär auf ambulant gewechselt. Muss den vorgekommenen Fällen bei Gelegenheit noch nachgehen...

**Comment by schoenenb** [comment]
Update:
Ich habe nun einige Fälle, bei denen jeweils beim 2. Aufenthalt die Apps vom 1. Aufenthalt aktiviert werden. (Es hat noch mehr Fälle, bei denen ich jedoch die stay-id's nicht rausgeschrieben habe.)

![image](https://cloud.githubusercontent.com/assets/15833792/25993249/b5bd1ee0-3709-11e7-9808-14d79c7ce08c.png)

Interessanterweise passiert das NICHT, wenn die Patienten am einen Tag austreten und am nächsten auf einer anderen Station eintreten (EAS / EP -> TK || TK -> EAS / EP).

**Comment by schoenenb** [comment]
Beim Log scheint auch etwas schräg zu laufen:
![image](https://cloud.githubusercontent.com/assets/15833792/26634359/ad9e6ec8-4616-11e7-939d-b7b32ee29bd0.png)
Hier sind Logs von heute Abend 22-23 Uhr - sollten die nicht erst geschrieben werden, wenn im System etwas passiert statt schon im Voraus? Geht der Zeitstempel einfach 1 Tag voraus oder nur 23 Stunden oder so was?

**Comment by schoenenb** [comment]
Zu der Gruppenzuordnung: Die scheint nun random zu funktionieren:
Von den Neueintritten von Gestern wurde 3059 in die EP-Gruppe (11) aufgenommen, 3051 und 3058 hingegen nicht; von den Übertritten wurde bei 2868 korrekt von EAS (10) auf EP (11) gewechselt und die zugehörigen Fragebögen aktiviert, bei 2968 hingegen nicht.
Beim zu beobachtenden TK-Fall 2442 wurde die Gruppe 13 bisher nicht aktiviert, die _Belegungs-App zeigt aber TK an (wird es ev. dort einfach schon angezeigt, ist aber für die Gruppenzuteilung nicht relevant?).

**Comment by ottigerb** [comment]
...nur Kurz - zwischen den Therapien:  ich kann mir Vorstellen dass der Zeitstempel mit "Timezone" gesetzt wird. =>  23h wäre dann ein 24h ->  Dann läuft ja auch der Abgleich mit "Polypoint - Belegung".

**Comment by schoenenb** [comment]
...was aber nicht erklärt, wieso die Gruppenzuteilung nur noch bei einem Teil der Patienten funktioniert, oder?! Bei http://optinomic.cust.local/api/#/patient/2442 wurde die Gruppenzuteilung nach wie vor nicht vorgenommen, ich habe die benötigten Apps nun von Hand aktiviert.

**Comment by ottigerb** [comment]
...

ich habe mal folgendes Debugging angegangen:

[Patient](http://optinomic.cust.local/api/#/patient/2442) ist hat die [korrekten Fallangaben gemäss der App com.optinomic.init.poly_stay](http://optinomic.cust.local/api/#/patient/2442/stay/1444/app/com.optinomic.init.poly_stay). Ebenfalls ist er erfolgreich in der [Gruppe 13 TK aufgenommen ](http://optinomic.cust.local/api/#/patient-group/13) werden.


```SQL
SELECT * FROM logs where target_patient_id = 2442
``` 
=> 
```
id|user_id|target_user_id|target_role|target_patient_id|target_patient_group_id|message|created_at|target_stay_group_id|target_stay_id
8785||||2442||"Activated module com.optinomic.init.poly_stay with PUM #10962"|"2016-12-16 15:00:08"||
8786||||2442|5|"Patient added to patient group"|"2016-12-16 15:00:08"||
8787||||2442|1|"Patient added to patient group"|"2016-12-16 15:00:13"||
9031||||2442|3|"Patient added to patient group"|"2017-01-03 12:30:09"||
11272|2|||2442|7|"Patient added to patient group"|"2017-01-05 12:24:50"||
10786|2|||2442||"Activated module ch.suedhang.apps.pdf_druckvorlagen with PUM #12922"|"2017-01-05 12:03:50"||
11257|2|||2442|11|"Patient added to patient group"|"2017-01-05 12:24:50"||
12607|2|||2442||"Activated module com.optinomic.init.poly_stay with PUM #13959"|"2017-01-16 05:18:22"||
12688||||2442|17|"Patient added to patient group"|"2017-01-16 08:00:26"||
12767||||2442|18|"Patient added to patient group"|"2017-01-16 08:00:28"||
21550||||2442|17|"Patient removed from patient group"|"2017-03-06 18:00:07"||
21552||||2442|18|"Patient removed from patient group"|"2017-03-06 18:00:08"||
15217||||2442|1|"Patient removed from patient group"|"2017-01-18 16:10:56"||
16849||||2442|1|"Patient added to patient group"|"2017-01-18 17:37:59"||
18285|25|||2442||"Activated module ch.suedhang.apps.zuepaz.production with PUM #15052"|"2017-01-20 10:54:44"||
21711||||2442|11|"Patient removed from patient group"|"2017-03-07 18:00:15"||
19180||||2442|23|"Patient added to patient group"|"2017-01-31 18:00:27"||
22302||||2442|23|"Patient removed from patient group"|"2017-03-21 18:00:16"||
27108||||2442||"Activated module com.optinomic.init.poly_stay with PUM #17884"|"2017-05-31 09:30:15"||
27109||||2442||"Activated module ch.suedhang.apps.pdf_druckvorlagen with PUM #17885"|"2017-05-31 09:30:15"||
27110||||2442|17|"Patient added to patient group"|"2017-05-31 09:30:16"||
27111||||2442|19|"Patient added to patient group"|"2017-05-31 09:30:16"||
27112||||2442|4|"Patient added to patient group"|"2017-05-31 09:30:17"||
27240|25|||2442||"Activated module ch.suedhang.apps.actinfo_ein.production with PUM #17947"|"2017-06-02 06:50:09"||
27241|25|||2442||"Activated module ch.suedhang.apps.actinfo_aus.production with PUM #17948"|"2017-06-02 06:50:16"||
```

=>  Log's zeigt kein `Patient added to patient group` 13 an.  Hmm...  Wieso ist dann der Patient in dieser Gruppe - scheint wohl die grosse Frage zu sein.

**Comment by ottigerb** [comment]
...ich habe den "Upgrader" angestossen -> es wird der neuste Stable build im Südhang gezogen. Da ist ein [Fix von Tom](https://github.com/ottigerb/therapy-server/commit/a6d8b5a3f782f203e84ec8cfabfb5f468e5e729b) drin, welcher eine mögliche Lösung darstellt.

**Comment by schoenenb** [comment]
Ist glaube ich gefixt... Das heute war ja Fehlalarm. Wenn noch benötigt, bitte wieder eröffnen!
